{-# OPTIONS --cubical --safe --guardedness #-}

module Boundary.Dense100HalfBound where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; _+_)
open import Cubical.Data.Sigma using (Σ-syntax)

open import Util.Scalars
open import Common.Dense100Spec
open import Boundary.Dense100AreaLaw using (regionArea)
open import Bridge.GenericBridge using (PatchData ; orbit-to-patch)
open import Bridge.GenericValidation using (d100OrbitPatch)
open import Bridge.HalfBound using (HalfBoundWitness)

--  Generated by sim/prototyping/17_generate_half_bound.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/17_generate_half_bound.py

-- ═══════════════════════════════════════════════════════════
--  PatchData for the Dense-100 patch
-- ═══════════════════════════════════════════════════════════

private
  pd : PatchData
  pd = orbit-to-patch d100OrbitPatch

  S∂ : D100Region → ℚ≥0
  S∂ = PatchData.S∂ pd

-- ═══════════════════════════════════════════════════════════
--  half-bound-proof — 2·S(A) ≤ area(A)  (717 cases)
-- ═══════════════════════════════════════════════════════════
--
--  The discrete Bekenstein–Hawking bound:  S(A) ≤ area(A)/2.
--  Stated as  (S∂ r + S∂ r) ≤ℚ regionArea r  to avoid
--  division in ℕ.
--
--  Each witness  (k , refl)  type-checks because
--  k + (S∂ r + S∂ r) reduces judgmentally to regionArea r
--  via ℕ addition on closed numerals.
--
--  Wrapped in  abstract  so downstream modules never
--  re-unfold the proof.  Since  _≤ℚ_  is propositional,
--  the abstract barrier does not damage the Univalence bridge.
--
--  Generated by sim/prototyping/17_generate_half_bound.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/17_generate_half_bound.py

abstract
  half-bound-proof : (r : D100Region) → (S∂ r +ℚ S∂ r) ≤ℚ regionArea r
  -- S=1, area=6, 2·S=2, slack=4
  half-bound-proof d100r0 = 4 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r1 = 4 , refl
  -- S=3, area=14, 2·S=6, slack=8
  half-bound-proof d100r2 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r3 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r4 = 8 , refl
  half-bound-proof d100r5 = 8 , refl
  -- S=6, area=22, 2·S=12, slack=10
  half-bound-proof d100r6 = 10 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r7 = 8 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r8 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r9 = 12 , refl
  -- S=6, area=22, 2·S=12, slack=10
  half-bound-proof d100r10 = 10 , refl
  -- S=4, area=18, 2·S=8, slack=10
  half-bound-proof d100r11 = 10 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r12 = 12 , refl
  -- S=6, area=14, 2·S=12, slack=2
  half-bound-proof d100r13 = 2 , refl
  -- S=7, area=18, 2·S=14, slack=4
  half-bound-proof d100r14 = 4 , refl
  -- S=8, area=22, 2·S=16, slack=6
  half-bound-proof d100r15 = 6 , refl
  half-bound-proof d100r16 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r17 = 8 , refl
  -- S=8, area=22, 2·S=16, slack=6
  half-bound-proof d100r18 = 6 , refl
  -- S=7, area=18, 2·S=14, slack=4
  half-bound-proof d100r19 = 4 , refl
  -- S=8, area=22, 2·S=16, slack=6
  half-bound-proof d100r20 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r21 = 8 , refl
  -- S=8, area=22, 2·S=16, slack=6
  half-bound-proof d100r22 = 6 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r23 = 6 , refl
  -- S=6, area=22, 2·S=12, slack=10
  half-bound-proof d100r24 = 10 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r25 = 4 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r26 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r27 = 12 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r28 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r29 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r30 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r31 = 8 , refl
  half-bound-proof d100r32 = 8 , refl
  -- S=8, area=22, 2·S=16, slack=6
  half-bound-proof d100r33 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r34 = 8 , refl
  half-bound-proof d100r35 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r36 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r37 = 8 , refl
  -- S=8, area=22, 2·S=16, slack=6
  half-bound-proof d100r38 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r39 = 8 , refl
  half-bound-proof d100r40 = 8 , refl
  -- S=7, area=18, 2·S=14, slack=4
  half-bound-proof d100r41 = 4 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r42 = 8 , refl
  -- S=8, area=22, 2·S=16, slack=6
  half-bound-proof d100r43 = 6 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r44 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r45 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r46 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r47 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r48 = 8 , refl
  -- S=8, area=22, 2·S=16, slack=6
  half-bound-proof d100r49 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r50 = 8 , refl
  half-bound-proof d100r51 = 8 , refl
  -- S=7, area=18, 2·S=14, slack=4
  half-bound-proof d100r52 = 4 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r53 = 8 , refl
  -- S=8, area=22, 2·S=16, slack=6
  half-bound-proof d100r54 = 6 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r55 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r56 = 8 , refl
  -- S=6, area=14, 2·S=12, slack=2
  half-bound-proof d100r57 = 2 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r58 = 6 , refl
  -- S=6, area=22, 2·S=12, slack=10
  half-bound-proof d100r59 = 10 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r60 = 4 , refl
  -- S=3, area=14, 2·S=6, slack=8
  half-bound-proof d100r61 = 8 , refl
  -- S=3, area=18, 2·S=6, slack=12
  half-bound-proof d100r62 = 12 , refl
  -- S=1, area=6, 2·S=2, slack=4
  half-bound-proof d100r63 = 4 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r64 = 4 , refl
  -- S=3, area=14, 2·S=6, slack=8
  half-bound-proof d100r65 = 8 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r66 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r67 = 12 , refl
  half-bound-proof d100r68 = 12 , refl
  half-bound-proof d100r69 = 12 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r70 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r71 = 12 , refl
  half-bound-proof d100r72 = 12 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r73 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r74 = 12 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r75 = 4 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r76 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r77 = 12 , refl
  half-bound-proof d100r78 = 12 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r79 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r80 = 12 , refl
  half-bound-proof d100r81 = 12 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r82 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r83 = 12 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r84 = 4 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r85 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r86 = 12 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r87 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r88 = 12 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r89 = 4 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r90 = 8 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r91 = 4 , refl
  -- S=3, area=14, 2·S=6, slack=8
  half-bound-proof d100r92 = 8 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r93 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r94 = 12 , refl
  half-bound-proof d100r95 = 12 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r96 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r97 = 12 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r98 = 4 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r99 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r100 = 12 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r101 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r102 = 12 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r103 = 4 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r104 = 8 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r105 = 4 , refl
  -- S=3, area=14, 2·S=6, slack=8
  half-bound-proof d100r106 = 8 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r107 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r108 = 12 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r109 = 4 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r110 = 8 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r111 = 4 , refl
  -- S=3, area=14, 2·S=6, slack=8
  half-bound-proof d100r112 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r113 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r114 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r115 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r116 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r117 = 8 , refl
  half-bound-proof d100r118 = 8 , refl
  half-bound-proof d100r119 = 8 , refl
  half-bound-proof d100r120 = 8 , refl
  half-bound-proof d100r121 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r122 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r123 = 8 , refl
  half-bound-proof d100r124 = 8 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r125 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r126 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r127 = 8 , refl
  half-bound-proof d100r128 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r129 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r130 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r131 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r132 = 8 , refl
  half-bound-proof d100r133 = 8 , refl
  half-bound-proof d100r134 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r135 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r136 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r137 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r138 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r139 = 8 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r140 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r141 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r142 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r143 = 8 , refl
  half-bound-proof d100r144 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r145 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r146 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r147 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r148 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r149 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r150 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r151 = 8 , refl
  half-bound-proof d100r152 = 8 , refl
  half-bound-proof d100r153 = 8 , refl
  half-bound-proof d100r154 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r155 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r156 = 8 , refl
  half-bound-proof d100r157 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r158 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r159 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r160 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r161 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r162 = 8 , refl
  half-bound-proof d100r163 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r164 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r165 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r166 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r167 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r168 = 8 , refl
  half-bound-proof d100r169 = 8 , refl
  half-bound-proof d100r170 = 8 , refl
  half-bound-proof d100r171 = 8 , refl
  half-bound-proof d100r172 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r173 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r174 = 8 , refl
  half-bound-proof d100r175 = 8 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r176 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r177 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r178 = 8 , refl
  half-bound-proof d100r179 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r180 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r181 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r182 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r183 = 8 , refl
  half-bound-proof d100r184 = 8 , refl
  half-bound-proof d100r185 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r186 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r187 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r188 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r189 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r190 = 8 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r191 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r192 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r193 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r194 = 8 , refl
  half-bound-proof d100r195 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r196 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r197 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r198 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r199 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r200 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r201 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r202 = 8 , refl
  half-bound-proof d100r203 = 8 , refl
  half-bound-proof d100r204 = 8 , refl
  half-bound-proof d100r205 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r206 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r207 = 8 , refl
  half-bound-proof d100r208 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r209 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r210 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r211 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r212 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r213 = 8 , refl
  half-bound-proof d100r214 = 8 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r215 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r216 = 6 , refl
  -- S=2, area=14, 2·S=4, slack=10
  half-bound-proof d100r217 = 10 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r218 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r219 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r220 = 2 , refl
  half-bound-proof d100r221 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r222 = 6 , refl
  -- S=2, area=14, 2·S=4, slack=10
  half-bound-proof d100r223 = 10 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r224 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r225 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r226 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r227 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r228 = 8 , refl
  half-bound-proof d100r229 = 8 , refl
  half-bound-proof d100r230 = 8 , refl
  half-bound-proof d100r231 = 8 , refl
  half-bound-proof d100r232 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r233 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r234 = 8 , refl
  half-bound-proof d100r235 = 8 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r236 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r237 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r238 = 8 , refl
  half-bound-proof d100r239 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r240 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r241 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r242 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r243 = 8 , refl
  half-bound-proof d100r244 = 8 , refl
  half-bound-proof d100r245 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r246 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r247 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r248 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r249 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r250 = 8 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r251 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r252 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r253 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r254 = 8 , refl
  half-bound-proof d100r255 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r256 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r257 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r258 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r259 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r260 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r261 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r262 = 8 , refl
  half-bound-proof d100r263 = 8 , refl
  half-bound-proof d100r264 = 8 , refl
  half-bound-proof d100r265 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r266 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r267 = 8 , refl
  half-bound-proof d100r268 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r269 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r270 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r271 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r272 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r273 = 8 , refl
  half-bound-proof d100r274 = 8 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r275 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r276 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r277 = 2 , refl
  half-bound-proof d100r278 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r279 = 6 , refl
  -- S=2, area=14, 2·S=4, slack=10
  half-bound-proof d100r280 = 10 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r281 = 0 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r282 = 4 , refl
  -- S=4, area=14, 2·S=8, slack=6
  half-bound-proof d100r283 = 6 , refl
  -- S=4, area=18, 2·S=8, slack=10
  half-bound-proof d100r284 = 10 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r285 = 12 , refl
  half-bound-proof d100r286 = 12 , refl
  -- S=5, area=18, 2·S=10, slack=8
  half-bound-proof d100r287 = 8 , refl
  -- S=5, area=22, 2·S=10, slack=12
  half-bound-proof d100r288 = 12 , refl
  -- S=4, area=14, 2·S=8, slack=6
  half-bound-proof d100r289 = 6 , refl
  -- S=4, area=18, 2·S=8, slack=10
  half-bound-proof d100r290 = 10 , refl
  -- S=4, area=22, 2·S=8, slack=14
  half-bound-proof d100r291 = 14 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r292 = 2 , refl
  -- S=4, area=14, 2·S=8, slack=6
  half-bound-proof d100r293 = 6 , refl
  -- S=4, area=18, 2·S=8, slack=10
  half-bound-proof d100r294 = 10 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r295 = 0 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r296 = 4 , refl
  -- S=3, area=14, 2·S=6, slack=8
  half-bound-proof d100r297 = 8 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r298 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r299 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r300 = 2 , refl
  half-bound-proof d100r301 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r302 = 6 , refl
  -- S=2, area=14, 2·S=4, slack=10
  half-bound-proof d100r303 = 10 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r304 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r305 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r306 = 2 , refl
  -- S=1, area=6, 2·S=2, slack=4
  half-bound-proof d100r307 = 4 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r308 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r309 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r310 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r311 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r312 = 8 , refl
  half-bound-proof d100r313 = 8 , refl
  half-bound-proof d100r314 = 8 , refl
  half-bound-proof d100r315 = 8 , refl
  half-bound-proof d100r316 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r317 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r318 = 8 , refl
  half-bound-proof d100r319 = 8 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r320 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r321 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r322 = 8 , refl
  half-bound-proof d100r323 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r324 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r325 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r326 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r327 = 8 , refl
  half-bound-proof d100r328 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r329 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r330 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r331 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r332 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r333 = 8 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r334 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r335 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r336 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r337 = 8 , refl
  half-bound-proof d100r338 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r339 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r340 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r341 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r342 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r343 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r344 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r345 = 8 , refl
  half-bound-proof d100r346 = 8 , refl
  half-bound-proof d100r347 = 8 , refl
  half-bound-proof d100r348 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r349 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r350 = 8 , refl
  half-bound-proof d100r351 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r352 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r353 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r354 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r355 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r356 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r357 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r358 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r359 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r360 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r361 = 8 , refl
  half-bound-proof d100r362 = 8 , refl
  half-bound-proof d100r363 = 8 , refl
  half-bound-proof d100r364 = 8 , refl
  half-bound-proof d100r365 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r366 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r367 = 8 , refl
  half-bound-proof d100r368 = 8 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r369 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r370 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r371 = 8 , refl
  half-bound-proof d100r372 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r373 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r374 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r375 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r376 = 8 , refl
  half-bound-proof d100r377 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r378 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r379 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r380 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r381 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r382 = 8 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r383 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r384 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r385 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r386 = 8 , refl
  half-bound-proof d100r387 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r388 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r389 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r390 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r391 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r392 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r393 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r394 = 8 , refl
  half-bound-proof d100r395 = 8 , refl
  half-bound-proof d100r396 = 8 , refl
  half-bound-proof d100r397 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r398 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r399 = 8 , refl
  half-bound-proof d100r400 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r401 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r402 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r403 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r404 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r405 = 8 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r406 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r407 = 6 , refl
  -- S=2, area=14, 2·S=4, slack=10
  half-bound-proof d100r408 = 10 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r409 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r410 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r411 = 2 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r412 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r413 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r414 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r415 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r416 = 8 , refl
  half-bound-proof d100r417 = 8 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r418 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r419 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r420 = 8 , refl
  half-bound-proof d100r421 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r422 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r423 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r424 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r425 = 8 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r426 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r427 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r428 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r429 = 8 , refl
  half-bound-proof d100r430 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r431 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r432 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r433 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r434 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r435 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r436 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r437 = 8 , refl
  half-bound-proof d100r438 = 8 , refl
  half-bound-proof d100r439 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r440 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r441 = 8 , refl
  half-bound-proof d100r442 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r443 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r444 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r445 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r446 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r447 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r448 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r449 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r450 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r451 = 8 , refl
  half-bound-proof d100r452 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r453 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r454 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r455 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r456 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r457 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r458 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r459 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r460 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r461 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r462 = 8 , refl
  half-bound-proof d100r463 = 8 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r464 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r465 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r466 = 8 , refl
  half-bound-proof d100r467 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r468 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r469 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r470 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r471 = 8 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r472 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r473 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r474 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r475 = 8 , refl
  half-bound-proof d100r476 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r477 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r478 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r479 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r480 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r481 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r482 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r483 = 8 , refl
  half-bound-proof d100r484 = 8 , refl
  half-bound-proof d100r485 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r486 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r487 = 8 , refl
  half-bound-proof d100r488 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r489 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r490 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r491 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r492 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r493 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r494 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r495 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r496 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r497 = 8 , refl
  half-bound-proof d100r498 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r499 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r500 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r501 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r502 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r503 = 8 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r504 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r505 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r506 = 2 , refl
  half-bound-proof d100r507 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r508 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r509 = 2 , refl
  half-bound-proof d100r510 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r511 = 6 , refl
  -- S=2, area=14, 2·S=4, slack=10
  half-bound-proof d100r512 = 10 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r513 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r514 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r515 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r516 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r517 = 8 , refl
  half-bound-proof d100r518 = 8 , refl
  half-bound-proof d100r519 = 8 , refl
  half-bound-proof d100r520 = 8 , refl
  half-bound-proof d100r521 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r522 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r523 = 8 , refl
  half-bound-proof d100r524 = 8 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r525 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r526 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r527 = 8 , refl
  half-bound-proof d100r528 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r529 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r530 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r531 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r532 = 8 , refl
  half-bound-proof d100r533 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r534 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r535 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r536 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r537 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r538 = 8 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r539 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r540 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r541 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r542 = 8 , refl
  half-bound-proof d100r543 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r544 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r545 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r546 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r547 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r548 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r549 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r550 = 8 , refl
  half-bound-proof d100r551 = 8 , refl
  half-bound-proof d100r552 = 8 , refl
  half-bound-proof d100r553 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r554 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r555 = 8 , refl
  half-bound-proof d100r556 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r557 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r558 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r559 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r560 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r561 = 8 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r562 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r563 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r564 = 2 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r565 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r566 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r567 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r568 = 6 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r569 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r570 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r571 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r572 = 6 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r573 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r574 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r575 = 6 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r576 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r577 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r578 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r579 = 6 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r580 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r581 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r582 = 4 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r583 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r584 = 2 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r585 = 0 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r586 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r587 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r588 = 2 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r589 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r590 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r591 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r592 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r593 = 8 , refl
  half-bound-proof d100r594 = 8 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r595 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r596 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r597 = 8 , refl
  half-bound-proof d100r598 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r599 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r600 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r601 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r602 = 8 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r603 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r604 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r605 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r606 = 8 , refl
  half-bound-proof d100r607 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r608 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r609 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r610 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r611 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r612 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r613 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r614 = 8 , refl
  half-bound-proof d100r615 = 8 , refl
  half-bound-proof d100r616 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r617 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r618 = 8 , refl
  half-bound-proof d100r619 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r620 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r621 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r622 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r623 = 8 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r624 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r625 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r626 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r627 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r628 = 8 , refl
  half-bound-proof d100r629 = 8 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r630 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r631 = 8 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r632 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r633 = 6 , refl
  -- S=7, area=22, 2·S=14, slack=8
  half-bound-proof d100r634 = 8 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r635 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r636 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r637 = 2 , refl
  half-bound-proof d100r638 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r639 = 6 , refl
  -- S=2, area=14, 2·S=4, slack=10
  half-bound-proof d100r640 = 10 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r641 = 0 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r642 = 4 , refl
  -- S=4, area=14, 2·S=8, slack=6
  half-bound-proof d100r643 = 6 , refl
  -- S=4, area=18, 2·S=8, slack=10
  half-bound-proof d100r644 = 10 , refl
  -- S=4, area=22, 2·S=8, slack=14
  half-bound-proof d100r645 = 14 , refl
  -- S=4, area=18, 2·S=8, slack=10
  half-bound-proof d100r646 = 10 , refl
  -- S=3, area=14, 2·S=6, slack=8
  half-bound-proof d100r647 = 8 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r648 = 4 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r649 = 2 , refl
  half-bound-proof d100r650 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r651 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r652 = 2 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r653 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r654 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r655 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r656 = 6 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r657 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r658 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r659 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r660 = 6 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r661 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r662 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r663 = 6 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r664 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r665 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r666 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r667 = 6 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r668 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r669 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r670 = 4 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r671 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r672 = 2 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r673 = 0 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r674 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r675 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r676 = 2 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r677 = 0 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r678 = 4 , refl
  -- S=3, area=14, 2·S=6, slack=8
  half-bound-proof d100r679 = 8 , refl
  -- S=3, area=10, 2·S=6, slack=4
  half-bound-proof d100r680 = 4 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r681 = 2 , refl
  half-bound-proof d100r682 = 2 , refl
  half-bound-proof d100r683 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r684 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r685 = 2 , refl
  -- S=1, area=6, 2·S=2, slack=4
  half-bound-proof d100r686 = 4 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r687 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r688 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r689 = 2 , refl
  half-bound-proof d100r690 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r691 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r692 = 2 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r693 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r694 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r695 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r696 = 6 , refl
  -- S=5, area=20, 2·S=10, slack=10
  half-bound-proof d100r697 = 10 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r698 = 6 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r699 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r700 = 6 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r701 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r702 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r703 = 6 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r704 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r705 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r706 = 4 , refl
  -- S=6, area=18, 2·S=12, slack=6
  half-bound-proof d100r707 = 6 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r708 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r709 = 2 , refl
  -- S=5, area=14, 2·S=10, slack=4
  half-bound-proof d100r710 = 4 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r711 = 0 , refl
  -- S=4, area=10, 2·S=8, slack=2
  half-bound-proof d100r712 = 2 , refl
  -- S=3, area=6, 2·S=6, slack=0
  half-bound-proof d100r713 = 0 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r714 = 2 , refl
  -- S=2, area=10, 2·S=4, slack=6
  half-bound-proof d100r715 = 6 , refl
  -- S=2, area=6, 2·S=4, slack=2
  half-bound-proof d100r716 = 2 , refl

-- ═══════════════════════════════════════════════════════════
--  tight-witness — A region achieving 2·S = area
-- ═══════════════════════════════════════════════════════════
--
--  d100r113: S=3, area=6, 2·3=6=6
--  This is a 1-cell region with n_cross = n_bdy = 3.
--

tight-witness : Σ[ r ∈ D100Region ] (S∂ r +ℚ S∂ r ≡ regionArea r)
tight-witness = d100r113 , refl

-- ═══════════════════════════════════════════════════════════
--  dense100HalfBound — The complete HalfBoundWitness
-- ═══════════════════════════════════════════════════════════
--
--  Packages the area function, the abstract half-bound proof,
--  and the tight achiever witness into a single record.
--  This is the per-instance deliverable from §15.11 Phase A.
--

dense100HalfBound : HalfBoundWitness pd
dense100HalfBound .HalfBoundWitness.area = regionArea
dense100HalfBound .HalfBoundWitness.half-bound = half-bound-proof
dense100HalfBound .HalfBoundWitness.tight = tight-witness

