{-# OPTIONS --cubical --safe --guardedness #-}

module Boundary.Dense1000Cut where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Dense1000Spec

record D1000BdyView : Type₀ where
  field
    dummy : ℚ≥0

--  Generated by sim/prototyping/12b_generate_dense1000.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/12b_generate_dense1000.py

S-cut-rep : D1000OrbitRep → ℚ≥0
S-cut-rep mc1 = 1
S-cut-rep mc2 = 2
S-cut-rep mc3 = 3
S-cut-rep mc4 = 4
S-cut-rep mc5 = 5
S-cut-rep mc6 = 6
S-cut-rep mc7 = 7
S-cut-rep mc8 = 8
S-cut-rep mc9 = 9

S-cut : D1000BdyView → D1000Region → ℚ≥0
S-cut _ r = S-cut-rep (classify1000 r)

