{-# OPTIONS --cubical --safe --guardedness #-}

module Boundary.Dense100Cut where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Dense100Spec

-- ═══════════════════════════════════════════════════════════
--  D100BdyView — Boundary-side architectural wrapper
-- ═══════════════════════════════════════════════════════════

record D100BdyView : Type₀ where
  field
    dummy : ℚ≥0

-- ═══════════════════════════════════════════════════════════
--  S-cut-rep — Boundary min-cut on orbit representatives
-- ═══════════════════════════════════════════════════════════
--
--  8-clause lookup on the small orbit type.
--  Each orbit representative maps to its min-cut value.
--
--  Generated by sim/prototyping/09_generate_dense100.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/09_generate_dense100.py

S-cut-rep : D100OrbitRep → ℚ≥0
S-cut-rep mc1 = 1
S-cut-rep mc2 = 2
S-cut-rep mc3 = 3
S-cut-rep mc4 = 4
S-cut-rep mc5 = 5
S-cut-rep mc6 = 6
S-cut-rep mc7 = 7
S-cut-rep mc8 = 8

-- ═══════════════════════════════════════════════════════════
--  S-cut — Boundary min-cut for the Dense-100 patch
-- ═══════════════════════════════════════════════════════════
--
--  Defined as  S-cut-rep ∘ classify100 .  Agda normalizes
--  this by first reducing classify100 r (one step on the
--  717-clause function) then S-cut-rep on the
--  result (one step on the 8-clause function).
--
--  This is the orbit reduction architecture from §6.5 of
--  docs/10-frontier.md: the large case analysis is in the
--  classification function, and the observable lookup is
--  on the small orbit type.
--
--  Generated by sim/prototyping/09_generate_dense100.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/09_generate_dense100.py

S-cut : D100BdyView → D100Region → ℚ≥0
S-cut _ r = S-cut-rep (classify100 r)

