{-# OPTIONS --cubical --safe --guardedness #-}

module Boundary.Dense200Cut where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Dense200Spec

record D200BdyView : Type₀ where
  field
    dummy : ℚ≥0

-- ═══════════════════════════════════════════════════════════
--  S-cut-rep — Boundary min-cut on orbit representatives
-- ═══════════════════════════════════════════════════════════
--
--  Generated by sim/prototyping/12_generate_dense200.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/12_generate_dense200.py

S-cut-rep : D200OrbitRep → ℚ≥0
S-cut-rep mc1 = 1
S-cut-rep mc2 = 2
S-cut-rep mc3 = 3
S-cut-rep mc4 = 4
S-cut-rep mc5 = 5
S-cut-rep mc6 = 6
S-cut-rep mc7 = 7
S-cut-rep mc8 = 8
S-cut-rep mc9 = 9

-- ═══════════════════════════════════════════════════════════
--  S-cut — Boundary min-cut for the Dense-200 patch
-- ═══════════════════════════════════════════════════════════
--
--  Defined as  S-cut-rep ∘ classify200 .
--
--  Generated by sim/prototyping/12_generate_dense200.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/12_generate_dense200.py

S-cut : D200BdyView → D200Region → ℚ≥0
S-cut _ r = S-cut-rep (classify200 r)

