{-# OPTIONS --cubical --safe --guardedness #-}

module Boundary.FilledSubadditivity where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; _+_)
open import Util.Scalars
open import Common.FilledSpec

-- ════════════════════════════════════════════════════════════
--  S-filled — Min-cut entropy on all 90 regions
-- ════════════════════════════════════════════════════════════
--
--  Self-contained lookup table (not importing S-cut from
--  Boundary.FilledCut) to avoid cross-module re-normalization.
--
--  Generated by sim/prototyping/03_generate_filled_patch.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/03_generate_filled_patch.py

S-filled : FilledRegion → ℚ≥0
S-filled r0x1 = 2
S-filled r1x1 = 2
S-filled r2x1 = 2
S-filled r3x1 = 2
S-filled r4x1 = 2
S-filled r5x1 = 2
S-filled r6x1 = 2
S-filled r7x1 = 2
S-filled r8x1 = 2
S-filled r9x1 = 2
S-filled r0x2 = 3
S-filled r1x2 = 3
S-filled r2x2 = 3
S-filled r3x2 = 3
S-filled r4x2 = 3
S-filled r5x2 = 3
S-filled r6x2 = 3
S-filled r7x2 = 3
S-filled r8x2 = 3
S-filled r9x2 = 3
S-filled r0x3 = 4
S-filled r1x3 = 3
S-filled r2x3 = 4
S-filled r3x3 = 3
S-filled r4x3 = 4
S-filled r5x3 = 3
S-filled r6x3 = 4
S-filled r7x3 = 3
S-filled r8x3 = 4
S-filled r9x3 = 3
S-filled r0x4 = 4
S-filled r1x4 = 4
S-filled r2x4 = 4
S-filled r3x4 = 4
S-filled r4x4 = 4
S-filled r5x4 = 4
S-filled r6x4 = 4
S-filled r7x4 = 4
S-filled r8x4 = 4
S-filled r9x4 = 4
S-filled r0x5 = 4
S-filled r1x5 = 4
S-filled r2x5 = 4
S-filled r3x5 = 4
S-filled r4x5 = 4
S-filled r5x5 = 4
S-filled r6x5 = 4
S-filled r7x5 = 4
S-filled r8x5 = 4
S-filled r9x5 = 4
S-filled r0x6 = 4
S-filled r1x6 = 4
S-filled r2x6 = 4
S-filled r3x6 = 4
S-filled r4x6 = 4
S-filled r5x6 = 4
S-filled r6x6 = 4
S-filled r7x6 = 4
S-filled r8x6 = 4
S-filled r9x6 = 4
S-filled r0x7 = 3
S-filled r1x7 = 4
S-filled r2x7 = 3
S-filled r3x7 = 4
S-filled r4x7 = 3
S-filled r5x7 = 4
S-filled r6x7 = 3
S-filled r7x7 = 4
S-filled r8x7 = 3
S-filled r9x7 = 4
S-filled r0x8 = 3
S-filled r1x8 = 3
S-filled r2x8 = 3
S-filled r3x8 = 3
S-filled r4x8 = 3
S-filled r5x8 = 3
S-filled r6x8 = 3
S-filled r7x8 = 3
S-filled r8x8 = 3
S-filled r9x8 = 3
S-filled r0x9 = 2
S-filled r1x9 = 2
S-filled r2x9 = 2
S-filled r3x9 = 2
S-filled r4x9 = 2
S-filled r5x9 = 2
S-filled r6x9 = 2
S-filled r7x9 = 2
S-filled r8x9 = 2
S-filled r9x9 = 2

-- ════════════════════════════════════════════════════════════
--  subadditivity — S(A ∪ B) ≤ S(A) + S(B)  (360 cases)
-- ════════════════════════════════════════════════════════════
--
--  Wrapped in  abstract  so that downstream modules
--  (Bridge/FilledEquiv.agda) never re-unfold the 360-case
--  proof when they use the subadditivity lemma.
--
--  Since  _≤ℚ_  is propositional (by isProp≤ℚ, proven in
--  Bridge/FullEnrichedStarObs.agda), sealing the proof
--  does not damage the Univalence bridge.
--
--  Each witness  (k , refl)  type-checks because
--  k + S(A∪B)  reduces judgmentally to  S(A) + S(B)
--  via ℕ addition on closed numerals.
--
--  Reference: §3.5 Approach A (abstract keyword)
--             §3.6 (combined A+C strategy)
--             Agda GitHub Issue #4573
--
--  Generated by sim/prototyping/03_generate_filled_patch.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/03_generate_filled_patch.py

abstract
  subadditivity :
    ∀ {r₁ r₂ r₃ : FilledRegion}
    → r₁ ∪F r₂ ≡F r₃
    → S-filled r₃ ≤ℚ (S-filled r₁ +ℚ S-filled r₂)
  -- lenA=1, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=2+2=4
  subadditivity u0-1-1 = 1 , refl
  -- lenA=1, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=2+3=5
  subadditivity u0-1-2 = 1 , refl
  -- lenA=1, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=2+3=5
  subadditivity u0-1-3 = 1 , refl
  -- lenA=1, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u0-1-4 = 2 , refl
  -- lenA=1, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u0-1-5 = 2 , refl
  -- lenA=1, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=2+4=6
  subadditivity u0-1-6 = 3 , refl
  -- lenA=1, lenB=7:  S(A∪B)=3 ≤ S(A)+S(B)=2+4=6
  subadditivity u0-1-7 = 3 , refl
  -- lenA=1, lenB=8:  S(A∪B)=2 ≤ S(A)+S(B)=2+3=5
  subadditivity u0-1-8 = 3 , refl
  -- lenA=2, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=3+2=5
  subadditivity u0-2-1 = 1 , refl
  -- lenA=2, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u0-2-2 = 2 , refl
  -- lenA=2, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u0-2-3 = 3 , refl
  -- lenA=2, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u0-2-4 = 3 , refl
  -- lenA=2, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u0-2-5 = 4 , refl
  -- lenA=2, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u0-2-6 = 4 , refl
  -- lenA=2, lenB=7:  S(A∪B)=2 ≤ S(A)+S(B)=3+3=6
  subadditivity u0-2-7 = 4 , refl
  -- lenA=3, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u0-3-1 = 2 , refl
  -- lenA=3, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u0-3-2 = 3 , refl
  -- lenA=3, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u0-3-3 = 3 , refl
  -- lenA=3, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u0-3-4 = 5 , refl
  -- lenA=3, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u0-3-5 = 5 , refl
  -- lenA=3, lenB=6:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u0-3-6 = 6 , refl
  -- lenA=4, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u0-4-1 = 2 , refl
  -- lenA=4, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u0-4-2 = 3 , refl
  -- lenA=4, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u0-4-3 = 5 , refl
  -- lenA=4, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u0-4-4 = 5 , refl
  -- lenA=4, lenB=5:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u0-4-5 = 6 , refl
  -- lenA=5, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u0-5-1 = 2 , refl
  -- lenA=5, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u0-5-2 = 4 , refl
  -- lenA=5, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u0-5-3 = 4 , refl
  -- lenA=5, lenB=4:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u0-5-4 = 6 , refl
  -- lenA=6, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=4+2=6
  subadditivity u0-6-1 = 3 , refl
  -- lenA=6, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u0-6-2 = 4 , refl
  -- lenA=6, lenB=3:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u0-6-3 = 6 , refl
  -- lenA=7, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=3+2=5
  subadditivity u0-7-1 = 2 , refl
  -- lenA=7, lenB=2:  S(A∪B)=2 ≤ S(A)+S(B)=3+3=6
  subadditivity u0-7-2 = 4 , refl
  -- lenA=8, lenB=1:  S(A∪B)=2 ≤ S(A)+S(B)=3+2=5
  subadditivity u0-8-1 = 3 , refl
  -- lenA=1, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=2+2=4
  subadditivity u1-1-1 = 1 , refl
  -- lenA=1, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=2+3=5
  subadditivity u1-1-2 = 2 , refl
  -- lenA=1, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u1-1-3 = 2 , refl
  -- lenA=1, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u1-1-4 = 2 , refl
  -- lenA=1, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u1-1-5 = 2 , refl
  -- lenA=1, lenB=6:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u1-1-6 = 2 , refl
  -- lenA=1, lenB=7:  S(A∪B)=3 ≤ S(A)+S(B)=2+3=5
  subadditivity u1-1-7 = 2 , refl
  -- lenA=1, lenB=8:  S(A∪B)=2 ≤ S(A)+S(B)=2+3=5
  subadditivity u1-1-8 = 3 , refl
  -- lenA=2, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=3+2=5
  subadditivity u1-2-1 = 2 , refl
  -- lenA=2, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u1-2-2 = 2 , refl
  -- lenA=2, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u1-2-3 = 2 , refl
  -- lenA=2, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u1-2-4 = 3 , refl
  -- lenA=2, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u1-2-5 = 3 , refl
  -- lenA=2, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u1-2-6 = 4 , refl
  -- lenA=2, lenB=7:  S(A∪B)=2 ≤ S(A)+S(B)=3+4=7
  subadditivity u1-2-7 = 5 , refl
  -- lenA=3, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=3+2=5
  subadditivity u1-3-1 = 1 , refl
  -- lenA=3, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u1-3-2 = 2 , refl
  -- lenA=3, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u1-3-3 = 3 , refl
  -- lenA=3, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u1-3-4 = 3 , refl
  -- lenA=3, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u1-3-5 = 4 , refl
  -- lenA=3, lenB=6:  S(A∪B)=2 ≤ S(A)+S(B)=3+4=7
  subadditivity u1-3-6 = 5 , refl
  -- lenA=4, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u1-4-1 = 2 , refl
  -- lenA=4, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u1-4-2 = 3 , refl
  -- lenA=4, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u1-4-3 = 3 , refl
  -- lenA=4, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u1-4-4 = 5 , refl
  -- lenA=4, lenB=5:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u1-4-5 = 6 , refl
  -- lenA=5, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u1-5-1 = 2 , refl
  -- lenA=5, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u1-5-2 = 3 , refl
  -- lenA=5, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u1-5-3 = 5 , refl
  -- lenA=5, lenB=4:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u1-5-4 = 6 , refl
  -- lenA=6, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u1-6-1 = 2 , refl
  -- lenA=6, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u1-6-2 = 4 , refl
  -- lenA=6, lenB=3:  S(A∪B)=2 ≤ S(A)+S(B)=4+3=7
  subadditivity u1-6-3 = 5 , refl
  -- lenA=7, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=4+2=6
  subadditivity u1-7-1 = 3 , refl
  -- lenA=7, lenB=2:  S(A∪B)=2 ≤ S(A)+S(B)=4+3=7
  subadditivity u1-7-2 = 5 , refl
  -- lenA=8, lenB=1:  S(A∪B)=2 ≤ S(A)+S(B)=3+2=5
  subadditivity u1-8-1 = 3 , refl
  -- lenA=1, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=2+2=4
  subadditivity u2-1-1 = 1 , refl
  -- lenA=1, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=2+3=5
  subadditivity u2-1-2 = 1 , refl
  -- lenA=1, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=2+3=5
  subadditivity u2-1-3 = 1 , refl
  -- lenA=1, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u2-1-4 = 2 , refl
  -- lenA=1, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u2-1-5 = 2 , refl
  -- lenA=1, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=2+4=6
  subadditivity u2-1-6 = 3 , refl
  -- lenA=1, lenB=7:  S(A∪B)=3 ≤ S(A)+S(B)=2+4=6
  subadditivity u2-1-7 = 3 , refl
  -- lenA=1, lenB=8:  S(A∪B)=2 ≤ S(A)+S(B)=2+3=5
  subadditivity u2-1-8 = 3 , refl
  -- lenA=2, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=3+2=5
  subadditivity u2-2-1 = 1 , refl
  -- lenA=2, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u2-2-2 = 2 , refl
  -- lenA=2, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u2-2-3 = 3 , refl
  -- lenA=2, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u2-2-4 = 3 , refl
  -- lenA=2, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u2-2-5 = 4 , refl
  -- lenA=2, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u2-2-6 = 4 , refl
  -- lenA=2, lenB=7:  S(A∪B)=2 ≤ S(A)+S(B)=3+3=6
  subadditivity u2-2-7 = 4 , refl
  -- lenA=3, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u2-3-1 = 2 , refl
  -- lenA=3, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u2-3-2 = 3 , refl
  -- lenA=3, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u2-3-3 = 3 , refl
  -- lenA=3, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u2-3-4 = 5 , refl
  -- lenA=3, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u2-3-5 = 5 , refl
  -- lenA=3, lenB=6:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u2-3-6 = 6 , refl
  -- lenA=4, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u2-4-1 = 2 , refl
  -- lenA=4, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u2-4-2 = 3 , refl
  -- lenA=4, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u2-4-3 = 5 , refl
  -- lenA=4, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u2-4-4 = 5 , refl
  -- lenA=4, lenB=5:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u2-4-5 = 6 , refl
  -- lenA=5, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u2-5-1 = 2 , refl
  -- lenA=5, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u2-5-2 = 4 , refl
  -- lenA=5, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u2-5-3 = 4 , refl
  -- lenA=5, lenB=4:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u2-5-4 = 6 , refl
  -- lenA=6, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=4+2=6
  subadditivity u2-6-1 = 3 , refl
  -- lenA=6, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u2-6-2 = 4 , refl
  -- lenA=6, lenB=3:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u2-6-3 = 6 , refl
  -- lenA=7, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=3+2=5
  subadditivity u2-7-1 = 2 , refl
  -- lenA=7, lenB=2:  S(A∪B)=2 ≤ S(A)+S(B)=3+3=6
  subadditivity u2-7-2 = 4 , refl
  -- lenA=8, lenB=1:  S(A∪B)=2 ≤ S(A)+S(B)=3+2=5
  subadditivity u2-8-1 = 3 , refl
  -- lenA=1, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=2+2=4
  subadditivity u3-1-1 = 1 , refl
  -- lenA=1, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=2+3=5
  subadditivity u3-1-2 = 2 , refl
  -- lenA=1, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u3-1-3 = 2 , refl
  -- lenA=1, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u3-1-4 = 2 , refl
  -- lenA=1, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u3-1-5 = 2 , refl
  -- lenA=1, lenB=6:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u3-1-6 = 2 , refl
  -- lenA=1, lenB=7:  S(A∪B)=3 ≤ S(A)+S(B)=2+3=5
  subadditivity u3-1-7 = 2 , refl
  -- lenA=1, lenB=8:  S(A∪B)=2 ≤ S(A)+S(B)=2+3=5
  subadditivity u3-1-8 = 3 , refl
  -- lenA=2, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=3+2=5
  subadditivity u3-2-1 = 2 , refl
  -- lenA=2, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u3-2-2 = 2 , refl
  -- lenA=2, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u3-2-3 = 2 , refl
  -- lenA=2, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u3-2-4 = 3 , refl
  -- lenA=2, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u3-2-5 = 3 , refl
  -- lenA=2, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u3-2-6 = 4 , refl
  -- lenA=2, lenB=7:  S(A∪B)=2 ≤ S(A)+S(B)=3+4=7
  subadditivity u3-2-7 = 5 , refl
  -- lenA=3, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=3+2=5
  subadditivity u3-3-1 = 1 , refl
  -- lenA=3, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u3-3-2 = 2 , refl
  -- lenA=3, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u3-3-3 = 3 , refl
  -- lenA=3, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u3-3-4 = 3 , refl
  -- lenA=3, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u3-3-5 = 4 , refl
  -- lenA=3, lenB=6:  S(A∪B)=2 ≤ S(A)+S(B)=3+4=7
  subadditivity u3-3-6 = 5 , refl
  -- lenA=4, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u3-4-1 = 2 , refl
  -- lenA=4, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u3-4-2 = 3 , refl
  -- lenA=4, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u3-4-3 = 3 , refl
  -- lenA=4, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u3-4-4 = 5 , refl
  -- lenA=4, lenB=5:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u3-4-5 = 6 , refl
  -- lenA=5, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u3-5-1 = 2 , refl
  -- lenA=5, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u3-5-2 = 3 , refl
  -- lenA=5, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u3-5-3 = 5 , refl
  -- lenA=5, lenB=4:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u3-5-4 = 6 , refl
  -- lenA=6, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u3-6-1 = 2 , refl
  -- lenA=6, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u3-6-2 = 4 , refl
  -- lenA=6, lenB=3:  S(A∪B)=2 ≤ S(A)+S(B)=4+3=7
  subadditivity u3-6-3 = 5 , refl
  -- lenA=7, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=4+2=6
  subadditivity u3-7-1 = 3 , refl
  -- lenA=7, lenB=2:  S(A∪B)=2 ≤ S(A)+S(B)=4+3=7
  subadditivity u3-7-2 = 5 , refl
  -- lenA=8, lenB=1:  S(A∪B)=2 ≤ S(A)+S(B)=3+2=5
  subadditivity u3-8-1 = 3 , refl
  -- lenA=1, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=2+2=4
  subadditivity u4-1-1 = 1 , refl
  -- lenA=1, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=2+3=5
  subadditivity u4-1-2 = 1 , refl
  -- lenA=1, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=2+3=5
  subadditivity u4-1-3 = 1 , refl
  -- lenA=1, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u4-1-4 = 2 , refl
  -- lenA=1, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u4-1-5 = 2 , refl
  -- lenA=1, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=2+4=6
  subadditivity u4-1-6 = 3 , refl
  -- lenA=1, lenB=7:  S(A∪B)=3 ≤ S(A)+S(B)=2+4=6
  subadditivity u4-1-7 = 3 , refl
  -- lenA=1, lenB=8:  S(A∪B)=2 ≤ S(A)+S(B)=2+3=5
  subadditivity u4-1-8 = 3 , refl
  -- lenA=2, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=3+2=5
  subadditivity u4-2-1 = 1 , refl
  -- lenA=2, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u4-2-2 = 2 , refl
  -- lenA=2, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u4-2-3 = 3 , refl
  -- lenA=2, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u4-2-4 = 3 , refl
  -- lenA=2, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u4-2-5 = 4 , refl
  -- lenA=2, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u4-2-6 = 4 , refl
  -- lenA=2, lenB=7:  S(A∪B)=2 ≤ S(A)+S(B)=3+3=6
  subadditivity u4-2-7 = 4 , refl
  -- lenA=3, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u4-3-1 = 2 , refl
  -- lenA=3, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u4-3-2 = 3 , refl
  -- lenA=3, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u4-3-3 = 3 , refl
  -- lenA=3, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u4-3-4 = 5 , refl
  -- lenA=3, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u4-3-5 = 5 , refl
  -- lenA=3, lenB=6:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u4-3-6 = 6 , refl
  -- lenA=4, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u4-4-1 = 2 , refl
  -- lenA=4, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u4-4-2 = 3 , refl
  -- lenA=4, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u4-4-3 = 5 , refl
  -- lenA=4, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u4-4-4 = 5 , refl
  -- lenA=4, lenB=5:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u4-4-5 = 6 , refl
  -- lenA=5, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u4-5-1 = 2 , refl
  -- lenA=5, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u4-5-2 = 4 , refl
  -- lenA=5, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u4-5-3 = 4 , refl
  -- lenA=5, lenB=4:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u4-5-4 = 6 , refl
  -- lenA=6, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=4+2=6
  subadditivity u4-6-1 = 3 , refl
  -- lenA=6, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u4-6-2 = 4 , refl
  -- lenA=6, lenB=3:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u4-6-3 = 6 , refl
  -- lenA=7, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=3+2=5
  subadditivity u4-7-1 = 2 , refl
  -- lenA=7, lenB=2:  S(A∪B)=2 ≤ S(A)+S(B)=3+3=6
  subadditivity u4-7-2 = 4 , refl
  -- lenA=8, lenB=1:  S(A∪B)=2 ≤ S(A)+S(B)=3+2=5
  subadditivity u4-8-1 = 3 , refl
  -- lenA=1, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=2+2=4
  subadditivity u5-1-1 = 1 , refl
  -- lenA=1, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=2+3=5
  subadditivity u5-1-2 = 2 , refl
  -- lenA=1, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u5-1-3 = 2 , refl
  -- lenA=1, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u5-1-4 = 2 , refl
  -- lenA=1, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u5-1-5 = 2 , refl
  -- lenA=1, lenB=6:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u5-1-6 = 2 , refl
  -- lenA=1, lenB=7:  S(A∪B)=3 ≤ S(A)+S(B)=2+3=5
  subadditivity u5-1-7 = 2 , refl
  -- lenA=1, lenB=8:  S(A∪B)=2 ≤ S(A)+S(B)=2+3=5
  subadditivity u5-1-8 = 3 , refl
  -- lenA=2, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=3+2=5
  subadditivity u5-2-1 = 2 , refl
  -- lenA=2, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u5-2-2 = 2 , refl
  -- lenA=2, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u5-2-3 = 2 , refl
  -- lenA=2, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u5-2-4 = 3 , refl
  -- lenA=2, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u5-2-5 = 3 , refl
  -- lenA=2, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u5-2-6 = 4 , refl
  -- lenA=2, lenB=7:  S(A∪B)=2 ≤ S(A)+S(B)=3+4=7
  subadditivity u5-2-7 = 5 , refl
  -- lenA=3, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=3+2=5
  subadditivity u5-3-1 = 1 , refl
  -- lenA=3, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u5-3-2 = 2 , refl
  -- lenA=3, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u5-3-3 = 3 , refl
  -- lenA=3, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u5-3-4 = 3 , refl
  -- lenA=3, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u5-3-5 = 4 , refl
  -- lenA=3, lenB=6:  S(A∪B)=2 ≤ S(A)+S(B)=3+4=7
  subadditivity u5-3-6 = 5 , refl
  -- lenA=4, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u5-4-1 = 2 , refl
  -- lenA=4, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u5-4-2 = 3 , refl
  -- lenA=4, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u5-4-3 = 3 , refl
  -- lenA=4, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u5-4-4 = 5 , refl
  -- lenA=4, lenB=5:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u5-4-5 = 6 , refl
  -- lenA=5, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u5-5-1 = 2 , refl
  -- lenA=5, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u5-5-2 = 3 , refl
  -- lenA=5, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u5-5-3 = 5 , refl
  -- lenA=5, lenB=4:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u5-5-4 = 6 , refl
  -- lenA=6, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u5-6-1 = 2 , refl
  -- lenA=6, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u5-6-2 = 4 , refl
  -- lenA=6, lenB=3:  S(A∪B)=2 ≤ S(A)+S(B)=4+3=7
  subadditivity u5-6-3 = 5 , refl
  -- lenA=7, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=4+2=6
  subadditivity u5-7-1 = 3 , refl
  -- lenA=7, lenB=2:  S(A∪B)=2 ≤ S(A)+S(B)=4+3=7
  subadditivity u5-7-2 = 5 , refl
  -- lenA=8, lenB=1:  S(A∪B)=2 ≤ S(A)+S(B)=3+2=5
  subadditivity u5-8-1 = 3 , refl
  -- lenA=1, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=2+2=4
  subadditivity u6-1-1 = 1 , refl
  -- lenA=1, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=2+3=5
  subadditivity u6-1-2 = 1 , refl
  -- lenA=1, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=2+3=5
  subadditivity u6-1-3 = 1 , refl
  -- lenA=1, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u6-1-4 = 2 , refl
  -- lenA=1, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u6-1-5 = 2 , refl
  -- lenA=1, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=2+4=6
  subadditivity u6-1-6 = 3 , refl
  -- lenA=1, lenB=7:  S(A∪B)=3 ≤ S(A)+S(B)=2+4=6
  subadditivity u6-1-7 = 3 , refl
  -- lenA=1, lenB=8:  S(A∪B)=2 ≤ S(A)+S(B)=2+3=5
  subadditivity u6-1-8 = 3 , refl
  -- lenA=2, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=3+2=5
  subadditivity u6-2-1 = 1 , refl
  -- lenA=2, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u6-2-2 = 2 , refl
  -- lenA=2, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u6-2-3 = 3 , refl
  -- lenA=2, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u6-2-4 = 3 , refl
  -- lenA=2, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u6-2-5 = 4 , refl
  -- lenA=2, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u6-2-6 = 4 , refl
  -- lenA=2, lenB=7:  S(A∪B)=2 ≤ S(A)+S(B)=3+3=6
  subadditivity u6-2-7 = 4 , refl
  -- lenA=3, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u6-3-1 = 2 , refl
  -- lenA=3, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u6-3-2 = 3 , refl
  -- lenA=3, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u6-3-3 = 3 , refl
  -- lenA=3, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u6-3-4 = 5 , refl
  -- lenA=3, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u6-3-5 = 5 , refl
  -- lenA=3, lenB=6:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u6-3-6 = 6 , refl
  -- lenA=4, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u6-4-1 = 2 , refl
  -- lenA=4, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u6-4-2 = 3 , refl
  -- lenA=4, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u6-4-3 = 5 , refl
  -- lenA=4, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u6-4-4 = 5 , refl
  -- lenA=4, lenB=5:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u6-4-5 = 6 , refl
  -- lenA=5, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u6-5-1 = 2 , refl
  -- lenA=5, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u6-5-2 = 4 , refl
  -- lenA=5, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u6-5-3 = 4 , refl
  -- lenA=5, lenB=4:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u6-5-4 = 6 , refl
  -- lenA=6, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=4+2=6
  subadditivity u6-6-1 = 3 , refl
  -- lenA=6, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u6-6-2 = 4 , refl
  -- lenA=6, lenB=3:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u6-6-3 = 6 , refl
  -- lenA=7, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=3+2=5
  subadditivity u6-7-1 = 2 , refl
  -- lenA=7, lenB=2:  S(A∪B)=2 ≤ S(A)+S(B)=3+3=6
  subadditivity u6-7-2 = 4 , refl
  -- lenA=8, lenB=1:  S(A∪B)=2 ≤ S(A)+S(B)=3+2=5
  subadditivity u6-8-1 = 3 , refl
  -- lenA=1, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=2+2=4
  subadditivity u7-1-1 = 1 , refl
  -- lenA=1, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=2+3=5
  subadditivity u7-1-2 = 2 , refl
  -- lenA=1, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u7-1-3 = 2 , refl
  -- lenA=1, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u7-1-4 = 2 , refl
  -- lenA=1, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u7-1-5 = 2 , refl
  -- lenA=1, lenB=6:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u7-1-6 = 2 , refl
  -- lenA=1, lenB=7:  S(A∪B)=3 ≤ S(A)+S(B)=2+3=5
  subadditivity u7-1-7 = 2 , refl
  -- lenA=1, lenB=8:  S(A∪B)=2 ≤ S(A)+S(B)=2+3=5
  subadditivity u7-1-8 = 3 , refl
  -- lenA=2, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=3+2=5
  subadditivity u7-2-1 = 2 , refl
  -- lenA=2, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u7-2-2 = 2 , refl
  -- lenA=2, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u7-2-3 = 2 , refl
  -- lenA=2, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u7-2-4 = 3 , refl
  -- lenA=2, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u7-2-5 = 3 , refl
  -- lenA=2, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u7-2-6 = 4 , refl
  -- lenA=2, lenB=7:  S(A∪B)=2 ≤ S(A)+S(B)=3+4=7
  subadditivity u7-2-7 = 5 , refl
  -- lenA=3, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=3+2=5
  subadditivity u7-3-1 = 1 , refl
  -- lenA=3, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u7-3-2 = 2 , refl
  -- lenA=3, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u7-3-3 = 3 , refl
  -- lenA=3, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u7-3-4 = 3 , refl
  -- lenA=3, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u7-3-5 = 4 , refl
  -- lenA=3, lenB=6:  S(A∪B)=2 ≤ S(A)+S(B)=3+4=7
  subadditivity u7-3-6 = 5 , refl
  -- lenA=4, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u7-4-1 = 2 , refl
  -- lenA=4, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u7-4-2 = 3 , refl
  -- lenA=4, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u7-4-3 = 3 , refl
  -- lenA=4, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u7-4-4 = 5 , refl
  -- lenA=4, lenB=5:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u7-4-5 = 6 , refl
  -- lenA=5, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u7-5-1 = 2 , refl
  -- lenA=5, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u7-5-2 = 3 , refl
  -- lenA=5, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u7-5-3 = 5 , refl
  -- lenA=5, lenB=4:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u7-5-4 = 6 , refl
  -- lenA=6, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u7-6-1 = 2 , refl
  -- lenA=6, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u7-6-2 = 4 , refl
  -- lenA=6, lenB=3:  S(A∪B)=2 ≤ S(A)+S(B)=4+3=7
  subadditivity u7-6-3 = 5 , refl
  -- lenA=7, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=4+2=6
  subadditivity u7-7-1 = 3 , refl
  -- lenA=7, lenB=2:  S(A∪B)=2 ≤ S(A)+S(B)=4+3=7
  subadditivity u7-7-2 = 5 , refl
  -- lenA=8, lenB=1:  S(A∪B)=2 ≤ S(A)+S(B)=3+2=5
  subadditivity u7-8-1 = 3 , refl
  -- lenA=1, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=2+2=4
  subadditivity u8-1-1 = 1 , refl
  -- lenA=1, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=2+3=5
  subadditivity u8-1-2 = 1 , refl
  -- lenA=1, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=2+3=5
  subadditivity u8-1-3 = 1 , refl
  -- lenA=1, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u8-1-4 = 2 , refl
  -- lenA=1, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u8-1-5 = 2 , refl
  -- lenA=1, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=2+4=6
  subadditivity u8-1-6 = 3 , refl
  -- lenA=1, lenB=7:  S(A∪B)=3 ≤ S(A)+S(B)=2+4=6
  subadditivity u8-1-7 = 3 , refl
  -- lenA=1, lenB=8:  S(A∪B)=2 ≤ S(A)+S(B)=2+3=5
  subadditivity u8-1-8 = 3 , refl
  -- lenA=2, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=3+2=5
  subadditivity u8-2-1 = 1 , refl
  -- lenA=2, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u8-2-2 = 2 , refl
  -- lenA=2, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u8-2-3 = 3 , refl
  -- lenA=2, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u8-2-4 = 3 , refl
  -- lenA=2, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u8-2-5 = 4 , refl
  -- lenA=2, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u8-2-6 = 4 , refl
  -- lenA=2, lenB=7:  S(A∪B)=2 ≤ S(A)+S(B)=3+3=6
  subadditivity u8-2-7 = 4 , refl
  -- lenA=3, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u8-3-1 = 2 , refl
  -- lenA=3, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u8-3-2 = 3 , refl
  -- lenA=3, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u8-3-3 = 3 , refl
  -- lenA=3, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u8-3-4 = 5 , refl
  -- lenA=3, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u8-3-5 = 5 , refl
  -- lenA=3, lenB=6:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u8-3-6 = 6 , refl
  -- lenA=4, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u8-4-1 = 2 , refl
  -- lenA=4, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u8-4-2 = 3 , refl
  -- lenA=4, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u8-4-3 = 5 , refl
  -- lenA=4, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u8-4-4 = 5 , refl
  -- lenA=4, lenB=5:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u8-4-5 = 6 , refl
  -- lenA=5, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u8-5-1 = 2 , refl
  -- lenA=5, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u8-5-2 = 4 , refl
  -- lenA=5, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u8-5-3 = 4 , refl
  -- lenA=5, lenB=4:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u8-5-4 = 6 , refl
  -- lenA=6, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=4+2=6
  subadditivity u8-6-1 = 3 , refl
  -- lenA=6, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u8-6-2 = 4 , refl
  -- lenA=6, lenB=3:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u8-6-3 = 6 , refl
  -- lenA=7, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=3+2=5
  subadditivity u8-7-1 = 2 , refl
  -- lenA=7, lenB=2:  S(A∪B)=2 ≤ S(A)+S(B)=3+3=6
  subadditivity u8-7-2 = 4 , refl
  -- lenA=8, lenB=1:  S(A∪B)=2 ≤ S(A)+S(B)=3+2=5
  subadditivity u8-8-1 = 3 , refl
  -- lenA=1, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=2+2=4
  subadditivity u9-1-1 = 1 , refl
  -- lenA=1, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=2+3=5
  subadditivity u9-1-2 = 2 , refl
  -- lenA=1, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u9-1-3 = 2 , refl
  -- lenA=1, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u9-1-4 = 2 , refl
  -- lenA=1, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u9-1-5 = 2 , refl
  -- lenA=1, lenB=6:  S(A∪B)=4 ≤ S(A)+S(B)=2+4=6
  subadditivity u9-1-6 = 2 , refl
  -- lenA=1, lenB=7:  S(A∪B)=3 ≤ S(A)+S(B)=2+3=5
  subadditivity u9-1-7 = 2 , refl
  -- lenA=1, lenB=8:  S(A∪B)=2 ≤ S(A)+S(B)=2+3=5
  subadditivity u9-1-8 = 3 , refl
  -- lenA=2, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=3+2=5
  subadditivity u9-2-1 = 2 , refl
  -- lenA=2, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u9-2-2 = 2 , refl
  -- lenA=2, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u9-2-3 = 2 , refl
  -- lenA=2, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u9-2-4 = 3 , refl
  -- lenA=2, lenB=5:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u9-2-5 = 3 , refl
  -- lenA=2, lenB=6:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u9-2-6 = 4 , refl
  -- lenA=2, lenB=7:  S(A∪B)=2 ≤ S(A)+S(B)=3+4=7
  subadditivity u9-2-7 = 5 , refl
  -- lenA=3, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=3+2=5
  subadditivity u9-3-1 = 1 , refl
  -- lenA=3, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=3+3=6
  subadditivity u9-3-2 = 2 , refl
  -- lenA=3, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u9-3-3 = 3 , refl
  -- lenA=3, lenB=4:  S(A∪B)=4 ≤ S(A)+S(B)=3+4=7
  subadditivity u9-3-4 = 3 , refl
  -- lenA=3, lenB=5:  S(A∪B)=3 ≤ S(A)+S(B)=3+4=7
  subadditivity u9-3-5 = 4 , refl
  -- lenA=3, lenB=6:  S(A∪B)=2 ≤ S(A)+S(B)=3+4=7
  subadditivity u9-3-6 = 5 , refl
  -- lenA=4, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u9-4-1 = 2 , refl
  -- lenA=4, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u9-4-2 = 3 , refl
  -- lenA=4, lenB=3:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u9-4-3 = 3 , refl
  -- lenA=4, lenB=4:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u9-4-4 = 5 , refl
  -- lenA=4, lenB=5:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u9-4-5 = 6 , refl
  -- lenA=5, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u9-5-1 = 2 , refl
  -- lenA=5, lenB=2:  S(A∪B)=4 ≤ S(A)+S(B)=4+3=7
  subadditivity u9-5-2 = 3 , refl
  -- lenA=5, lenB=3:  S(A∪B)=3 ≤ S(A)+S(B)=4+4=8
  subadditivity u9-5-3 = 5 , refl
  -- lenA=5, lenB=4:  S(A∪B)=2 ≤ S(A)+S(B)=4+4=8
  subadditivity u9-5-4 = 6 , refl
  -- lenA=6, lenB=1:  S(A∪B)=4 ≤ S(A)+S(B)=4+2=6
  subadditivity u9-6-1 = 2 , refl
  -- lenA=6, lenB=2:  S(A∪B)=3 ≤ S(A)+S(B)=4+3=7
  subadditivity u9-6-2 = 4 , refl
  -- lenA=6, lenB=3:  S(A∪B)=2 ≤ S(A)+S(B)=4+3=7
  subadditivity u9-6-3 = 5 , refl
  -- lenA=7, lenB=1:  S(A∪B)=3 ≤ S(A)+S(B)=4+2=6
  subadditivity u9-7-1 = 3 , refl
  -- lenA=7, lenB=2:  S(A∪B)=2 ≤ S(A)+S(B)=4+3=7
  subadditivity u9-7-2 = 5 , refl
  -- lenA=8, lenB=1:  S(A∪B)=2 ≤ S(A)+S(B)=3+2=5
  subadditivity u9-8-1 = 3 , refl

