{-# OPTIONS --cubical --safe --guardedness #-}

module Boundary.Layer54d5Cut where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Layer54d5Spec

record Layer54d5BdyView : Type₀ where
  field
    dummy : ℚ≥0

-- S-cut-rep — Boundary min-cut on orbit representatives
--  Generated by sim/prototyping/13_generate_layerN.py --depth 5
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 5

S-cut-rep : Layer54d5OrbitRep → ℚ≥0
S-cut-rep mc1 = 1
S-cut-rep mc2 = 2

-- S-cut — Boundary min-cut (via orbit reduction)
S-cut : Layer54d5BdyView → Layer54d5Region → ℚ≥0
S-cut _ r = S-cut-rep (classifyLayer54d5 r)

