{-# OPTIONS --cubical --safe --guardedness #-}

module Bridge.Dense200Obs where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Dense200Spec
open import Common.ObsPackage
open import Boundary.Dense200Cut
open import Bulk.Dense200Chain

d200BdyView : D200BdyView
d200BdyView .D200BdyView.dummy = 0

d200BulkView : D200BulkView
d200BulkView .D200BulkView.dummy = 0

D200Obs∂ : ObsPackage D200Region
D200Obs∂ .ObsPackage.obs = S-cut d200BdyView

D200ObsBulk : ObsPackage D200Region
D200ObsBulk .ObsPackage.obs = L-min d200BulkView

-- ═══════════════════════════════════════════════════════════
--  d200-pointwise-rep — All 9 orbit cases by refl
-- ═══════════════════════════════════════════════════════════
--
--  The core proof: S-cut-rep and L-min-rep agree on every
--  orbit representative.  Both return the same ℕ literal,
--  so each case holds by refl.
--
--  Generated by sim/prototyping/12_generate_dense200.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/12_generate_dense200.py

d200-pointwise-rep :
  (o : D200OrbitRep) → S-cut-rep o ≡ L-min-rep o
d200-pointwise-rep mc1 = refl
d200-pointwise-rep mc2 = refl
d200-pointwise-rep mc3 = refl
d200-pointwise-rep mc4 = refl
d200-pointwise-rep mc5 = refl
d200-pointwise-rep mc6 = refl
d200-pointwise-rep mc7 = refl
d200-pointwise-rep mc8 = refl
d200-pointwise-rep mc9 = refl

-- ═══════════════════════════════════════════════════════════
--  d200-pointwise — Lifted to all 1246 regions
-- ═══════════════════════════════════════════════════════════
--
--  Single-line proof composing orbit-level proof with classify200.
--
--  Generated by sim/prototyping/12_generate_dense200.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/12_generate_dense200.py

d200-pointwise :
  (r : D200Region) →
  S-cut d200BdyView r ≡ L-min d200BulkView r
d200-pointwise r = d200-pointwise-rep (classify200 r)

S∂D200 : D200Region → ℚ≥0
S∂D200 = S-cut d200BdyView

LBD200 : D200Region → ℚ≥0
LBD200 = L-min d200BulkView

d200-obs-path : S∂D200 ≡ LBD200
d200-obs-path = funExt d200-pointwise

d200-package-path : D200Obs∂ ≡ D200ObsBulk
d200-package-path i .ObsPackage.obs = d200-obs-path i

