{-# OPTIONS --cubical --safe --guardedness #-}

module Bridge.Dense100Thermodynamics where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Sigma using (Σ-syntax)

open import Util.Scalars
open import Common.Dense100Spec
  using (D100Region ; D100OrbitRep ; classify100 ;
         d100r0 ; d100r1 ; d100r4 ; d100r8 ; d100r15 ; d100r215)
open import Boundary.Dense100Cut
  using (D100BdyView ; S-cut ; S-cut-rep)
open import Bridge.Dense100Obs
  using (d100BdyView)
open import Bridge.CoarseGrain
  using ( CoarseGrainWitness ; CoarseGrainedRT
        ; dense100-coarse-witness )
open import Boundary.Dense100AreaLaw
  using (regionArea ; area-law)

-- ── Phase B imports: the discrete Bekenstein–Hawking half-bound ────
open import Bridge.HalfBound
  using (HalfBoundWitness)
open import Boundary.Dense100HalfBound
  using (dense100HalfBound)
  renaming ( half-bound-proof to d100-half-bound-proof
           ; tight-witness    to d100-tight-witness )


-- ════════════════════════════════════════════════════════════════════
--  Dense-100 Thermodynamic Illusion — Coarse-Grained RT Instantiation
-- ════════════════════════════════════════════════════════════════════
--
--  This module is the capstone of the thermodynamic layer
--  (docs/formal/09-thermodynamics.md).
--  It instantiates  CoarseGrainedRT  from Bridge/CoarseGrain.agda
--  by combining three independently constructed components:
--
--    1.  dense100-coarse-witness : CoarseGrainWitness
--        — The orbit reduction from 717 fine-grained regions to
--          8 orbit representatives, with compat by refl.
--          (Bridge/CoarseGrain.agda)
--
--    2.  regionArea : D100Region → ℚ≥0
--        — The boundary surface area of each cell-aligned region,
--          computed as  6k − 2·|internal faces within A| .
--          (Boundary/Dense100AreaLaw.agda, generated by
--           sim/prototyping/11_generate_area_law.py)
--
--    3.  area-law : (r : D100Region) → S-cut d100BdyView r ≤ℚ regionArea r
--        — The discrete isoperimetric inequality, verified on all
--          717 regions by (k , refl) witnesses, sealed in abstract.
--          (Boundary/Dense100AreaLaw.agda)
--
--  The module now also carries the STRENGTHENED discrete
--  Bekenstein–Hawking half-bound (Theorem 3 in the canonical
--  theorem registry, docs/formal/01-theorems.md):
--
--    4.  dense100HalfBound : HalfBoundWitness pd
--        — The sharp bound  2·S(A) ≤ area(A)  for all 717 regions,
--          with a tight achiever where  2·S = area .
--          (Boundary/Dense100HalfBound.agda, generated by
--           sim/prototyping/17_generate_half_bound.py)
--
--  The half-bound SUBSUMES the area law:  2·S ≤ area  implies
--  S ≤ area  (since S ≤ 2·S ≤ area for non-negative S).  But
--  both are kept for backward compatibility: existing code consuming
--  area-law continues to work, and the half-bound provides the
--  strictest constraint.
--
--  The key architectural consequence (docs/formal/12-bekenstein-hawking.md):
--  the old  ConvergenceWitness  (which required constructive reals
--  and Cauchy completeness for the η_N limit) is REPLACED by the
--  sharp half-bound (which requires only ℕ arithmetic and refl).
--  The discrete Newton's constant  1/(4G) = 1/2  in bond-dimension-1
--  units is verified by refl on closed ℕ terms at every resolution
--  level.  This ELIMINATES the constructive-reals wall
--  (docs/physics/five-walls.md) for the entropy-area relationship.
--
--  Reference:
--    docs/formal/09-thermodynamics.md    (area law, coarse-graining,
--                                         resolution tower)
--    docs/formal/12-bekenstein-hawking.md (discrete BH proof,
--                                         HalfBound, from-two-cuts)
--    docs/formal/01-theorems.md §Thm 3   (Discrete Bekenstein–Hawking)
--    docs/formal/11-generic-bridge.md    (SchematicTower, tower form)
--    docs/instances/dense-100.md         (Dense-100 instance data)
--    docs/physics/five-walls.md          (constructive-reals wall)
--    docs/physics/discrete-bekenstein-hawking.md
--                                        (physics interpretation)
--    sim/prototyping/11_generate_area_law.py   (area-law oracle)
--    sim/prototyping/17_generate_half_bound.py (half-bound oracle)
--
--  Architectural role:
--    This is a Tier 3 (Bridge Layer) module.  It integrates the
--    CoarseGrainedRT triple and the HalfBoundWitness for the
--    Dense-100 patch, providing three levels of entropy-area
--    constraint through the same observable S-cut d100BdyView
--    and the same area function regionArea.
--    See docs/getting-started/architecture.md for the module
--    dependency DAG.
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
--  §1.  Type Compatibility Verification
-- ════════════════════════════════════════════════════════════════════
--
--  Before constructing the triple, we verify that all types align:
--
--    CoarseGrainWitness.FineRegion dense100-coarse-witness
--      = D100Region                              (definitional)
--
--    CoarseGrainWitness.obs-fine dense100-coarse-witness
--      = S-cut d100BdyView                       (definitional)
--
--  Therefore:
--    • regionArea : D100Region → ℚ≥0
--      has the type expected by the second Sigma component:
--        CoarseGrainWitness.FineRegion dense100-coarse-witness → ℚ≥0
--
--    • area-law : (r : D100Region) → S-cut d100BdyView r ≤ℚ regionArea r
--      has the type expected by the third Sigma component:
--        (r : CoarseGrainWitness.FineRegion w) →
--        CoarseGrainWitness.obs-fine w r ≤ℚ regionArea r
--
--  These equalities hold definitionally, so no coercion is needed.
-- ════════════════════════════════════════════════════════════════════

private
  -- FineRegion of the witness is D100Region
  fine-region-check :
    CoarseGrainWitness.FineRegion dense100-coarse-witness ≡ D100Region
  fine-region-check = refl

  -- obs-fine of the witness is S-cut d100BdyView
  obs-fine-check :
    CoarseGrainWitness.obs-fine dense100-coarse-witness ≡ S-cut d100BdyView
  obs-fine-check = refl


-- ════════════════════════════════════════════════════════════════════
--  §2.  The CoarseGrainedRT Instance
-- ════════════════════════════════════════════════════════════════════
--
--  The fully formalized thermodynamic statement
--  (docs/formal/09-thermodynamics.md §6):
--
--    CoarseGrainedRT = Σ[ w ∈ CoarseGrainWitness ]
--      Σ[ regionArea ∈ (FineRegion w → ℚ≥0) ]
--        ((r : FineRegion w) → obs-fine w r ≤ℚ regionArea r)
--
--  The triple (dense100-coarse-witness , regionArea , area-law)
--  instantiates this type because:
--
--    w           = dense100-coarse-witness
--    regionArea  : FineRegion w → ℚ≥0
--                = D100Region → ℚ≥0             (definitional)
--    area-law    : (r : FineRegion w) → obs-fine w r ≤ℚ regionArea r
--                = (r : D100Region) → S-cut d100BdyView r ≤ℚ regionArea r
--                                                        (definitional)
--
--  The area-law field is abstract (sealed in Dense100AreaLaw.agda),
--  so downstream modules never re-unfold the 717 case analyses.
--  Since _≤ℚ_ is propositional (by isProp≤ℚ from
--  Bridge/FullEnrichedStarObs.agda), the abstract barrier does not
--  damage any Univalence bridge or transport computation.
--  See docs/engineering/abstract-barrier.md for details.
-- ════════════════════════════════════════════════════════════════════

dense100-thermodynamics : CoarseGrainedRT
dense100-thermodynamics = dense100-coarse-witness , regionArea , area-law


-- ════════════════════════════════════════════════════════════════════
--  §3.  Component Extraction
-- ════════════════════════════════════════════════════════════════════
--
--  The three components of the triple are extractable as projections.
--  These serve as stable references for downstream modules and
--  documentation.
-- ════════════════════════════════════════════════════════════════════

-- The coarse-graining witness (orbit reduction 717 → 8)
the-witness : CoarseGrainWitness
the-witness = fst dense100-thermodynamics

-- The boundary area function
the-area : D100Region → ℚ≥0
the-area = fst (snd dense100-thermodynamics)

-- The area-law bound (abstract)
the-bound : (r : D100Region)
  → CoarseGrainWitness.obs-fine the-witness r ≤ℚ the-area r
the-bound = snd (snd dense100-thermodynamics)


-- ════════════════════════════════════════════════════════════════════
--  §4.  Concrete Spot Checks
-- ════════════════════════════════════════════════════════════════════
--
--  These regression tests verify that the instantiated triple
--  produces the expected concrete values at specific regions.
--  Each test exercises the full pipeline:
--
--    D100Region  →classify100→  D100OrbitRep  →S-cut-rep→  ℕ
--    D100Region  →regionArea→  ℕ
--    area-law r  :  Σ[ k ∈ ℕ ] (k + S r ≡ area r)
--
--  The area-law proofs are abstract (we cannot inspect the k
--  component), but we CAN verify the observable and area values.
--
--  See docs/instances/dense-100.md §5 for the full min-cut /
--  observable agreement table.
-- ════════════════════════════════════════════════════════════════════

-- d100r0:  1-cell region, S=1, area=6, slack=5
check-obs-r0 : CoarseGrainWitness.obs-fine the-witness d100r0 ≡ 1
check-obs-r0 = refl

check-area-r0 : the-area d100r0 ≡ 6
check-area-r0 = refl

-- d100r215:  1-cell region, S=2, area=6, slack=4
check-obs-r215 : CoarseGrainWitness.obs-fine the-witness d100r215 ≡ 2
check-obs-r215 = refl

check-area-r215 : the-area d100r215 ≡ 6
check-area-r215 = refl

-- d100r1:  2-cell region, S=3, area=10, slack=7
check-obs-r1 : CoarseGrainWitness.obs-fine the-witness d100r1 ≡ 3
check-obs-r1 = refl

check-area-r1 : the-area d100r1 ≡ 10
check-area-r1 = refl

-- d100r8:  4-cell region, S=5, area=18, slack=13
check-obs-r8 : CoarseGrainWitness.obs-fine the-witness d100r8 ≡ 5
check-obs-r8 = refl

check-area-r8 : the-area d100r8 ≡ 18
check-area-r8 = refl

-- d100r4:  5-cell region, S=7, area=22, slack=15  (high min-cut)
check-obs-r4 : CoarseGrainWitness.obs-fine the-witness d100r4 ≡ 7
check-obs-r4 = refl

check-area-r4 : the-area d100r4 ≡ 22
check-area-r4 = refl

-- d100r15:  5-cell region, S=8, area=22, slack=14  (maximum min-cut)
check-obs-r15 : CoarseGrainWitness.obs-fine the-witness d100r15 ≡ 8
check-obs-r15 = refl

check-area-r15 : the-area d100r15 ≡ 22
check-area-r15 = refl


-- ════════════════════════════════════════════════════════════════════
--  §5.  Orbit Coherence
-- ════════════════════════════════════════════════════════════════════
--
--  The coarse-graining witness carries a  compat  field that
--  witnesses the factorization:
--
--    S-cut d100BdyView r ≡ S-cut-rep (classify100 r)
--
--  This holds by refl because S-cut is DEFINED as
--  S-cut-rep ∘ classify100 in Boundary/Dense100Cut.agda.
--
--  The area-law bound factors through this:
--
--    S-cut d100BdyView r  ≤ℚ  regionArea r
--    ‖ (by compat)
--    S-cut-rep (classify100 r)  ≤ℚ  regionArea r
--
--  An observer who sees only the 8-constructor D100OrbitRep type
--  reads the correct entropy value for each orbit class (via
--  S-cut-rep), and the area law holds for every region in the
--  orbit (via area-law).  This is the type-theoretic content of
--  "statistical averaging preserves the entropy–area relationship."
--
--  See docs/engineering/orbit-reduction.md for the full scaling
--  analysis of the orbit reduction strategy.
-- ════════════════════════════════════════════════════════════════════

-- The compat field is refl (S-cut is S-cut-rep ∘ classify100)
compat-is-trivial : (r : D100Region)
  → S-cut d100BdyView r ≡ S-cut-rep (classify100 r)
compat-is-trivial = CoarseGrainWitness.compat the-witness


-- ════════════════════════════════════════════════════════════════════
--  §6.  Connection to the Enriched Bridge (D100Theorem3)
-- ════════════════════════════════════════════════════════════════════
--
--  The Dense-100 enriched bridge (Bridge/Dense100Equiv.agda) proves
--  the observable-package equivalence:
--
--    transport (ua d100-enriched-equiv) d100-bdy-instance
--      ≡ d100-bulk-instance
--
--  The coarse-grained RT instance in this module is COMPATIBLE with
--  that bridge: both reference the same observable function
--  S-cut d100BdyView : D100Region → ℚ≥0, and the area-law bound
--  provides an additional structural property (the discrete
--  isoperimetric inequality) that coexists with the bridge
--  equivalence.
--
--  Together, the Dense-100 formalization provides:
--
--    Discrete RT correspondence (Theorem 1 via GenericBridge):
--      The exact S = L on 717 regions, with transport along a
--      Univalence path verified.
--      (Bridge/GenericValidation.agda, docs/formal/03-holographic-bridge.md)
--
--    dense100-thermodynamics (this module):
--      The area-law bound S ≤ area on 717 regions, packaged with
--      the orbit reduction into a CoarseGrainedRT triple.
--      (docs/formal/09-thermodynamics.md §6)
--
--    dense100-half-bound-witness (§9 below):
--      The SHARP half-bound 2·S ≤ area on 717 regions, with a
--      tight achiever where 2·S = area.
--      (docs/formal/12-bekenstein-hawking.md)
--
--  The three results are independent (the area-law and half-bound
--  modules do not import the bridge) but share the same fine-grained
--  observable S-cut d100BdyView.
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
--  §7.  The Macroscopic Observer Interpretation
-- ════════════════════════════════════════════════════════════════════
--
--  The Dense-100 orbit reduction implements a concrete "macroscopic
--  observer" with bounded memory
--  (docs/formal/09-thermodynamics.md §7):
--
--    Fine   = D100Region   (717 constructors)
--    Coarse = D100OrbitRep (8 constructors)
--    Memory = 3 bits       (⌈log₂ 8⌉)
--
--  An observer with 3 bits of memory cannot distinguish the 717
--  individual boundary configurations — they see only which of
--  the 8 min-cut-value classes each region belongs to.  The compat
--  field of the coarse-graining witness certifies that this lossy
--  compression preserves the entropy observable exactly.
--
--  The area-law bound (S ≤ area) holds at both resolution levels:
--
--    Fine level:    S-cut d100BdyView r  ≤ℚ  regionArea r
--                   (directly from area-law)
--
--    Coarse level:  S-cut-rep (classify100 r)  ≤ℚ  regionArea r
--                   (by compat + area-law)
--
--  The half-bound (2·S ≤ area) strengthens this to:
--
--    Fine level:    (S r + S r)  ≤ℚ  regionArea r
--                   (directly from d100-half-bound-proof)
--
--  The thermodynamic claim — that as the patch grows (N → ∞) while
--  the observer's memory stays bounded, the coarse-grained
--  observable approaches the continuum entropy formula — is a
--  metatheoretic claim beyond the scope of constructive Cubical
--  Agda (docs/formal/09-thermodynamics.md §8,
--  docs/physics/translation-problem.md).  However, the SHARP
--  half-bound eliminates the need for a limit argument entirely:
--  the discrete Newton's constant is exactly 1/2 at every finite
--  resolution level.
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
--  §8.  Summary and Exit Criterion (Original)
-- ════════════════════════════════════════════════════════════════════
--
--  This module satisfies the original exit criterion for the
--  thermodynamic layer:
--
--    1. ✓  A CoarseGrainWitness record type-checks in
--          Bridge/CoarseGrain.agda with the Dense-100 orbit
--          reduction as the concrete instance.
--
--    2. ✓  A Python-generated Boundary/Dense100AreaLaw.agda
--          contains 717 abstract cases of (k , refl) proving
--          the discrete area law.
--
--    3. ✓  (This module)  The CoarseGrainedRT triple is fully
--          instantiated, combining all three components into a
--          single inspectable Agda term.
--
--  Proof pipeline:
--
--    11_generate_area_law.py       (Python oracle: areas + slacks)
--      │
--      ├──▶ Boundary/Dense100AreaLaw.agda   (regionArea + area-law)
--      │
--      └──▶ Bridge/CoarseGrain.agda         (dense100-coarse-witness)
--              │
--              ▼
--         Bridge/Dense100Thermodynamics.agda  (this module)
--              │
--              ▼
--         dense100-thermodynamics : CoarseGrainedRT
--         = ( dense100-coarse-witness , regionArea , area-law )
--
--  Every step is machine-checked by the Cubical Agda type-checker.
--
--  The fully formalized statement:
--
--    "For every finite discrete holographic patch formalized in
--     this repository, the entropy–area relationship holds exactly
--     at every resolution level accessible to a finite observer."
--
--  is witnessed concretely by  dense100-thermodynamics  for the
--  Dense-100 patch of the {4,3,5} hyperbolic honeycomb.
--
--  Reference:
--    docs/formal/09-thermodynamics.md    (thermodynamic layer)
--    docs/engineering/oracle-pipeline.md  (Python oracle pipeline)
--    docs/instances/dense-100.md          (Dense-100 instance data)
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
-- ════════════════════════════════════════════════════════════════════
--
--  §9.  THE DISCRETE BEKENSTEIN–HAWKING HALF-BOUND (Phase B)
--
--  The sharp half-bound  2·S(A) ≤ area(A)  is proven generically
--  in  Bridge/HalfBound.agda  (via the two-cut decomposition
--  area = n_cross + n_bdy)  and instantiated per-patch by the
--  Python oracle in  Boundary/Dense100HalfBound.agda .
--
--  This section integrates the half-bound with the existing
--  CoarseGrainedRT infrastructure, showing that the strengthened
--  bound coexists with and subsumes the original area law.
--
--  The key result (docs/formal/12-bekenstein-hawking.md):
--
--    The discrete Newton's constant is exactly  1/(4G) = 1/2
--    in bond-dimension-1 units.  This is verified by refl on
--    closed ℕ terms — no limit argument, no constructive reals,
--    no Cauchy completeness needed.
--
--  Reference:
--    docs/formal/12-bekenstein-hawking.md  (formal treatment)
--    docs/physics/discrete-bekenstein-hawking.md  (physics)
--    docs/physics/five-walls.md  (constructive-reals wall bypass)
--
-- ════════════════════════════════════════════════════════════════════
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
--  §9.1  The HalfBoundWitness — Re-exported for downstream use
-- ════════════════════════════════════════════════════════════════════
--
--  The concrete HalfBoundWitness for the Dense-100 patch, imported
--  from  Boundary/Dense100HalfBound.agda .  This packages:
--
--    • area       = regionArea  (from Dense100AreaLaw)
--    • half-bound = d100-half-bound-proof  (abstract, 717 cases)
--    • tight      = d100-tight-witness  (a concrete achiever
--                   where  2·S = area)
--
--  The half-bound subsumes the area law:
--    2·S ≤ area  implies  S ≤ area
--  (since  S ≤ S + S = 2·S ≤ area  for non-negative S).
-- ════════════════════════════════════════════════════════════════════

dense100-half-bound-witness : HalfBoundWitness _
dense100-half-bound-witness = dense100HalfBound


-- ════════════════════════════════════════════════════════════════════
--  §9.2  Half-Bound Spot Checks
-- ════════════════════════════════════════════════════════════════════
--
--  These regression tests verify the half-bound at the same specific
--  regions used in §4 for the area-law spot checks.  The half-bound
--  proofs are abstract (we cannot inspect the slack value k), but
--  we CAN verify that  S + S  and  area  have the expected values.
--
--  Comparison of bounds:
--
--    Region  │  S  │  area  │  S ≤ area  │  2·S ≤ area
--    ────────┼─────┼────────┼───────────┼────────────
--    d100r0  │  1  │    6   │  slack 5  │  slack 4   (2 ≤ 6)
--    d100r215│  2  │    6   │  slack 4  │  slack 2   (4 ≤ 6)
--    d100r1  │  3  │   10   │  slack 7  │  slack 4   (6 ≤ 10)
--    d100r8  │  5  │   18   │  slack 13 │  slack 8   (10 ≤ 18)
--    d100r4  │  7  │   22   │  slack 15 │  slack 8   (14 ≤ 22)
--    d100r15 │  8  │   22   │  slack 14 │  slack 6   (16 ≤ 22)
--
--  The half-bound is STRICTLY TIGHTER in every case: the half-slack
--  values are smaller than the original area-law slack values.
-- ════════════════════════════════════════════════════════════════════

-- 2·S(r0) = 2·1 = 2, area = 6 → half-slack = 4
check-2S-r0 : S-cut d100BdyView d100r0 +ℚ S-cut d100BdyView d100r0 ≡ 2
check-2S-r0 = refl

-- 2·S(r215) = 2·2 = 4, area = 6 → half-slack = 2
check-2S-r215 : S-cut d100BdyView d100r215 +ℚ S-cut d100BdyView d100r215 ≡ 4
check-2S-r215 = refl

-- 2·S(r1) = 2·3 = 6, area = 10 → half-slack = 4
check-2S-r1 : S-cut d100BdyView d100r1 +ℚ S-cut d100BdyView d100r1 ≡ 6
check-2S-r1 = refl

-- 2·S(r8) = 2·5 = 10, area = 18 → half-slack = 8
check-2S-r8 : S-cut d100BdyView d100r8 +ℚ S-cut d100BdyView d100r8 ≡ 10
check-2S-r8 = refl

-- 2·S(r4) = 2·7 = 14, area = 22 → half-slack = 8
check-2S-r4 : S-cut d100BdyView d100r4 +ℚ S-cut d100BdyView d100r4 ≡ 14
check-2S-r4 = refl

-- 2·S(r15) = 2·8 = 16, area = 22 → half-slack = 6
check-2S-r15 : S-cut d100BdyView d100r15 +ℚ S-cut d100BdyView d100r15 ≡ 16
check-2S-r15 = refl


-- ════════════════════════════════════════════════════════════════════
--  §10.  Tight Achiever
-- ════════════════════════════════════════════════════════════════════
--
--  The tight field of the HalfBoundWitness identifies a specific
--  region where  2·S = area  — the bound is SATURATED.  From the
--  Python oracle (17_generate_half_bound_OUTPUT.txt):
--
--    40 achiever regions for Dense-100, all with k=1 cells
--    Example: S=3, area=6, 2·3=6=area  (a single cell with 3
--    neighbors in the {4,3,5} honeycomb: n_cross = 3, n_bdy = 3)
--
--  This is the type-theoretic content of the statement:
--    "1/(4G) = 1/2 in bond-dimension-1 units"
--
--  The achiever exists because some 1-cell regions have exactly
--  half their faces crossing to neighbors (n_cross = 3) and half
--  exposed as boundary legs (n_bdy = 3), giving n_cross = n_bdy
--  = area/2 = 3.  The min-cut saturates both independent cuts.
--
--  Reference:
--    docs/formal/12-bekenstein-hawking.md §4  (per-instance witnesses)
--    docs/physics/discrete-bekenstein-hawking.md §3  (the proof)
-- ════════════════════════════════════════════════════════════════════

-- Re-exported for direct access
the-tight-witness : Σ[ r ∈ D100Region ]
  (S-cut d100BdyView r +ℚ S-cut d100BdyView r ≡ regionArea r)
the-tight-witness = d100-tight-witness


-- ════════════════════════════════════════════════════════════════════
--  §11.  Updated Summary — The Discrete Bekenstein–Hawking Bound
-- ════════════════════════════════════════════════════════════════════
--
--  The Dense-100 formalization now provides THREE levels of
--  entropy-area constraint:
--
--    Level 1 (weak):    S(A) = L(A)     for all 717 regions
--             ← The discrete Ryu–Takayanagi correspondence
--                (Bridge/GenericValidation.agda via GenericBridge)
--                (docs/formal/01-theorems.md §Thm 1)
--
--    Level 2 (medium):  S(A) ≤ area(A)  for all 717 regions
--             ← The discrete isoperimetric inequality
--                (dense100-thermodynamics : CoarseGrainedRT)
--                (docs/formal/09-thermodynamics.md §3)
--
--    Level 3 (sharp):   2·S(A) ≤ area(A)  for all 717 regions
--             ← The discrete Bekenstein–Hawking bound
--                (dense100-half-bound-witness : HalfBoundWitness)
--                with tight achiever:  2·S = area  (40 regions)
--                (docs/formal/12-bekenstein-hawking.md)
--
--  Level 3 subsumes Level 2 (2·S ≤ area implies S ≤ area).
--  Level 1 is independent (RT correspondence, not a bound).
--  All three cohere through the same observable  S-cut d100BdyView
--  and the same area function  regionArea .
--
--  The upgraded proof pipeline:
--
--    11_generate_area_law.py        (areas + S ≤ area slacks)
--    17_generate_half_bound.py      (areas + 2·S ≤ area slacks)
--      │
--      ├──▶ Boundary/Dense100AreaLaw.agda     (regionArea + area-law)
--      ├──▶ Boundary/Dense100HalfBound.agda   (half-bound + tight)
--      │
--      └──▶ Bridge/CoarseGrain.agda           (dense100-coarse-witness)
--              │
--              ▼
--         Bridge/Dense100Thermodynamics.agda    (this module)
--              │
--              ├──▶ dense100-thermodynamics      : CoarseGrainedRT
--              │    = (coarse-witness, regionArea, area-law)
--              │
--              └──▶ dense100-half-bound-witness   : HalfBoundWitness
--                   = (regionArea, half-bound-proof, tight-witness)
--
--  The half-bound is also integrated into the tower infrastructure:
--
--    Bridge/SchematicTower.agda  §25:
--      • dense100-half-bound     : HalfBoundWitness (...)
--      • dense100-half-bound-level : HalfBoundLevel
--      • d100→d200-full          : FullLayerStep (with half-bound)
--      • convergence-certificate-3L-HB : ConvergenceCertificate3L-HB
--      • discrete-bekenstein-hawking   : DiscreteBekensteinHawking
--
--  The fully formalized statement (strengthened from §8):
--
--    "For every finite discrete holographic patch formalized in
--     this repository, the entropy–area relationship
--     S(A) ≤ area(A)/2 holds exactly at every resolution level,
--     with equality achieved.  The discrete Newton's constant is
--     1/(4G) = 1/2 in bond-dimension-1 units, verified by refl
--     on closed ℕ terms — no limit argument needed."
--
--  Reference:
--    docs/formal/01-theorems.md §Thm 3  (theorem registry)
--    docs/formal/09-thermodynamics.md    (area law, coarse-graining)
--    docs/formal/12-bekenstein-hawking.md (half-bound, tower form)
--    docs/formal/11-generic-bridge.md    (SchematicTower)
--    docs/instances/dense-100.md          (Dense-100 instance)
--    docs/getting-started/architecture.md (module dependency DAG)
--    docs/reference/module-index.md       (module description)
--    docs/engineering/oracle-pipeline.md   (Python oracle scripts)
--
-- ════════════════════════════════════════════════════════════════════