{-# OPTIONS --cubical --safe --guardedness #-}

module Bridge.Dense1000Obs where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Dense1000Spec
open import Common.ObsPackage
open import Boundary.Dense1000Cut
open import Bulk.Dense1000Chain

d1000BdyView : D1000BdyView
d1000BdyView .D1000BdyView.dummy = 0

d1000BulkView : D1000BulkView
d1000BulkView .D1000BulkView.dummy = 0

D1000Obs∂ : ObsPackage D1000Region
D1000Obs∂ .ObsPackage.obs = S-cut d1000BdyView

D1000ObsBulk : ObsPackage D1000Region
D1000ObsBulk .ObsPackage.obs = L-min d1000BulkView

--  Generated by sim/prototyping/12b_generate_dense1000.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/12b_generate_dense1000.py

d1000-pointwise-rep :
  (o : D1000OrbitRep) → S-cut-rep o ≡ L-min-rep o
d1000-pointwise-rep mc1 = refl
d1000-pointwise-rep mc2 = refl
d1000-pointwise-rep mc3 = refl
d1000-pointwise-rep mc4 = refl
d1000-pointwise-rep mc5 = refl
d1000-pointwise-rep mc6 = refl
d1000-pointwise-rep mc7 = refl
d1000-pointwise-rep mc8 = refl
d1000-pointwise-rep mc9 = refl

d1000-pointwise :
  (r : D1000Region) →
  S-cut d1000BdyView r ≡ L-min d1000BulkView r
d1000-pointwise r = d1000-pointwise-rep (classify1000 r)

S∂D1000 : D1000Region → ℚ≥0
S∂D1000 = S-cut d1000BdyView

LBD1000 : D1000Region → ℚ≥0
LBD1000 = L-min d1000BulkView

d1000-obs-path : S∂D1000 ≡ LBD1000
d1000-obs-path = funExt d1000-pointwise

d1000-package-path : D1000Obs∂ ≡ D1000ObsBulk
d1000-package-path i .ObsPackage.obs = d1000-obs-path i

