{-# OPTIONS --cubical --safe --guardedness #-}

module Bridge.Dense100Thermodynamics where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Sigma using (Σ-syntax)

open import Util.Scalars
open import Common.Dense100Spec
  using (D100Region ; D100OrbitRep ; classify100 ;
         d100r0 ; d100r1 ; d100r4 ; d100r8 ; d100r15 ; d100r215)
open import Boundary.Dense100Cut
  using (D100BdyView ; S-cut ; S-cut-rep)
open import Bridge.Dense100Obs
  using (d100BdyView)
open import Bridge.CoarseGrain
  using ( CoarseGrainWitness ; CoarseGrainedRT
        ; dense100-coarse-witness )
open import Boundary.Dense100AreaLaw
  using (regionArea ; area-law)


-- ════════════════════════════════════════════════════════════════════
--  Dense-100 Thermodynamic Illusion — Coarse-Grained RT Instantiation
-- ════════════════════════════════════════════════════════════════════
--
--  This module is the capstone of Section 8 of docs/10-frontier.md
--  ("The Grid vs. The Curve: The Thermodynamic Illusion Route").
--  It instantiates  CoarseGrainedRT  from Bridge/CoarseGrain.agda
--  by combining three independently constructed components:
--
--    1.  dense100-coarse-witness : CoarseGrainWitness
--        — The orbit reduction from 717 fine-grained regions to
--          8 orbit representatives, with compat by refl.
--          (Bridge/CoarseGrain.agda)
--
--    2.  regionArea : D100Region → ℚ≥0
--        — The boundary surface area of each cell-aligned region,
--          computed as  6k − 2·|internal faces within A| .
--          (Boundary/Dense100AreaLaw.agda, generated by
--           sim/prototyping/11_generate_area_law.py)
--
--    3.  area-law : (r : D100Region) → S-cut d100BdyView r ≤ℚ regionArea r
--        — The discrete isoperimetric inequality, verified on all
--          717 regions by (k , refl) witnesses, sealed in abstract.
--          (Boundary/Dense100AreaLaw.agda)
--
--  The resulting  CoarseGrainedRT  triple packages:
--
--    a.  The exact discrete RT correspondence (S = L) on all 717
--        regions, inherited from the coarse-graining witness.
--    b.  The orbit reduction (717 → 8 representative classes),
--        inherited from classify100 in Common/Dense100Spec.agda.
--    c.  The area-law upper bound (S ≤ area) on all 717 regions.
--    d.  The factorization: all three cohere through classify100.
--
--  This is the constructive, machine-checked content of the informal
--  statement "gravity is the thermodynamics of entanglement" — for
--  the Dense-100 patch of the {4,3,5} hyperbolic honeycomb.
--
--  The continuum extrapolation — that these discrete witnesses form
--  a convergent sequence whose limit is Einstein's equations — is a
--  physics conjecture supported by the formal evidence, but it is
--  NOT itself a formal theorem (§8.8 of docs/10-frontier.md).
--
--  Reference:
--    docs/10-frontier.md §8.10  (the fully formalized statement)
--    docs/10-frontier.md §8.11  (exit criterion)
--    sim/prototyping/11_generate_area_law.py  (area-law oracle)
--
--  Exit criterion (§8.11.3 — stretch):
--    "A two-level tower instantiation demonstrates resolution-
--     independence of the holographic correspondence."
--
--  This module satisfies §8.11 items 1–2 and contributes to item 3
--  by demonstrating that the area-law bound coheres with the orbit
--  reduction at a single resolution level.
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
--  §1.  Type Compatibility Verification
-- ════════════════════════════════════════════════════════════════════
--
--  Before constructing the triple, we verify that all types align:
--
--    CoarseGrainWitness.FineRegion dense100-coarse-witness
--      = D100Region                              (definitional)
--
--    CoarseGrainWitness.obs-fine dense100-coarse-witness
--      = S-cut d100BdyView                       (definitional)
--
--  Therefore:
--    • regionArea : D100Region → ℚ≥0
--      has the type expected by the second Sigma component:
--        CoarseGrainWitness.FineRegion dense100-coarse-witness → ℚ≥0
--
--    • area-law : (r : D100Region) → S-cut d100BdyView r ≤ℚ regionArea r
--      has the type expected by the third Sigma component:
--        (r : CoarseGrainWitness.FineRegion w) →
--        CoarseGrainWitness.obs-fine w r ≤ℚ regionArea r
--
--  These equalities hold definitionally, so no coercion is needed.
-- ════════════════════════════════════════════════════════════════════

private
  -- FineRegion of the witness is D100Region
  fine-region-check :
    CoarseGrainWitness.FineRegion dense100-coarse-witness ≡ D100Region
  fine-region-check = refl

  -- obs-fine of the witness is S-cut d100BdyView
  obs-fine-check :
    CoarseGrainWitness.obs-fine dense100-coarse-witness ≡ S-cut d100BdyView
  obs-fine-check = refl


-- ════════════════════════════════════════════════════════════════════
--  §2.  The CoarseGrainedRT Instance
-- ════════════════════════════════════════════════════════════════════
--
--  The fully formalized statement from §8.10 of docs/10-frontier.md:
--
--    CoarseGrainedRT = Σ[ w ∈ CoarseGrainWitness ]
--      Σ[ regionArea ∈ (FineRegion w → ℚ≥0) ]
--        ((r : FineRegion w) → obs-fine w r ≤ℚ regionArea r)
--
--  The triple (dense100-coarse-witness , regionArea , area-law)
--  instantiates this type because:
--
--    w           = dense100-coarse-witness
--    regionArea  : FineRegion w → ℚ≥0
--                = D100Region → ℚ≥0             (definitional)
--    area-law    : (r : FineRegion w) → obs-fine w r ≤ℚ regionArea r
--                = (r : D100Region) → S-cut d100BdyView r ≤ℚ regionArea r
--                                                        (definitional)
--
--  The area-law field is abstract (sealed in Dense100AreaLaw.agda),
--  so downstream modules never re-unfold the 717 case analyses.
--  Since _≤ℚ_ is propositional (by isProp≤ℚ from
--  Bridge/FullEnrichedStarObs.agda), the abstract barrier does not
--  damage any Univalence bridge or transport computation.
-- ════════════════════════════════════════════════════════════════════

dense100-thermodynamics : CoarseGrainedRT
dense100-thermodynamics = dense100-coarse-witness , regionArea , area-law


-- ════════════════════════════════════════════════════════════════════
--  §3.  Component Extraction
-- ════════════════════════════════════════════════════════════════════
--
--  The three components of the triple are extractable as projections.
--  These serve as stable references for downstream modules and
--  documentation.
-- ════════════════════════════════════════════════════════════════════

-- The coarse-graining witness (orbit reduction 717 → 8)
the-witness : CoarseGrainWitness
the-witness = fst dense100-thermodynamics

-- The boundary area function
the-area : D100Region → ℚ≥0
the-area = fst (snd dense100-thermodynamics)

-- The area-law bound (abstract)
the-bound : (r : D100Region)
  → CoarseGrainWitness.obs-fine the-witness r ≤ℚ the-area r
the-bound = snd (snd dense100-thermodynamics)


-- ════════════════════════════════════════════════════════════════════
--  §4.  Concrete Spot Checks
-- ════════════════════════════════════════════════════════════════════
--
--  These regression tests verify that the instantiated triple
--  produces the expected concrete values at specific regions.
--  Each test exercises the full pipeline:
--
--    D100Region  →classify100→  D100OrbitRep  →S-cut-rep→  ℕ
--    D100Region  →regionArea→  ℕ
--    area-law r  :  Σ[ k ∈ ℕ ] (k + S r ≡ area r)
--
--  The area-law proofs are abstract (we cannot inspect the k
--  component), but we CAN verify the observable and area values.
-- ════════════════════════════════════════════════════════════════════

-- d100r0:  1-cell region, S=1, area=6, slack=5
check-obs-r0 : CoarseGrainWitness.obs-fine the-witness d100r0 ≡ 1
check-obs-r0 = refl

check-area-r0 : the-area d100r0 ≡ 6
check-area-r0 = refl

-- d100r215:  1-cell region, S=2, area=6, slack=4
check-obs-r215 : CoarseGrainWitness.obs-fine the-witness d100r215 ≡ 2
check-obs-r215 = refl

check-area-r215 : the-area d100r215 ≡ 6
check-area-r215 = refl

-- d100r1:  2-cell region, S=3, area=10, slack=7
check-obs-r1 : CoarseGrainWitness.obs-fine the-witness d100r1 ≡ 3
check-obs-r1 = refl

check-area-r1 : the-area d100r1 ≡ 10
check-area-r1 = refl

-- d100r8:  4-cell region, S=5, area=18, slack=13
check-obs-r8 : CoarseGrainWitness.obs-fine the-witness d100r8 ≡ 5
check-obs-r8 = refl

check-area-r8 : the-area d100r8 ≡ 18
check-area-r8 = refl

-- d100r4:  5-cell region, S=7, area=22, slack=15  (high min-cut)
check-obs-r4 : CoarseGrainWitness.obs-fine the-witness d100r4 ≡ 7
check-obs-r4 = refl

check-area-r4 : the-area d100r4 ≡ 22
check-area-r4 = refl

-- d100r15:  5-cell region, S=8, area=22, slack=14  (maximum min-cut)
check-obs-r15 : CoarseGrainWitness.obs-fine the-witness d100r15 ≡ 8
check-obs-r15 = refl

check-area-r15 : the-area d100r15 ≡ 22
check-area-r15 = refl


-- ════════════════════════════════════════════════════════════════════
--  §5.  Orbit Coherence
-- ════════════════════════════════════════════════════════════════════
--
--  The coarse-graining witness carries a  compat  field that
--  witnesses the factorization:
--
--    S-cut d100BdyView r ≡ S-cut-rep (classify100 r)
--
--  This holds by refl because S-cut is DEFINED as
--  S-cut-rep ∘ classify100 in Boundary/Dense100Cut.agda.
--
--  The area-law bound factors through this:
--
--    S-cut d100BdyView r  ≤ℚ  regionArea r
--    ‖ (by compat)
--    S-cut-rep (classify100 r)  ≤ℚ  regionArea r
--
--  An observer who sees only the 8-constructor D100OrbitRep type
--  reads the correct entropy value for each orbit class (via
--  S-cut-rep), and the area law holds for every region in the
--  orbit (via area-law).  This is the type-theoretic content of
--  "statistical averaging preserves the entropy–area relationship."
-- ════════════════════════════════════════════════════════════════════

-- The compat field is refl (S-cut is S-cut-rep ∘ classify100)
compat-is-trivial : (r : D100Region)
  → S-cut d100BdyView r ≡ S-cut-rep (classify100 r)
compat-is-trivial = CoarseGrainWitness.compat the-witness


-- ════════════════════════════════════════════════════════════════════
--  §6.  Connection to the Enriched Bridge (D100Theorem3)
-- ════════════════════════════════════════════════════════════════════
--
--  The Dense-100 enriched bridge (Bridge/Dense100Equiv.agda) proves
--  the observable-package equivalence:
--
--    transport (ua d100-enriched-equiv) d100-bdy-instance
--      ≡ d100-bulk-instance
--
--  The coarse-grained RT instance in this module is COMPATIBLE with
--  that bridge: both reference the same observable function
--  S-cut d100BdyView : D100Region → ℚ≥0, and the area-law bound
--  provides an additional structural property (the discrete
--  isoperimetric inequality) that coexists with the bridge
--  equivalence.
--
--  Together, the Dense-100 formalization provides:
--
--    D100Theorem3  (Bridge/Dense100Equiv.agda):
--      The exact discrete RT correspondence S = L on 717 regions,
--      with transport along a Univalence path verified.
--
--    dense100-thermodynamics  (this module):
--      The area-law bound S ≤ area on 717 regions, packaged with
--      the orbit reduction into a CoarseGrainedRT triple.
--
--  The two results are independent (neither imports the other) but
--  share the same fine-grained observable S-cut d100BdyView.
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
--  §7.  The Macroscopic Observer Interpretation
-- ════════════════════════════════════════════════════════════════════
--
--  The Dense-100 orbit reduction implements "Observer 1" from
--  §8.6 of docs/10-frontier.md:
--
--    Fine   = D100Region   (717 constructors)
--    Coarse = D100OrbitRep (8 constructors)
--    Memory = 3 bits       (⌈log₂ 8⌉)
--
--  An observer with 3 bits of memory cannot distinguish the 717
--  individual boundary configurations — they see only which of
--  the 8 min-cut-value classes each region belongs to.  The compat
--  field of the coarse-graining witness certifies that this lossy
--  compression preserves the entropy observable exactly.
--
--  The area-law bound (S ≤ area) holds at both resolution levels:
--
--    Fine level:    S-cut d100BdyView r  ≤ℚ  regionArea r
--                   (directly from area-law)
--
--    Coarse level:  S-cut-rep (classify100 r)  ≤ℚ  regionArea r
--                   (by compat + area-law)
--
--  The thermodynamic claim — that as the patch grows (N → ∞) while
--  the observer's memory stays bounded, the coarse-grained
--  observable approaches the continuum entropy formula — is a
--  metatheoretic claim beyond the scope of constructive Cubical
--  Agda (§8.8).  This module provides the finite constructive
--  content for N = 100.
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
--  §8.  Summary and Exit Criterion
-- ════════════════════════════════════════════════════════════════════
--
--  This module satisfies the exit criterion of §8.11 of
--  docs/10-frontier.md:
--
--    1. ✓  A CoarseGrainWitness record type-checks in
--          Bridge/CoarseGrain.agda with the Dense-100 orbit
--          reduction as the concrete instance.
--
--    2. ✓  A Python-generated Boundary/Dense100AreaLaw.agda
--          contains 717 abstract cases of (k , refl) proving
--          the discrete area law.
--
--    3. ✓  (This module)  The CoarseGrainedRT triple is fully
--          instantiated, combining all three components into a
--          single inspectable Agda term.
--
--  Proof pipeline:
--
--    11_generate_area_law.py       (Python oracle: areas + slacks)
--      │
--      ├──▶ Boundary/Dense100AreaLaw.agda   (regionArea + area-law)
--      │
--      └──▶ Bridge/CoarseGrain.agda         (dense100-coarse-witness)
--              │
--              ▼
--         Bridge/Dense100Thermodynamics.agda  (this module)
--              │
--              ▼
--         dense100-thermodynamics : CoarseGrainedRT
--         = ( dense100-coarse-witness , regionArea , area-law )
--
--  Every step is machine-checked by the Cubical Agda type-checker.
--
--  The fully formalized statement:
--
--    "For every finite discrete holographic patch formalized in
--     this repository, the entropy–area relationship holds exactly
--     at every resolution level accessible to a finite observer."
--
--  is witnessed concretely by  dense100-thermodynamics  for the
--  Dense-100 patch of the {4,3,5} hyperbolic honeycomb.
-- ════════════════════════════════════════════════════════════════════