{-# OPTIONS --cubical --safe --guardedness #-}

module Bridge.Dense50Obs where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Dense50Spec
open import Common.ObsPackage
open import Boundary.Dense50Cut
open import Bulk.Dense50Chain

-- ═══════════════════════════════════════════════════════════
--  Canonical views (dummy instances)
-- ═══════════════════════════════════════════════════════════

d50BdyView : D50BdyView
d50BdyView .D50BdyView.dummy = 0

d50BulkView : D50BulkView
d50BulkView .D50BulkView.dummy = 0

-- ═══════════════════════════════════════════════════════════
--  Observable packages for the Dense-50 {4,3,5} patch
-- ═══════════════════════════════════════════════════════════

D50Obs∂ : ObsPackage D50Region
D50Obs∂ .ObsPackage.obs = S-cut d50BdyView

D50ObsBulk : ObsPackage D50Region
D50ObsBulk .ObsPackage.obs = L-min d50BulkView

-- ═══════════════════════════════════════════════════════════
--  d50-pointwise — All 139 cases hold by refl
-- ═══════════════════════════════════════════════════════════
--
--  Both S-cut and L-min return the same ℕ literal for each
--  region: both encode the true min-cut (min separating
--  surface area) through the 3D cell complex.
--
--  This is the 3D discrete Ryu–Takayanagi correspondence:
--  boundary entanglement entropy = bulk minimal surface area.
--
--  The Dense-50 patch achieves min-cut values from 2 to 7,
--  confirming genuine multi-face RT surfaces — unlike the
--  BFS shell patches where min-cut ≈ 1 for all singletons.
--
--  Generated by sim/prototyping/08_generate_dense50.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/08_generate_dense50.py

d50-pointwise :
  (r : D50Region) →
  S-cut d50BdyView r ≡ L-min d50BulkView r
d50-pointwise d50r0 = refl
d50-pointwise d50r1 = refl
d50-pointwise d50r2 = refl
d50-pointwise d50r3 = refl
d50-pointwise d50r4 = refl
d50-pointwise d50r5 = refl
d50-pointwise d50r6 = refl
d50-pointwise d50r7 = refl
d50-pointwise d50r8 = refl
d50-pointwise d50r9 = refl
d50-pointwise d50r10 = refl
d50-pointwise d50r11 = refl
d50-pointwise d50r12 = refl
d50-pointwise d50r13 = refl
d50-pointwise d50r14 = refl
d50-pointwise d50r15 = refl
d50-pointwise d50r16 = refl
d50-pointwise d50r17 = refl
d50-pointwise d50r18 = refl
d50-pointwise d50r19 = refl
d50-pointwise d50r20 = refl
d50-pointwise d50r21 = refl
d50-pointwise d50r22 = refl
d50-pointwise d50r23 = refl
d50-pointwise d50r24 = refl
d50-pointwise d50r25 = refl
d50-pointwise d50r26 = refl
d50-pointwise d50r27 = refl
d50-pointwise d50r28 = refl
d50-pointwise d50r29 = refl
d50-pointwise d50r30 = refl
d50-pointwise d50r31 = refl
d50-pointwise d50r32 = refl
d50-pointwise d50r33 = refl
d50-pointwise d50r34 = refl
d50-pointwise d50r35 = refl
d50-pointwise d50r36 = refl
d50-pointwise d50r37 = refl
d50-pointwise d50r38 = refl
d50-pointwise d50r39 = refl
d50-pointwise d50r40 = refl
d50-pointwise d50r41 = refl
d50-pointwise d50r42 = refl
d50-pointwise d50r43 = refl
d50-pointwise d50r44 = refl
d50-pointwise d50r45 = refl
d50-pointwise d50r46 = refl
d50-pointwise d50r47 = refl
d50-pointwise d50r48 = refl
d50-pointwise d50r49 = refl
d50-pointwise d50r50 = refl
d50-pointwise d50r51 = refl
d50-pointwise d50r52 = refl
d50-pointwise d50r53 = refl
d50-pointwise d50r54 = refl
d50-pointwise d50r55 = refl
d50-pointwise d50r56 = refl
d50-pointwise d50r57 = refl
d50-pointwise d50r58 = refl
d50-pointwise d50r59 = refl
d50-pointwise d50r60 = refl
d50-pointwise d50r61 = refl
d50-pointwise d50r62 = refl
d50-pointwise d50r63 = refl
d50-pointwise d50r64 = refl
d50-pointwise d50r65 = refl
d50-pointwise d50r66 = refl
d50-pointwise d50r67 = refl
d50-pointwise d50r68 = refl
d50-pointwise d50r69 = refl
d50-pointwise d50r70 = refl
d50-pointwise d50r71 = refl
d50-pointwise d50r72 = refl
d50-pointwise d50r73 = refl
d50-pointwise d50r74 = refl
d50-pointwise d50r75 = refl
d50-pointwise d50r76 = refl
d50-pointwise d50r77 = refl
d50-pointwise d50r78 = refl
d50-pointwise d50r79 = refl
d50-pointwise d50r80 = refl
d50-pointwise d50r81 = refl
d50-pointwise d50r82 = refl
d50-pointwise d50r83 = refl
d50-pointwise d50r84 = refl
d50-pointwise d50r85 = refl
d50-pointwise d50r86 = refl
d50-pointwise d50r87 = refl
d50-pointwise d50r88 = refl
d50-pointwise d50r89 = refl
d50-pointwise d50r90 = refl
d50-pointwise d50r91 = refl
d50-pointwise d50r92 = refl
d50-pointwise d50r93 = refl
d50-pointwise d50r94 = refl
d50-pointwise d50r95 = refl
d50-pointwise d50r96 = refl
d50-pointwise d50r97 = refl
d50-pointwise d50r98 = refl
d50-pointwise d50r99 = refl
d50-pointwise d50r100 = refl
d50-pointwise d50r101 = refl
d50-pointwise d50r102 = refl
d50-pointwise d50r103 = refl
d50-pointwise d50r104 = refl
d50-pointwise d50r105 = refl
d50-pointwise d50r106 = refl
d50-pointwise d50r107 = refl
d50-pointwise d50r108 = refl
d50-pointwise d50r109 = refl
d50-pointwise d50r110 = refl
d50-pointwise d50r111 = refl
d50-pointwise d50r112 = refl
d50-pointwise d50r113 = refl
d50-pointwise d50r114 = refl
d50-pointwise d50r115 = refl
d50-pointwise d50r116 = refl
d50-pointwise d50r117 = refl
d50-pointwise d50r118 = refl
d50-pointwise d50r119 = refl
d50-pointwise d50r120 = refl
d50-pointwise d50r121 = refl
d50-pointwise d50r122 = refl
d50-pointwise d50r123 = refl
d50-pointwise d50r124 = refl
d50-pointwise d50r125 = refl
d50-pointwise d50r126 = refl
d50-pointwise d50r127 = refl
d50-pointwise d50r128 = refl
d50-pointwise d50r129 = refl
d50-pointwise d50r130 = refl
d50-pointwise d50r131 = refl
d50-pointwise d50r132 = refl
d50-pointwise d50r133 = refl
d50-pointwise d50r134 = refl
d50-pointwise d50r135 = refl
d50-pointwise d50r136 = refl
d50-pointwise d50r137 = refl
d50-pointwise d50r138 = refl

-- ═══════════════════════════════════════════════════════════
--  d50-obs-path — Function equality via funExt
-- ═══════════════════════════════════════════════════════════
--
--  Packages the 139 pointwise refl proofs into a single path
--  between the boundary and bulk observable functions:
--    S∂D50 ≡ LBD50
--
--  This is the 3D analogue of star-obs-path and
--  filled-obs-path, now on a densely-connected 3D patch
--  with non-trivial separating-surface geometry.
--

S∂D50 : D50Region → ℚ≥0
S∂D50 = S-cut d50BdyView

LBD50 : D50Region → ℚ≥0
LBD50 = L-min d50BulkView

d50-obs-path : S∂D50 ≡ LBD50
d50-obs-path = funExt d50-pointwise

-- ═══════════════════════════════════════════════════════════
--  d50-package-path — Package-level path
-- ═══════════════════════════════════════════════════════════
--
--  Identifies the boundary and bulk observable packages.
--  The downstream enriched equivalence (Dense50Equiv.agda)
--  uses d50-obs-path to construct the Iso / Equiv / ua /
--  transport pipeline, mirroring Honeycomb3DEquiv.agda and
--  FilledEquiv.agda.
--

d50-package-path : D50Obs∂ ≡ D50ObsBulk
d50-package-path i .ObsPackage.obs = d50-obs-path i

