{-# OPTIONS --cubical --safe --guardedness #-}

module Bridge.GenericValidation where

open import Cubical.Foundations.Prelude

open import Util.Scalars

-- ════════════════════════════════════════════════════════════════════
--  Generic Bridge Validation — Retroactive Consistency Tests
-- ════════════════════════════════════════════════════════════════════
--
--  This module verifies that every existing bridge instance in the
--  repository can be expressed as an instantiation of the generic
--  bridge machinery from  Bridge/GenericBridge.agda .
--
--  For each concrete bridge, we:
--
--    1. Construct a  PatchData  (or  OrbitReducedPatch ) from the
--       existing observable functions and agreement paths.
--
--    2. Apply  GenericEnriched  (or  orbit-bridge-witness ) to
--       extract a fully proof-carrying  BridgeWitness .
--
--    3. Verify coherence: the generic construction's observable
--       functions agree definitionally with the concrete ones.
--
--  The fact that this module TYPE-CHECKS is the validation:
--  it proves that the generic architecture subsumes all existing
--  bridges without modifying any of them.
--
--  Instances validated:
--
--    §1. Star       (10 regions, 2D {5,4} star)         — PatchData
--    §2. Filled     (90 regions, 2D {5,4} disk)         — PatchData
--    §3. Honeycomb  (26 regions, 3D {4,3,5} BFS star)   — PatchData
--    §4. Dense-50   (139 regions, 3D {4,3,5} dense)     — PatchData
--    §5. Dense-100  (717 regions → 8 orbits)            — OrbitReducedPatch
--    §6. Dense-200  (1246 regions → 9 orbits)           — OrbitReducedPatch
--
--  Reference:
--    docs/10-frontier.md §5.5   (What This Achieves)
--    docs/10-frontier.md §5.11  (Phase C.0 — item 2: retroactive validation)
--    docs/10-frontier.md §5.12  (Conditions for Advancement — item 1)
--
--  Condition for advancement (§5.12):
--    "The generic bridge module (Bridge/GenericBridge.agda) type-checks
--     and retroactively validates at least one existing bridge instance."
--
--  This module validates ALL SIX existing bridge instances.
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
--  Imports — Generic Bridge Infrastructure
-- ════════════════════════════════════════════════════════════════════

open import Bridge.GenericBridge
  using ( PatchData ; OrbitReducedPatch
        ; orbit-to-patch ; orbit-bridge-witness
        ; module GenericEnriched )

open import Bridge.EnrichedStarEquiv
  using (BridgeWitness)


-- ════════════════════════════════════════════════════════════════════
--  §1.  Star Instance  (10 regions, 2D {5,4} star patch)
-- ════════════════════════════════════════════════════════════════════
--
--  The 6-tile star patch is the simplest nontrivial bridge instance.
--  Both S∂ and LB are 10-clause lookup tables returning 1q or 2q,
--  and star-obs-path is funExt of 10 refl proofs.
--
--  Existing modules:
--    Common/StarSpec.agda           — Region (10 constructors)
--    Bridge/EnrichedStarObs.agda    — S∂, LB, enriched-equiv
--    Bridge/StarEquiv.agda          — star-obs-path
--    Bridge/EnrichedStarEquiv.agda  — spec-witness : BridgeWitness
--
--  Validation: the generic GenericEnriched applied to starPatchData
--  produces a BridgeWitness that type-checks.
-- ════════════════════════════════════════════════════════════════════

open import Common.StarSpec using (Region)
open import Bridge.EnrichedStarObs
  using ()
  renaming (S∂ to star-S∂ ; LB to star-LB)
open import Bridge.StarEquiv using (star-obs-path)

starPatchData : PatchData
starPatchData .PatchData.RegionTy = Region
starPatchData .PatchData.S∂       = star-S∂
starPatchData .PatchData.LB       = star-LB
starPatchData .PatchData.obs-path = star-obs-path

module StarGeneric = GenericEnriched starPatchData

star-generic-witness : BridgeWitness
star-generic-witness = StarGeneric.abstract-bridge-witness

-- ── Coherence: PatchData fields are the concrete imports ────────
private
  star-S∂-check : PatchData.S∂ starPatchData ≡ star-S∂
  star-S∂-check = refl

  star-LB-check : PatchData.LB starPatchData ≡ star-LB
  star-LB-check = refl


-- ════════════════════════════════════════════════════════════════════
--  §2.  Filled Instance  (90 regions, 2D {5,4} full disk)
-- ════════════════════════════════════════════════════════════════════
--
--  The 11-tile filled patch is the smallest {5,4} patch forming a
--  proper manifold with boundary.  Its 90-region type and 90-clause
--  lookup tables are generated by the Python oracle
--  (03_generate_filled_patch.py).
--
--  The generic bridge theorem handles the 90-region case identically
--  to the 10-region star case — no code change needed.
--
--  Existing modules:
--    Common/FilledSpec.agda       — FilledRegion (90 constructors)
--    Bridge/FilledObs.agda        — filled-obs-path
--    Bridge/FilledEquiv.agda      — S∂F, LBF, filled-enriched-equiv
-- ════════════════════════════════════════════════════════════════════

open import Common.FilledSpec using (FilledRegion)
open import Bridge.FilledEquiv using (S∂F ; LBF)
open import Bridge.FilledObs using (filled-obs-path)

filledPatchData : PatchData
filledPatchData .PatchData.RegionTy = FilledRegion
filledPatchData .PatchData.S∂       = S∂F
filledPatchData .PatchData.LB       = LBF
filledPatchData .PatchData.obs-path = filled-obs-path

module FilledGeneric = GenericEnriched filledPatchData

filled-generic-witness : BridgeWitness
filled-generic-witness = FilledGeneric.abstract-bridge-witness


-- ════════════════════════════════════════════════════════════════════
--  §3.  Honeycomb 3D Instance  (26 regions, {4,3,5} BFS star)
-- ════════════════════════════════════════════════════════════════════
--
--  The first 3D bridge instance: a BFS-shell patch of the {4,3,5}
--  honeycomb with 32 cubes, 130 boundary faces, and 26 singleton-
--  cell boundary regions (all with min-cut = 1).
--
--  The generic bridge theorem works identically in 3D — it depends
--  only on the abstract PatchData interface, not on the dimension
--  of the underlying geometry.
--
--  Existing modules:
--    Common/Honeycomb3DSpec.agda       — H3Region (26 constructors)
--    Bridge/Honeycomb3DObs.agda        — h3-obs-path
--    Bridge/Honeycomb3DEquiv.agda      — S∂3D, LB3D, h3-enriched-equiv
-- ════════════════════════════════════════════════════════════════════

open import Common.Honeycomb3DSpec using (H3Region)
open import Bridge.Honeycomb3DEquiv using (S∂3D ; LB3D)
open import Bridge.Honeycomb3DObs using (h3-obs-path)

h3PatchData : PatchData
h3PatchData .PatchData.RegionTy = H3Region
h3PatchData .PatchData.S∂       = S∂3D
h3PatchData .PatchData.LB       = LB3D
h3PatchData .PatchData.obs-path = h3-obs-path

module H3Generic = GenericEnriched h3PatchData

h3-generic-witness : BridgeWitness
h3-generic-witness = H3Generic.abstract-bridge-witness


-- ════════════════════════════════════════════════════════════════════
--  §4.  Dense-50 Instance  (139 regions, {4,3,5} dense)
-- ════════════════════════════════════════════════════════════════════
--
--  The Dense-50 patch uses flat enumeration (no orbit reduction),
--  with 139 regions and min-cut values 1–7.  It is the last
--  instance before the orbit reduction strategy is needed.
--
--  Existing modules:
--    Common/Dense50Spec.agda     — D50Region (139 constructors)
--    Bridge/Dense50Obs.agda      — S∂D50, LBD50, d50-obs-path
--    Bridge/Dense50Equiv.agda    — d50-enriched-equiv
-- ════════════════════════════════════════════════════════════════════

open import Common.Dense50Spec using (D50Region)
open import Bridge.Dense50Obs using (S∂D50 ; LBD50 ; d50-obs-path)

d50PatchData : PatchData
d50PatchData .PatchData.RegionTy = D50Region
d50PatchData .PatchData.S∂       = S∂D50
d50PatchData .PatchData.LB       = LBD50
d50PatchData .PatchData.obs-path = d50-obs-path

module D50Generic = GenericEnriched d50PatchData

d50-generic-witness : BridgeWitness
d50-generic-witness = D50Generic.abstract-bridge-witness


-- ════════════════════════════════════════════════════════════════════
--  §5.  Dense-100 Orbit-Reduced Instance  (717 regions → 8 orbits)
-- ════════════════════════════════════════════════════════════════════
--
--  The Dense-100 patch is the first to use the orbit reduction
--  strategy: 717 regions are classified into 8 orbit representatives
--  by min-cut value, and the observable lookups (S-cut-rep, L-min-rep)
--  are defined on the 8-constructor orbit type.
--
--  This validates the  orbit-to-patch + orbit-bridge-witness  path:
--  the OrbitReducedPatch record is constructed from the existing
--  Dense-100 infrastructure, orbit-to-patch extracts the PatchData
--  (with obs-path assembled automatically by funExt of the orbit-
--  level agreement), and orbit-bridge-witness produces the full
--  BridgeWitness.
--
--  The pointwise coherence check verifies that the generic S∂
--  (λ r → S-cut-rep (classify100 r)) agrees definitionally with
--  the concrete S∂D100 (= S-cut d100BdyView, which unfolds to
--  S-cut-rep (classify100 r) by the single-clause definition in
--  Boundary/Dense100Cut.agda).  Both sides reduce to the same
--  normal form, so the check is refl.
--
--  Existing modules:
--    Common/Dense100Spec.agda      — D100Region, D100OrbitRep, classify100
--    Boundary/Dense100Cut.agda     — S-cut-rep  (8 clauses)
--    Bulk/Dense100Chain.agda       — L-min-rep  (8 clauses)
--    Bridge/Dense100Obs.agda       — d100-pointwise-rep (8 refl proofs)
--    Bridge/Dense100Equiv.agda     — d100-enriched-equiv
-- ════════════════════════════════════════════════════════════════════

open import Common.Dense100Spec
  using (D100Region ; D100OrbitRep ; classify100)

-- Qualified imports to avoid name clashes with Dense-200
import Boundary.Dense100Cut as D100Cut
import Bulk.Dense100Chain   as D100Chain

open import Bridge.Dense100Obs
  using (d100-pointwise-rep ; S∂D100 ; LBD100)

d100OrbitPatch : OrbitReducedPatch
d100OrbitPatch .OrbitReducedPatch.RegionTy  = D100Region
d100OrbitPatch .OrbitReducedPatch.OrbitTy   = D100OrbitRep
d100OrbitPatch .OrbitReducedPatch.classify  = classify100
d100OrbitPatch .OrbitReducedPatch.S-rep     = D100Cut.S-cut-rep
d100OrbitPatch .OrbitReducedPatch.L-rep     = D100Chain.L-min-rep
d100OrbitPatch .OrbitReducedPatch.rep-agree = d100-pointwise-rep

d100-generic-witness : BridgeWitness
d100-generic-witness = orbit-bridge-witness d100OrbitPatch

-- ── Coherence: generic S∂ agrees pointwise with concrete S∂D100 ──
--
--  Both sides reduce to  S-cut-rep (classify100 r)  when applied
--  to a concrete region  r .  The LHS unfolds via beta-reduction
--  of the lambda in orbit-to-patch; the RHS unfolds via the
--  single-clause  S-cut _ r = S-cut-rep (classify100 r)  in
--  Boundary/Dense100Cut.agda.

d100-S∂-pointwise : (r : D100Region)
  → PatchData.S∂ (orbit-to-patch d100OrbitPatch) r ≡ S∂D100 r
d100-S∂-pointwise _ = refl

d100-LB-pointwise : (r : D100Region)
  → PatchData.LB (orbit-to-patch d100OrbitPatch) r ≡ LBD100 r
d100-LB-pointwise _ = refl


-- ════════════════════════════════════════════════════════════════════
--  §6.  Dense-200 Orbit-Reduced Instance  (1246 regions → 9 orbits)
-- ════════════════════════════════════════════════════════════════════
--
--  The Dense-200 patch extends the resolution tower to the third
--  level.  It uses the same orbit reduction architecture as
--  Dense-100, now with 9 orbit representatives (min-cut values 1–9).
--
--  The max min-cut grew from 8 (Dense-100) to 9 (Dense-200),
--  confirming monotone convergence of the discrete RT spectrum.
--  The orbit-bridge-witness machinery handles the 1246-region type
--  identically to the 717-region type — only the classify function
--  is larger, not the proof obligations.
--
--  Existing modules:
--    Common/Dense200Spec.agda      — D200Region, D200OrbitRep, classify200
--    Boundary/Dense200Cut.agda     — S-cut-rep  (9 clauses)
--    Bulk/Dense200Chain.agda       — L-min-rep  (9 clauses)
--    Bridge/Dense200Obs.agda       — d200-pointwise-rep (9 refl proofs)
-- ════════════════════════════════════════════════════════════════════

open import Common.Dense200Spec
  using (D200Region ; D200OrbitRep ; classify200)

-- Qualified imports to avoid name clashes with Dense-100
import Boundary.Dense200Cut as D200Cut
import Bulk.Dense200Chain   as D200Chain

open import Bridge.Dense200Obs
  using (d200-pointwise-rep ; S∂D200 ; LBD200)

d200OrbitPatch : OrbitReducedPatch
d200OrbitPatch .OrbitReducedPatch.RegionTy  = D200Region
d200OrbitPatch .OrbitReducedPatch.OrbitTy   = D200OrbitRep
d200OrbitPatch .OrbitReducedPatch.classify  = classify200
d200OrbitPatch .OrbitReducedPatch.S-rep     = D200Cut.S-cut-rep
d200OrbitPatch .OrbitReducedPatch.L-rep     = D200Chain.L-min-rep
d200OrbitPatch .OrbitReducedPatch.rep-agree = d200-pointwise-rep

d200-generic-witness : BridgeWitness
d200-generic-witness = orbit-bridge-witness d200OrbitPatch

-- ── Coherence: generic S∂ agrees pointwise with concrete S∂D200 ──

d200-S∂-pointwise : (r : D200Region)
  → PatchData.S∂ (orbit-to-patch d200OrbitPatch) r ≡ S∂D200 r
d200-S∂-pointwise _ = refl

d200-LB-pointwise : (r : D200Region)
  → PatchData.LB (orbit-to-patch d200OrbitPatch) r ≡ LBD200 r
d200-LB-pointwise _ = refl


-- ════════════════════════════════════════════════════════════════════
--  §7.  Summary and Design Notes
-- ════════════════════════════════════════════════════════════════════
--
--  Exports:
--
--    starPatchData        : PatchData
--    filledPatchData      : PatchData
--    h3PatchData          : PatchData
--    d50PatchData         : PatchData
--    d100OrbitPatch       : OrbitReducedPatch
--    d200OrbitPatch       : OrbitReducedPatch
--
--    star-generic-witness   : BridgeWitness
--    filled-generic-witness : BridgeWitness
--    h3-generic-witness     : BridgeWitness
--    d50-generic-witness    : BridgeWitness
--    d100-generic-witness   : BridgeWitness
--    d200-generic-witness   : BridgeWitness
--
--    d100-S∂-pointwise  : generic S∂ ≡ concrete S∂D100  (pointwise refl)
--    d100-LB-pointwise  : generic LB ≡ concrete LBD100  (pointwise refl)
--    d200-S∂-pointwise  : generic S∂ ≡ concrete S∂D200  (pointwise refl)
--    d200-LB-pointwise  : generic LB ≡ concrete LBD200  (pointwise refl)
--
--  Retroactive validation results:
--
--    Instance    │ RegionTy       │ #ctors │ Strategy         │ ✓
--    ────────────┼────────────────┼────────┼──────────────────┼──
--    Star        │ Region         │     10 │ PatchData        │ ✓
--    Filled      │ FilledRegion   │     90 │ PatchData        │ ✓
--    Honeycomb   │ H3Region       │     26 │ PatchData        │ ✓
--    Dense-50    │ D50Region      │    139 │ PatchData        │ ✓
--    Dense-100   │ D100Region     │    717 │ OrbitReducedPatch│ ✓
--    Dense-200   │ D200Region     │   1246 │ OrbitReducedPatch│ ✓
--
--  The fact that this module type-checks confirms:
--
--    1. The generic bridge theorem (GenericEnriched) subsumes all
--       existing bridge constructions.
--
--    2. The orbit reduction path (OrbitReducedPatch → orbit-to-patch
--       → GenericEnriched → BridgeWitness) correctly handles the
--       large-region cases that require classification functions.
--
--    3. The generic S∂ and LB agree definitionally (pointwise) with
--       the concrete observables in the orbit-reduced cases, because
--       the concrete S-cut is DEFINED as S-cut-rep ∘ classify and
--       the generic orbit-to-patch produces exactly λ r → S-rep (classify r).
--
--    4. No existing module is modified — this module is purely
--       additive, importing from existing modules and constructing
--       new terms from them.
--
--  This satisfies the conditions for advancement from §5.12 of
--  docs/10-frontier.md:
--
--    "The generic bridge module (Bridge/GenericBridge.agda) type-checks
--     and retroactively validates at least one existing bridge instance."
--
--  Six instances validated. Direction C can advance from "deferred"
--  to "active" when the Python oracle is extended to emit
--  OrbitReducedPatch Agda modules for layer-N {5,4} patches.
--
--  Relationship to existing code:
--
--    This module imports from (but does NOT modify):
--      • Bridge/GenericBridge.agda       — PatchData, OrbitReducedPatch,
--                                          GenericEnriched, orbit-to-patch,
--                                          orbit-bridge-witness
--      • Bridge/EnrichedStarEquiv.agda   — BridgeWitness record
--      • Bridge/EnrichedStarObs.agda     — star S∂, LB
--      • Bridge/StarEquiv.agda           — star-obs-path
--      • Bridge/FilledEquiv.agda         — S∂F, LBF
--      • Bridge/FilledObs.agda           — filled-obs-path
--      • Bridge/Honeycomb3DEquiv.agda    — S∂3D, LB3D
--      • Bridge/Honeycomb3DObs.agda      — h3-obs-path
--      • Bridge/Dense50Obs.agda          — S∂D50, LBD50, d50-obs-path
--      • Boundary/Dense100Cut.agda       — S-cut-rep (D100)
--      • Bulk/Dense100Chain.agda         — L-min-rep (D100)
--      • Bridge/Dense100Obs.agda         — d100-pointwise-rep, S∂D100, LBD100
--      • Boundary/Dense200Cut.agda       — S-cut-rep (D200)
--      • Bulk/Dense200Chain.agda         — L-min-rep (D200)
--      • Bridge/Dense200Obs.agda         — d200-pointwise-rep, S∂D200, LBD200
--      • Common/*Spec.agda               — region and orbit types
-- ════════════════════════════════════════════════════════════════════