{-# OPTIONS --cubical --safe --guardedness #-}

module Bridge.HalfBound where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat
  using (ℕ ; zero ; suc ; _+_)
open import Cubical.Data.Sigma
  using (Σ-syntax)

open import Util.Scalars
open import Util.NatLemmas using (+-comm ; +-assoc)
open import Bridge.GenericBridge using (PatchData)


-- ════════════════════════════════════════════════════════════════════
--  The Discrete Bekenstein–Hawking Half-Bound
-- ════════════════════════════════════════════════════════════════════
--
--  This module provides **Theorem 3** (Discrete Bekenstein–Hawking)
--  from the canonical theorem registry (docs/formal/01-theorems.md):
--
--      S(A) ≤ area(A) / 2
--
--  for all cell-aligned boundary regions A on any verified patch,
--  with a tight achiever where 2·S(A) = area(A).  The discrete
--  Newton's constant is thereby identified as 1/(4G) = 1/2 in
--  bond-dimension-1 units.
--
--  The module exports three components:
--
--    1. HalfBoundWitness — a record parameterized by PatchData,
--       packaging an area function, the abstract half-bound proof,
--       and a tight achiever.
--
--    2. two-le-sum — the arithmetic core: given s ≤ a and s ≤ b,
--       derive (s + s) ≤ (a + b).
--
--    3. from-two-cuts — the generic half-bound lemma: given the
--       area decomposition area(r) ≡ n_cross(r) + n_bdy(r) and
--       two independent cut bounds S(r) ≤ n_cross(r) and
--       S(r) ≤ n_bdy(r), derive (S(r) + S(r)) ≤ area(r).
--
--  The graph-theoretic proof (docs/formal/12-bekenstein-hawking.md):
--
--    For any cell-aligned boundary region A:
--
--      area(A) = n_cross + n_bdy
--
--    where n_cross = bonds crossing from A to its complement, and
--    n_bdy = boundary legs of A-cells.  The max-flow S(A) is
--    bounded by two independent cuts:
--
--      Cut 1 — sever all crossing bonds:    S ≤ n_cross
--      Cut 2 — sever all A-boundary legs:   S ≤ n_bdy
--
--    Therefore:
--
--      S ≤ min(n_cross, n_bdy) ≤ (n_cross + n_bdy)/2 = area/2
--
--  The bound is:
--    • TIGHT — achieved by regions where n_cross = n_bdy = area/2
--    • UNIVERSAL — holds for {4,3,5}, {5,4}, {4,4}, and {5,3}
--    • CURVATURE-AGNOSTIC — independent of the curvature sign
--    • CAPACITY-UNIVERSAL — holds for uniform capacity c = 1, 2, 3
--
--  This result eliminates the constructive-reals wall for the
--  entropy-area relationship: the discrete Newton's constant
--  1/(4G) = 1/2 is an exact rational verified by refl on closed
--  ℕ terms — no limit argument, no Cauchy completeness needed.
--  The ConvergenceWitness from the original Entropic Convergence
--  Conjecture is replaced by HalfBoundWitness at each tower level.
--
--  Per-instance witnesses (717 for Dense-100, 1246 for Dense-200)
--  are generated by the Python oracle (sim/prototyping/
--  17_generate_half_bound.py) and sealed behind abstract in
--  Boundary/Dense100HalfBound.agda and Boundary/Dense200HalfBound.agda.
--
--  Numerical verification:
--    sim/prototyping/15_discrete_bekenstein_hawking.py  (5,140 regions)
--    sim/prototyping/16_half_bound_scaling.py           (32,134 regions)
--    sim/prototyping/17_generate_half_bound.py          (1,963 regions)
--    Zero violations across 4 tilings, 4 strategies, 3 capacities.
--
--  Downstream consumers:
--    Boundary/Dense100HalfBound.agda   — per-instance (717 cases)
--    Boundary/Dense200HalfBound.agda   — per-instance (1246 cases)
--    Bridge/Dense100Thermodynamics.agda — integration with CoarseGrainedRT
--    Bridge/SchematicTower.agda §25    — tower integration
--      (HalfBoundLevel, FullLayerStep, ConvergenceCertificate3L-HB,
--       DiscreteBekensteinHawking)
--
--  Architectural role:
--    This is a Tier 3 (Bridge Layer) module providing the generic
--    half-bound infrastructure consumed by per-instance witnesses
--    and the tower integration.  It depends only on Util/Scalars.agda
--    (for ℚ≥0 = ℕ and _≤ℚ_), Util/NatLemmas.agda (for +-comm and
--    +-assoc), and Bridge/GenericBridge.agda (for PatchData).
--
--  Reference:
--    docs/formal/01-theorems.md §Thm 3     (theorem registry entry)
--    docs/formal/12-bekenstein-hawking.md   (formal treatment)
--    docs/formal/09-thermodynamics.md §5    (tower integration)
--    docs/formal/11-generic-bridge.md §7    (capstone type)
--    docs/physics/discrete-bekenstein-hawking.md  (physics interpretation)
--    docs/physics/five-walls.md             (constructive-reals bypass)
--    docs/engineering/abstract-barrier.md   (why abstract is safe)
--    docs/engineering/oracle-pipeline.md    (scripts 15–17)
--    docs/reference/module-index.md         (module description)
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
--  §1.  HalfBoundWitness — The per-patch half-bound certificate
-- ════════════════════════════════════════════════════════════════════
--
--  A HalfBoundWitness parameterized by a PatchData pd packages:
--
--    area       : RegionTy → ℚ≥0
--      The boundary surface area function.  For a region of k cells
--      with faces_per_cell faces each:
--        area(A) = faces_per_cell · k − 2 · |internal faces within A|
--      Imported from the corresponding AreaLaw module (e.g.,
--      Boundary/Dense100AreaLaw.regionArea).
--
--    half-bound : (r : RegionTy) → (S∂ r +ℚ S∂ r) ≤ℚ area r
--      The sharp half-bound: for every region r, twice the min-cut
--      entropy is bounded by the boundary area.  Stated as
--      (S∂ r + S∂ r) ≤ area r  to avoid division in ℕ.
--      Each per-instance witness is  (k , refl)  where
--      k = area(r) − 2·S(r)  (the "half-slack").
--
--    tight      : Σ[ r ∈ RegionTy ] (S∂ r +ℚ S∂ r ≡ area r)
--      A concrete achiever region where 2·S = area — the bound is
--      saturated.  This confirms that the bound is sharp: the
--      constant 1/2 cannot be improved.
--      For Dense-100: 40 achiever regions (all k=1 cells with
--      S=3, area=6).  For Dense-200: 88 achievers (k=1, k=2, k=3).
--
--  The record lives in Type₀ because all fields are ℕ-valued
--  functions and propositions.
--
--  Reference:
--    docs/formal/12-bekenstein-hawking.md §3.1  (the record)
--    docs/formal/01-theorems.md §Thm 3          (type signature)
-- ════════════════════════════════════════════════════════════════════

record HalfBoundWitness (pd : PatchData) : Type₀ where
  open PatchData pd
  field
    area       : RegionTy → ℚ≥0
    half-bound : (r : RegionTy)
               → (S∂ r +ℚ S∂ r) ≤ℚ area r
    tight      : Σ[ r ∈ RegionTy ]
                   (S∂ r +ℚ S∂ r ≡ area r)


-- ════════════════════════════════════════════════════════════════════
--  §2.  two-le-sum — The arithmetic core
-- ════════════════════════════════════════════════════════════════════
--
--  Given witnesses  (k₁ , p₁)  for  s ≤ a  (meaning k₁ + s ≡ a)
--  and  (k₂ , p₂)  for  s ≤ b  (meaning k₂ + s ≡ b), produce a
--  witness  (k₁ + k₂ , proof)  for  (s + s) ≤ (a + b)  (meaning
--  (k₁ + k₂) + (s + s) ≡ (a + b)).
--
--  The proof  rearrange  shuffles:
--
--    (k₁ + k₂) + (s + s)
--    ≡ (k₁ + s) + (k₂ + s)       [by +-assoc, +-comm rearrangement]
--
--  then  cong₂ _+_ p₁ p₂  converts  (k₁ + s) + (k₂ + s)  to
--  a + b .
--
--  The rearrangement uses 5 steps of ℕ arithmetic from
--  Util/NatLemmas.agda (+-assoc, +-comm):
--
--    1. sym (+-assoc k₁ k₂ (s + s))
--       : k₁ + k₂ + (s + s) ≡ k₁ + (k₂ + (s + s))
--
--    2. cong (k₁ +_) (+-assoc k₂ s s)
--       : k₁ + (k₂ + (s + s)) ≡ k₁ + ((k₂ + s) + s)
--
--    3. +-assoc k₁ (k₂ + s) s
--       : k₁ + ((k₂ + s) + s) ≡ (k₁ + (k₂ + s)) + s
--
--    4. cong (_+ s) (cong (k₁ +_) (+-comm k₂ s) ∙ +-assoc k₁ s k₂)
--       : (k₁ + (k₂ + s)) + s ≡ ((k₁ + s) + k₂) + s
--
--    5. sym (+-assoc (k₁ + s) k₂ s)
--       : ((k₁ + s) + k₂) + s ≡ (k₁ + s) + (k₂ + s)
--
--  This is the only non-trivial ℕ arithmetic in the module.  All
--  downstream proofs (from-two-cuts, per-instance witnesses) reduce
--  to applications of two-le-sum or direct (k , refl) witnesses.
--
--  Reference:
--    docs/formal/12-bekenstein-hawking.md §3.2  (the arithmetic core)
-- ════════════════════════════════════════════════════════════════════

two-le-sum : {s a b : ℕ} → s ≤ℚ a → s ≤ℚ b → (s +ℚ s) ≤ℚ (a +ℚ b)
two-le-sum {s} {a} {b} (k₁ , p₁) (k₂ , p₂) =
  k₁ + k₂ , rearrange ∙ cong₂ _+_ p₁ p₂
  where
    rearrange : (k₁ + k₂) + (s + s) ≡ (k₁ + s) + (k₂ + s)
    rearrange =
        sym (+-assoc k₁ k₂ (s + s))
      ∙ cong (k₁ +_) (+-assoc k₂ s s)
      ∙ +-assoc k₁ (k₂ + s) s
      ∙ cong (_+ s) (cong (k₁ +_) (+-comm k₂ s) ∙ +-assoc k₁ s k₂)
      ∙ sym (+-assoc (k₁ + s) k₂ s)


-- ════════════════════════════════════════════════════════════════════
--  §3.  from-two-cuts — The generic half-bound lemma
-- ════════════════════════════════════════════════════════════════════
--
--  The two-cut decomposition, expressed generically for any region
--  type:
--
--    Given:
--      decomp   : area(r) ≡ n-cross(r) + n-bdy(r)
--      le-cross : S∂(r) ≤ n-cross(r)
--      le-bdy   : S∂(r) ≤ n-bdy(r)
--
--    Derive:
--      (S∂(r) + S∂(r)) ≤ area(r)
--
--  The proof:
--    1. Apply two-le-sum to le-cross(r) and le-bdy(r), obtaining
--       (S∂ r + S∂ r) ≤ (n-cross r + n-bdy r)
--
--    2. Apply subst along sym (decomp r) to convert the RHS from
--       (n-cross r + n-bdy r) to area r.
--
--  This lemma is the GENERIC proof — it works for any finite cell
--  complex with any area decomposition, not just the specific
--  Dense-100 or Dense-200 patches.  Per-instance witnesses (in
--  Boundary/Dense100HalfBound.agda and Dense200HalfBound.agda)
--  instantiate this pattern by providing concrete (k , refl)
--  witnesses for le-cross and le-bdy at each region.
--
--  In practice, the per-instance modules use the simpler direct
--  approach: emit  (k , refl)  where k = area(r) − 2·S(r), which
--  type-checks because ℕ addition reduces judgmentally on closed
--  numerals.  The from-two-cuts lemma is provided for the generic
--  proof path (docs/formal/12-bekenstein-hawking.md §3.3).
--
--  Reference:
--    docs/formal/12-bekenstein-hawking.md §3.3  (from-two-cuts)
--    docs/formal/01-theorems.md §Thm 3          (type signature)
-- ════════════════════════════════════════════════════════════════════

from-two-cuts :
  {RegionTy : Type₀}
  (S∂ area n-cross n-bdy : RegionTy → ℚ≥0)
  → ((r : RegionTy) → area r ≡ n-cross r +ℚ n-bdy r)
  → ((r : RegionTy) → S∂ r ≤ℚ n-cross r)
  → ((r : RegionTy) → S∂ r ≤ℚ n-bdy r)
  → (r : RegionTy) → (S∂ r +ℚ S∂ r) ≤ℚ area r
from-two-cuts S∂ area nc nb decomp le-cross le-bdy r =
  subst ((S∂ r +ℚ S∂ r) ≤ℚ_) (sym (decomp r))
        (two-le-sum (le-cross r) (le-bdy r))


-- ════════════════════════════════════════════════════════════════════
--  §4.  Regression tests
-- ════════════════════════════════════════════════════════════════════
--
--  These verify that two-le-sum and from-two-cuts produce the
--  expected results on concrete numeral arguments.  All hold by
--  refl because ℕ addition computes by structural recursion on
--  closed numerals.
--
--  The tests exercise:
--    • two-le-sum with slack > 0  (3 ≤ 5 and 3 ≤ 4 → 6 ≤ 9)
--    • two-le-sum with slack = 0  (3 ≤ 3 and 3 ≤ 3 → 6 ≤ 6, tight)
--    • The half-bound value itself (3 + 3 = 6)
--    • A direct slack witness ((1 + 1) ≤ 6 via (4 , refl))
--    • from-two-cuts on a trivial constant region type
--
--  These serve as regression tests: if two-le-sum or from-two-cuts
--  changes behavior, these proofs will fail at type-check time.
-- ════════════════════════════════════════════════════════════════════

private

  -- two-le-sum with positive slack:
  --   3 ≤ 5 (via (2 , refl))  and  3 ≤ 4 (via (1 , refl))
  --   → (3 + 3) ≤ (5 + 4) = 6 ≤ 9, slack = 3
  test-two-le : (3 +ℚ 3) ≤ℚ (5 +ℚ 4)
  test-two-le = two-le-sum {3} {5} {4} (2 , refl) (1 , refl)

  -- The composed witness has first component k₁ + k₂ = 2 + 1 = 3
  test-two-le-fst : fst test-two-le ≡ 3
  test-two-le-fst = refl

  -- two-le-sum with zero slack (tight case):
  --   3 ≤ 3 (via (0 , refl))  and  3 ≤ 3 (via (0 , refl))
  --   → (3 + 3) ≤ (3 + 3) = 6 ≤ 6, slack = 0
  --
  --   This is the pattern for achiever regions where 2·S = area.
  test-tight : (3 +ℚ 3) ≤ℚ (3 +ℚ 3)
  test-tight = two-le-sum {3} {3} {3} (0 , refl) (0 , refl)

  -- The tight witness has first component 0 + 0 = 0
  test-tight-fst : fst test-tight ≡ 0
  test-tight-fst = refl

  -- Half-bound value: 3 + 3 = 6 (judgmental)
  --   This is the pattern for a k=1 cell with S=3, area=6 in the
  --   {4,3,5} honeycomb (a cube with 3 neighbors in the patch).
  test-halfbound-value : 3 +ℚ 3 ≡ 6
  test-halfbound-value = refl

  -- Direct slack witness: (1 + 1) ≤ 6 via (4 , refl)
  --   because 4 + (1 + 1) = 4 + 2 = 6 judgmentally
  test-halfbound-slack : (1 +ℚ 1) ≤ℚ 6
  test-halfbound-slack = 4 , refl

  -- from-two-cuts on a trivial constant region type:
  --   S∂ = λ _ → 3,  area = λ _ → 9,
  --   n-cross = λ _ → 5,  n-bdy = λ _ → 4
  --   decomp:  9 ≡ 5 + 4 = 9  (refl)
  --   le-cross:  3 ≤ 5  via (2 , refl)
  --   le-bdy:    3 ≤ 4  via (1 , refl)
  --   → (3 + 3) ≤ 9  with witness k₁ + k₂ = 2 + 1 = 3
  --
  --  Verify the witness first component is 3.
  test-from-two-cuts :
    from-two-cuts {ℕ}
      (λ _ → 3) (λ _ → 9) (λ _ → 5) (λ _ → 4)
      (λ _ → refl) (λ _ → (2 , refl)) (λ _ → (1 , refl))
      0 .fst
    ≡ 3
  test-from-two-cuts = refl


-- ════════════════════════════════════════════════════════════════════
--  §5.  Summary and design notes
-- ════════════════════════════════════════════════════════════════════
--
--  Exports:
--
--    HalfBoundWitness : (pd : PatchData) → Type₀
--      (record with fields  area, half-bound, tight)
--
--    two-le-sum : {s a b : ℕ} → s ≤ℚ a → s ≤ℚ b → (s +ℚ s) ≤ℚ (a +ℚ b)
--      (the arithmetic core — composes two ≤ witnesses into a
--       doubled bound using +-assoc and +-comm)
--
--    from-two-cuts :
--      {RegionTy : Type₀}
--      (S∂ area n-cross n-bdy : RegionTy → ℚ≥0)
--      → ((r : RegionTy) → area r ≡ n-cross r +ℚ n-bdy r)
--      → ((r : RegionTy) → S∂ r ≤ℚ n-cross r)
--      → ((r : RegionTy) → S∂ r ≤ℚ n-bdy r)
--      → (r : RegionTy) → (S∂ r +ℚ S∂ r) ≤ℚ area r
--      (the generic two-cut decomposition — composes decomp +
--       two independent cut bounds via two-le-sum + subst)
--
--  Key architectural consequence:
--
--    The ConvergenceWitness from the original Entropic Convergence
--    Conjecture (which required constructive reals and Cauchy
--    completeness) is replaced by HalfBoundWitness at each tower
--    level (requiring only ℕ arithmetic and refl).
--
--    The discrete Newton's constant 1/(4G) = 1/2 is verified by
--    refl on closed ℕ terms at every resolution level — no limit
--    argument needed.  This bypasses the constructive-reals wall
--    for the entropy-area relationship.
--
--  Tower integration (Bridge/SchematicTower.agda §25):
--
--    DiscreteBekensteinHawking : Type₁
--    DiscreteBekensteinHawking = ConvergenceCertificate3L-HB
--
--    discrete-bekenstein-hawking : DiscreteBekensteinHawking
--
--    This capstone type carries HalfBoundLevel (with area, half-bound,
--    and tight achiever) at each of the 3 resolution levels (Dense-50,
--    Dense-100, Dense-200), together with monotonicity witnesses
--    (7 ≤ 8 ≤ 9).
--
--  Relationship to the area law:
--
--    The half-bound  2·S ≤ area  is strictly stronger than the
--    area law  S ≤ area  (from Boundary/Dense100AreaLaw.agda):
--    since  S ≤ S + S = 2·S ≤ area  for non-negative S, the
--    half-bound implies the area law.  Both are carried in the
--    tower for backward compatibility: existing code consuming
--    area-law continues to work.
--
--  Reference:
--    docs/formal/12-bekenstein-hawking.md  (full formal treatment)
--    docs/formal/01-theorems.md §Thm 3    (theorem registry)
--    docs/formal/11-generic-bridge.md §7  (DiscreteBekensteinHawking)
--    docs/formal/09-thermodynamics.md §5  (tower integration)
--    docs/physics/discrete-bekenstein-hawking.md
--                                         (physics interpretation)
--    docs/physics/five-walls.md           (Wall 1 partially bypassed)
--    docs/getting-started/architecture.md (Bridge Layer)
--    docs/reference/module-index.md       (module description)
-- ════════════════════════════════════════════════════════════════════