{-# OPTIONS --cubical --safe --guardedness #-}

module Bridge.Honeycomb3DObs where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Honeycomb3DSpec
open import Common.ObsPackage
open import Boundary.Honeycomb3DCut
open import Bulk.Honeycomb3DChain

-- ═══════════════════════════════════════════════════════════
--  Canonical views (dummy instances)
-- ═══════════════════════════════════════════════════════════

h3BdyView : H3BdyView
h3BdyView .H3BdyView.dummy = 0

h3BulkView : H3BulkView
h3BulkView .H3BulkView.dummy = 0

-- ═══════════════════════════════════════════════════════════
--  Observable packages for the 3D {4,3,5} patch
-- ═══════════════════════════════════════════════════════════

H3Obs∂ : ObsPackage H3Region
H3Obs∂ .ObsPackage.obs = S-cut h3BdyView

H3ObsBulk : ObsPackage H3Region
H3ObsBulk .ObsPackage.obs = L-min h3BulkView

-- ═══════════════════════════════════════════════════════════
--  h3-pointwise — All 26 cases hold by refl
-- ═══════════════════════════════════════════════════════════
--
--  Both S-cut and L-min return the same ℕ literal for each
--  region: both encode the true min-cut (min separating
--  surface area) through the 3D cell complex.
--
--  This is the 3D discrete Ryu–Takayanagi correspondence:
--  boundary entanglement entropy = bulk minimal surface area.
--
--  Generated by sim/prototyping/06_generate_honeycomb_3d.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/06_generate_honeycomb_3d.py

h3-pointwise :
  (r : H3Region) →
  S-cut h3BdyView r ≡ L-min h3BulkView r
h3-pointwise h3r0 = refl
h3-pointwise h3r1 = refl
h3-pointwise h3r2 = refl
h3-pointwise h3r3 = refl
h3-pointwise h3r4 = refl
h3-pointwise h3r5 = refl
h3-pointwise h3r6 = refl
h3-pointwise h3r7 = refl
h3-pointwise h3r8 = refl
h3-pointwise h3r9 = refl
h3-pointwise h3r10 = refl
h3-pointwise h3r11 = refl
h3-pointwise h3r12 = refl
h3-pointwise h3r13 = refl
h3-pointwise h3r14 = refl
h3-pointwise h3r15 = refl
h3-pointwise h3r16 = refl
h3-pointwise h3r17 = refl
h3-pointwise h3r18 = refl
h3-pointwise h3r19 = refl
h3-pointwise h3r20 = refl
h3-pointwise h3r21 = refl
h3-pointwise h3r22 = refl
h3-pointwise h3r23 = refl
h3-pointwise h3r24 = refl
h3-pointwise h3r25 = refl

-- ═══════════════════════════════════════════════════════════
--  h3-obs-path — Function equality via funExt
-- ═══════════════════════════════════════════════════════════

h3-obs-path :
  S-cut h3BdyView ≡ L-min h3BulkView
h3-obs-path = funExt h3-pointwise

-- ═══════════════════════════════════════════════════════════
--  h3-package-path — Package-level path
-- ═══════════════════════════════════════════════════════════
--
--  This is the 3D analogue of filled-package-path: it
--  identifies the boundary and bulk observable packages
--  for the {4,3,5} honeycomb patch.  The downstream
--  enriched equivalence (Phase D.3) mirrors FilledEquiv.agda
--  using h3-obs-path in place of filled-obs-path.
--

h3-package-path : H3Obs∂ ≡ H3ObsBulk
h3-package-path i .ObsPackage.obs = h3-obs-path i

