{-# OPTIONS --cubical --safe --guardedness #-}

module Bridge.Layer54d2Obs where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Layer54d2Spec
open import Common.ObsPackage
open import Boundary.Layer54d2Cut
open import Bulk.Layer54d2Chain

layer54d2BdyView : Layer54d2BdyView
layer54d2BdyView .Layer54d2BdyView.dummy = 0

layer54d2BulkView : Layer54d2BulkView
layer54d2BulkView .Layer54d2BulkView.dummy = 0

Layer54d2Obs∂ : ObsPackage Layer54d2Region
Layer54d2Obs∂ .ObsPackage.obs = S-cut layer54d2BdyView

Layer54d2ObsBulk : ObsPackage Layer54d2Region
Layer54d2ObsBulk .ObsPackage.obs = L-min layer54d2BulkView

-- layer54d2-pointwise-rep — All 2 orbit cases by refl
-- S-cut-rep and L-min-rep return the same ℕ literal on each orbit.
--  Generated by sim/prototyping/13_generate_layerN.py --depth 2
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 2

layer54d2-pointwise-rep :
  (o : Layer54d2OrbitRep) → S-cut-rep o ≡ L-min-rep o
layer54d2-pointwise-rep mc1 = refl
layer54d2-pointwise-rep mc2 = refl

-- layer54d2-pointwise — Lifted to all 15 regions
-- via classifyLayer54d2 (the orbit reduction 1-line lifting)
--  Generated by sim/prototyping/13_generate_layerN.py --depth 2
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 2

layer54d2-pointwise :
  (r : Layer54d2Region) →
  S-cut layer54d2BdyView r ≡ L-min layer54d2BulkView r
layer54d2-pointwise r = layer54d2-pointwise-rep (classifyLayer54d2 r)

S∂Layer54d2 : Layer54d2Region → ℚ≥0
S∂Layer54d2 = S-cut layer54d2BdyView

LBLayer54d2 : Layer54d2Region → ℚ≥0
LBLayer54d2 = L-min layer54d2BulkView

layer54d2-obs-path : S∂Layer54d2 ≡ LBLayer54d2
layer54d2-obs-path = funExt layer54d2-pointwise

layer54d2-package-path : Layer54d2Obs∂ ≡ Layer54d2ObsBulk
layer54d2-package-path i .ObsPackage.obs = layer54d2-obs-path i

