{-# OPTIONS --cubical --safe --guardedness #-}

module Bridge.SchematicTower where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Equiv
open import Cubical.Data.Nat using (ℕ ; zero ; suc)

open import Util.Scalars

open import Bridge.GenericBridge
  using ( PatchData ; OrbitReducedPatch
        ; orbit-to-patch ; orbit-bridge-witness )

open import Bridge.BridgeWitness
  using (BridgeWitness)


-- ════════════════════════════════════════════════════════════════════
--  §1.  TowerLevel — A single verified holographic slice
-- ════════════════════════════════════════════════════════════════════
--
--  A TowerLevel bundles an oracle-generated OrbitReducedPatch with
--  the fully proof-carrying BridgeWitness extracted from the generic
--  bridge theorem.  The  maxCut  field records the maximum min-cut
--  value among the orbit representatives — the "holographic depth"
--  of this resolution level.
--
--  Reference:
--    docs/10-frontier.md §5.6  (The Inductive Tower)
-- ════════════════════════════════════════════════════════════════════

record TowerLevel : Type₁ where
  field
    patch  : OrbitReducedPatch
    maxCut : ℚ≥0
    bridge : BridgeWitness


-- ════════════════════════════════════════════════════════════════════
--  §2.  mkTowerLevel — Smart constructor (forces generic bridge)
-- ════════════════════════════════════════════════════════════════════
--
--  Derives the bridge witness from  orbit-bridge-witness , ensuring
--  topological consistency: every level uses the same generic proof
--  schema, parameterized only by the oracle-generated data.
-- ════════════════════════════════════════════════════════════════════

mkTowerLevel : OrbitReducedPatch → ℚ≥0 → TowerLevel
mkTowerLevel orp mc = record
  { patch  = orp
  ; maxCut = mc
  ; bridge = orbit-bridge-witness orp
  }


-- ════════════════════════════════════════════════════════════════════
--  §3.  LayerStep — Monotonicity between consecutive tower levels
-- ════════════════════════════════════════════════════════════════════

record LayerStep (lo hi : TowerLevel) : Type₀ where
  field
    monotone : TowerLevel.maxCut lo ≤ℚ TowerLevel.maxCut hi


-- ════════════════════════════════════════════════════════════════════
--  §4.  AreaLawForPatch — Discrete isoperimetric inequality
--       tied to a specific PatchData
-- ════════════════════════════════════════════════════════════════════

record AreaLawForPatch (pd : PatchData) : Type₀ where
  field
    area       : PatchData.RegionTy pd → ℚ≥0
    area-bound : (r : PatchData.RegionTy pd) → PatchData.S∂ pd r ≤ℚ area r


-- ════════════════════════════════════════════════════════════════════
--  §5.  RichLayerStep — Monotonicity + area law at the higher level
-- ════════════════════════════════════════════════════════════════════

record RichLayerStep (lo hi : TowerLevel) : Type₁ where
  field
    monotone : TowerLevel.maxCut lo ≤ℚ TowerLevel.maxCut hi
    area-law : AreaLawForPatch (orbit-to-patch (TowerLevel.patch hi))


-- ════════════════════════════════════════════════════════════════════
--  §6.  Dense-100 and Dense-200 — Existing orbit-reduced patches
-- ════════════════════════════════════════════════════════════════════
--
--  These are imported from Bridge/GenericValidation.agda, which
--  already constructs OrbitReducedPatch instances from the existing
--  Dense-100 (8 orbits, max S=8) and Dense-200 (9 orbits, max S=9)
--  infrastructure.
-- ════════════════════════════════════════════════════════════════════

open import Bridge.GenericValidation
  using (d100OrbitPatch ; d200OrbitPatch)

d100-tower-level : TowerLevel
d100-tower-level = mkTowerLevel d100OrbitPatch 8

d200-tower-level : TowerLevel
d200-tower-level = mkTowerLevel d200OrbitPatch 9


-- ════════════════════════════════════════════════════════════════════
--  §7.  Dense-100 → Dense-200 Layer Step
-- ════════════════════════════════════════════════════════════════════
--
--  The max min-cut grew from 8 to 9.
--  1 + 8 = 9 judgmentally.
-- ════════════════════════════════════════════════════════════════════

d100→d200 : LayerStep d100-tower-level d200-tower-level
d100→d200 .LayerStep.monotone = 1 , refl


-- ════════════════════════════════════════════════════════════════════
--  §8.  Dense-100 → Dense-200 Rich Layer Step  (with area law)
-- ════════════════════════════════════════════════════════════════════

import Boundary.Dense200AreaLaw as D200AL

d100→d200-rich : RichLayerStep d100-tower-level d200-tower-level
d100→d200-rich .RichLayerStep.monotone = 1 , refl
d100→d200-rich .RichLayerStep.area-law = record
  { area       = D200AL.regionArea
  ; area-bound = D200AL.area-law
  }


-- ════════════════════════════════════════════════════════════════════
--  §9.  {5,4} Layer Imports  (Depth 2 through Depth 7)
-- ════════════════════════════════════════════════════════════════════
--
--  Each depth-N patch of the {5,4} hyperbolic pentagonal tiling
--  is generated by sim/prototyping/13_generate_layerN.py and
--  produces 4 Agda modules: Spec, Cut, Chain, Obs.
--
--  Qualified imports prevent name clashes on  S-cut-rep  and
--  L-min-rep  (each depth defines its own versions).
--
--  From 13_generate_layerN_OUTPUT.txt:
--
--    Depth | Tiles | Regions | Orbits | Max S
--    ──────┼───────┼─────────┼────────┼──────
--      2   |   21  |    15   |    2   |   2
--      3   |   61  |    40   |    2   |   2
--      4   |  166  |   105   |    2   |   2
--      5   |  441  |   275   |    2   |   2
--      6   | 1161  |   720   |    2   |   2
--      7   | 3046  |  1885   |    2   |   2
--
--  The exponential boundary growth is the hallmark of hyperbolic
--  geometry: each layer ring adds ~2.6× more tiles than the
--  previous one.  The orbit count stays at 2 (min-cut values
--  are always 1 or 2 for BFS-grown {5,4} patches).
-- ════════════════════════════════════════════════════════════════════

-- ── Depth 2 ────────────────────────────────────────────────────────
import Common.Layer54d2Spec    as L2S
import Boundary.Layer54d2Cut   as L2Cut
import Bulk.Layer54d2Chain     as L2Chain
import Bridge.Layer54d2Obs     as L2Obs

-- ── Depth 3 ────────────────────────────────────────────────────────
import Common.Layer54d3Spec    as L3S
import Boundary.Layer54d3Cut   as L3Cut
import Bulk.Layer54d3Chain     as L3Chain
import Bridge.Layer54d3Obs     as L3Obs

-- ── Depth 4 ────────────────────────────────────────────────────────
import Common.Layer54d4Spec    as L4S
import Boundary.Layer54d4Cut   as L4Cut
import Bulk.Layer54d4Chain     as L4Chain
import Bridge.Layer54d4Obs     as L4Obs

-- ── Depth 5 ────────────────────────────────────────────────────────
import Common.Layer54d5Spec    as L5S
import Boundary.Layer54d5Cut   as L5Cut
import Bulk.Layer54d5Chain     as L5Chain
import Bridge.Layer54d5Obs     as L5Obs

-- ── Depth 6 ────────────────────────────────────────────────────────
import Common.Layer54d6Spec    as L6S
import Boundary.Layer54d6Cut   as L6Cut
import Bulk.Layer54d6Chain     as L6Chain
import Bridge.Layer54d6Obs     as L6Obs

-- ── Depth 7 ────────────────────────────────────────────────────────
import Common.Layer54d7Spec    as L7S
import Boundary.Layer54d7Cut   as L7Cut
import Bulk.Layer54d7Chain     as L7Chain
import Bridge.Layer54d7Obs     as L7Obs


-- ════════════════════════════════════════════════════════════════════
--  §10.  OrbitReducedPatch instances for each {5,4} layer
-- ════════════════════════════════════════════════════════════════════

-- ── Depth 2:  21 tiles, 15 regions → 2 orbits ─────────────────────

layer54d2-orbit : OrbitReducedPatch
layer54d2-orbit .OrbitReducedPatch.RegionTy  = L2S.Layer54d2Region
layer54d2-orbit .OrbitReducedPatch.OrbitTy   = L2S.Layer54d2OrbitRep
layer54d2-orbit .OrbitReducedPatch.classify  = L2S.classifyLayer54d2
layer54d2-orbit .OrbitReducedPatch.S-rep     = L2Cut.S-cut-rep
layer54d2-orbit .OrbitReducedPatch.L-rep     = L2Chain.L-min-rep
layer54d2-orbit .OrbitReducedPatch.rep-agree = L2Obs.layer54d2-pointwise-rep

-- ── Depth 3:  61 tiles, 40 regions → 2 orbits ─────────────────────

layer54d3-orbit : OrbitReducedPatch
layer54d3-orbit .OrbitReducedPatch.RegionTy  = L3S.Layer54d3Region
layer54d3-orbit .OrbitReducedPatch.OrbitTy   = L3S.Layer54d3OrbitRep
layer54d3-orbit .OrbitReducedPatch.classify  = L3S.classifyLayer54d3
layer54d3-orbit .OrbitReducedPatch.S-rep     = L3Cut.S-cut-rep
layer54d3-orbit .OrbitReducedPatch.L-rep     = L3Chain.L-min-rep
layer54d3-orbit .OrbitReducedPatch.rep-agree = L3Obs.layer54d3-pointwise-rep

-- ── Depth 4:  166 tiles, 105 regions → 2 orbits ───────────────────

layer54d4-orbit : OrbitReducedPatch
layer54d4-orbit .OrbitReducedPatch.RegionTy  = L4S.Layer54d4Region
layer54d4-orbit .OrbitReducedPatch.OrbitTy   = L4S.Layer54d4OrbitRep
layer54d4-orbit .OrbitReducedPatch.classify  = L4S.classifyLayer54d4
layer54d4-orbit .OrbitReducedPatch.S-rep     = L4Cut.S-cut-rep
layer54d4-orbit .OrbitReducedPatch.L-rep     = L4Chain.L-min-rep
layer54d4-orbit .OrbitReducedPatch.rep-agree = L4Obs.layer54d4-pointwise-rep

-- ── Depth 5:  441 tiles, 275 regions → 2 orbits ───────────────────

layer54d5-orbit : OrbitReducedPatch
layer54d5-orbit .OrbitReducedPatch.RegionTy  = L5S.Layer54d5Region
layer54d5-orbit .OrbitReducedPatch.OrbitTy   = L5S.Layer54d5OrbitRep
layer54d5-orbit .OrbitReducedPatch.classify  = L5S.classifyLayer54d5
layer54d5-orbit .OrbitReducedPatch.S-rep     = L5Cut.S-cut-rep
layer54d5-orbit .OrbitReducedPatch.L-rep     = L5Chain.L-min-rep
layer54d5-orbit .OrbitReducedPatch.rep-agree = L5Obs.layer54d5-pointwise-rep

-- ── Depth 6:  1161 tiles, 720 regions → 2 orbits ──────────────────

layer54d6-orbit : OrbitReducedPatch
layer54d6-orbit .OrbitReducedPatch.RegionTy  = L6S.Layer54d6Region
layer54d6-orbit .OrbitReducedPatch.OrbitTy   = L6S.Layer54d6OrbitRep
layer54d6-orbit .OrbitReducedPatch.classify  = L6S.classifyLayer54d6
layer54d6-orbit .OrbitReducedPatch.S-rep     = L6Cut.S-cut-rep
layer54d6-orbit .OrbitReducedPatch.L-rep     = L6Chain.L-min-rep
layer54d6-orbit .OrbitReducedPatch.rep-agree = L6Obs.layer54d6-pointwise-rep

-- ── Depth 7:  3046 tiles, 1885 regions → 2 orbits ─────────────────

layer54d7-orbit : OrbitReducedPatch
layer54d7-orbit .OrbitReducedPatch.RegionTy  = L7S.Layer54d7Region
layer54d7-orbit .OrbitReducedPatch.OrbitTy   = L7S.Layer54d7OrbitRep
layer54d7-orbit .OrbitReducedPatch.classify  = L7S.classifyLayer54d7
layer54d7-orbit .OrbitReducedPatch.S-rep     = L7Cut.S-cut-rep
layer54d7-orbit .OrbitReducedPatch.L-rep     = L7Chain.L-min-rep
layer54d7-orbit .OrbitReducedPatch.rep-agree = L7Obs.layer54d7-pointwise-rep


-- ════════════════════════════════════════════════════════════════════
--  §11.  TowerLevel instances for each {5,4} layer
-- ════════════════════════════════════════════════════════════════════
--
--  Each call to  mkTowerLevel  invokes  orbit-bridge-witness ,
--  which composes  orbit-to-patch  with  GenericEnriched  to
--  produce the full enriched equivalence + Univalence path +
--  verified transport.  No per-layer proof engineering is needed.
--
--  All {5,4} BFS-grown layers have max min-cut = 2.
-- ════════════════════════════════════════════════════════════════════

layer54d2-level : TowerLevel
layer54d2-level = mkTowerLevel layer54d2-orbit 2

layer54d3-level : TowerLevel
layer54d3-level = mkTowerLevel layer54d3-orbit 2

layer54d4-level : TowerLevel
layer54d4-level = mkTowerLevel layer54d4-orbit 2

layer54d5-level : TowerLevel
layer54d5-level = mkTowerLevel layer54d5-orbit 2

layer54d6-level : TowerLevel
layer54d6-level = mkTowerLevel layer54d6-orbit 2

layer54d7-level : TowerLevel
layer54d7-level = mkTowerLevel layer54d7-orbit 2


-- ════════════════════════════════════════════════════════════════════
--  §12.  BridgeWitness extraction — the immutable registry
-- ════════════════════════════════════════════════════════════════════

-- ── Dense patches (3D {4,3,5} honeycomb) ───────────────────────────

dense100-bridge : BridgeWitness
dense100-bridge = TowerLevel.bridge d100-tower-level

dense200-bridge : BridgeWitness
dense200-bridge = TowerLevel.bridge d200-tower-level

-- ── {5,4} tiling layers (2D hyperbolic pentagonal tiling) ──────────

layer54d2-bridge : BridgeWitness
layer54d2-bridge = TowerLevel.bridge layer54d2-level

layer54d3-bridge : BridgeWitness
layer54d3-bridge = TowerLevel.bridge layer54d3-level

layer54d4-bridge : BridgeWitness
layer54d4-bridge = TowerLevel.bridge layer54d4-level

layer54d5-bridge : BridgeWitness
layer54d5-bridge = TowerLevel.bridge layer54d5-level

layer54d6-bridge : BridgeWitness
layer54d6-bridge = TowerLevel.bridge layer54d6-level

layer54d7-bridge : BridgeWitness
layer54d7-bridge = TowerLevel.bridge layer54d7-level


-- ════════════════════════════════════════════════════════════════════
--  §13.  LayerStep instances for the {5,4} tower
-- ════════════════════════════════════════════════════════════════════

step-d2→d3 : LayerStep layer54d2-level layer54d3-level
step-d2→d3 .LayerStep.monotone = 0 , refl

step-d3→d4 : LayerStep layer54d3-level layer54d4-level
step-d3→d4 .LayerStep.monotone = 0 , refl

step-d4→d5 : LayerStep layer54d4-level layer54d5-level
step-d4→d5 .LayerStep.monotone = 0 , refl

step-d5→d6 : LayerStep layer54d5-level layer54d6-level
step-d5→d6 .LayerStep.monotone = 0 , refl

step-d6→d7 : LayerStep layer54d6-level layer54d7-level
step-d6→d7 .LayerStep.monotone = 0 , refl


-- ════════════════════════════════════════════════════════════════════
--  §14.  Tower packaging records
-- ════════════════════════════════════════════════════════════════════

-- ── Two-level Dense tower (Dense-100 → Dense-200) ──────────────────

record TwoLevelTower : Type₁ where
  field
    lo-level  : TowerLevel
    hi-level  : TowerLevel
    step      : LayerStep lo-level hi-level

dense-two-level-tower : TwoLevelTower
dense-two-level-tower .TwoLevelTower.lo-level = d100-tower-level
dense-two-level-tower .TwoLevelTower.hi-level = d200-tower-level
dense-two-level-tower .TwoLevelTower.step     = d100→d200

-- ── Full {5,4} layer tower (depth 2 through 7) ────────────────────

record Layer54Tower : Type₁ where
  field
    level-d2   : TowerLevel
    level-d3   : TowerLevel
    level-d4   : TowerLevel
    level-d5   : TowerLevel
    level-d6   : TowerLevel
    level-d7   : TowerLevel
    step-2→3   : LayerStep level-d2 level-d3
    step-3→4   : LayerStep level-d3 level-d4
    step-4→5   : LayerStep level-d4 level-d5
    step-5→6   : LayerStep level-d5 level-d6
    step-6→7   : LayerStep level-d6 level-d7

layer54-tower : Layer54Tower
layer54-tower .Layer54Tower.level-d2 = layer54d2-level
layer54-tower .Layer54Tower.level-d3 = layer54d3-level
layer54-tower .Layer54Tower.level-d4 = layer54d4-level
layer54-tower .Layer54Tower.level-d5 = layer54d5-level
layer54-tower .Layer54Tower.level-d6 = layer54d6-level
layer54-tower .Layer54Tower.level-d7 = layer54d7-level
layer54-tower .Layer54Tower.step-2→3 = step-d2→d3
layer54-tower .Layer54Tower.step-3→4 = step-d3→d4
layer54-tower .Layer54Tower.step-4→5 = step-d4→d5
layer54-tower .Layer54Tower.step-5→6 = step-d5→d6
layer54-tower .Layer54Tower.step-6→7 = step-d6→d7


-- ════════════════════════════════════════════════════════════════════
--  §15.  TowerLevel / Layer regression tests
-- ════════════════════════════════════════════════════════════════════

private
  -- ── Dense maxCut values ──────────────────────────────────────
  check-d100-maxCut : TowerLevel.maxCut d100-tower-level ≡ 8
  check-d100-maxCut = refl

  check-d200-maxCut : TowerLevel.maxCut d200-tower-level ≡ 9
  check-d200-maxCut = refl

  -- ── {5,4} layer maxCut values (all = 2) ──────────────────────
  check-d2-maxCut : TowerLevel.maxCut layer54d2-level ≡ 2
  check-d2-maxCut = refl

  check-d3-maxCut : TowerLevel.maxCut layer54d3-level ≡ 2
  check-d3-maxCut = refl

  check-d7-maxCut : TowerLevel.maxCut layer54d7-level ≡ 2
  check-d7-maxCut = refl

  -- ── Dense monotonicity witness ───────────────────────────────
  check-dense-monotone : LayerStep.monotone d100→d200 ≡ (1 , refl)
  check-dense-monotone = refl

  -- ── {5,4} flat monotonicity witness ──────────────────────────
  check-54-monotone : LayerStep.monotone step-d2→d3 ≡ (0 , refl)
  check-54-monotone = refl

  -- ── Bridge witnesses are well-formed ─────────────────────────
  check-d2-bridge : BridgeWitness
  check-d2-bridge = layer54d2-bridge

  check-d7-bridge : BridgeWitness
  check-d7-bridge = layer54d7-bridge

  check-dense-bridge : BridgeWitness
  check-dense-bridge = dense200-bridge


-- ════════════════════════════════════════════════════════════════════
-- ════════════════════════════════════════════════════════════════════
--
--  ABSORBED FROM Bridge/ResolutionTower.agda
--
--  The following sections consolidate the resolution-tower and
--  convergence-certificate infrastructure that was originally
--  defined in Bridge/ResolutionTower.agda.  That module is now
--  architecturally redundant: SchematicTower subsumes it entirely.
--
--  The ResolutionStep record captures the coarse-graining pattern
--  (dense regions → orbit representatives), while the TowerLevel
--  record (above) captures the bridge-witness pattern.  Both
--  concepts coexist in the same module because the schematic
--  tower needs both: the bridge at each level, AND the resolution
--  factorization between levels.
--
--  Reference:
--    docs/repo-close.md  (Architectural Rewiring Recommendation §4)
--    docs/10-frontier.md §10  (Infinite Resolution / Continuum Limit)
--
-- ════════════════════════════════════════════════════════════════════
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
--  Imports — Dense-100 / Dense-200 Infrastructure for ResolutionStep
-- ════════════════════════════════════════════════════════════════════

open import Common.Dense100Spec
  using ( D100Region ; D100OrbitRep ; classify100 )
open import Boundary.Dense100Cut
  using ( S-cut-rep )
open import Bridge.Dense100Obs
  using ( d100-pointwise ; S∂D100 ; LBD100 )
open import Boundary.Dense100AreaLaw
  using ( regionArea ; area-law )

open import Common.Dense200Spec
  using ( D200Region ; D200OrbitRep ; classify200 )

-- Qualified import to avoid name clash with Dense-100's S-cut-rep
import Boundary.Dense200Cut as D200Cut

open import Bridge.Dense200Obs
  using ( d200-pointwise ; S∂D200 ; LBD200 )

-- D200AL already imported above for RichLayerStep


-- ════════════════════════════════════════════════════════════════════
--  §16.  ResolutionStep — A single step of the resolution tower
-- ════════════════════════════════════════════════════════════════════
--
--  A resolution step pairs two resolution levels (fine and coarse)
--  with a projection from the finer to the coarser, together with:
--
--    • Observable functions at each level  (S-fine, L-fine, S-coarse)
--    • The RT correspondence at the fine level  (rt-fine)
--    • A placeholder RT at the coarse level  (rt-coarse)
--    • A compatibility witness certifying that the fine-level
--      observable factors through the projection  (compat)
--
--  This is exactly  CoarseGrainWitness  from  Bridge/CoarseGrain.agda
--  augmented with the RT correspondence at the fine level.
--
--  The record lives in  Type₁  because it stores types as fields.
--
--  Reference: §10.3 of docs/10-frontier.md
-- ════════════════════════════════════════════════════════════════════

record ResolutionStep : Type₁ where
  field
    -- The two resolution levels
    FineRegion   : Type₀
    CoarseRegion : Type₀

    -- Observables at each level
    S-fine       : FineRegion → ℚ≥0
    L-fine       : FineRegion → ℚ≥0
    S-coarse     : CoarseRegion → ℚ≥0

    -- RT correspondence at each level
    rt-fine      : (r : FineRegion) → S-fine r ≡ L-fine r
    rt-coarse    : (o : CoarseRegion) → S-coarse o ≡ S-coarse o

    -- The coarse-graining factorization
    project      : FineRegion → CoarseRegion
    compat       : (r : FineRegion) →
                   S-fine r ≡ S-coarse (project r)


-- ════════════════════════════════════════════════════════════════════
--  §17.  Dense ResolutionStep instances
-- ════════════════════════════════════════════════════════════════════

dense-resolution-step : ResolutionStep
dense-resolution-step .ResolutionStep.FineRegion   = D100Region
dense-resolution-step .ResolutionStep.CoarseRegion = D100OrbitRep
dense-resolution-step .ResolutionStep.S-fine       = S∂D100
dense-resolution-step .ResolutionStep.L-fine       = LBD100
dense-resolution-step .ResolutionStep.S-coarse     = S-cut-rep
dense-resolution-step .ResolutionStep.rt-fine      = d100-pointwise
dense-resolution-step .ResolutionStep.rt-coarse _  = refl
dense-resolution-step .ResolutionStep.project      = classify100
dense-resolution-step .ResolutionStep.compat _     = refl

dense200-resolution-step : ResolutionStep
dense200-resolution-step .ResolutionStep.FineRegion   = D200Region
dense200-resolution-step .ResolutionStep.CoarseRegion = D200OrbitRep
dense200-resolution-step .ResolutionStep.S-fine       = S∂D200
dense200-resolution-step .ResolutionStep.L-fine       = LBD200
dense200-resolution-step .ResolutionStep.S-coarse     = D200Cut.S-cut-rep
dense200-resolution-step .ResolutionStep.rt-fine      = d200-pointwise
dense200-resolution-step .ResolutionStep.rt-coarse _  = refl
dense200-resolution-step .ResolutionStep.project      = classify200
dense200-resolution-step .ResolutionStep.compat _     = refl


-- ════════════════════════════════════════════════════════════════════
--  §18.  ResolutionTower — ℕ-indexed list of resolution steps
-- ════════════════════════════════════════════════════════════════════
--
--  A tower is a sequence of resolution steps indexed by ℕ.  The
--  base case holds a single step; each subsequent step extends the
--  tower.  The index counts the number of  step  constructors used.
--
--  Reference: §10.3 of docs/10-frontier.md
-- ════════════════════════════════════════════════════════════════════

data ResolutionTower : ℕ → Type₁ where
  base : ResolutionStep → ResolutionTower zero
  step : ∀ {n} → ResolutionStep → ResolutionTower n
       → ResolutionTower (suc n)

single-step-tower : ResolutionTower zero
single-step-tower = base dense-resolution-step

two-step-tower : ResolutionTower (suc zero)
two-step-tower = step dense200-resolution-step single-step-tower


-- ════════════════════════════════════════════════════════════════════
--  §19.  Spectrum monotonicity — The growing min-cut spectrum
-- ════════════════════════════════════════════════════════════════════
--
--  The min-cut spectrum grows monotonically with resolution:
--
--    Dense-50:   max min-cut = 7
--    Dense-100:  max min-cut = 8
--    Dense-200:  max min-cut = 9
--
--  Each transition is a concrete inequality witnessed by (k , refl).
--
--  Reference: §10.5 of docs/10-frontier.md
-- ════════════════════════════════════════════════════════════════════

spectrum-grows-50-100 : 7 ≤ℚ 8
spectrum-grows-50-100 = 1 , refl

spectrum-grows-100-200 : 8 ≤ℚ 9
spectrum-grows-100-200 = 1 , refl


-- ════════════════════════════════════════════════════════════════════
--  §20.  AreaLawLevel — The discrete area law at a single level
-- ════════════════════════════════════════════════════════════════════
--
--  At each finite resolution level, the min-cut entropy is bounded
--  by the boundary surface area of the region:
--
--    S_cut(A)  ≤  area(A)
--
--  This record stores types as fields (RegionTy), so it lives in
--  Type₁.  Compare with  AreaLawForPatch  (§4 above), which is
--  tied to a specific  PatchData  and lives in Type₀.
--
--  Reference: §10.6 of docs/10-frontier.md
-- ════════════════════════════════════════════════════════════════════

record AreaLawLevel : Type₁ where
  field
    RegionTy     : Type₀
    S-obs        : RegionTy → ℚ≥0
    area         : RegionTy → ℚ≥0
    area-bound   : (r : RegionTy) → S-obs r ≤ℚ area r

dense100-area-law-level : AreaLawLevel
dense100-area-law-level .AreaLawLevel.RegionTy   = D100Region
dense100-area-law-level .AreaLawLevel.S-obs      = S∂D100
dense100-area-law-level .AreaLawLevel.area       = regionArea
dense100-area-law-level .AreaLawLevel.area-bound = area-law

dense200-area-law-level : AreaLawLevel
dense200-area-law-level .AreaLawLevel.RegionTy   = D200Region
dense200-area-law-level .AreaLawLevel.S-obs      = S∂D200
dense200-area-law-level .AreaLawLevel.area       = D200AL.regionArea
dense200-area-law-level .AreaLawLevel.area-bound = D200AL.area-law


-- ════════════════════════════════════════════════════════════════════
--  §21.  ConvergenceCertificate — Finite convergence evidence
-- ════════════════════════════════════════════════════════════════════
--
--  These records package the complete convergence evidence at
--  different tower heights.  The 2-level certificate is retained
--  for backward compatibility; the 3-level one extends it with
--  Dense-200.
--
--  Reference: §10.9 / §10.10 of docs/10-frontier.md
-- ════════════════════════════════════════════════════════════════════

-- ── 2-level certificate (Dense-50 → Dense-100) ────────────────────

record ConvergenceCertificate : Type₁ where
  field
    resolution       : ResolutionStep
    tower            : ResolutionTower zero
    monotone         : 7 ≤ℚ 8
    area-law-level   : AreaLawLevel

convergence-certificate : ConvergenceCertificate
convergence-certificate .ConvergenceCertificate.resolution     = dense-resolution-step
convergence-certificate .ConvergenceCertificate.tower          = single-step-tower
convergence-certificate .ConvergenceCertificate.monotone       = spectrum-grows-50-100
convergence-certificate .ConvergenceCertificate.area-law-level = dense100-area-law-level

-- ── 3-level certificate (Dense-50 → Dense-100 → Dense-200) ────────

record ConvergenceCertificate3L : Type₁ where
  field
    -- The two resolution steps (orbit reductions at each level)
    step-100         : ResolutionStep
    step-200         : ResolutionStep

    -- The 2-step resolution tower packaging both steps
    tower            : ResolutionTower (suc zero)

    -- Monotonicity: the max min-cut grows between consecutive levels
    monotone-50-100  : 7 ≤ℚ 8
    monotone-100-200 : 8 ≤ℚ 9

    -- Area law holds at both verified levels
    area-law-100     : AreaLawLevel
    area-law-200     : AreaLawLevel

convergence-certificate-3L : ConvergenceCertificate3L
convergence-certificate-3L .ConvergenceCertificate3L.step-100         = dense-resolution-step
convergence-certificate-3L .ConvergenceCertificate3L.step-200         = dense200-resolution-step
convergence-certificate-3L .ConvergenceCertificate3L.tower            = two-step-tower
convergence-certificate-3L .ConvergenceCertificate3L.monotone-50-100  = spectrum-grows-50-100
convergence-certificate-3L .ConvergenceCertificate3L.monotone-100-200 = spectrum-grows-100-200
convergence-certificate-3L .ConvergenceCertificate3L.area-law-100     = dense100-area-law-level
convergence-certificate-3L .ConvergenceCertificate3L.area-law-200     = dense200-area-law-level


-- ════════════════════════════════════════════════════════════════════
--  §22.  ContinuumLimitEvidence — The fully formalized statement
-- ════════════════════════════════════════════════════════════════════
--
--  The resolution tower for the {4,3,5} honeycomb factors through
--  the orbit reduction at each level, the RT correspondence holds
--  at every resolution, the area-law bound holds at every
--  resolution, and the min-cut spectrum grows monotonically:
--
--    7 ≤ 8 ≤ 9
--
--  Reference: §10.14 of docs/10-frontier.md
-- ════════════════════════════════════════════════════════════════════

ContinuumLimitEvidence : Type₁
ContinuumLimitEvidence = ConvergenceCertificate3L

continuum-limit-evidence : ContinuumLimitEvidence
continuum-limit-evidence = convergence-certificate-3L


-- ════════════════════════════════════════════════════════════════════
--  §23.  ResolutionStep / ConvergenceCertificate regression tests
-- ════════════════════════════════════════════════════════════════════

open import Common.Dense100Spec using (d100r0 ; d100r15)
open import Common.Dense200Spec using (d200r0 ; d200r9)

private
  -- ── Dense-100 compat checks ──────────────────────────────────
  compat-check-d100-0 :
    ResolutionStep.S-fine dense-resolution-step d100r0
    ≡ ResolutionStep.S-coarse dense-resolution-step
        (ResolutionStep.project dense-resolution-step d100r0)
  compat-check-d100-0 = refl

  compat-check-d100-15 :
    ResolutionStep.S-fine dense-resolution-step d100r15
    ≡ ResolutionStep.S-coarse dense-resolution-step
        (ResolutionStep.project dense-resolution-step d100r15)
  compat-check-d100-15 = refl

  -- ── Dense-100 RT checks ──────────────────────────────────────
  rt-check-d100-0 :
    ResolutionStep.S-fine dense-resolution-step d100r0
    ≡ ResolutionStep.L-fine dense-resolution-step d100r0
  rt-check-d100-0 = ResolutionStep.rt-fine dense-resolution-step d100r0

  rt-check-d100-15 :
    ResolutionStep.S-fine dense-resolution-step d100r15
    ≡ ResolutionStep.L-fine dense-resolution-step d100r15
  rt-check-d100-15 = ResolutionStep.rt-fine dense-resolution-step d100r15

  -- ── Dense-200 compat checks ──────────────────────────────────
  compat-check-d200-0 :
    ResolutionStep.S-fine dense200-resolution-step d200r0
    ≡ ResolutionStep.S-coarse dense200-resolution-step
        (ResolutionStep.project dense200-resolution-step d200r0)
  compat-check-d200-0 = refl

  compat-check-d200-9 :
    ResolutionStep.S-fine dense200-resolution-step d200r9
    ≡ ResolutionStep.S-coarse dense200-resolution-step
        (ResolutionStep.project dense200-resolution-step d200r9)
  compat-check-d200-9 = refl

  -- ── Dense-200 RT checks ──────────────────────────────────────
  rt-check-d200-0 :
    ResolutionStep.S-fine dense200-resolution-step d200r0
    ≡ ResolutionStep.L-fine dense200-resolution-step d200r0
  rt-check-d200-0 = ResolutionStep.rt-fine dense200-resolution-step d200r0

  rt-check-d200-9 :
    ResolutionStep.S-fine dense200-resolution-step d200r9
    ≡ ResolutionStep.L-fine dense200-resolution-step d200r9
  rt-check-d200-9 = ResolutionStep.rt-fine dense200-resolution-step d200r9

  -- ── Monotonicity witnesses ────────────────────────────────────
  mono-check-50-100 : spectrum-grows-50-100 ≡ (1 , refl)
  mono-check-50-100 = refl

  mono-check-100-200 : spectrum-grows-100-200 ≡ (1 , refl)
  mono-check-100-200 = refl


-- ════════════════════════════════════════════════════════════════════
--  §24.  Summary and design notes
-- ════════════════════════════════════════════════════════════════════
--
--  This module is the SINGLE CANONICAL tower module for the
--  repository, consolidating the former Bridge/SchematicTower.agda
--  and Bridge/ResolutionTower.agda into one location.
--
--  Exports:
--
--    -- Tower infrastructure (§1-§5)
--    TowerLevel            — OrbitReducedPatch + maxCut + BridgeWitness
--    mkTowerLevel          : OrbitReducedPatch → ℚ≥0 → TowerLevel
--    LayerStep             — monotonicity witness between levels
--    AreaLawForPatch       — area-law bound linked to PatchData
--    RichLayerStep         — LayerStep + AreaLawForPatch at hi level
--
--    -- Dense {4,3,5} honeycomb patches (§6-§8)
--    d100-tower-level      : TowerLevel  (Dense-100, maxCut = 8)
--    d200-tower-level      : TowerLevel  (Dense-200, maxCut = 9)
--    d100→d200             : LayerStep
--    d100→d200-rich        : RichLayerStep
--    dense100-bridge       : BridgeWitness
--    dense200-bridge       : BridgeWitness
--
--    -- {5,4} tiling layers depth 2–7 (§9-§13)
--    layer54d2-orbit .. layer54d7-orbit   : OrbitReducedPatch
--    layer54d2-level .. layer54d7-level   : TowerLevel  (all maxCut = 2)
--    layer54d2-bridge .. layer54d7-bridge : BridgeWitness
--    step-d2→d3 .. step-d6→d7            : LayerStep  (all flat: 2 ≤ 2)
--
--    -- Tower packaging (§14)
--    dense-two-level-tower : TwoLevelTower
--    layer54-tower         : Layer54Tower
--
--    -- Resolution infrastructure (absorbed from ResolutionTower, §16-§22)
--    ResolutionStep             — coarse-graining step record
--    dense-resolution-step      — Dense-100 orbit reduction
--    dense200-resolution-step   — Dense-200 orbit reduction
--    ResolutionTower            — ℕ-indexed tower data type
--    single-step-tower          — 1-step (Dense-100)
--    two-step-tower             — 2-step (Dense-100 + Dense-200)
--    spectrum-grows-50-100      — 7 ≤ℚ 8
--    spectrum-grows-100-200     — 8 ≤ℚ 9
--    AreaLawLevel               — area-law at a standalone level
--    dense100-area-law-level    — Dense-100 area-law instance
--    dense200-area-law-level    — Dense-200 area-law instance
--    ConvergenceCertificate     — 2-level certificate
--    convergence-certificate    — concrete 2-level certificate
--    ConvergenceCertificate3L   — 3-level certificate
--    convergence-certificate-3L — concrete 3-level certificate
--    ContinuumLimitEvidence     — type alias (= ConvergenceCertificate3L)
--    continuum-limit-evidence   — the concrete evidence term
--
--  Architecture:
--
--    Bridge/ResolutionTower.agda is now architecturally redundant.
--    All downstream code should import tower infrastructure from
--    this module instead.  ResolutionTower.agda remains valid and
--    can serve as a historical record, but it is no longer on the
--    critical path.
--
--  Resolution tower summary:
--
--    Level   Patch      Regions  Orbits  Max S  Monotone   Area law
--    ─────   ─────────  ───────  ──────  ─────  ─────────  ────────
--      0     Dense-50     139      —       7      —          —
--      1     Dense-100    717      8       8    (1,refl)   717 cases
--      2     Dense-200   1246      9       9    (1,refl)  1246 cases
-- ════════════════════════════════════════════════════════════════════