#!/usr/bin/env python3
"""
06_generate_honeycomb_3d.py  —  Phase D.1 Agda Code Generator (3D)

Generates five Cubical Agda modules for the {4,3,5} honeycomb 3D
patch, targeting the specification-agreement equivalence (like
FilledEquiv.agda).

Because the 3D star patch has only 130 boundary faces, we skip
the abstract subadditivity/union proofs entirely and target the
pointwise agreement + enriched Iso + ua + transport pipeline.

Generated modules:
  src/Common/Honeycomb3DSpec.agda        — H3Region type, cell type
  src/Boundary/Honeycomb3DCut.agda       — S-cut lookup (boundary)
  src/Bulk/Honeycomb3DChain.agda         — L-min lookup (bulk)
  src/Bulk/Honeycomb3DCurvature.agda     — edge-class curvature, 3D GB
  src/Bridge/Honeycomb3DObs.agda         — pointwise refl, funExt, pkg path

Usage (from repository root):
  python3 sim/prototyping/06_generate_honeycomb_3d.py
  python3 sim/prototyping/06_generate_honeycomb_3d.py --dry-run

Dependencies:  numpy, networkx

Reference:
  docs/10-frontier.md §6.9  (Phase D.0–D.1)
  sim/prototyping/05_honeycomb_3d_prototype.py  (feasibility probe)
"""

from __future__ import annotations

import argparse
import importlib
import sys
from collections import Counter, defaultdict
from itertools import combinations
from pathlib import Path
from typing import NamedTuple

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

try:
    proto = importlib.import_module("05_honeycomb_3d_prototype")
except ModuleNotFoundError:
    sys.exit(
        "ERROR: Could not import 05_honeycomb_3d_prototype.py.\n"
        "       Run from the repository root."
    )

try:
    import numpy as np
    import networkx as nx
except ImportError:
    sys.exit("ERROR: numpy and networkx are required.")

DEFAULT_SRC_DIR = SCRIPT_DIR.parent.parent / "src"

GENERATED_BANNER = (
    "--  Generated by sim/prototyping/06_generate_honeycomb_3d.py\n"
    "--  Do not edit by hand.  Regenerate with:\n"
    "--    python3 sim/prototyping/06_generate_honeycomb_3d.py"
)

# ════════════════════════════════════════════════════════════════════
#  1.  Build the 3D Patch (reusing 05's infrastructure)
# ════════════════════════════════════════════════════════════════════

MAX_CELLS = 7  # yields the "3D star" (~32 cells, 130 bdy faces)


def build_3d_patch() -> dict:
    """Build the {4,3,5} 3D star patch via Coxeter reflections."""
    G = proto.build_gram_matrix()
    refls = proto.build_reflections(G)
    proto.validate_reflections(G, refls)
    cell_center = proto.find_cell_center(G)
    stab = proto.enumerate_group(refls[:3], expected=48)
    face_crossings = proto.find_face_crossings(refls, stab, G)
    adj_pairs, _ = proto.classify_face_pairs(face_crossings)
    patch = proto.build_patch(
        face_crossings, cell_center, MAX_CELLS,
        name="{4,3,5} 3D Star Patch"
    )
    return {
        "patch": patch,
        "face_crossings": face_crossings,
        "adj_pairs": adj_pairs,
        "cell_center": cell_center,
        "gram": G,
    }


# ════════════════════════════════════════════════════════════════════
#  2.  Region Enumeration (connected subsets of boundary cells)
# ════════════════════════════════════════════════════════════════════

class RegionInfo(NamedTuple):
    idx: int
    cells: frozenset[int]
    n_bdy_faces: int
    min_cut: int


def identify_boundary_cells(patch: dict) -> dict[int, int]:
    """Return {cell_id: n_boundary_faces} for all boundary cells."""
    return {cid: n for cid, n in patch["bdy_per_cell"].items() if n > 0}


def build_boundary_adjacency(
    patch: dict, bdy_cells: set[int],
) -> nx.Graph:
    """Build adjacency graph on boundary cells (connected via internal faces)."""
    bg = nx.Graph()
    bg.add_nodes_from(bdy_cells)
    for c1, c2 in patch["internal_faces"]:
        if c1 in bdy_cells and c2 in bdy_cells:
            bg.add_edge(c1, c2)
    return bg


def enumerate_connected_subsets(
    graph: nx.Graph,
    max_size: int,
) -> list[frozenset[int]]:
    """Enumerate all connected subsets of nodes up to max_size."""
    results: set[frozenset[int]] = set()
    nodes = sorted(graph.nodes())

    for start in nodes:
        _dfs_subsets(graph, frozenset([start]), set(graph.neighbors(start)),
                     max_size, results)
    return sorted(results, key=lambda s: (len(s), tuple(sorted(s))))


def _dfs_subsets(
    graph: nx.Graph,
    current: frozenset[int],
    frontier: set[int],
    max_size: int,
    results: set[frozenset[int]],
) -> None:
    """DFS enumeration of connected subsets."""
    if current in results:
        return
    results.add(current)
    if len(current) >= max_size:
        return
    for node in sorted(frontier):
        new_set = current | frozenset([node])
        if new_set not in results:
            new_frontier = (
                frontier
                | set(graph.neighbors(node))
            ) - new_set
            _dfs_subsets(graph, new_set, new_frontier, max_size, results)


def compute_regions(
    patch: dict,
    max_region_cells: int = 4,
) -> list[RegionInfo]:
    """Enumerate boundary-cell regions and compute min-cuts."""
    bdy_cells_map = identify_boundary_cells(patch)
    bdy_cells = set(bdy_cells_map.keys())
    bg = build_boundary_adjacency(patch, bdy_cells)

    subsets = enumerate_connected_subsets(bg, max_region_cells)
    # Remove full boundary (complement is empty)
    if frozenset(bdy_cells) in subsets:
        subsets = [s for s in subsets if s != frozenset(bdy_cells)]

    # Build flow graph
    flow_G, bnode_ids, bnode_to_cell = proto.build_flow_graph(patch)

    # Map cell → boundary pseudo-nodes
    cell_bnodes: dict[int, set[int]] = defaultdict(set)
    for idx in bnode_ids:
        cell_bnodes[bnode_to_cell[idx]].add(idx)

    regions: list[RegionInfo] = []
    for i, subset in enumerate(subsets):
        idx_set: set[int] = set()
        for cid in subset:
            idx_set.update(cell_bnodes[cid])
        if not idx_set:
            continue
        s = proto.compute_min_cut(flow_G, bnode_ids, idx_set)
        regions.append(RegionInfo(i, subset, len(idx_set), s))

    # Re-index
    regions = [
        RegionInfo(i, r.cells, r.n_bdy_faces, r.min_cut)
        for i, r in enumerate(regions)
    ]
    return regions


# ════════════════════════════════════════════════════════════════════
#  3.  Edge Curvature Data
# ════════════════════════════════════════════════════════════════════

class EdgeClassInfo(NamedTuple):
    name: str
    valence_in_patch: int
    full_valence: int       # 5 in {4,3,5}
    count: int
    kappa_quarters: int     # curvature in units of π/2:  4 − valence


def compute_edge_classes(
    data: dict, patch: dict,
) -> list[EdgeClassInfo]:
    """
    Classify the 12 edges of the central cube by their valence
    within the patch.
    """
    face_crossings = data["face_crossings"]
    adj_pairs = data["adj_pairs"]
    cell_center = data["cell_center"]
    p = cell_center

    valences: list[int] = []
    for fi, fj in adj_pairs:
        F_a, F_b = face_crossings[fi], face_crossings[fj]
        dih_elems = proto.enumerate_group([F_a, F_b])
        in_patch = 0
        for g in dih_elems:
            c = g @ p
            k = proto._vec_key(c)
            for cid, mat in patch["cells"].items():
                if proto._vec_key(mat @ p) == k:
                    in_patch += 1
                    break
        valences.append(in_patch)

    # Group by valence
    val_counts = Counter(valences)
    classes: list[EdgeClassInfo] = []
    for val in sorted(val_counts.keys()):
        kappa_q = 4 - val  # in units of π/2
        name = f"ev{val}"
        classes.append(EdgeClassInfo(
            name=name,
            valence_in_patch=val,
            full_valence=5,
            count=val_counts[val],
            kappa_quarters=kappa_q,
        ))
    return classes


# ════════════════════════════════════════════════════════════════════
#  4.  Agda Naming Helpers
# ════════════════════════════════════════════════════════════════════

def region_agda_name(r: RegionInfo) -> str:
    """Agda constructor name for a region."""
    return f"h3r{r.idx}"


def cells_comment(r: RegionInfo) -> str:
    """Human-readable cell set for Agda comments."""
    return "{" + ",".join(f"c{c}" for c in sorted(r.cells)) + "}"


# ════════════════════════════════════════════════════════════════════
#  5.  Agda Module Generators
# ════════════════════════════════════════════════════════════════════

def gen_spec(regions: list[RegionInfo]) -> str:
    """Generate Common/Honeycomb3DSpec.agda."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Common.Honeycomb3DSpec where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  H3Region — Cell-aligned boundary regions of the")
    a("--  {4,3,5} 3D star patch (connected subsets of bdy cells)")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  The patch is the BFS neighborhood of a central cube in")
    a("--  the {4,3,5} hyperbolic honeycomb (5 cubes per edge).")
    a("--  Boundary cells = cells with at least one exposed face.")
    a("--  Regions = connected subsets of boundary cells.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("data H3Region : Type₀ where")

    # Group by region size
    sizes: dict[int, list[RegionInfo]] = defaultdict(list)
    for r in regions:
        sizes[len(r.cells)].append(r)

    for size in sorted(sizes.keys()):
        rs = sizes[size]
        names = [region_agda_name(r) for r in rs]
        a(f"  -- size {size}  ({len(rs)} regions)")
        # Emit in batches of 10 for readability
        for i in range(0, len(names), 10):
            batch = names[i:i+10]
            a(f"  {' '.join(batch)} : H3Region")

    a("")
    return "\n".join(L) + "\n"


def gen_cut(regions: list[RegionInfo]) -> str:
    """Generate Boundary/Honeycomb3DCut.agda."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Boundary.Honeycomb3DCut where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Honeycomb3DSpec")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  H3BdyView — Boundary-side architectural wrapper")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("record H3BdyView : Type₀ where")
    a("  field")
    a("    dummy : ℚ≥0")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  S-cut — Boundary min-cut for the 3D {4,3,5} patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  The min-cut separates a cell-aligned boundary region from")
    a("--  its complement in the 3D cell complex.  In 3D the cut is")
    a("--  a set of internal *faces* (not edges as in 2D).")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("S-cut : H3BdyView → H3Region → ℚ≥0")

    for r in regions:
        rn = region_agda_name(r)
        tc = cells_comment(r)
        a(f"S-cut _ {rn} = {r.min_cut}    -- {tc}")

    a("")
    return "\n".join(L) + "\n"


def gen_chain(regions: list[RegionInfo]) -> str:
    """Generate Bulk/Honeycomb3DChain.agda."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bulk.Honeycomb3DChain where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Honeycomb3DSpec")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  H3BulkView — Bulk-side architectural wrapper")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("record H3BulkView : Type₀ where")
    a("  field")
    a("    dummy : ℚ≥0")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  L-min — Bulk minimal separating surface for the 3D patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  In 3D the bulk minimal chain is a minimal *surface*: a")
    a("--  set of internal faces whose removal disconnects the region")
    a("--  from its complement.  The min-cut = min surface area")
    a("--  (measured in face-count units) is the 3D discrete RT.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("L-min : H3BulkView → H3Region → ℚ≥0")

    for r in regions:
        rn = region_agda_name(r)
        tc = cells_comment(r)
        a(f"L-min _ {rn} = {r.min_cut}    -- {tc}")

    a("")
    return "\n".join(L) + "\n"


def gen_curvature(edge_classes: list[EdgeClassInfo]) -> str:
    """Generate Bulk/Honeycomb3DCurvature.agda."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bulk.Honeycomb3DCurvature where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Cubical.Data.Nat  using (ℕ ; zero ; suc ; _+_ ; _·_)")
    a("open import Cubical.Data.Int")
    a("  using (ℤ ; pos ; negsuc)")
    a("  renaming (_+_ to _+ℤ_)")
    a("")
    a("open import Util.Rationals")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  3D Edge Curvature for the {4,3,5} Honeycomb Patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  In 3D, curvature lives on EDGES (not vertices).")
    a("--  At an interior edge e with valence v (cubes meeting):")
    a("--    κ(e) = 2π − v · (π/2)")
    a("--")
    a("--  For {4,3,5}: full valence = 5, so κ = −π/2 (hyperbolic).")
    a("--  In the flat cubic tiling {4,3,4}: valence = 4, κ = 0.")
    a("--")
    a("--  Combinatorial encoding:  ℚ₁₀ with denominator 20.")
    a("--  κ₂₀(e) = 20 · (1 − v/4) = 20 − 5v   (in twentieths)")
    a("--    v=5 → κ₂₀ = −5   (hyperbolic)")
    a("--    v=4 → κ₂₀ =  0   (flat)")
    a("--    v=3 → κ₂₀ = +5   (boundary)")
    a("--    v=2 → κ₂₀ = +10  (boundary)")
    a("--")
    a(GENERATED_BANNER)
    a("")

    # Edge class data type
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  H3EdgeClass — Edge classes by in-patch valence")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("data H3EdgeClass : Type₀ where")
    names = [ec.name for ec in edge_classes]
    a(f"  {' '.join(names)} : H3EdgeClass")
    a("")

    # Count per class
    a("h3EdgeCount : H3EdgeClass → ℕ")
    for ec in edge_classes:
        a(f"h3EdgeCount {ec.name} = {ec.count}")
    a("")

    # Valence per class
    a("h3Valence : H3EdgeClass → ℕ")
    for ec in edge_classes:
        a(f"h3Valence {ec.name} = {ec.valence_in_patch}")
    a("")

    # Curvature per class (in twentieths)
    a("-- Curvature in twentieths:  20 − 5·valence")
    a("h3Kappa : H3EdgeClass → ℚ₁₀")
    for ec in edge_classes:
        k20 = 20 - 5 * ec.valence_in_patch
        if k20 >= 0:
            a(f"h3Kappa {ec.name} = pos {k20}"
              f"    -- val={ec.valence_in_patch}, κ₂₀={k20}")
        else:
            a(f"h3Kappa {ec.name} = negsuc {-k20 - 1}"
              f"    -- val={ec.valence_in_patch}, κ₂₀={k20}")
    a("")

    # Total curvature sum
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  Total edge curvature (class-weighted sum over 12 edges")
    a("--  of the central cube)")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("totalH3Curvature : ℚ₁₀")
    parts: list[str] = []
    for ec in edge_classes:
        parts.append(f"{ec.count} ·₁₀ h3Kappa {ec.name}")
    a(f"totalH3Curvature = {' +₁₀ '.join(parts)}")
    a("")

    # Compute expected sum
    total_val = sum(ec.count * (20 - 5 * ec.valence_in_patch)
                    for ec in edge_classes)
    if total_val >= 0:
        a(f"-- Expected value: pos {total_val}")
        a(f"totalH3Curvature-check : totalH3Curvature ≡ pos {total_val}")
    else:
        a(f"-- Expected value: negsuc {-total_val - 1}")
        a(f"totalH3Curvature-check : totalH3Curvature"
          f" ≡ negsuc {-total_val - 1}")
    a("totalH3Curvature-check = refl")
    a("")

    return "\n".join(L) + "\n"


def gen_obs(regions: list[RegionInfo]) -> str:
    """Generate Bridge/Honeycomb3DObs.agda."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bridge.Honeycomb3DObs where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Honeycomb3DSpec")
    a("open import Common.ObsPackage")
    a("open import Boundary.Honeycomb3DCut")
    a("open import Bulk.Honeycomb3DChain")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  Canonical views (dummy instances)")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("h3BdyView : H3BdyView")
    a("h3BdyView .H3BdyView.dummy = 0")
    a("")
    a("h3BulkView : H3BulkView")
    a("h3BulkView .H3BulkView.dummy = 0")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  Observable packages for the 3D {4,3,5} patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("H3Obs∂ : ObsPackage H3Region")
    a("H3Obs∂ .ObsPackage.obs = S-cut h3BdyView")
    a("")
    a("H3ObsBulk : ObsPackage H3Region")
    a("H3ObsBulk .ObsPackage.obs = L-min h3BulkView")
    a("")

    # Pointwise agreement
    a("-- ═══════════════════════════════════════════════════════════")
    a(f"--  h3-pointwise — All {len(regions)} cases hold by refl")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Both S-cut and L-min return the same ℕ literal for each")
    a("--  region: both encode the true min-cut (min separating")
    a("--  surface area) through the 3D cell complex.")
    a("--")
    a("--  This is the 3D discrete Ryu–Takayanagi correspondence:")
    a("--  boundary entanglement entropy = bulk minimal surface area.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("h3-pointwise :")
    a("  (r : H3Region) →")
    a("  S-cut h3BdyView r ≡ L-min h3BulkView r")

    for r in regions:
        rn = region_agda_name(r)
        a(f"h3-pointwise {rn} = refl")

    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  h3-obs-path — Function equality via funExt")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("h3-obs-path :")
    a("  S-cut h3BdyView ≡ L-min h3BulkView")
    a("h3-obs-path = funExt h3-pointwise")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  h3-package-path — Package-level path")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  This is the 3D analogue of filled-package-path: it")
    a("--  identifies the boundary and bulk observable packages")
    a("--  for the {4,3,5} honeycomb patch.  The downstream")
    a("--  enriched equivalence (Phase D.3) mirrors FilledEquiv.agda")
    a("--  using h3-obs-path in place of filled-obs-path.")
    a("--")
    a("")
    a("h3-package-path : H3Obs∂ ≡ H3ObsBulk")
    a("h3-package-path i .ObsPackage.obs = h3-obs-path i")
    a("")

    return "\n".join(L) + "\n"


# ════════════════════════════════════════════════════════════════════
#  6.  File Writing
# ════════════════════════════════════════════════════════════════════

FILE_MAP = [
    ("Common/Honeycomb3DSpec.agda",       "spec"),
    ("Boundary/Honeycomb3DCut.agda",      "cut"),
    ("Bulk/Honeycomb3DChain.agda",        "chain"),
    ("Bulk/Honeycomb3DCurvature.agda",    "curv"),
    ("Bridge/Honeycomb3DObs.agda",        "obs"),
]


def write_file(path: Path, content: str, dry_run: bool) -> None:
    lines = content.count("\n")
    if dry_run:
        print(f"  [dry-run]  {path}  ({lines} lines)")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  ✓  {path}  ({lines} lines)")


# ════════════════════════════════════════════════════════════════════
#  7.  Summary
# ════════════════════════════════════════════════════════════════════

def print_summary(
    regions: list[RegionInfo],
    edge_classes: list[EdgeClassInfo],
    patch_info: dict,
) -> None:
    patch = patch_info["patch"]
    print(f"\n  ── Patch Topology ──")
    print(f"  Cells:            {len(patch['cells'])}")
    print(f"  Internal faces:   {len(patch['internal_faces'])}")
    print(f"  Boundary faces:   {patch['n_boundary_faces']}")

    cut_dist = Counter(r.min_cut for r in regions)
    size_dist = Counter(len(r.cells) for r in regions)

    print(f"\n  ── Region Statistics ({len(regions)} total) ──")
    print(f"  By size:")
    for sz in sorted(size_dist):
        print(f"    {sz}-cell regions:  {size_dist[sz]}")
    print(f"  By min-cut value:")
    for val in sorted(cut_dist):
        print(f"    S = {val}:  {cut_dist[val]} regions")

    print(f"\n  ── Edge Curvature (12 central-cube edges) ──")
    for ec in edge_classes:
        k = ec.kappa_quarters
        tag = " ← hyperbolic" if k < 0 else (" (flat)" if k == 0 else "")
        print(f"    Valence {ec.valence_in_patch} (×{ec.count}): "
              f"κ = {k}·(π/2){tag}")

    total_k = sum(ec.count * ec.kappa_quarters for ec in edge_classes)
    print(f"  Total:  Σ κ = {total_k}·(π/2)")


# ════════════════════════════════════════════════════════════════════
#  8.  Main
# ════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate 3D Honeycomb Agda modules (Phase D.1)")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_SRC_DIR)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--max-region-cells", type=int, default=4,
                        help="Max cells per region (default: 4)")
    args = parser.parse_args()

    print("╔══════════════════════════════════════════════════════════╗")
    print("║  Phase D.1: {4,3,5} Honeycomb — 3D Agda Code Generator   ║")
    print("║  Specification-Agreement Equivalence (like FilledEquiv)  ║")
    print("╚══════════════════════════════════════════════════════════╝")

    # Step 1: Build the 3D patch
    print("\n  Building {4,3,5} 3D star patch ...")
    data = build_3d_patch()
    patch = data["patch"]
    print(f"  ✓  {len(patch['cells'])} cells, "
          f"{patch['n_boundary_faces']} boundary faces.")

    # Step 2: Enumerate regions and compute min-cuts
    print(f"\n  Enumerating cell-aligned regions "
          f"(max {args.max_region_cells} cells) ...")
    regions = compute_regions(patch, args.max_region_cells)
    print(f"  ✓  {len(regions)} regions computed.")

    # Step 3: Compute edge curvature
    print("  Computing edge curvature classes ...")
    edge_classes = compute_edge_classes(data, patch)
    print(f"  ✓  {len(edge_classes)} edge classes.")

    # Step 4: Print summary
    print_summary(regions, edge_classes, data)

    # Step 5: Generate Agda files
    src_dir = args.output_dir.resolve()
    print(f"\n  Output directory: {src_dir}")
    if args.dry_run:
        print("  [DRY RUN — no files written]\n")
    print()

    generators = {
        "spec":  lambda: gen_spec(regions),
        "cut":   lambda: gen_cut(regions),
        "chain": lambda: gen_chain(regions),
        "curv":  lambda: gen_curvature(edge_classes),
        "obs":   lambda: gen_obs(regions),
    }

    total_lines = 0
    for rel_path, gen_key in FILE_MAP:
        content = generators[gen_key]()
        full_path = src_dir / rel_path
        write_file(full_path, content, args.dry_run)
        total_lines += content.count("\n")

    # Step 6: Final report
    action = "would generate" if args.dry_run else "generated"
    print(f"\n  ── Summary: {action} {len(FILE_MAP)} files, "
          f"~{total_lines} lines total ──")

    # Gate check
    n_bdy = patch["n_boundary_faces"]
    n_regs = len(regions)
    n_full = sum(1 for ec in edge_classes
                 if ec.valence_in_patch >= 5)
    print(f"\n  ── Gate Check ──")
    print(f"    Boundary faces:   {n_bdy}"
          f"  {'✓' if 100 <= n_bdy <= 500 else '✗'}  (target 100–500)")
    print(f"    Region count:     {n_regs}"
          f"  {'✓' if n_regs <= 200 else '✗'}  (target ≤200)")
    print(f"    Full-valence edges: {n_full * 12 if n_full else 0}"
          f"  {'✓' if n_full > 0 else '✗'}  (need ≥1)")

    print(f"""
  Next steps:
    1. Load generated files in Agda to verify they type-check.
    2. Write  Bridge/Honeycomb3DEquiv.agda  (hand-written) to
       assemble the enriched Iso / Equiv / ua / transport,
       mirroring Bridge/FilledEquiv.agda.
    3. If orbit count or region count is too large, trigger
       Phase D.2 (boolean reflection) per §6.9.
""")


if __name__ == "__main__":
    main()