#!/usr/bin/env python3
"""
06b_generate_honeycomb145.py  —  Honeycomb-145 Agda Code Generator

Generates Cubical Agda modules for a 145-cell Dense patch of the
{4,3,5} hyperbolic honeycomb, utilizing the orbit reduction strategy.

This is a thin adaptation of 09_generate_dense100.py with:
  MAX_CELLS = 145
  Module names:  Dense100  →  Honeycomb145
  Constructor prefix:  d100  →  h145
  Classify function:  classify100  →  classify145

Generated modules:
  src/Common/Honeycomb145Spec.agda
  src/Boundary/Honeycomb145Cut.agda
  src/Bulk/Honeycomb145Chain.agda
  src/Bulk/Honeycomb145Curvature.agda
  src/Bridge/Honeycomb145Obs.agda

Usage (from repository root):
  python3 sim/prototyping/06b_generate_honeycomb145.py
  python3 sim/prototyping/06b_generate_honeycomb145.py --dry-run

Dependencies:  numpy, networkx
"""

from __future__ import annotations

import argparse
import importlib
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import NamedTuple

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

try:
    multi = importlib.import_module("07_honeycomb_3d_multiStrategy")
except ModuleNotFoundError:
    sys.exit(
        "ERROR: Could not import 07_honeycomb_3d_multiStrategy.py.\n"
        "       Run this script from the repository root:\n"
        "         python3 sim/prototyping/06b_generate_honeycomb145.py"
    )

try:
    import numpy as np
    import networkx as nx
except ImportError:
    sys.exit("ERROR: numpy and networkx are required.  "
             "pip install numpy networkx")

DEFAULT_SRC_DIR = SCRIPT_DIR.parent.parent / "src"

GENERATED_BANNER = (
    "--  Generated by sim/prototyping/06b_generate_honeycomb145.py\n"
    "--  Do not edit by hand.  Regenerate with:\n"
    "--    python3 sim/prototyping/06b_generate_honeycomb145.py"
)

MAX_CELLS = 145
MAX_REGION_CELLS = 5


# ════════════════════════════════════════════════════════════════════
#  1.  Build the Dense-145 Patch
# ════════════════════════════════════════════════════════════════════

def build_patch() -> dict:
    G = multi.build_gram_matrix()
    refls = multi.build_reflections(G)
    multi.validate_reflections(G, refls)
    cell_center = multi.find_cell_center(G)
    stab = multi.enumerate_group(refls[:3], expected=48)
    face_crossings = multi.find_face_crossings(refls, stab, G)
    adj_pairs, opp_pairs = multi.classify_face_pairs(face_crossings)
    patch = multi.build_patch_dense(
        face_crossings, cell_center, MAX_CELLS,
        name=f"Honeycomb-145 ({{4,3,5}} honeycomb)"
    )
    return {
        "patch": patch,
        "face_crossings": face_crossings,
        "adj_pairs": adj_pairs,
        "opp_pairs": opp_pairs,
        "cell_center": cell_center,
        "gram": G,
    }


# ════════════════════════════════════════════════════════════════════
#  2.  Region Computation
# ════════════════════════════════════════════════════════════════════

class RegionInfo(NamedTuple):
    idx: int
    cells: frozenset[int]
    n_bdy_faces: int
    min_cut: int


def compute_regions(patch: dict) -> list[RegionInfo]:
    flow_G, bnode_ids, bnode_to_cell = multi.build_flow_graph(patch)
    regions_raw = multi.enumerate_cell_aligned_regions(
        patch, bnode_to_cell, bnode_ids,
        max_region_cells=MAX_REGION_CELLS,
    )
    regions: list[RegionInfo] = []
    for label, idx_set in regions_raw:
        cells_str = label.strip("{}").split(",")
        cells = frozenset(
            int(s.strip().lstrip("c")) for s in cells_str if s.strip()
        )
        s = multi.compute_min_cut(flow_G, bnode_ids, idx_set)
        regions.append(RegionInfo(len(regions), cells, len(idx_set), s))
    return regions


# ════════════════════════════════════════════════════════════════════
#  3.  Orbit Reduction
# ════════════════════════════════════════════════════════════════════

class OrbitRep(NamedTuple):
    name: str
    min_cut: int
    count: int


def compute_orbits(regions: list[RegionInfo]) -> list[OrbitRep]:
    cut_counts = Counter(r.min_cut for r in regions)
    return [OrbitRep(f"mc{v}", v, cut_counts[v])
            for v in sorted(cut_counts)]


def orbit_for_region(r: RegionInfo, orbits: list[OrbitRep]) -> OrbitRep:
    for orb in orbits:
        if orb.min_cut == r.min_cut:
            return orb
    raise ValueError(f"No orbit for min-cut {r.min_cut}")


# ════════════════════════════════════════════════════════════════════
#  4.  Edge Curvature Classes
# ════════════════════════════════════════════════════════════════════

class EdgeClassInfo(NamedTuple):
    name: str
    valence_in_patch: int
    full_valence: int
    count: int
    kappa_twentieths: int


def compute_edge_classes(data: dict, patch: dict) -> list[EdgeClassInfo]:
    face_crossings = data["face_crossings"]
    adj_pairs = data["adj_pairs"]
    cell_center = data["cell_center"]
    p = cell_center
    patch_centers = {multi._vec_key(mat @ p)
                     for mat in patch["cells"].values()}
    valences: list[int] = []
    for fi, fj in adj_pairs:
        F_a, F_b = face_crossings[fi], face_crossings[fj]
        dih_elems = multi.enumerate_group([F_a, F_b])
        orbit_centers = {multi._vec_key(g @ p) for g in dih_elems}
        in_patch = len(orbit_centers & patch_centers)
        valences.append(in_patch)
    val_counts = Counter(valences)
    return [EdgeClassInfo(f"ev{v}", v, 5, val_counts[v], 20 - 5 * v)
            for v in sorted(val_counts)]


# ════════════════════════════════════════════════════════════════════
#  5.  Agda Helpers
# ════════════════════════════════════════════════════════════════════

def region_agda_name(r: RegionInfo) -> str:
    return f"h145r{r.idx}"


def cells_comment(r: RegionInfo) -> str:
    cs = sorted(r.cells)
    if len(cs) <= 6:
        return "{" + ",".join(f"c{c}" for c in cs) + "}"
    return "{" + ",".join(f"c{c}" for c in cs[:5]) + ",..." + "}"


# ════════════════════════════════════════════════════════════════════
#  6.  Agda Module Generators
# ════════════════════════════════════════════════════════════════════

def gen_spec(regions, orbits):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Common.Honeycomb145Spec where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars"); a("")
    a(GENERATED_BANNER); a("")
    a("data H145Region : Type₀ where")
    sizes: dict[int, list] = defaultdict(list)
    for r in regions:
        sizes[len(r.cells)].append(r)
    for size in sorted(sizes):
        rs = sizes[size]
        names = [region_agda_name(r) for r in rs]
        a(f"  -- size {size}  ({len(rs)} regions)")
        for i in range(0, len(names), 10):
            a(f"  {' '.join(names[i:i+10])} : H145Region")
    a("")
    a("data H145OrbitRep : Type₀ where")
    a(f"  {' '.join(o.name for o in orbits)} : H145OrbitRep")
    a("")
    a(GENERATED_BANNER); a("")
    a("classify145 : H145Region → H145OrbitRep")
    for r in regions:
        orb = orbit_for_region(r, orbits)
        a(f"classify145 {region_agda_name(r)} = {orb.name}")
    a("")
    return "\n".join(L) + "\n"


def gen_cut(regions, orbits):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Boundary.Honeycomb145Cut where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Honeycomb145Spec"); a("")
    a("record H145BdyView : Type₀ where")
    a("  field"); a("    dummy : ℚ≥0"); a("")
    a(GENERATED_BANNER); a("")
    a("S-cut-rep : H145OrbitRep → ℚ≥0")
    for orb in orbits:
        a(f"S-cut-rep {orb.name} = {orb.min_cut}")
    a("")
    a("S-cut : H145BdyView → H145Region → ℚ≥0")
    a("S-cut _ r = S-cut-rep (classify145 r)")
    a("")
    return "\n".join(L) + "\n"


def gen_chain(regions, orbits):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Bulk.Honeycomb145Chain where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Honeycomb145Spec"); a("")
    a("record H145BulkView : Type₀ where")
    a("  field"); a("    dummy : ℚ≥0"); a("")
    a(GENERATED_BANNER); a("")
    a("L-min-rep : H145OrbitRep → ℚ≥0")
    for orb in orbits:
        a(f"L-min-rep {orb.name} = {orb.min_cut}")
    a("")
    a("L-min : H145BulkView → H145Region → ℚ≥0")
    a("L-min _ r = L-min-rep (classify145 r)")
    a("")
    return "\n".join(L) + "\n"


def gen_curvature(edge_classes):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Bulk.Honeycomb145Curvature where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Cubical.Data.Nat  using (ℕ ; zero ; suc ; _+_ ; _·_)")
    a("open import Cubical.Data.Int")
    a("  using (ℤ ; pos ; negsuc)")
    a("  renaming (_+_ to _+ℤ_)")
    a(""); a("open import Util.Rationals")
    a(""); a(GENERATED_BANNER); a("")
    a("data H145EdgeClass : Type₀ where")
    a(f"  {' '.join(ec.name for ec in edge_classes)} : H145EdgeClass")
    a("")
    a("h145EdgeCount : H145EdgeClass → ℕ")
    for ec in edge_classes:
        a(f"h145EdgeCount {ec.name} = {ec.count}")
    a("")
    a("h145Kappa : H145EdgeClass → ℚ₁₀")
    for ec in edge_classes:
        k20 = ec.kappa_twentieths
        if k20 >= 0:
            a(f"h145Kappa {ec.name} = pos {k20}")
        else:
            a(f"h145Kappa {ec.name} = negsuc {-k20 - 1}")
    a("")
    a("totalH145Curvature : ℚ₁₀")
    parts = [f"{ec.count} ·₁₀ h145Kappa {ec.name}" for ec in edge_classes]
    a(f"totalH145Curvature = {' +₁₀ '.join(parts)}")
    a("")
    total_val = sum(ec.count * ec.kappa_twentieths for ec in edge_classes)
    exp = f"pos {total_val}" if total_val >= 0 else f"negsuc {-total_val - 1}"
    a(f"totalH145Curvature-check : totalH145Curvature ≡ {exp}")
    a("totalH145Curvature-check = refl")
    a("")
    return "\n".join(L) + "\n"


def gen_obs(regions, orbits):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Bridge.Honeycomb145Obs where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Honeycomb145Spec")
    a("open import Common.ObsPackage")
    a("open import Boundary.Honeycomb145Cut")
    a("open import Bulk.Honeycomb145Chain"); a("")
    a("h145BdyView : H145BdyView")
    a("h145BdyView .H145BdyView.dummy = 0"); a("")
    a("h145BulkView : H145BulkView")
    a("h145BulkView .H145BulkView.dummy = 0"); a("")
    a("H145Obs∂ : ObsPackage H145Region")
    a("H145Obs∂ .ObsPackage.obs = S-cut h145BdyView"); a("")
    a("H145ObsBulk : ObsPackage H145Region")
    a("H145ObsBulk .ObsPackage.obs = L-min h145BulkView"); a("")
    a(GENERATED_BANNER); a("")
    a("h145-pointwise-rep :")
    a("  (o : H145OrbitRep) → S-cut-rep o ≡ L-min-rep o")
    for orb in orbits:
        a(f"h145-pointwise-rep {orb.name} = refl")
    a("")
    a("h145-pointwise :")
    a("  (r : H145Region) →")
    a("  S-cut h145BdyView r ≡ L-min h145BulkView r")
    a("h145-pointwise r = h145-pointwise-rep (classify145 r)")
    a("")
    a("S∂H145 : H145Region → ℚ≥0")
    a("S∂H145 = S-cut h145BdyView"); a("")
    a("LBH145 : H145Region → ℚ≥0")
    a("LBH145 = L-min h145BulkView"); a("")
    a("h145-obs-path : S∂H145 ≡ LBH145")
    a("h145-obs-path = funExt h145-pointwise"); a("")
    a("h145-package-path : H145Obs∂ ≡ H145ObsBulk")
    a("h145-package-path i .ObsPackage.obs = h145-obs-path i")
    a("")
    return "\n".join(L) + "\n"


# ════════════════════════════════════════════════════════════════════
#  7.  File Writing
# ════════════════════════════════════════════════════════════════════

FILE_MAP = [
    ("Common/Honeycomb145Spec.agda",       "spec"),
    ("Boundary/Honeycomb145Cut.agda",      "cut"),
    ("Bulk/Honeycomb145Chain.agda",        "chain"),
    ("Bulk/Honeycomb145Curvature.agda",    "curv"),
    ("Bridge/Honeycomb145Obs.agda",        "obs"),
]


def write_file(path: Path, content: str, dry_run: bool) -> None:
    lines = content.count("\n")
    if dry_run:
        print(f"  [dry-run]  {path}  ({lines} lines)")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  ✓  {path}  ({lines} lines)")


# ════════════════════════════════════════════════════════════════════
#  8.  Main
# ════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Honeycomb-145 Cubical Agda modules "
                    "with orbit reduction")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_SRC_DIR)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    print("╔═══════════════════════════════════════════════════════════╗")
    print("║  Honeycomb-145 {4,3,5} — Orbit-Reduced Agda Generator   ║")
    print("║  Greedy max-connectivity • 145 cells                     ║")
    print("╚═══════════════════════════════════════════════════════════╝")

    # Step 1: Build the patch
    print(f"\n  Building Dense-{MAX_CELLS} patch ...")
    data = build_patch()
    patch = data["patch"]
    print(f"  ✓  {len(patch['cells'])} cells, "
          f"{len(patch['internal_faces'])} internal faces, "
          f"{patch['n_boundary_faces']} boundary faces.")

    # Step 2: Compute regions
    print(f"\n  Enumerating regions (max {MAX_REGION_CELLS} cells) ...")
    regions = compute_regions(patch)
    print(f"  ✓  {len(regions)} regions computed.")
    if not regions:
        print("  ✗  No regions found!")
        return
    min_s = min(r.min_cut for r in regions)
    max_s = max(r.min_cut for r in regions)
    print(f"  Min-cut range: {min_s} – {max_s}")

    # Step 3: Orbits
    print("  Computing orbit reduction ...")
    orbits = compute_orbits(regions)
    print(f"  ✓  {len(orbits)} orbits "
          f"({len(regions)} → {len(orbits)}, "
          f"{len(regions)//max(len(orbits),1)}× reduction)")

    # Step 4: Curvature
    print("  Computing edge curvature classes ...")
    edge_classes = compute_edge_classes(data, patch)
    print(f"  ✓  {len(edge_classes)} edge class(es).")

    # Step 5: Summary
    print(f"\n  ── Summary ──")
    cut_dist = Counter(r.min_cut for r in regions)
    for val in sorted(cut_dist):
        print(f"    S = {val}: {cut_dist[val]} regions")
    print(f"  Orbits:")
    for orb in orbits:
        print(f"    {orb.name}  (S={orb.min_cut}): {orb.count} regions")

    # Step 6: Generate files
    src_dir = args.output_dir.resolve()
    print(f"\n  Output directory: {src_dir}")
    if args.dry_run:
        print("  [DRY RUN]\n")
    print()

    generators = {
        "spec":  lambda: gen_spec(regions, orbits),
        "cut":   lambda: gen_cut(regions, orbits),
        "chain": lambda: gen_chain(regions, orbits),
        "curv":  lambda: gen_curvature(edge_classes),
        "obs":   lambda: gen_obs(regions, orbits),
    }

    total_lines = 0
    for rel_path, gen_key in FILE_MAP:
        content = generators[gen_key]()
        write_file(src_dir / rel_path, content, args.dry_run)
        total_lines += content.count("\n")

    action = "would generate" if args.dry_run else "generated"
    print(f"\n  ── {action} {len(FILE_MAP)} files, "
          f"~{total_lines} lines total ──")
    print(f"\n  H145Region constructors:  {len(regions)}")
    print(f"  H145OrbitRep constructors: {len(orbits)}")
    print(f"  classify145 clauses:       {len(regions)}")
    print(f"  Pointwise-rep proofs:      {len(orbits)}")
    print(f"  Max min-cut:               {max_s}")
    print(f"""
  To register in Bridge/GenericValidation.agda:

    open import Common.Honeycomb145Spec
      using (H145Region ; H145OrbitRep ; classify145)
    import Boundary.Honeycomb145Cut as H145Cut
    import Bulk.Honeycomb145Chain   as H145Chain
    open import Bridge.Honeycomb145Obs
      using (h145-pointwise-rep)

    h145OrbitPatch : OrbitReducedPatch
    h145OrbitPatch .OrbitReducedPatch.RegionTy  = H145Region
    h145OrbitPatch .OrbitReducedPatch.OrbitTy   = H145OrbitRep
    h145OrbitPatch .OrbitReducedPatch.classify  = classify145
    h145OrbitPatch .OrbitReducedPatch.S-rep     = H145Cut.S-cut-rep
    h145OrbitPatch .OrbitReducedPatch.L-rep     = H145Chain.L-min-rep
    h145OrbitPatch .OrbitReducedPatch.rep-agree = h145-pointwise-rep

    h145-generic-witness : BridgeWitness
    h145-generic-witness = orbit-bridge-witness h145OrbitPatch
""")


if __name__ == "__main__":
    main()