#!/usr/bin/env python3
"""
08_generate_dense50.py  —  Phase D.1b Dense-50 Agda Code Generator

Synthesizes the graph traversal from 07_honeycomb_3d_multiStrategy.py
with the code-emission logic of 06_generate_honeycomb_3d.py to generate
five Cubical Agda modules for the Dense-50 patch of the {4,3,5}
hyperbolic honeycomb.

The Dense-50 patch is grown by greedy max-connectivity from the
central cube in the {4,3,5} honeycomb (5 cubes at every edge),
producing 50 cells with 68 internal shared faces, 164 boundary
faces, and 139 cell-aligned boundary regions with min-cut values
ranging from 2 to 7.  This establishes genuine "Holographic Depth":
boundary regions require cutting through multi-face separating
surfaces in the 3D bulk, not just single-face cuts as in the BFS
shell patches.

Generated modules:
  src/Common/Dense50Spec.agda           — D50Region (139 constructors)
  src/Boundary/Dense50Cut.agda          — S-cut (139 clauses, values 2–7)
  src/Bulk/Dense50Chain.agda            — L-min (139 clauses)
  src/Bulk/Dense50Curvature.agda        — edge-class κ₂₀ + Gauss–Bonnet refl
  src/Bridge/Dense50Obs.agda            — d50-pointwise, d50-obs-path,
                                          d50-package-path

Usage (from repository root):
  python3 sim/prototyping/08_generate_dense50.py
  python3 sim/prototyping/08_generate_dense50.py --dry-run
  python3 sim/prototyping/08_generate_dense50.py --output-dir /path/to/src

Dependencies:  numpy, networkx

Reference:
  docs/10-frontier.md §6  (Direction D — 3D Hyperbolic Honeycombs)
  sim/prototyping/07_honeycomb_3d_multiStrategy.py  (Dense growth strategy)
  sim/prototyping/06_generate_honeycomb_3d.py       (code-emission pattern)
"""

from __future__ import annotations

import argparse
import importlib
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import NamedTuple

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

try:
    multi = importlib.import_module("07_honeycomb_3d_multiStrategy")
except ModuleNotFoundError:
    sys.exit(
        "ERROR: Could not import 07_honeycomb_3d_multiStrategy.py.\n"
        "       Run this script from the repository root:\n"
        "         python3 sim/prototyping/08_generate_dense50.py"
    )

try:
    import numpy as np
    import networkx as nx
except ImportError:
    sys.exit("ERROR: numpy and networkx are required.  "
             "pip install numpy networkx")

DEFAULT_SRC_DIR = SCRIPT_DIR.parent.parent / "src"

GENERATED_BANNER = (
    "--  Generated by sim/prototyping/08_generate_dense50.py\n"
    "--  Do not edit by hand.  Regenerate with:\n"
    "--    python3 sim/prototyping/08_generate_dense50.py"
)

MAX_CELLS = 50
MAX_REGION_CELLS = 5


# ════════════════════════════════════════════════════════════════════
#  1.  Build the Dense-50 Patch
# ════════════════════════════════════════════════════════════════════

def build_dense50_patch() -> dict:
    """
    Build the Dense-50 patch of the {4,3,5} honeycomb using the
    greedy max-connectivity growth strategy from 07.

    Returns a dict with the patch data plus Coxeter geometry objects
    needed for edge-class curvature computation.
    """
    G = multi.build_gram_matrix()
    refls = multi.build_reflections(G)
    multi.validate_reflections(G, refls)

    cell_center = multi.find_cell_center(G)
    stab = multi.enumerate_group(refls[:3], expected=48)
    face_crossings = multi.find_face_crossings(refls, stab, G)
    adj_pairs, opp_pairs = multi.classify_face_pairs(face_crossings)

    patch = multi.build_patch_dense(
        face_crossings, cell_center, MAX_CELLS,
        name="Dense-50 ({4,3,5} honeycomb)"
    )

    return {
        "patch": patch,
        "face_crossings": face_crossings,
        "adj_pairs": adj_pairs,
        "opp_pairs": opp_pairs,
        "cell_center": cell_center,
        "gram": G,
    }


# ════════════════════════════════════════════════════════════════════
#  2.  Region Computation
# ════════════════════════════════════════════════════════════════════

class RegionInfo(NamedTuple):
    idx: int
    cells: frozenset[int]
    n_bdy_faces: int
    min_cut: int


def compute_regions(patch: dict) -> list[RegionInfo]:
    """
    Enumerate all cell-aligned boundary regions (connected subsets
    of boundary cells up to MAX_REGION_CELLS cells) and compute
    their min-cut values via max-flow.
    """
    flow_G, bnode_ids, bnode_to_cell = multi.build_flow_graph(patch)

    # Use 07's region enumeration which returns (label, bnode_set) pairs
    regions_raw = multi.enumerate_cell_aligned_regions(
        patch, bnode_to_cell, bnode_ids,
        max_region_cells=MAX_REGION_CELLS,
    )

    regions: list[RegionInfo] = []
    for label, idx_set in regions_raw:
        # Parse cell IDs from label "{c0,c1,...}"
        cells_str = label.strip("{}").split(",")
        cells = frozenset(
            int(s.strip().lstrip("c")) for s in cells_str if s.strip()
        )
        s = multi.compute_min_cut(flow_G, bnode_ids, idx_set)
        regions.append(RegionInfo(len(regions), cells, len(idx_set), s))

    return regions


# ════════════════════════════════════════════════════════════════════
#  3.  Edge Curvature Classes
# ════════════════════════════════════════════════════════════════════

class EdgeClassInfo(NamedTuple):
    name: str
    valence_in_patch: int
    full_valence: int       # 5 in {4,3,5}
    count: int
    kappa_twentieths: int   # curvature encoding: 20 − 5·valence


def compute_edge_classes(data: dict, patch: dict) -> list[EdgeClassInfo]:
    """
    Classify the 12 edges of the central cube by their in-patch
    valence (number of dihedral-orbit cells actually present in
    the patch).

    Uses the deduplicated orbit-center approach from 07 (not the
    buggy double-counting in 05).
    """
    face_crossings = data["face_crossings"]
    adj_pairs = data["adj_pairs"]
    cell_center = data["cell_center"]
    p = cell_center

    patch_centers = {multi._vec_key(mat @ p)
                     for mat in patch["cells"].values()}

    valences: list[int] = []
    for fi, fj in adj_pairs:
        F_a, F_b = face_crossings[fi], face_crossings[fj]
        dih_elems = multi.enumerate_group([F_a, F_b])
        orbit_centers = {multi._vec_key(g @ p) for g in dih_elems}
        in_patch = len(orbit_centers & patch_centers)
        valences.append(in_patch)

    val_counts = Counter(valences)
    classes: list[EdgeClassInfo] = []
    for val in sorted(val_counts.keys()):
        k20 = 20 - 5 * val
        name = f"ev{val}"
        classes.append(EdgeClassInfo(
            name=name,
            valence_in_patch=val,
            full_valence=5,
            count=val_counts[val],
            kappa_twentieths=k20,
        ))
    return classes


# ════════════════════════════════════════════════════════════════════
#  4.  Agda Naming Helpers
# ════════════════════════════════════════════════════════════════════

def region_agda_name(r: RegionInfo) -> str:
    """Agda constructor name for a region: d50r0, d50r1, ..."""
    return f"d50r{r.idx}"


def cells_comment(r: RegionInfo) -> str:
    """Human-readable cell set for Agda comments."""
    return "{" + ",".join(f"c{c}" for c in sorted(r.cells)) + "}"


# ════════════════════════════════════════════════════════════════════
#  5.  Agda Module Generators
# ════════════════════════════════════════════════════════════════════

def gen_spec(regions: list[RegionInfo]) -> str:
    """Generate  Common/Dense50Spec.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Common.Dense50Spec where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  D50Region — Cell-aligned boundary regions of the Dense-50")
    a("--  patch of the {4,3,5} hyperbolic honeycomb")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  The Dense-50 patch is grown by greedy max-connectivity")
    a("--  from the central cube, producing 50 cells with 68 internal")
    a("--  shared faces and 164 boundary faces.  Regions are connected")
    a("--  subsets of boundary cells (up to 5 cells).")
    a("--")
    a("--  The dense growth strategy produces a multiply-connected")
    a("--  bulk, giving non-trivial min-cut values (2–7) that confirm")
    a("--  genuine multi-face RT separating surfaces in the 3D bulk.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("data D50Region : Type₀ where")

    # Group by region size for readability
    sizes: dict[int, list[RegionInfo]] = defaultdict(list)
    for r in regions:
        sizes[len(r.cells)].append(r)

    for size in sorted(sizes.keys()):
        rs = sizes[size]
        names = [region_agda_name(r) for r in rs]
        a(f"  -- size {size}  ({len(rs)} regions)")
        for i in range(0, len(names), 10):
            batch = names[i:i + 10]
            a(f"  {' '.join(batch)} : D50Region")

    a("")
    return "\n".join(L) + "\n"


def gen_cut(regions: list[RegionInfo]) -> str:
    """Generate  Boundary/Dense50Cut.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Boundary.Dense50Cut where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense50Spec")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  D50BdyView — Boundary-side architectural wrapper")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("record D50BdyView : Type₀ where")
    a("  field")
    a("    dummy : ℚ≥0")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  S-cut — Boundary min-cut for the Dense-50 patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  The min-cut separates a cell-aligned boundary region from")
    a("--  its complement in the 3D cell complex.  In 3D the cut is")
    a("--  a set of internal *faces* (a minimal separating surface).")
    a("--")
    a("--  Dense growth produces min-cut values from 2 to 7,")
    a("--  confirming multi-face RT surfaces in the bulk.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("S-cut : D50BdyView → D50Region → ℚ≥0")

    for r in regions:
        rn = region_agda_name(r)
        tc = cells_comment(r)
        a(f"S-cut _ {rn} = {r.min_cut}    -- {tc}")

    a("")
    return "\n".join(L) + "\n"


def gen_chain(regions: list[RegionInfo]) -> str:
    """Generate  Bulk/Dense50Chain.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bulk.Dense50Chain where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense50Spec")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  D50BulkView — Bulk-side architectural wrapper")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("record D50BulkView : Type₀ where")
    a("  field")
    a("    dummy : ℚ≥0")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  L-min — Bulk minimal separating surface for the Dense-50")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  In 3D the bulk minimal chain is a minimal *surface*: a")
    a("--  set of internal cube-faces whose removal disconnects the")
    a("--  region from its complement.  min-cut = min surface area")
    a("--  (in face-count units) is the 3D discrete Ryu–Takayanagi")
    a("--  formula.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("L-min : D50BulkView → D50Region → ℚ≥0")

    for r in regions:
        rn = region_agda_name(r)
        tc = cells_comment(r)
        a(f"L-min _ {rn} = {r.min_cut}    -- {tc}")

    a("")
    return "\n".join(L) + "\n"


def gen_curvature(edge_classes: list[EdgeClassInfo]) -> str:
    """Generate  Bulk/Dense50Curvature.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bulk.Dense50Curvature where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Cubical.Data.Nat  using (ℕ ; zero ; suc ; _+_ ; _·_)")
    a("open import Cubical.Data.Int")
    a("  using (ℤ ; pos ; negsuc)")
    a("  renaming (_+_ to _+ℤ_)")
    a("")
    a("open import Util.Rationals")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  3D Edge Curvature for the Dense-50 {4,3,5} Patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  In 3D, curvature lives on EDGES (not vertices).")
    a("--  At an interior edge e with valence v (cubes meeting):")
    a("--    κ(e) = 2π − v · (π/2)")
    a("--")
    a("--  For {4,3,5}: full valence = 5, so κ = −π/2 (hyperbolic).")
    a("--  In the flat cubic tiling {4,3,4}: valence = 4, κ = 0.")
    a("--")
    a("--  Combinatorial encoding in twentieths (via ℚ₁₀ = ℤ):")
    a("--    κ₂₀(e) = 20 − 5·v")
    a("--      v=5 → κ₂₀ = −5   (hyperbolic)")
    a("--      v=4 → κ₂₀ =  0   (flat)")
    a("--      v=3 → κ₂₀ = +5   (boundary)")
    a("--      v=2 → κ₂₀ = +10  (boundary)")
    a("--")
    a("--  Edge valences are computed with deduplicated dihedral")
    a("--  orbit enumeration (07_honeycomb_3d_multiStrategy.py),")
    a("--  counting distinct cell centers in the patch.")
    a("--")
    a(GENERATED_BANNER)
    a("")

    # ── Edge class datatype ─────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  D50EdgeClass — Edge classes by in-patch valence")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("data D50EdgeClass : Type₀ where")
    names = [ec.name for ec in edge_classes]
    a(f"  {' '.join(names)} : D50EdgeClass")
    a("")

    # ── Count per class ─────────────────────────────────────────────
    a("d50EdgeCount : D50EdgeClass → ℕ")
    for ec in edge_classes:
        a(f"d50EdgeCount {ec.name} = {ec.count}")
    a("")

    # ── Valence per class ───────────────────────────────────────────
    a("d50Valence : D50EdgeClass → ℕ")
    for ec in edge_classes:
        a(f"d50Valence {ec.name} = {ec.valence_in_patch}")
    a("")

    # ── Curvature per class (in twentieths) ─────────────────────────
    a("-- Curvature in twentieths:  κ₂₀ = 20 − 5·valence")
    a("d50Kappa : D50EdgeClass → ℚ₁₀")
    for ec in edge_classes:
        k20 = ec.kappa_twentieths
        if k20 >= 0:
            a(f"d50Kappa {ec.name} = pos {k20}"
              f"    -- val={ec.valence_in_patch}, κ₂₀={k20}")
        else:
            a(f"d50Kappa {ec.name} = negsuc {-k20 - 1}"
              f"    -- val={ec.valence_in_patch}, κ₂₀={k20}")
    a("")

    # ── Total curvature ─────────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  Total edge curvature (class-weighted sum over 12 edges")
    a("--  of the central cube)")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("totalD50Curvature : ℚ₁₀")
    parts = [f"{ec.count} ·₁₀ d50Kappa {ec.name}" for ec in edge_classes]
    a(f"totalD50Curvature = {' +₁₀ '.join(parts)}")
    a("")

    # ── Gauss–Bonnet refl check ─────────────────────────────────────
    total_val = sum(ec.count * ec.kappa_twentieths for ec in edge_classes)
    if total_val >= 0:
        expected_str = f"pos {total_val}"
    else:
        expected_str = f"negsuc {-total_val - 1}"

    a(f"-- Expected value: {expected_str}  (= {total_val} in twentieths)")
    a(f"-- Interpretation: total edge curvature = {total_val}/20 × 2π")
    a(f"--")
    a(f"-- For the Dense-50 patch, all 12 central-cube edges are")
    a(f"-- fully surrounded by 5 cubes (the {{4,3,5}} condition),")
    a(f"-- confirming genuine 3D hyperbolic geometry.")
    a(f"")
    a(f"totalD50Curvature-check : totalD50Curvature ≡ {expected_str}")
    a("totalD50Curvature-check = refl")
    a("")

    # ── Per-class contribution checks ───────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  Per-class contribution regression tests")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    for ec in edge_classes:
        contrib = ec.count * ec.kappa_twentieths
        if contrib >= 0:
            contrib_str = f"pos {contrib}"
        else:
            contrib_str = f"negsuc {-contrib - 1}"
        a(f"-- {ec.count} edges × κ₂₀={ec.kappa_twentieths} = {contrib}")
        a(f"contrib-{ec.name} : {ec.count} ·₁₀ d50Kappa {ec.name}"
          f" ≡ {contrib_str}")
        a(f"contrib-{ec.name} = refl")
        a("")

    return "\n".join(L) + "\n"


def gen_obs(regions: list[RegionInfo]) -> str:
    """Generate  Bridge/Dense50Obs.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bridge.Dense50Obs where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense50Spec")
    a("open import Common.ObsPackage")
    a("open import Boundary.Dense50Cut")
    a("open import Bulk.Dense50Chain")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  Canonical views (dummy instances)")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("d50BdyView : D50BdyView")
    a("d50BdyView .D50BdyView.dummy = 0")
    a("")
    a("d50BulkView : D50BulkView")
    a("d50BulkView .D50BulkView.dummy = 0")
    a("")

    # ── Observable packages ─────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  Observable packages for the Dense-50 {4,3,5} patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("D50Obs∂ : ObsPackage D50Region")
    a("D50Obs∂ .ObsPackage.obs = S-cut d50BdyView")
    a("")
    a("D50ObsBulk : ObsPackage D50Region")
    a("D50ObsBulk .ObsPackage.obs = L-min d50BulkView")
    a("")

    # ── Pointwise agreement ─────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a(f"--  d50-pointwise — All {len(regions)} cases hold by refl")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Both S-cut and L-min return the same ℕ literal for each")
    a("--  region: both encode the true min-cut (min separating")
    a("--  surface area) through the 3D cell complex.")
    a("--")
    a("--  This is the 3D discrete Ryu–Takayanagi correspondence:")
    a("--  boundary entanglement entropy = bulk minimal surface area.")
    a("--")
    a("--  The Dense-50 patch achieves min-cut values from 2 to 7,")
    a("--  confirming genuine multi-face RT surfaces — unlike the")
    a("--  BFS shell patches where min-cut ≈ 1 for all singletons.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("d50-pointwise :")
    a("  (r : D50Region) →")
    a("  S-cut d50BdyView r ≡ L-min d50BulkView r")

    for r in regions:
        rn = region_agda_name(r)
        a(f"d50-pointwise {rn} = refl")

    a("")

    # ── Function path ───────────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  d50-obs-path — Function equality via funExt")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Packages the 139 pointwise refl proofs into a single path")
    a("--  between the boundary and bulk observable functions:")
    a("--    S∂D50 ≡ LBD50")
    a("--")
    a("--  This is the 3D analogue of star-obs-path and")
    a("--  filled-obs-path, now on a densely-connected 3D patch")
    a("--  with non-trivial separating-surface geometry.")
    a("--")
    a("")
    a("S∂D50 : D50Region → ℚ≥0")
    a("S∂D50 = S-cut d50BdyView")
    a("")
    a("LBD50 : D50Region → ℚ≥0")
    a("LBD50 = L-min d50BulkView")
    a("")
    a("d50-obs-path : S∂D50 ≡ LBD50")
    a("d50-obs-path = funExt d50-pointwise")
    a("")

    # ── Package path ────────────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  d50-package-path — Package-level path")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Identifies the boundary and bulk observable packages.")
    a("--  The downstream enriched equivalence (Dense50Equiv.agda)")
    a("--  uses d50-obs-path to construct the Iso / Equiv / ua /")
    a("--  transport pipeline, mirroring Honeycomb3DEquiv.agda and")
    a("--  FilledEquiv.agda.")
    a("--")
    a("")
    a("d50-package-path : D50Obs∂ ≡ D50ObsBulk")
    a("d50-package-path i .ObsPackage.obs = d50-obs-path i")
    a("")

    return "\n".join(L) + "\n"


# ════════════════════════════════════════════════════════════════════
#  6.  File Writing
# ════════════════════════════════════════════════════════════════════

FILE_MAP = [
    ("Common/Dense50Spec.agda",       "spec"),
    ("Boundary/Dense50Cut.agda",      "cut"),
    ("Bulk/Dense50Chain.agda",        "chain"),
    ("Bulk/Dense50Curvature.agda",    "curv"),
    ("Bridge/Dense50Obs.agda",        "obs"),
]


def write_file(path: Path, content: str, dry_run: bool) -> None:
    """Write content to path, creating parent directories as needed."""
    lines = content.count("\n")
    if dry_run:
        print(f"  [dry-run]  {path}  ({lines} lines)")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  ✓  {path}  ({lines} lines)")


# ════════════════════════════════════════════════════════════════════
#  7.  Summary and Diagnostics
# ════════════════════════════════════════════════════════════════════

def print_summary(
    regions: list[RegionInfo],
    edge_classes: list[EdgeClassInfo],
    patch: dict,
) -> None:
    """Print a human-readable summary of the computed data."""
    print(f"\n  ── Patch Topology ──")
    print(f"  Cells:            {len(patch['cells'])}")
    print(f"  Internal faces:   {len(patch['internal_faces'])}")
    print(f"  Boundary faces:   {patch['n_boundary_faces']}")

    density = 2 * len(patch["internal_faces"]) / max(len(patch["cells"]), 1)
    print(f"  Density (2·IntF/Cells): {density:.2f}")

    cut_dist = Counter(r.min_cut for r in regions)
    size_dist = Counter(len(r.cells) for r in regions)

    print(f"\n  ── Region Statistics ({len(regions)} total) ──")
    print(f"  By size:")
    for sz in sorted(size_dist):
        print(f"    {sz}-cell regions:  {size_dist[sz]}")
    print(f"  By min-cut value:")
    for val in sorted(cut_dist):
        print(f"    S = {val}:  {cut_dist[val]} regions")

    min_s = min(r.min_cut for r in regions)
    max_s = max(r.min_cut for r in regions)
    print(f"  Min-cut range:  {min_s} – {max_s}")

    print(f"\n  ── Edge Curvature (12 central-cube edges) ──")
    for ec in edge_classes:
        k = ec.kappa_twentieths
        tag = " ← hyperbolic" if k < 0 else (" (flat)" if k == 0 else "")
        print(f"    Valence {ec.valence_in_patch} (×{ec.count}): "
              f"κ₂₀ = {k}{tag}")

    total_k = sum(ec.count * ec.kappa_twentieths for ec in edge_classes)
    print(f"  Total:  Σ κ₂₀ = {total_k}")

    n_full = sum(ec.count for ec in edge_classes
                 if ec.valence_in_patch >= 5)
    print(f"  Full-valence (≥5) edges: {n_full} of 12")


def print_gate_check(
    regions: list[RegionInfo],
    edge_classes: list[EdgeClassInfo],
    patch: dict,
) -> bool:
    """Print gate check and return True if all pass."""
    n_bdy = patch["n_boundary_faces"]
    n_regs = len(regions)
    n_full = sum(ec.count for ec in edge_classes
                 if ec.valence_in_patch >= 5)
    max_cut = max(r.min_cut for r in regions) if regions else 0

    print(f"\n  ═══════════════════════════════════════════════════════")
    print(f"  GATE CHECK (Dense-50 Feasibility)")
    print(f"  ═══════════════════════════════════════════════════════")

    gate_pass = True
    checks = [
        ("Boundary faces 100–500",
         100 <= n_bdy <= 500, n_bdy),
        ("Region count ≤ 500 (manageable for Agda)",
         n_regs <= 500, n_regs),
        ("≥1 full-valence edge in patch",
         n_full > 0, n_full),
        ("Max min-cut > 1 (genuine holographic depth)",
         max_cut > 1, max_cut),
    ]
    for desc, ok, val in checks:
        status = "✓ PASS" if ok else "✗ FAIL"
        if not ok:
            gate_pass = False
        print(f"    {status}  {desc}  (actual: {val})")

    if gate_pass:
        print(f"\n  ▶  ALL GATES PASS — Dense-50 Agda formalization FEASIBLE")
    else:
        print(f"\n  ▶  GATE(S) BLOCKED")

    return gate_pass


# ════════════════════════════════════════════════════════════════════
#  8.  Main
# ════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Dense-50 Cubical Agda modules (Phase D.1b)")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_SRC_DIR,
                        help="Root source directory "
                             "(default: ../../src relative to script)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Compute and verify without writing files")
    args = parser.parse_args()

    print("╔═══════════════════════════════════════════════════════════╗")
    print("║  Phase D.1b: Dense-50 {4,3,5} — Agda Code Generator     ║")
    print("║  Greedy max-connectivity • Genuine holographic depth     ║")
    print("╚═══════════════════════════════════════════════════════════╝")

    # ── Step 1: Build the Dense-50 patch ────────────────────────────
    print("\n  Building Dense-50 patch via greedy max-connectivity ...")
    data = build_dense50_patch()
    patch = data["patch"]
    print(f"  ✓  {len(patch['cells'])} cells, "
          f"{len(patch['internal_faces'])} internal faces, "
          f"{patch['n_boundary_faces']} boundary faces.")

    # ── Step 2: Compute regions and min-cuts ────────────────────────
    print(f"\n  Enumerating cell-aligned boundary regions "
          f"(max {MAX_REGION_CELLS} cells) ...")
    regions = compute_regions(patch)
    print(f"  ✓  {len(regions)} regions computed.")

    if regions:
        min_s = min(r.min_cut for r in regions)
        max_s = max(r.min_cut for r in regions)
        print(f"  Min-cut range: {min_s} – {max_s}")
    else:
        print("  ✗  No regions found!")
        return

    # ── Step 3: Compute edge curvature classes ──────────────────────
    print("  Computing edge curvature classes ...")
    edge_classes = compute_edge_classes(data, patch)
    print(f"  ✓  {len(edge_classes)} edge class(es).")

    # ── Step 4: Print summary and gate check ────────────────────────
    print_summary(regions, edge_classes, patch)
    gate_ok = print_gate_check(regions, edge_classes, patch)

    if not gate_ok:
        print("\n  WARNING: Gate check failed. Generated modules may not")
        print("  satisfy all formalization criteria.")

    # ── Step 5: Generate and write Agda files ───────────────────────
    src_dir = args.output_dir.resolve()
    print(f"\n  Output directory: {src_dir}")
    if args.dry_run:
        print("  [DRY RUN — no files will be written]\n")
    print()

    generators = {
        "spec":  lambda: gen_spec(regions),
        "cut":   lambda: gen_cut(regions),
        "chain": lambda: gen_chain(regions),
        "curv":  lambda: gen_curvature(edge_classes),
        "obs":   lambda: gen_obs(regions),
    }

    total_lines = 0
    for rel_path, gen_key in FILE_MAP:
        content = generators[gen_key]()
        full_path = src_dir / rel_path
        write_file(full_path, content, args.dry_run)
        total_lines += content.count("\n")

    # ── Step 6: Final report ────────────────────────────────────────
    action = "would generate" if args.dry_run else "generated"
    print(f"\n  ── Summary: {action} {len(FILE_MAP)} files, "
          f"~{total_lines} lines total ──")

    print(f"\n  Module contents:")
    print(f"    D50Region constructors:     {len(regions)}")
    print(f"    S-cut clauses:              {len(regions)}")
    print(f"    L-min clauses:              {len(regions)}")
    print(f"    Edge curvature classes:     {len(edge_classes)}")
    print(f"    Pointwise refl proofs:      {len(regions)}")

    total_k = sum(ec.count * ec.kappa_twentieths for ec in edge_classes)
    if total_k >= 0:
        expected_agda = f"pos {total_k}"
    else:
        expected_agda = f"negsuc {-total_k - 1}"
    print(f"    totalD50Curvature-check:    refl  (= {expected_agda})")

    print(f"""
  Next steps:
    1. Load each generated file in Agda to verify it type-checks.
    2. Implement  src/Bridge/Dense50Equiv.agda  (hand-written) to
       assemble the enriched Iso / Equiv / ua / transport pipeline,
       mirroring Bridge/Honeycomb3DEquiv.agda.
    3. Scale to Dense-100 (300 bdy faces, 717 regions) using the
       orbit reduction strategy per §6.5 of docs/10-frontier.md.
""")


if __name__ == "__main__":
    main()