#!/usr/bin/env python3
"""
09_generate_dense100.py  —  Phase D.1c Dense-100 Agda Code Generator

Generates Cubical Agda modules for the Dense-100 patch of the {4,3,5}
hyperbolic honeycomb, utilizing the orbit reduction strategy from
§6.5 of docs/10-frontier.md to manage the ~717 cell-aligned boundary
regions.

Key innovation over Dense-50 (08_generate_dense50.py):
  The ~717 regions are classified into orbit representatives by their
  min-cut value (~8 orbits).  The observable lookup functions (S-cut,
  L-min) are defined on orbit representatives (~8 clauses), then
  lifted to full regions via a classification function.  This reduces
  the proof obligations from ~717 pointwise refl cases to ~8 orbit-
  representative refl cases, while the 717-clause classification
  function is traversed only during concrete evaluation — never
  during proof normalization.

  This is the first use of the orbit reduction strategy in the
  repository.  It demonstrates that the architecture scales past
  the ~500-constructor threshold where flat enumeration begins to
  stress Agda's parser, by factoring proofs through a small orbit
  type.

Generated modules:
  src/Common/Dense100Spec.agda        — D100Region (~717 ctors),
                                        D100OrbitRep (~8 ctors),
                                        classify100 (~717 clauses)
  src/Boundary/Dense100Cut.agda       — S-cut via orbit reps
  src/Bulk/Dense100Chain.agda         — L-min via orbit reps
  src/Bulk/Dense100Curvature.agda     — edge-class curvature + GB refl
  src/Bridge/Dense100Obs.agda         — orbit-based pointwise agreement

Usage (from repository root):
  python3 sim/prototyping/09_generate_dense100.py
  python3 sim/prototyping/09_generate_dense100.py --dry-run
  python3 sim/prototyping/09_generate_dense100.py --output-dir /path/to/src

Dependencies:  numpy, networkx

Reference:
  docs/10-frontier.md §6    (Direction D — 3D Hyperbolic Honeycombs)
  docs/10-frontier.md §6.5  (Stage 2 — Symmetry Quotient / Orbit Reduction)
  sim/prototyping/07_honeycomb_3d_multiStrategy.py  (Dense growth strategy)
  sim/prototyping/08_generate_dense50.py            (Dense-50 baseline)
"""

from __future__ import annotations

import argparse
import importlib
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import NamedTuple

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

try:
    multi = importlib.import_module("07_honeycomb_3d_multiStrategy")
except ModuleNotFoundError:
    sys.exit(
        "ERROR: Could not import 07_honeycomb_3d_multiStrategy.py.\n"
        "       Run this script from the repository root:\n"
        "         python3 sim/prototyping/09_generate_dense100.py"
    )

try:
    import numpy as np
    import networkx as nx
except ImportError:
    sys.exit("ERROR: numpy and networkx are required.  "
             "pip install numpy networkx")

DEFAULT_SRC_DIR = SCRIPT_DIR.parent.parent / "src"

GENERATED_BANNER = (
    "--  Generated by sim/prototyping/09_generate_dense100.py\n"
    "--  Do not edit by hand.  Regenerate with:\n"
    "--    python3 sim/prototyping/09_generate_dense100.py"
)

MAX_CELLS = 100
MAX_REGION_CELLS = 5


# ════════════════════════════════════════════════════════════════════
#  1.  Build the Dense-100 Patch
# ════════════════════════════════════════════════════════════════════

def build_dense100_patch() -> dict:
    """
    Build the Dense-100 patch of the {4,3,5} honeycomb using the
    greedy max-connectivity growth strategy from 07.

    Returns a dict with the patch data plus Coxeter geometry objects
    needed for edge-class curvature computation.
    """
    G = multi.build_gram_matrix()
    refls = multi.build_reflections(G)
    multi.validate_reflections(G, refls)

    cell_center = multi.find_cell_center(G)
    stab = multi.enumerate_group(refls[:3], expected=48)
    face_crossings = multi.find_face_crossings(refls, stab, G)
    adj_pairs, opp_pairs = multi.classify_face_pairs(face_crossings)

    patch = multi.build_patch_dense(
        face_crossings, cell_center, MAX_CELLS,
        name="Dense-100 ({4,3,5} honeycomb)"
    )

    return {
        "patch": patch,
        "face_crossings": face_crossings,
        "adj_pairs": adj_pairs,
        "opp_pairs": opp_pairs,
        "cell_center": cell_center,
        "gram": G,
    }


# ════════════════════════════════════════════════════════════════════
#  2.  Region Computation
# ════════════════════════════════════════════════════════════════════

class RegionInfo(NamedTuple):
    idx: int
    cells: frozenset[int]
    n_bdy_faces: int
    min_cut: int


def compute_regions(patch: dict) -> list[RegionInfo]:
    """
    Enumerate all cell-aligned boundary regions (connected subsets
    of boundary cells up to MAX_REGION_CELLS cells) and compute
    their min-cut values via max-flow.
    """
    flow_G, bnode_ids, bnode_to_cell = multi.build_flow_graph(patch)

    regions_raw = multi.enumerate_cell_aligned_regions(
        patch, bnode_to_cell, bnode_ids,
        max_region_cells=MAX_REGION_CELLS,
    )

    regions: list[RegionInfo] = []
    for label, idx_set in regions_raw:
        cells_str = label.strip("{}").split(",")
        cells = frozenset(
            int(s.strip().lstrip("c")) for s in cells_str if s.strip()
        )
        s = multi.compute_min_cut(flow_G, bnode_ids, idx_set)
        regions.append(RegionInfo(len(regions), cells, len(idx_set), s))

    return regions


# ════════════════════════════════════════════════════════════════════
#  3.  Orbit Reduction (by min-cut value)
# ════════════════════════════════════════════════════════════════════
#
#  The orbit reduction strategy from §6.5 of docs/10-frontier.md
#  classifies regions into orbits such that:
#    (a) all regions in an orbit have the same S-cut and L-min value
#    (b) proofs only case-split on orbit representatives
#
#  The simplest orbit classification that satisfies (a): group by
#  min-cut value.  This produces one orbit per distinct min-cut value
#  (typically ~8 orbits for the Dense-100 patch, versus ~717 regions).
#
#  This is a refinement-compatible choice: if a finer classification
#  is needed later (e.g. for subadditivity proofs), it can refine
#  these orbits without changing the bridge proofs.

class OrbitRep(NamedTuple):
    """An orbit representative, identified by its min-cut value."""
    name: str       # Agda constructor name: mc1, mc2, ...
    min_cut: int    # The shared min-cut value for all regions in this orbit
    count: int      # Number of regions in this orbit


def compute_orbits(regions: list[RegionInfo]) -> list[OrbitRep]:
    """Group regions by min-cut value into orbit representatives."""
    cut_counts = Counter(r.min_cut for r in regions)
    orbits: list[OrbitRep] = []
    for mc_val in sorted(cut_counts.keys()):
        orbits.append(OrbitRep(
            name=f"mc{mc_val}",
            min_cut=mc_val,
            count=cut_counts[mc_val],
        ))
    return orbits


def orbit_for_region(r: RegionInfo, orbits: list[OrbitRep]) -> OrbitRep:
    """Find the orbit representative for a region."""
    for orb in orbits:
        if orb.min_cut == r.min_cut:
            return orb
    raise ValueError(f"No orbit for min-cut {r.min_cut}")


# ════════════════════════════════════════════════════════════════════
#  4.  Edge Curvature Classes
# ════════════════════════════════════════════════════════════════════

class EdgeClassInfo(NamedTuple):
    name: str
    valence_in_patch: int
    full_valence: int
    count: int
    kappa_twentieths: int


def compute_edge_classes(data: dict, patch: dict) -> list[EdgeClassInfo]:
    """
    Classify the 12 edges of the central cube by their in-patch
    valence using the deduplicated orbit-center approach from 07.
    """
    face_crossings = data["face_crossings"]
    adj_pairs = data["adj_pairs"]
    cell_center = data["cell_center"]
    p = cell_center

    patch_centers = {multi._vec_key(mat @ p)
                     for mat in patch["cells"].values()}

    valences: list[int] = []
    for fi, fj in adj_pairs:
        F_a, F_b = face_crossings[fi], face_crossings[fj]
        dih_elems = multi.enumerate_group([F_a, F_b])
        orbit_centers = {multi._vec_key(g @ p) for g in dih_elems}
        in_patch = len(orbit_centers & patch_centers)
        valences.append(in_patch)

    val_counts = Counter(valences)
    classes: list[EdgeClassInfo] = []
    for val in sorted(val_counts.keys()):
        k20 = 20 - 5 * val
        classes.append(EdgeClassInfo(
            name=f"ev{val}",
            valence_in_patch=val,
            full_valence=5,
            count=val_counts[val],
            kappa_twentieths=k20,
        ))
    return classes


# ════════════════════════════════════════════════════════════════════
#  5.  Agda Naming Helpers
# ════════════════════════════════════════════════════════════════════

def region_agda_name(r: RegionInfo) -> str:
    return f"d100r{r.idx}"


def cells_comment(r: RegionInfo) -> str:
    return "{" + ",".join(f"c{c}" for c in sorted(r.cells)) + "}"


# ════════════════════════════════════════════════════════════════════
#  6.  Agda Module Generators
# ════════════════════════════════════════════════════════════════════

def gen_spec(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
) -> str:
    """Generate  Common/Dense100Spec.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Common.Dense100Spec where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("")

    # ── D100Region ──────────────────────────────────────────────────
    a("-- ══════════════════════════════════════════════════════════════")
    a("--  D100Region — Cell-aligned boundary regions of the Dense-100")
    a("--  patch of the {4,3,5} hyperbolic honeycomb")
    a("-- ══════════════════════════════════════════════════════════════")
    a("--")
    a("--  The Dense-100 patch is grown by greedy max-connectivity")
    a(f"--  from the central cube, producing {MAX_CELLS} cells.")
    a(f"--  Regions are connected subsets of boundary cells (up to")
    a(f"--  {MAX_REGION_CELLS} cells), giving {len(regions)} regions.")
    a("--")
    a("--  This is the first use of the orbit reduction strategy in")
    a("--  the repository: the observable lookups are defined on the")
    a(f"--  small D100OrbitRep type ({len(orbits)} constructors), then")
    a(f"--  lifted to D100Region via classify100.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("data D100Region : Type₀ where")

    sizes: dict[int, list[RegionInfo]] = defaultdict(list)
    for r in regions:
        sizes[len(r.cells)].append(r)

    for size in sorted(sizes.keys()):
        rs = sizes[size]
        names = [region_agda_name(r) for r in rs]
        a(f"  -- size {size}  ({len(rs)} regions)")
        for i in range(0, len(names), 10):
            batch = names[i:i + 10]
            a(f"  {' '.join(batch)} : D100Region")
    a("")

    # ── D100OrbitRep ────────────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  D100OrbitRep — Orbit representatives by min-cut value")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Each orbit representative corresponds to a distinct min-cut")
    a("--  value.  All regions in the same orbit have the same S-cut")
    a("--  and L-min value.  The observable functions are defined on")
    a("--  this small type, then lifted to D100Region via classify100.")
    a("--")
    a("--  Orbit decomposition:")
    for orb in orbits:
        a(f"--    {orb.name}  (S = {orb.min_cut}):  {orb.count} regions")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("data D100OrbitRep : Type₀ where")
    orb_names = [orb.name for orb in orbits]
    a(f"  {' '.join(orb_names)} : D100OrbitRep")
    a("")

    # ── classify100 ─────────────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  classify100 — Map each region to its orbit representative")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a(f"--  {len(regions)}-clause pattern match.  Each clause is")
    a("--  trivial (maps a constructor to a constructor).  This")
    a("--  function is traversed only during concrete evaluation,")
    a("--  never during proof normalization — the proofs operate on")
    a("--  D100OrbitRep and are lifted via this classification.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("classify100 : D100Region → D100OrbitRep")

    for r in regions:
        rn = region_agda_name(r)
        orb = orbit_for_region(r, orbits)
        a(f"classify100 {rn} = {orb.name}")

    a("")
    return "\n".join(L) + "\n"


def gen_cut(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
) -> str:
    """Generate  Boundary/Dense100Cut.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Boundary.Dense100Cut where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense100Spec")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  D100BdyView — Boundary-side architectural wrapper")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("record D100BdyView : Type₀ where")
    a("  field")
    a("    dummy : ℚ≥0")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  S-cut-rep — Boundary min-cut on orbit representatives")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a(f"--  {len(orbits)}-clause lookup on the small orbit type.")
    a("--  Each orbit representative maps to its min-cut value.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("S-cut-rep : D100OrbitRep → ℚ≥0")
    for orb in orbits:
        a(f"S-cut-rep {orb.name} = {orb.min_cut}")
    a("")

    a("-- ═══════════════════════════════════════════════════════════")
    a("--  S-cut — Boundary min-cut for the Dense-100 patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Defined as  S-cut-rep ∘ classify100 .  Agda normalizes")
    a("--  this by first reducing classify100 r (one step on the")
    a(f"--  {len(regions)}-clause function) then S-cut-rep on the")
    a(f"--  result (one step on the {len(orbits)}-clause function).")
    a("--")
    a("--  This is the orbit reduction architecture from §6.5 of")
    a("--  docs/10-frontier.md: the large case analysis is in the")
    a("--  classification function, and the observable lookup is")
    a("--  on the small orbit type.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("S-cut : D100BdyView → D100Region → ℚ≥0")
    a("S-cut _ r = S-cut-rep (classify100 r)")
    a("")

    return "\n".join(L) + "\n"


def gen_chain(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
) -> str:
    """Generate  Bulk/Dense100Chain.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bulk.Dense100Chain where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense100Spec")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  D100BulkView — Bulk-side architectural wrapper")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("record D100BulkView : Type₀ where")
    a("  field")
    a("    dummy : ℚ≥0")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  L-min-rep — Bulk minimal surface on orbit representatives")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a(f"--  {len(orbits)}-clause lookup on the small orbit type.")
    a("--  Each orbit representative maps to the same min-cut value")
    a("--  as S-cut-rep — this is the 3D discrete RT correspondence.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("L-min-rep : D100OrbitRep → ℚ≥0")
    for orb in orbits:
        a(f"L-min-rep {orb.name} = {orb.min_cut}")
    a("")

    a("-- ═══════════════════════════════════════════════════════════")
    a("--  L-min — Bulk minimal separating surface for Dense-100")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Defined as  L-min-rep ∘ classify100 , mirroring S-cut.")
    a("--  Both S-cut and L-min are definitionally distinct (defined")
    a("--  in different modules with different rep functions) but")
    a("--  propositionally equal because S-cut-rep and L-min-rep")
    a(f"--  agree on all {len(orbits)} orbit representatives by refl.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("L-min : D100BulkView → D100Region → ℚ≥0")
    a("L-min _ r = L-min-rep (classify100 r)")
    a("")

    return "\n".join(L) + "\n"


def gen_curvature(edge_classes: list[EdgeClassInfo]) -> str:
    """Generate  Bulk/Dense100Curvature.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bulk.Dense100Curvature where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Cubical.Data.Nat  using (ℕ ; zero ; suc ; _+_ ; _·_)")
    a("open import Cubical.Data.Int")
    a("  using (ℤ ; pos ; negsuc)")
    a("  renaming (_+_ to _+ℤ_)")
    a("")
    a("open import Util.Rationals")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  3D Edge Curvature for the Dense-100 {4,3,5} Patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  In 3D, curvature lives on EDGES (not vertices).")
    a("--  At an interior edge e with valence v (cubes meeting):")
    a("--    κ(e) = 2π − v · (π/2)")
    a("--")
    a("--  For {4,3,5}: full valence = 5, so κ = −π/2 (hyperbolic).")
    a("--")
    a("--  Combinatorial encoding in twentieths (via ℚ₁₀ = ℤ):")
    a("--    κ₂₀(e) = 20 − 5·v")
    a("--      v=5 → κ₂₀ = −5   (hyperbolic)")
    a("--      v=4 → κ₂₀ =  0   (flat)")
    a("--      v=3 → κ₂₀ = +5   (boundary)")
    a("--      v=2 → κ₂₀ = +10  (boundary)")
    a("--")
    a(GENERATED_BANNER)
    a("")

    # Edge class datatype
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  D100EdgeClass — Edge classes by in-patch valence")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("data D100EdgeClass : Type₀ where")
    names = [ec.name for ec in edge_classes]
    a(f"  {' '.join(names)} : D100EdgeClass")
    a("")

    a("d100EdgeCount : D100EdgeClass → ℕ")
    for ec in edge_classes:
        a(f"d100EdgeCount {ec.name} = {ec.count}")
    a("")

    a("d100Valence : D100EdgeClass → ℕ")
    for ec in edge_classes:
        a(f"d100Valence {ec.name} = {ec.valence_in_patch}")
    a("")

    a("-- Curvature in twentieths:  κ₂₀ = 20 − 5·valence")
    a("d100Kappa : D100EdgeClass → ℚ₁₀")
    for ec in edge_classes:
        k20 = ec.kappa_twentieths
        if k20 >= 0:
            a(f"d100Kappa {ec.name} = pos {k20}"
              f"    -- val={ec.valence_in_patch}, κ₂₀={k20}")
        else:
            a(f"d100Kappa {ec.name} = negsuc {-k20 - 1}"
              f"    -- val={ec.valence_in_patch}, κ₂₀={k20}")
    a("")

    # Total curvature
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  Total edge curvature (class-weighted sum over 12 edges")
    a("--  of the central cube)")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("totalD100Curvature : ℚ₁₀")
    parts = [f"{ec.count} ·₁₀ d100Kappa {ec.name}" for ec in edge_classes]
    a(f"totalD100Curvature = {' +₁₀ '.join(parts)}")
    a("")

    total_val = sum(ec.count * ec.kappa_twentieths for ec in edge_classes)
    if total_val >= 0:
        expected_str = f"pos {total_val}"
    else:
        expected_str = f"negsuc {-total_val - 1}"

    a(f"-- Expected value: {expected_str}  (= {total_val} in twentieths)")
    a(f"")
    a(f"totalD100Curvature-check : totalD100Curvature ≡ {expected_str}")
    a("totalD100Curvature-check = refl")
    a("")

    # Per-class contributions
    a("-- ═════════════════════════════════════════════")
    a("--  Per-class contribution regression tests")
    a("-- ═════════════════════════════════════════════")
    a("")
    for ec in edge_classes:
        contrib = ec.count * ec.kappa_twentieths
        if contrib >= 0:
            contrib_str = f"pos {contrib}"
        else:
            contrib_str = f"negsuc {-contrib - 1}"
        a(f"-- {ec.count} edges × κ₂₀={ec.kappa_twentieths} = {contrib}")
        a(f"contrib-{ec.name} : {ec.count} ·₁₀ d100Kappa {ec.name}"
          f" ≡ {contrib_str}")
        a(f"contrib-{ec.name} = refl")
        a("")

    return "\n".join(L) + "\n"


def gen_obs(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
) -> str:
    """Generate  Bridge/Dense100Obs.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bridge.Dense100Obs where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense100Spec")
    a("open import Common.ObsPackage")
    a("open import Boundary.Dense100Cut")
    a("open import Bulk.Dense100Chain")
    a("")

    # ── Canonical views ─────────────────────────────────────────────
    a("-- ═════════════════════════════════════")
    a("--  Canonical views (dummy instances)")
    a("-- ═════════════════════════════════════")
    a("")
    a("d100BdyView : D100BdyView")
    a("d100BdyView .D100BdyView.dummy = 0")
    a("")
    a("d100BulkView : D100BulkView")
    a("d100BulkView .D100BulkView.dummy = 0")
    a("")

    # ── Observable packages ─────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  Observable packages for the Dense-100 {4,3,5} patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("D100Obs∂ : ObsPackage D100Region")
    a("D100Obs∂ .ObsPackage.obs = S-cut d100BdyView")
    a("")
    a("D100ObsBulk : ObsPackage D100Region")
    a("D100ObsBulk .ObsPackage.obs = L-min d100BulkView")
    a("")

    # ── Orbit-level pointwise agreement ─────────────────────────────
    a("-- ══════════════════════════════════════════════════════════════")
    a(f"--  d100-pointwise-rep — All {len(orbits)} orbit cases by refl")
    a("-- ══════════════════════════════════════════════════════════════")
    a("--")
    a("--  The core proof: S-cut-rep and L-min-rep agree on every")
    a("--  orbit representative.  Both return the same ℕ literal")
    a("--  for each orbit (the shared min-cut value), so each case")
    a("--  holds by refl.")
    a("--")
    a("--  This replaces the 717-case pointwise proof from the flat")
    a("--  enumeration approach (Dense-50 style) with a compact")
    a(f"--  {len(orbits)}-case proof on orbit representatives.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("d100-pointwise-rep :")
    a("  (o : D100OrbitRep) → S-cut-rep o ≡ L-min-rep o")

    for orb in orbits:
        a(f"d100-pointwise-rep {orb.name} = refl")

    a("")

    # ── Full pointwise agreement (via orbit lifting) ────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a(f"--  d100-pointwise — Lifted to all {len(regions)} regions")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  The pointwise agreement for the full D100Region type is a")
    a("--  SINGLE-LINE proof that composes the orbit-level proof with")
    a("--  the classification function:")
    a("--")
    a("--    d100-pointwise r = d100-pointwise-rep (classify100 r)")
    a("--")
    a("--  This works because:")
    a("--    S-cut _ r  = S-cut-rep (classify100 r)    (definitional)")
    a("--    L-min _ r  = L-min-rep (classify100 r)    (definitional)")
    a("--")
    a("--  So the type of  d100-pointwise-rep (classify100 r)  is:")
    a("--    S-cut-rep (classify100 r) ≡ L-min-rep (classify100 r)")
    a("--  which IS  S-cut _ r ≡ L-min _ r  by the definitional")
    a("--  equalities above.")
    a("--")
    a("--  For a concrete constructor r, Agda normalizes classify100 r")
    a(f"--  (one step on the {len(regions)}-clause function), then")
    a(f"--  d100-pointwise-rep on the result (one step on the")
    a(f"--  {len(orbits)}-clause function, returning refl).  Fast.")
    a("--")
    a("--  This is the orbit reduction strategy from §6.5 of")
    a("--  docs/10-frontier.md in action: the proof term is tiny,")
    a("--  the classification function does the case analysis.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("d100-pointwise :")
    a("  (r : D100Region) →")
    a("  S-cut d100BdyView r ≡ L-min d100BulkView r")
    a("d100-pointwise r = d100-pointwise-rep (classify100 r)")
    a("")

    # ── Function path ───────────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════")
    a("--  d100-obs-path — Function equality via funExt")
    a("-- ═══════════════════════════════════════════════════")
    a("")
    a("S∂D100 : D100Region → ℚ≥0")
    a("S∂D100 = S-cut d100BdyView")
    a("")
    a("LBD100 : D100Region → ℚ≥0")
    a("LBD100 = L-min d100BulkView")
    a("")
    a("d100-obs-path : S∂D100 ≡ LBD100")
    a("d100-obs-path = funExt d100-pointwise")
    a("")

    # ── Package path ────────────────────────────────────────────────
    a("-- ═════════════════════════════════════════════")
    a("--  d100-package-path — Package-level path")
    a("-- ═════════════════════════════════════════════")
    a("")
    a("d100-package-path : D100Obs∂ ≡ D100ObsBulk")
    a("d100-package-path i .ObsPackage.obs = d100-obs-path i")
    a("")

    return "\n".join(L) + "\n"


# ════════════════════════════════════════════════════════════════════
#  7.  File Writing
# ════════════════════════════════════════════════════════════════════

FILE_MAP = [
    ("Common/Dense100Spec.agda",       "spec"),
    ("Boundary/Dense100Cut.agda",      "cut"),
    ("Bulk/Dense100Chain.agda",        "chain"),
    ("Bulk/Dense100Curvature.agda",    "curv"),
    ("Bridge/Dense100Obs.agda",        "obs"),
]


def write_file(path: Path, content: str, dry_run: bool) -> None:
    lines = content.count("\n")
    if dry_run:
        print(f"  [dry-run]  {path}  ({lines} lines)")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  ✓  {path}  ({lines} lines)")


# ════════════════════════════════════════════════════════════════════
#  8.  Summary and Diagnostics
# ════════════════════════════════════════════════════════════════════

def print_summary(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
    edge_classes: list[EdgeClassInfo],
    patch: dict,
) -> None:
    print(f"\n  ── Patch Topology ──")
    print(f"  Cells:            {len(patch['cells'])}")
    print(f"  Internal faces:   {len(patch['internal_faces'])}")
    print(f"  Boundary faces:   {patch['n_boundary_faces']}")

    density = 2 * len(patch["internal_faces"]) / max(len(patch["cells"]), 1)
    print(f"  Density (2·IntF/Cells): {density:.2f}")

    cut_dist = Counter(r.min_cut for r in regions)
    size_dist = Counter(len(r.cells) for r in regions)

    print(f"\n  ── Region Statistics ({len(regions)} total) ──")
    print(f"  By size:")
    for sz in sorted(size_dist):
        print(f"    {sz}-cell regions:  {size_dist[sz]}")
    print(f"  By min-cut value:")
    for val in sorted(cut_dist):
        print(f"    S = {val}:  {cut_dist[val]} regions")

    min_s = min(r.min_cut for r in regions)
    max_s = max(r.min_cut for r in regions)
    print(f"  Min-cut range:  {min_s} – {max_s}")

    print(f"\n  ── Orbit Reduction ──")
    print(f"  Distinct min-cut values:  {len(orbits)}")
    print(f"  Orbit decomposition:")
    for orb in orbits:
        print(f"    {orb.name}  (S = {orb.min_cut}):  {orb.count} regions")
    reduction = len(regions) / max(len(orbits), 1)
    print(f"  Reduction factor:  {len(regions)} → {len(orbits)}"
          f"  ({reduction:.0f}× fewer proof cases)")

    print(f"\n  ── Comparison with Dense-50 ──")
    print(f"    Dense-50:   139 regions, 139 flat refl proofs")
    print(f"    Dense-100:  {len(regions)} regions, "
          f"{len(orbits)} orbit refl proofs + 1-line lifting")
    print(f"    Architecture: flat enumeration → orbit reduction")

    print(f"\n  ── Edge Curvature (12 central-cube edges) ──")
    for ec in edge_classes:
        k = ec.kappa_twentieths
        tag = " ← hyperbolic" if k < 0 else (" (flat)" if k == 0 else "")
        print(f"    Valence {ec.valence_in_patch} (×{ec.count}): "
              f"κ₂₀ = {k}{tag}")

    total_k = sum(ec.count * ec.kappa_twentieths for ec in edge_classes)
    print(f"  Total:  Σ κ₂₀ = {total_k}")

    n_full = sum(ec.count for ec in edge_classes
                 if ec.valence_in_patch >= 5)
    print(f"  Full-valence (≥5) edges: {n_full} of 12")


def print_gate_check(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
    edge_classes: list[EdgeClassInfo],
    patch: dict,
) -> bool:
    n_bdy = patch["n_boundary_faces"]
    n_regs = len(regions)
    n_orbs = len(orbits)
    n_full = sum(ec.count for ec in edge_classes
                 if ec.valence_in_patch >= 5)
    max_cut = max(r.min_cut for r in regions) if regions else 0

    print(f"\n  ═══════════════════════════════════════════════════════")
    print(f"  GATE CHECK (Dense-100 Feasibility)")
    print(f"  ═══════════════════════════════════════════════════════")

    gate_pass = True
    checks = [
        ("Boundary faces 100–500",
         100 <= n_bdy <= 500, n_bdy),
        ("Region count (raw ≤ 1000, orbit ≤ 200)",
         n_regs <= 1000 and n_orbs <= 200, f"{n_regs} raw / {n_orbs} orbits"),
        ("≥1 full-valence edge in patch",
         n_full > 0, n_full),
        ("Max min-cut > 1 (genuine holographic depth)",
         max_cut > 1, max_cut),
        ("Orbit reduction effective (ratio > 5×)",
         n_regs / max(n_orbs, 1) > 5, f"{n_regs/max(n_orbs,1):.0f}×"),
    ]
    for desc, ok, val in checks:
        status = "✓ PASS" if ok else "✗ FAIL"
        if not ok:
            gate_pass = False
        print(f"    {status}  {desc}  (actual: {val})")

    if gate_pass:
        print(f"\n  ▶  ALL GATES PASS — Dense-100 with orbit reduction FEASIBLE")
    else:
        print(f"\n  ▶  GATE(S) BLOCKED")

    return gate_pass


# ════════════════════════════════════════════════════════════════════
#  9.  Main
# ════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Dense-100 Cubical Agda modules "
                    "with orbit reduction (Phase D.1c)")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_SRC_DIR,
                        help="Root source directory "
                             "(default: ../../src relative to script)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Compute and verify without writing files")
    args = parser.parse_args()

    print("╔═══════════════════════════════════════════════════════════╗")
    print("║  Phase D.1c: Dense-100 {4,3,5} — Orbit-Reduced Agda Gen   ║")
    print("║  Greedy max-connectivity • Orbit reduction strategy       ║")
    print("╚═══════════════════════════════════════════════════════════╝")

    # ── Step 1: Build the Dense-100 patch ───────────────────────────
    print("\n  Building Dense-100 patch via greedy max-connectivity ...")
    data = build_dense100_patch()
    patch = data["patch"]
    print(f"  ✓  {len(patch['cells'])} cells, "
          f"{len(patch['internal_faces'])} internal faces, "
          f"{patch['n_boundary_faces']} boundary faces.")

    # ── Step 2: Compute regions and min-cuts ────────────────────────
    print(f"\n  Enumerating cell-aligned boundary regions "
          f"(max {MAX_REGION_CELLS} cells) ...")
    regions = compute_regions(patch)
    print(f"  ✓  {len(regions)} regions computed.")

    if regions:
        min_s = min(r.min_cut for r in regions)
        max_s = max(r.min_cut for r in regions)
        print(f"  Min-cut range: {min_s} – {max_s}")
    else:
        print("  ✗  No regions found!")
        return

    # ── Step 3: Compute orbit reduction ─────────────────────────────
    print("  Computing orbit reduction by min-cut value ...")
    orbits = compute_orbits(regions)
    print(f"  ✓  {len(orbits)} orbit representatives "
          f"(from {len(regions)} regions, "
          f"{len(regions)/len(orbits):.0f}× reduction)")

    # ── Step 4: Compute edge curvature classes ──────────────────────
    print("  Computing edge curvature classes ...")
    edge_classes = compute_edge_classes(data, patch)
    print(f"  ✓  {len(edge_classes)} edge class(es).")

    # ── Step 5: Print summary and gate check ────────────────────────
    print_summary(regions, orbits, edge_classes, patch)
    gate_ok = print_gate_check(regions, orbits, edge_classes, patch)

    if not gate_ok:
        print("\n  WARNING: Gate check failed. Generated modules may not")
        print("  satisfy all formalization criteria.")

    # ── Step 6: Generate and write Agda files ───────────────────────
    src_dir = args.output_dir.resolve()
    print(f"\n  Output directory: {src_dir}")
    if args.dry_run:
        print("  [DRY RUN — no files will be written]\n")
    print()

    generators = {
        "spec":  lambda: gen_spec(regions, orbits),
        "cut":   lambda: gen_cut(regions, orbits),
        "chain": lambda: gen_chain(regions, orbits),
        "curv":  lambda: gen_curvature(edge_classes),
        "obs":   lambda: gen_obs(regions, orbits),
    }

    total_lines = 0
    for rel_path, gen_key in FILE_MAP:
        content = generators[gen_key]()
        full_path = src_dir / rel_path
        write_file(full_path, content, args.dry_run)
        total_lines += content.count("\n")

    # ── Step 7: Final report ────────────────────────────────────────
    action = "would generate" if args.dry_run else "generated"
    print(f"\n  ── Summary: {action} {len(FILE_MAP)} files, "
          f"~{total_lines} lines total ──")

    print(f"\n  Module contents:")
    print(f"    D100Region constructors:        {len(regions)}")
    print(f"    D100OrbitRep constructors:       {len(orbits)}")
    print(f"    classify100 clauses:             {len(regions)}")
    print(f"    S-cut-rep / L-min-rep clauses:   {len(orbits)} each")
    print(f"    Pointwise-rep refl proofs:       {len(orbits)}")
    print(f"    Pointwise lifting:               1 line (!)")
    print(f"    Edge curvature classes:          {len(edge_classes)}")

    total_k = sum(ec.count * ec.kappa_twentieths for ec in edge_classes)
    if total_k >= 0:
        expected_agda = f"pos {total_k}"
    else:
        expected_agda = f"negsuc {-total_k - 1}"
    print(f"    totalD100Curvature-check:        refl  (= {expected_agda})")

    print(f"""
  Key architectural innovation:
    Dense-50 (08):   139 flat refl proofs  (one per region)
    Dense-100 (09):  {len(orbits)} orbit refl proofs + 1-line lifting
                     ({len(regions)} regions → {len(orbits)} orbits)

  The orbit reduction strategy from §6.5 of docs/10-frontier.md is
  now validated: the classification function absorbs the large case
  analysis, while proofs operate on the compact orbit type.  This
  pattern scales to arbitrary patch sizes — adding more cells only
  grows the classify function, not the proof obligations.

  Next steps:
    1. Load generated files in Agda to verify they type-check.
    2. Write  Bridge/Dense100Equiv.agda  (hand-written) to assemble
       the enriched Iso / Equiv / ua / transport pipeline.
    3. Retroactively apply orbit reduction to the 2D 11-tile patch
       (5-fold symmetry → 72 orbit representatives instead of 360
       subadditivity cases, per §6.11 of docs/10-frontier.md).
""")


if __name__ == "__main__":
    main()