#!/usr/bin/env python3
"""
11_generate_area_law.py  —  Area-Law Oracle + Agda Emitter

Generates  src/Boundary/Dense100AreaLaw.agda  containing:

  1. A function  regionArea : D100Region → ℚ≥0  returning the
     boundary surface area (face-count) of each cell-aligned region.

  2. An  abstract  proof:
       area-law : (r : D100Region) → S-cut d100BdyView r ≤ℚ regionArea r
     where each case is  (k , refl)  with k = area − mincut.

The boundary surface area of a cell-aligned region A of k cells is:

    area(A) = 6k − 2 · |internal faces within A|

Each cube has 6 faces.  Each shared face between two A-cells is
counted by both cells (contributing 2 to the 6k total) but is
internal to A and does not cross the boundary.  Subtracting 2 per
such face yields the number of faces that EXIT A — connecting to
non-A cells or to the exterior of the patch.

The area law  S(A) ≤ area(A)  is a graph-theoretic tautology:
the max-flow is bounded by the capacity of any cut, and the
trivial cut (severing all exiting faces of A) provides the
upper bound.

This follows the Approach A+C strategy from §3.6 of
docs/10-frontier.md:
  • Approach C:  Python oracle computes areas and slack witnesses
  • Approach A:  the Agda proof is wrapped in  abstract  so
    downstream modules never re-unfold the 717 cases

Reference:
  docs/10-frontier.md §8.5   (the discrete area law theorem)
  docs/10-frontier.md §8.7   (Tier 2 implementation plan)
  docs/10-frontier.md §8.11  (exit criterion)
  sim/prototyping/09_generate_dense100.py  (Dense-100 infrastructure)

Usage (from repository root):
  python3 sim/prototyping/11_generate_area_law.py
  python3 sim/prototyping/11_generate_area_law.py --dry-run

Dependencies:  numpy, networkx
"""

from __future__ import annotations

import argparse
import importlib
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import NamedTuple

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

try:
    multi = importlib.import_module("07_honeycomb_3d_multiStrategy")
except ModuleNotFoundError:
    sys.exit(
        "ERROR: Could not import 07_honeycomb_3d_multiStrategy.py.\n"
        "       Run this script from the repository root:\n"
        "         python3 sim/prototyping/11_generate_area_law.py"
    )

try:
    import numpy as np
    import networkx as nx
except ImportError:
    sys.exit("ERROR: numpy and networkx are required.  "
             "pip install numpy networkx")

DEFAULT_SRC_DIR = SCRIPT_DIR.parent.parent / "src"

GENERATED_BANNER = (
    "--  Generated by sim/prototyping/11_generate_area_law.py\n"
    "--  Do not edit by hand.  Regenerate with:\n"
    "--    python3 sim/prototyping/11_generate_area_law.py"
)

MAX_CELLS = 100
MAX_REGION_CELLS = 5


# ════════════════════════════════════════════════════════════════════
#  1.  Build the Dense-100 Patch (reusing 07 infrastructure)
# ════════════════════════════════════════════════════════════════════

def build_dense100_patch() -> dict:
    """
    Build the Dense-100 patch of the {4,3,5} honeycomb using the
    greedy max-connectivity growth strategy from 07.

    Returns a dict with the patch data plus Coxeter geometry objects.
    """
    G = multi.build_gram_matrix()
    refls = multi.build_reflections(G)
    multi.validate_reflections(G, refls)

    cell_center = multi.find_cell_center(G)
    stab = multi.enumerate_group(refls[:3], expected=48)
    face_crossings = multi.find_face_crossings(refls, stab, G)
    adj_pairs, opp_pairs = multi.classify_face_pairs(face_crossings)

    patch = multi.build_patch_dense(
        face_crossings, cell_center, MAX_CELLS,
        name="Dense-100 ({4,3,5} honeycomb)"
    )

    return {
        "patch": patch,
        "face_crossings": face_crossings,
        "adj_pairs": adj_pairs,
        "cell_center": cell_center,
    }


# ════════════════════════════════════════════════════════════════════
#  2.  Region Computation (with boundary area)
# ════════════════════════════════════════════════════════════════════

class RegionAreaInfo(NamedTuple):
    idx: int
    cells: frozenset[int]
    n_bdy_faces: int         # number of boundary pseudo-nodes in region
    min_cut: int             # min-cut value (from max-flow)
    boundary_area: int       # 6|A| − 2·|internal faces within A|
    slack: int               # boundary_area − min_cut  (must be ≥ 0)


def compute_boundary_area(
    cells: frozenset[int],
    internal_faces: list[tuple[int, int]],
) -> int:
    """
    Boundary surface area of a cell-aligned region A.

        area(A) = 6·|A| − 2·|{shared faces between two cells in A}|

    This counts the total number of faces of A-cells that EXIT A
    (connecting to non-A cells or to the exterior of the patch).

    Each cube has 6 faces.  Each internal face shared between two
    A-cells is counted by both cells (contributing 2 to the 6|A|
    total) but does not exit A — so we subtract 2 per shared face.
    """
    n_cells = len(cells)
    internal_within = sum(
        1 for c1, c2 in internal_faces
        if c1 in cells and c2 in cells
    )
    return 6 * n_cells - 2 * internal_within


def compute_regions_with_area(patch: dict) -> list[RegionAreaInfo]:
    """
    Enumerate all cell-aligned boundary regions (connected subsets
    of boundary cells up to MAX_REGION_CELLS cells), compute their
    min-cut values and boundary surface areas.
    """
    flow_G, bnode_ids, bnode_to_cell = multi.build_flow_graph(patch)
    internal_faces = patch["internal_faces"]

    # Use 07's region enumeration
    regions_raw = multi.enumerate_cell_aligned_regions(
        patch, bnode_to_cell, bnode_ids,
        max_region_cells=MAX_REGION_CELLS,
    )

    regions: list[RegionAreaInfo] = []
    for label, idx_set in regions_raw:
        # Parse cell IDs from label "{c0,c1,...}"
        cells_str = label.strip("{}").split(",")
        cells = frozenset(
            int(s.strip().lstrip("c")) for s in cells_str if s.strip()
        )

        # Min-cut via max-flow
        s = multi.compute_min_cut(flow_G, bnode_ids, idx_set)

        # Boundary surface area
        area = compute_boundary_area(cells, internal_faces)

        # Slack (must be ≥ 0 for the area law to hold)
        slack = area - s

        regions.append(RegionAreaInfo(
            idx=len(regions),
            cells=cells,
            n_bdy_faces=len(idx_set),
            min_cut=s,
            boundary_area=area,
            slack=slack,
        ))

    return regions


# ════════════════════════════════════════════════════════════════════
#  3.  Agda Naming Helpers
# ════════════════════════════════════════════════════════════════════

def region_agda_name(r: RegionAreaInfo) -> str:
    """Agda constructor name for a region: d100r0, d100r1, ..."""
    return f"d100r{r.idx}"


def cells_comment(r: RegionAreaInfo) -> str:
    """Human-readable cell set for Agda comments."""
    return "{" + ",".join(f"c{c}" for c in sorted(r.cells)) + "}"


# ════════════════════════════════════════════════════════════════════
#  4.  Agda Module Generator
# ════════════════════════════════════════════════════════════════════

def generate_area_law_module(regions: list[RegionAreaInfo]) -> str:
    """Generate  Boundary/Dense100AreaLaw.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Boundary.Dense100AreaLaw where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Cubical.Data.Nat using (ℕ ; _+_)")
    a("open import Util.Scalars")
    a("open import Common.Dense100Spec")
    a("open import Boundary.Dense100Cut")
    a("open import Bridge.Dense100Obs using (d100BdyView)")
    a("")

    # ── regionArea ──────────────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  regionArea — Boundary surface area of each region")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  For a cell-aligned boundary region A of k cells:")
    a("--")
    a("--    area(A) = 6k − 2 · |internal faces within A|")
    a("--")
    a("--  Each cube has 6 faces.  Each shared face between two")
    a("--  A-cells is internal to A and does not exit; we subtract 2")
    a("--  for each such face (once per cell sharing it).  The result")
    a("--  is the total count of faces connecting A to non-A entities")
    a("--  (neighboring cells outside A, or the patch exterior).")
    a("--")
    a("--  This is the discrete analogue of the Bekenstein–Hawking")
    a("--  area:  S ≤ A / 4G  becomes  S_cut(A) ≤ area(A)  with")
    a("--  the factor 1/4G absorbed into bond dimension and geometry.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("regionArea : D100Region → ℚ≥0")

    for r in regions:
        rn = region_agda_name(r)
        tc = cells_comment(r)
        n = len(r.cells)
        a(f"regionArea {rn} = {r.boundary_area}"
          f"    -- {tc}  ({n} cells, area=6·{n}−2·"
          f"{(6*n - r.boundary_area)//2}={r.boundary_area})")

    a("")

    # ── area-law (abstract) ─────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a(f"--  area-law — S_cut(A) ≤ area(A)  ({len(regions)} cases)")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  The discrete isoperimetric inequality: the min-cut entropy")
    a("--  of any cell-aligned boundary region is bounded by its")
    a("--  boundary surface area within the cell complex.")
    a("--")
    a("--  This is a graph-theoretic tautology: the max-flow is")
    a("--  bounded by the capacity of any cut, and the trivial cut")
    a("--  (severing all faces on the boundary of A within the cell")
    a("--  complex) provides the upper bound.")
    a("--")
    a("--  Wrapped in  abstract  so that downstream modules never")
    a("--  re-unfold the 717-case proof.  Since  _≤ℚ_  is")
    a("--  propositional (by isProp≤ℚ from")
    a("--  Bridge/FullEnrichedStarObs.agda), the abstract barrier")
    a("--  does not damage any Univalence bridge.")
    a("--")
    a("--  Each witness  (k , refl)  type-checks because")
    a("--  k + S-cut d100BdyView r  reduces judgmentally to")
    a("--  regionArea r  via ℕ addition on closed numerals.")
    a("--")
    a("--  Reference:")
    a("--    docs/10-frontier.md §8.5  (the theorem statement)")
    a("--    docs/10-frontier.md §8.7  (Tier 2 implementation)")
    a("--    Approach A (abstract) + C (external oracle)")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("abstract")
    a("  area-law : (r : D100Region)"
      " → S-cut d100BdyView r ≤ℚ regionArea r")

    # Group by (min_cut, slack) for readability
    prev_key = (-1, -1)
    for r in regions:
        key = (r.min_cut, r.slack)
        if key != prev_key:
            a(f"  -- S={r.min_cut}, area={r.boundary_area},"
              f" slack={r.slack}:"
              f"  {r.slack} + {r.min_cut} = {r.boundary_area}")
            prev_key = key
        rn = region_agda_name(r)
        a(f"  area-law {rn} = {r.slack} , refl")

    a("")
    return "\n".join(L) + "\n"


# ════════════════════════════════════════════════════════════════════
#  5.  Verification and Summary
# ════════════════════════════════════════════════════════════════════

def verify_area_law(regions: list[RegionAreaInfo]) -> bool:
    """Verify that the area law holds for every region."""
    violations = []
    for r in regions:
        if r.slack < 0:
            violations.append(
                f"  VIOLATION at {region_agda_name(r)}: "
                f"S={r.min_cut} > area={r.boundary_area} "
                f"(slack={r.slack})"
            )
    if violations:
        for v in violations:
            print(v)
        return False
    return True


def print_summary(regions: list[RegionAreaInfo]) -> None:
    """Print a human-readable summary of the area-law data."""

    # Min-cut distribution
    cut_dist = Counter(r.min_cut for r in regions)
    area_dist = Counter(r.boundary_area for r in regions)
    slack_dist = Counter(r.slack for r in regions)
    size_dist = Counter(len(r.cells) for r in regions)

    print(f"\n  ── Region Statistics ({len(regions)} regions) ──")

    print(f"\n  By region size (number of cells):")
    for sz in sorted(size_dist):
        rs = [r for r in regions if len(r.cells) == sz]
        min_area = min(r.boundary_area for r in rs)
        max_area = max(r.boundary_area for r in rs)
        min_mc = min(r.min_cut for r in rs)
        max_mc = max(r.min_cut for r in rs)
        print(f"    {sz}-cell:  {size_dist[sz]:>4d} regions, "
              f"area {min_area}–{max_area}, "
              f"min-cut {min_mc}–{max_mc}")

    print(f"\n  Min-cut value distribution:")
    for val in sorted(cut_dist):
        print(f"    S = {val}:  {cut_dist[val]:>4d} regions")

    print(f"\n  Boundary area distribution:")
    for val in sorted(area_dist):
        print(f"    area = {val:>2d}:  {area_dist[val]:>4d} regions")

    print(f"\n  Slack distribution (area − min-cut):")
    for val in sorted(slack_dist):
        print(f"    k = {val:>2d}:  {slack_dist[val]:>4d} regions")

    min_slack = min(r.slack for r in regions)
    max_slack = max(r.slack for r in regions)
    avg_slack = sum(r.slack for r in regions) / len(regions)
    print(f"\n  Slack range:  {min_slack} – {max_slack}  "
          f"(mean {avg_slack:.1f})")

    # Area law tightness: how often does S = area?
    tight = sum(1 for r in regions if r.slack == 0)
    print(f"\n  Tight cases (S = area):  {tight} / {len(regions)}"
          f"  ({100*tight/len(regions):.1f}%)")


def print_sample(regions: list[RegionAreaInfo], n: int = 15) -> None:
    """Print a sample of regions with their area-law data."""
    print(f"\n  ── Sample Regions ──")
    print(f"  {'Region':<12s} | {'Cells':>5s} | {'S':>3s} | "
          f"{'Area':>4s} | {'Slack':>5s} | {'Witness':>12s}")
    print(f"  {'─' * 55}")

    # Sample across different sizes and slacks
    sample = sorted(regions, key=lambda r: (len(r.cells), r.min_cut))
    shown: set[tuple[int, int]] = set()
    count = 0
    for r in sample:
        key = (len(r.cells), r.min_cut)
        if key in shown:
            continue
        shown.add(key)
        rn = region_agda_name(r)
        print(f"  {rn:<12s} | {len(r.cells):>5d} | {r.min_cut:>3d} | "
              f"{r.boundary_area:>4d} | {r.slack:>5d} | "
              f"({r.slack} , refl)")
        count += 1
        if count >= n:
            break

    if len(regions) > n:
        print(f"  ... ({len(regions) - count} more)")


# ════════════════════════════════════════════════════════════════════
#  6.  File Writing
# ════════════════════════════════════════════════════════════════════

def write_file(path: Path, content: str, dry_run: bool) -> None:
    """Write content to path, creating parent directories as needed."""
    lines = content.count("\n")
    if dry_run:
        print(f"  [dry-run]  {path}  ({lines} lines)")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  ✓  {path}  ({lines} lines)")


# ════════════════════════════════════════════════════════════════════
#  7.  Main
# ════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Boundary/Dense100AreaLaw.agda — "
                    "discrete area law for the Dense-100 patch")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_SRC_DIR,
                        help="Root source directory "
                             "(default: ../../src relative to script)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Compute and verify without writing files")
    args = parser.parse_args()

    print("╔═══════════════════════════════════════════════════════════╗")
    print("║  11: Discrete Area Law — Dense-100 {4,3,5} Honeycomb    ║")
    print("║  S_cut(A) ≤ area(A)  for all 717 boundary regions       ║")
    print("╚═══════════════════════════════════════════════════════════╝")

    # ── Step 1: Build the Dense-100 patch ───────────────────────────
    print("\n  Building Dense-100 patch via greedy max-connectivity ...")
    data = build_dense100_patch()
    patch = data["patch"]
    print(f"  ✓  {len(patch['cells'])} cells, "
          f"{len(patch['internal_faces'])} internal faces, "
          f"{patch['n_boundary_faces']} boundary faces.")

    # ── Step 2: Compute regions with boundary areas ─────────────────
    print(f"\n  Enumerating cell-aligned boundary regions "
          f"(max {MAX_REGION_CELLS} cells) ...")
    print("  Computing min-cut values and boundary surface areas ...")
    regions = compute_regions_with_area(patch)
    print(f"  ✓  {len(regions)} regions computed.")

    if not regions:
        print("  ✗  No regions found!")
        return

    min_s = min(r.min_cut for r in regions)
    max_s = max(r.min_cut for r in regions)
    min_a = min(r.boundary_area for r in regions)
    max_a = max(r.boundary_area for r in regions)
    print(f"  Min-cut range:       {min_s} – {max_s}")
    print(f"  Boundary area range: {min_a} – {max_a}")

    # ── Step 3: Verify the area law ─────────────────────────────────
    print(f"\n  Verifying discrete area law: S(A) ≤ area(A) ...")
    ok = verify_area_law(regions)
    if ok:
        print(f"  ✓  Area law verified for all {len(regions)} regions!")
    else:
        print(f"  ✗  Area law VIOLATED — cannot generate Agda module.")
        return

    # ── Step 4: Print summary ───────────────────────────────────────
    print_summary(regions)
    print_sample(regions)

    # ── Step 5: Generate and write the Agda module ──────────────────
    src_dir = args.output_dir.resolve()
    out_path = src_dir / "Boundary" / "Dense100AreaLaw.agda"

    print(f"\n  Output: {out_path}")
    if args.dry_run:
        print("  [DRY RUN — no files will be written]\n")

    content = generate_area_law_module(regions)
    write_file(out_path, content, args.dry_run)

    lines = content.count("\n")

    # ── Step 6: Final report ────────────────────────────────────────
    action = "would generate" if args.dry_run else "generated"
    print(f"\n  ── Summary: {action} 1 file, ~{lines} lines ──")

    print(f"\n  Module contents:")
    print(f"    regionArea clauses:        {len(regions)}")
    print(f"    area-law abstract proofs:  {len(regions)}")

    slack_dist = Counter(r.slack for r in regions)
    print(f"    Distinct slack values:     {len(slack_dist)}")
    print(f"    Slack witnesses used:")
    for k in sorted(slack_dist):
        print(f"      ({k} , refl):  {slack_dist[k]} cases")

    tight = sum(1 for r in regions if r.slack == 0)
    print(f"    Tight cases (slack = 0):   {tight}")

    print(f"""
  This module provides the area-law upper bound for the Dense-100
  patch, satisfying Tier 2 of the §8.7 implementation plan and
  contributing to the CoarseGrainedRT type from Bridge/CoarseGrain.agda.

  Together with  dense100-coarse-witness  (from Bridge/CoarseGrain.agda),
  the triple  (dense100-coarse-witness , regionArea , area-law)
  instantiates  CoarseGrainedRT , packaging:

    1. The exact discrete RT correspondence (S = L) on all 717 regions
    2. The orbit reduction (717 → 8 representative classes)
    3. The area-law upper bound (S ≤ area) on all 717 regions
    4. The factorization: all three cohere through classify100

  Exit criterion (§8.11 of docs/10-frontier.md):
    "A Python-generated Boundary/Dense100AreaLaw.agda contains
     717 abstract cases of (k , refl) proving the discrete area
     law, and type-checks."

  Next steps:
    1. Load  Boundary/Dense100AreaLaw.agda  in Agda to verify
       it type-checks.
    2. Instantiate  CoarseGrainedRT  in a downstream module by
       combining  dense100-coarse-witness  with  regionArea  and
       area-law  from this module.
""")


if __name__ == "__main__":
    main()