#!/usr/bin/env python3
"""
12_generate_dense200.py  —  Phase G.1 Dense-200 Agda Code Generator

Extends the Dense growth strategy to 200 cells in the {4,3,5}
hyperbolic honeycomb, generating 6 Cubical Agda modules for the
second refinement step of the Convergence Certificate (§10.9 of
docs/10-frontier.md).

This script combines:
  • The greedy max-connectivity growth from 07_honeycomb_3d_multiStrategy.py
  • The orbit reduction architecture from 09_generate_dense100.py
  • The area-law emission from 11_generate_area_law.py

into a single generator that produces all 6 modules needed to
extend the resolution tower from 2 levels (Dense-50, Dense-100)
to 3 levels (Dense-50, Dense-100, Dense-200).

The key empirical question (§10.5, §10.11):
  Does the max min-cut grow to 9 or beyond?
  Dense-50 max = 7, Dense-100 max = 8 → Dense-200 max = ???

If the max min-cut is ≥ 9, the monotonicity witness for the
Dense-100 → Dense-200 transition is  (k , refl)  where k ≥ 1.
If it stays at 8, the witness is  (0 , refl)  (non-strict).
Either way the area law and RT correspondence are verified.

Generated modules:
  src/Common/Dense200Spec.agda          — D200Region, D200OrbitRep,
                                          classify200
  src/Boundary/Dense200Cut.agda         — S-cut via orbit reps
  src/Bulk/Dense200Chain.agda           — L-min via orbit reps
  src/Bulk/Dense200Curvature.agda       — edge-class κ₂₀ + GB refl
  src/Bridge/Dense200Obs.agda           — orbit-based pointwise agreement
  src/Boundary/Dense200AreaLaw.agda     — area-law bound (abstract)

Usage (from repository root):
  python3 sim/prototyping/12_generate_dense200.py
  python3 sim/prototyping/12_generate_dense200.py --dry-run
  python3 sim/prototyping/12_generate_dense200.py --output-dir /path/to/src

Dependencies:  numpy, networkx

Reference:
  docs/10-frontier.md §10    (Infinite Resolution / Continuum Limit)
  docs/10-frontier.md §10.5  (Monotonicity Witness)
  docs/10-frontier.md §10.11 (Phase G.1 — Dense-200 extension)
  docs/10-frontier.md §10.12 (The Python Oracle's Role)
  sim/prototyping/09_generate_dense100.py  (orbit reduction pattern)
  sim/prototyping/11_generate_area_law.py  (area-law pattern)
"""

from __future__ import annotations

import argparse
import importlib
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import NamedTuple

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

try:
    multi = importlib.import_module("07_honeycomb_3d_multiStrategy")
except ModuleNotFoundError:
    sys.exit(
        "ERROR: Could not import 07_honeycomb_3d_multiStrategy.py.\n"
        "       Run this script from the repository root:\n"
        "         python3 sim/prototyping/12_generate_dense200.py"
    )

try:
    import numpy as np
    import networkx as nx
except ImportError:
    sys.exit("ERROR: numpy and networkx are required.  "
             "pip install numpy networkx")

DEFAULT_SRC_DIR = SCRIPT_DIR.parent.parent / "src"

GENERATED_BANNER = (
    "--  Generated by sim/prototyping/12_generate_dense200.py\n"
    "--  Do not edit by hand.  Regenerate with:\n"
    "--    python3 sim/prototyping/12_generate_dense200.py"
)

MAX_CELLS = 200
MAX_REGION_CELLS = 5

# Dense-100 max min-cut for monotonicity comparison
DENSE100_MAX_MINCUT = 8


# ════════════════════════════════════════════════════════════════════
#  1.  Build the Dense-200 Patch
# ════════════════════════════════════════════════════════════════════

def build_dense200_patch() -> dict:
    """
    Build the Dense-200 patch of the {4,3,5} honeycomb using the
    greedy max-connectivity growth strategy from 07.

    Returns a dict with the patch data plus Coxeter geometry objects
    needed for edge-class curvature computation.
    """
    G = multi.build_gram_matrix()
    refls = multi.build_reflections(G)
    multi.validate_reflections(G, refls)

    cell_center = multi.find_cell_center(G)
    stab = multi.enumerate_group(refls[:3], expected=48)
    face_crossings = multi.find_face_crossings(refls, stab, G)
    adj_pairs, opp_pairs = multi.classify_face_pairs(face_crossings)

    patch = multi.build_patch_dense(
        face_crossings, cell_center, MAX_CELLS,
        name="Dense-200 ({4,3,5} honeycomb)"
    )

    return {
        "patch": patch,
        "face_crossings": face_crossings,
        "adj_pairs": adj_pairs,
        "opp_pairs": opp_pairs,
        "cell_center": cell_center,
        "gram": G,
    }


# ════════════════════════════════════════════════════════════════════
#  2.  Region Computation (with boundary area for area-law)
# ════════════════════════════════════════════════════════════════════

class RegionInfo(NamedTuple):
    idx: int
    cells: frozenset[int]
    n_bdy_faces: int         # number of boundary pseudo-nodes in region
    min_cut: int             # min-cut value (from max-flow)
    boundary_area: int       # 6|A| − 2·|internal faces within A|
    slack: int               # boundary_area − min_cut  (must be ≥ 0)


def compute_boundary_area(
    cells: frozenset[int],
    internal_faces: list[tuple[int, int]],
) -> int:
    """
    Boundary surface area of a cell-aligned region A.

        area(A) = 6·|A| − 2·|{shared faces between two cells in A}|

    Each cube has 6 faces.  Each internal face shared between two
    A-cells is counted by both cells (contributing 2 to the 6|A|
    total) but does not exit A — so we subtract 2 per shared face.
    """
    n_cells = len(cells)
    internal_within = sum(
        1 for c1, c2 in internal_faces
        if c1 in cells and c2 in cells
    )
    return 6 * n_cells - 2 * internal_within


def compute_regions(patch: dict) -> list[RegionInfo]:
    """
    Enumerate all cell-aligned boundary regions (connected subsets
    of boundary cells up to MAX_REGION_CELLS cells), compute their
    min-cut values and boundary surface areas.
    """
    flow_G, bnode_ids, bnode_to_cell = multi.build_flow_graph(patch)
    internal_faces = patch["internal_faces"]

    regions_raw = multi.enumerate_cell_aligned_regions(
        patch, bnode_to_cell, bnode_ids,
        max_region_cells=MAX_REGION_CELLS,
    )

    regions: list[RegionInfo] = []
    for label, idx_set in regions_raw:
        cells_str = label.strip("{}").split(",")
        cells = frozenset(
            int(s.strip().lstrip("c")) for s in cells_str if s.strip()
        )
        s = multi.compute_min_cut(flow_G, bnode_ids, idx_set)
        area = compute_boundary_area(cells, internal_faces)
        slack = area - s
        regions.append(RegionInfo(
            idx=len(regions),
            cells=cells,
            n_bdy_faces=len(idx_set),
            min_cut=s,
            boundary_area=area,
            slack=slack,
        ))

    return regions


# ════════════════════════════════════════════════════════════════════
#  3.  Orbit Reduction (by min-cut value)
# ════════════════════════════════════════════════════════════════════

class OrbitRep(NamedTuple):
    """An orbit representative, identified by its min-cut value."""
    name: str       # Agda constructor name: mc1, mc2, ...
    min_cut: int    # The shared min-cut value for all regions in this orbit
    count: int      # Number of regions in this orbit


def compute_orbits(regions: list[RegionInfo]) -> list[OrbitRep]:
    """Group regions by min-cut value into orbit representatives."""
    cut_counts = Counter(r.min_cut for r in regions)
    orbits: list[OrbitRep] = []
    for mc_val in sorted(cut_counts.keys()):
        orbits.append(OrbitRep(
            name=f"mc{mc_val}",
            min_cut=mc_val,
            count=cut_counts[mc_val],
        ))
    return orbits


def orbit_for_region(r: RegionInfo, orbits: list[OrbitRep]) -> OrbitRep:
    """Find the orbit representative for a region."""
    for orb in orbits:
        if orb.min_cut == r.min_cut:
            return orb
    raise ValueError(f"No orbit for min-cut {r.min_cut}")


# ════════════════════════════════════════════════════════════════════
#  4.  Edge Curvature Classes
# ════════════════════════════════════════════════════════════════════

class EdgeClassInfo(NamedTuple):
    name: str
    valence_in_patch: int
    full_valence: int
    count: int
    kappa_twentieths: int


def compute_edge_classes(data: dict, patch: dict) -> list[EdgeClassInfo]:
    """
    Classify the 12 edges of the central cube by their in-patch
    valence using the deduplicated orbit-center approach from 07.
    """
    face_crossings = data["face_crossings"]
    adj_pairs = data["adj_pairs"]
    cell_center = data["cell_center"]
    p = cell_center

    patch_centers = {multi._vec_key(mat @ p)
                     for mat in patch["cells"].values()}

    valences: list[int] = []
    for fi, fj in adj_pairs:
        F_a, F_b = face_crossings[fi], face_crossings[fj]
        dih_elems = multi.enumerate_group([F_a, F_b])
        orbit_centers = {multi._vec_key(g @ p) for g in dih_elems}
        in_patch = len(orbit_centers & patch_centers)
        valences.append(in_patch)

    val_counts = Counter(valences)
    classes: list[EdgeClassInfo] = []
    for val in sorted(val_counts.keys()):
        k20 = 20 - 5 * val
        classes.append(EdgeClassInfo(
            name=f"ev{val}",
            valence_in_patch=val,
            full_valence=5,
            count=val_counts[val],
            kappa_twentieths=k20,
        ))
    return classes


# ════════════════════════════════════════════════════════════════════
#  5.  Agda Naming Helpers
# ════════════════════════════════════════════════════════════════════

def region_agda_name(r: RegionInfo) -> str:
    return f"d200r{r.idx}"


def cells_comment(r: RegionInfo) -> str:
    cs = sorted(r.cells)
    if len(cs) <= 6:
        return "{" + ",".join(f"c{c}" for c in cs) + "}"
    return "{" + ",".join(f"c{c}" for c in cs[:5]) + ",..." + "}"


# ════════════════════════════════════════════════════════════════════
#  6.  Agda Module Generators
# ════════════════════════════════════════════════════════════════════

def gen_spec(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
) -> str:
    """Generate  Common/Dense200Spec.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Common.Dense200Spec where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("")

    # ── D200Region ──────────────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  D200Region — Cell-aligned boundary regions of the Dense-200")
    a("--  patch of the {4,3,5} hyperbolic honeycomb")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a(f"--  The Dense-200 patch is grown by greedy max-connectivity")
    a(f"--  from the central cube, producing {MAX_CELLS} cells.")
    a(f"--  Regions are connected subsets of boundary cells (up to")
    a(f"--  {MAX_REGION_CELLS} cells), giving {len(regions)} regions.")
    a("--")
    a("--  This is the third resolution level in the convergence")
    a("--  certificate, extending the tower:")
    a("--    Dense-50 (139 regions) → Dense-100 (717 regions)")
    a(f"--    → Dense-200 ({len(regions)} regions)")
    a("--")
    a("--  The orbit reduction strategy classifies regions by")
    a(f"--  min-cut value into {len(orbits)} orbit representatives.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("data D200Region : Type₀ where")

    sizes: dict[int, list[RegionInfo]] = defaultdict(list)
    for r in regions:
        sizes[len(r.cells)].append(r)

    for size in sorted(sizes.keys()):
        rs = sizes[size]
        names = [region_agda_name(r) for r in rs]
        a(f"  -- size {size}  ({len(rs)} regions)")
        for i in range(0, len(names), 10):
            batch = names[i:i + 10]
            a(f"  {' '.join(batch)} : D200Region")
    a("")

    # ── D200OrbitRep ────────────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  D200OrbitRep — Orbit representatives by min-cut value")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Orbit decomposition:")
    for orb in orbits:
        a(f"--    {orb.name}  (S = {orb.min_cut}):  {orb.count} regions")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("data D200OrbitRep : Type₀ where")
    orb_names = [orb.name for orb in orbits]
    a(f"  {' '.join(orb_names)} : D200OrbitRep")
    a("")

    # ── classify200 ─────────────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  classify200 — Map each region to its orbit representative")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a(f"--  {len(regions)}-clause pattern match.  Each clause maps")
    a("--  a constructor to an orbit representative.  This function")
    a("--  is traversed only during concrete evaluation, never")
    a("--  during proof normalization.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("classify200 : D200Region → D200OrbitRep")

    for r in regions:
        rn = region_agda_name(r)
        orb = orbit_for_region(r, orbits)
        a(f"classify200 {rn} = {orb.name}")

    a("")
    return "\n".join(L) + "\n"


def gen_cut(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
) -> str:
    """Generate  Boundary/Dense200Cut.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Boundary.Dense200Cut where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense200Spec")
    a("")
    a("record D200BdyView : Type₀ where")
    a("  field")
    a("    dummy : ℚ≥0")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  S-cut-rep — Boundary min-cut on orbit representatives")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("S-cut-rep : D200OrbitRep → ℚ≥0")
    for orb in orbits:
        a(f"S-cut-rep {orb.name} = {orb.min_cut}")
    a("")

    a("-- ═══════════════════════════════════════════════════════════")
    a("--  S-cut — Boundary min-cut for the Dense-200 patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Defined as  S-cut-rep ∘ classify200 .")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("S-cut : D200BdyView → D200Region → ℚ≥0")
    a("S-cut _ r = S-cut-rep (classify200 r)")
    a("")

    return "\n".join(L) + "\n"


def gen_chain(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
) -> str:
    """Generate  Bulk/Dense200Chain.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bulk.Dense200Chain where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense200Spec")
    a("")
    a("record D200BulkView : Type₀ where")
    a("  field")
    a("    dummy : ℚ≥0")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  L-min-rep — Bulk minimal surface on orbit representatives")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("L-min-rep : D200OrbitRep → ℚ≥0")
    for orb in orbits:
        a(f"L-min-rep {orb.name} = {orb.min_cut}")
    a("")

    a("-- ═══════════════════════════════════════════════════════════")
    a("--  L-min — Bulk minimal separating surface for Dense-200")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Defined as  L-min-rep ∘ classify200 , mirroring S-cut.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("L-min : D200BulkView → D200Region → ℚ≥0")
    a("L-min _ r = L-min-rep (classify200 r)")
    a("")

    return "\n".join(L) + "\n"


def gen_curvature(edge_classes: list[EdgeClassInfo]) -> str:
    """Generate  Bulk/Dense200Curvature.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bulk.Dense200Curvature where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Cubical.Data.Nat  using (ℕ ; zero ; suc ; _+_ ; _·_)")
    a("open import Cubical.Data.Int")
    a("  using (ℤ ; pos ; negsuc)")
    a("  renaming (_+_ to _+ℤ_)")
    a("")
    a("open import Util.Rationals")
    a("")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  3D Edge Curvature for the Dense-200 {4,3,5} Patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  In 3D, curvature lives on EDGES (not vertices).")
    a("--  At an interior edge e with valence v (cubes meeting):")
    a("--    κ(e) = 2π − v · (π/2)")
    a("--")
    a("--  Combinatorial encoding in twentieths (via ℚ₁₀ = ℤ):")
    a("--    κ₂₀(e) = 20 − 5·v")
    a("--")
    a(GENERATED_BANNER)
    a("")

    a("data D200EdgeClass : Type₀ where")
    names = [ec.name for ec in edge_classes]
    a(f"  {' '.join(names)} : D200EdgeClass")
    a("")

    a("d200EdgeCount : D200EdgeClass → ℕ")
    for ec in edge_classes:
        a(f"d200EdgeCount {ec.name} = {ec.count}")
    a("")

    a("d200Valence : D200EdgeClass → ℕ")
    for ec in edge_classes:
        a(f"d200Valence {ec.name} = {ec.valence_in_patch}")
    a("")

    a("d200Kappa : D200EdgeClass → ℚ₁₀")
    for ec in edge_classes:
        k20 = ec.kappa_twentieths
        if k20 >= 0:
            a(f"d200Kappa {ec.name} = pos {k20}"
              f"    -- val={ec.valence_in_patch}, κ₂₀={k20}")
        else:
            a(f"d200Kappa {ec.name} = negsuc {-k20 - 1}"
              f"    -- val={ec.valence_in_patch}, κ₂₀={k20}")
    a("")

    a("totalD200Curvature : ℚ₁₀")
    parts = [f"{ec.count} ·₁₀ d200Kappa {ec.name}" for ec in edge_classes]
    a(f"totalD200Curvature = {' +₁₀ '.join(parts)}")
    a("")

    total_val = sum(ec.count * ec.kappa_twentieths for ec in edge_classes)
    if total_val >= 0:
        expected_str = f"pos {total_val}"
    else:
        expected_str = f"negsuc {-total_val - 1}"

    a(f"-- Expected value: {expected_str}  (= {total_val} in twentieths)")
    a(f"totalD200Curvature-check : totalD200Curvature ≡ {expected_str}")
    a("totalD200Curvature-check = refl")
    a("")

    for ec in edge_classes:
        contrib = ec.count * ec.kappa_twentieths
        if contrib >= 0:
            contrib_str = f"pos {contrib}"
        else:
            contrib_str = f"negsuc {-contrib - 1}"
        a(f"contrib-{ec.name} : {ec.count} ·₁₀ d200Kappa {ec.name}"
          f" ≡ {contrib_str}")
        a(f"contrib-{ec.name} = refl")
        a("")

    return "\n".join(L) + "\n"


def gen_obs(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
) -> str:
    """Generate  Bridge/Dense200Obs.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Bridge.Dense200Obs where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense200Spec")
    a("open import Common.ObsPackage")
    a("open import Boundary.Dense200Cut")
    a("open import Bulk.Dense200Chain")
    a("")

    a("d200BdyView : D200BdyView")
    a("d200BdyView .D200BdyView.dummy = 0")
    a("")
    a("d200BulkView : D200BulkView")
    a("d200BulkView .D200BulkView.dummy = 0")
    a("")

    a("D200Obs∂ : ObsPackage D200Region")
    a("D200Obs∂ .ObsPackage.obs = S-cut d200BdyView")
    a("")
    a("D200ObsBulk : ObsPackage D200Region")
    a("D200ObsBulk .ObsPackage.obs = L-min d200BulkView")
    a("")

    # ── Orbit-level pointwise agreement ─────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a(f"--  d200-pointwise-rep — All {len(orbits)} orbit cases by refl")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  The core proof: S-cut-rep and L-min-rep agree on every")
    a("--  orbit representative.  Both return the same ℕ literal,")
    a("--  so each case holds by refl.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("d200-pointwise-rep :")
    a("  (o : D200OrbitRep) → S-cut-rep o ≡ L-min-rep o")

    for orb in orbits:
        a(f"d200-pointwise-rep {orb.name} = refl")

    a("")

    # ── Full pointwise agreement (via orbit lifting) ────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a(f"--  d200-pointwise — Lifted to all {len(regions)} regions")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Single-line proof composing orbit-level proof with classify200.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("d200-pointwise :")
    a("  (r : D200Region) →")
    a("  S-cut d200BdyView r ≡ L-min d200BulkView r")
    a("d200-pointwise r = d200-pointwise-rep (classify200 r)")
    a("")

    # ── Function path ───────────────────────────────────────────────
    a("S∂D200 : D200Region → ℚ≥0")
    a("S∂D200 = S-cut d200BdyView")
    a("")
    a("LBD200 : D200Region → ℚ≥0")
    a("LBD200 = L-min d200BulkView")
    a("")
    a("d200-obs-path : S∂D200 ≡ LBD200")
    a("d200-obs-path = funExt d200-pointwise")
    a("")

    # ── Package path ────────────────────────────────────────────────
    a("d200-package-path : D200Obs∂ ≡ D200ObsBulk")
    a("d200-package-path i .ObsPackage.obs = d200-obs-path i")
    a("")

    return "\n".join(L) + "\n"


def gen_area_law(regions: list[RegionInfo]) -> str:
    """Generate  Boundary/Dense200AreaLaw.agda ."""
    L: list[str] = []
    a = L.append

    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a("module Boundary.Dense200AreaLaw where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Cubical.Data.Nat using (ℕ ; _+_)")
    a("open import Util.Scalars")
    a("open import Common.Dense200Spec")
    a("open import Boundary.Dense200Cut")
    a("open import Bridge.Dense200Obs using (d200BdyView)")
    a("")

    # ── regionArea ──────────────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  regionArea — Boundary surface area of each region")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  area(A) = 6k − 2 · |internal faces within A|")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("regionArea : D200Region → ℚ≥0")

    for r in regions:
        rn = region_agda_name(r)
        n = len(r.cells)
        a(f"regionArea {rn} = {r.boundary_area}"
          f"    -- {n} cells")

    a("")

    # ── area-law (abstract) ─────────────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a(f"--  area-law — S_cut(A) ≤ area(A)  ({len(regions)} cases)")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Wrapped in  abstract  so downstream modules never")
    a("--  re-unfold the proof.  Since  _≤ℚ_  is propositional,")
    a("--  the abstract barrier does not damage the Univalence bridge.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("abstract")
    a("  area-law : (r : D200Region)"
      " → S-cut d200BdyView r ≤ℚ regionArea r")

    prev_key = (-1, -1)
    for r in regions:
        key = (r.min_cut, r.slack)
        if key != prev_key:
            a(f"  -- S={r.min_cut}, area={r.boundary_area},"
              f" slack={r.slack}")
            prev_key = key
        rn = region_agda_name(r)
        a(f"  area-law {rn} = {r.slack} , refl")

    a("")
    return "\n".join(L) + "\n"


# ════════════════════════════════════════════════════════════════════
#  7.  File Writing
# ════════════════════════════════════════════════════════════════════

FILE_MAP = [
    ("Common/Dense200Spec.agda",         "spec"),
    ("Boundary/Dense200Cut.agda",        "cut"),
    ("Bulk/Dense200Chain.agda",          "chain"),
    ("Bulk/Dense200Curvature.agda",      "curv"),
    ("Bridge/Dense200Obs.agda",          "obs"),
    ("Boundary/Dense200AreaLaw.agda",    "area"),
]


def write_file(path: Path, content: str, dry_run: bool) -> None:
    lines = content.count("\n")
    if dry_run:
        print(f"  [dry-run]  {path}  ({lines} lines)")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  ✓  {path}  ({lines} lines)")


# ════════════════════════════════════════════════════════════════════
#  8.  Summary, Diagnostics, and Monotonicity
# ════════════════════════════════════════════════════════════════════

def print_summary(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
    edge_classes: list[EdgeClassInfo],
    patch: dict,
) -> None:
    print(f"\n  ── Patch Topology ──")
    print(f"  Cells:            {len(patch['cells'])}")
    print(f"  Internal faces:   {len(patch['internal_faces'])}")
    print(f"  Boundary faces:   {patch['n_boundary_faces']}")

    density = 2 * len(patch["internal_faces"]) / max(len(patch["cells"]), 1)
    print(f"  Density (2·IntF/Cells): {density:.2f}")

    cut_dist = Counter(r.min_cut for r in regions)
    size_dist = Counter(len(r.cells) for r in regions)
    slack_dist = Counter(r.slack for r in regions)

    print(f"\n  ── Region Statistics ({len(regions)} total) ──")
    print(f"  By size:")
    for sz in sorted(size_dist):
        rs = [r for r in regions if len(r.cells) == sz]
        min_mc = min(r.min_cut for r in rs)
        max_mc = max(r.min_cut for r in rs)
        min_area = min(r.boundary_area for r in rs)
        max_area = max(r.boundary_area for r in rs)
        print(f"    {sz}-cell:  {size_dist[sz]:>5d} regions, "
              f"area {min_area}–{max_area}, min-cut {min_mc}–{max_mc}")

    print(f"  By min-cut value:")
    for val in sorted(cut_dist):
        print(f"    S = {val:>2d}:  {cut_dist[val]:>5d} regions")

    min_s = min(r.min_cut for r in regions)
    max_s = max(r.min_cut for r in regions)
    print(f"  Min-cut range:  {min_s} – {max_s}")

    print(f"\n  ── Orbit Reduction ──")
    print(f"  Distinct min-cut values:  {len(orbits)}")
    print(f"  Orbit decomposition:")
    for orb in orbits:
        print(f"    {orb.name}  (S = {orb.min_cut}):  {orb.count} regions")
    reduction = len(regions) / max(len(orbits), 1)
    print(f"  Reduction factor:  {len(regions)} → {len(orbits)}"
          f"  ({reduction:.0f}× fewer proof cases)")

    print(f"\n  ── Area-Law Statistics ──")
    min_slack = min(r.slack for r in regions)
    max_slack = max(r.slack for r in regions)
    avg_slack = sum(r.slack for r in regions) / len(regions)
    tight = sum(1 for r in regions if r.slack == 0)
    violations = sum(1 for r in regions if r.slack < 0)
    print(f"  Slack range:    {min_slack} – {max_slack}  (mean {avg_slack:.1f})")
    print(f"  Tight (S=area): {tight} / {len(regions)}")
    print(f"  Violations:     {violations}")
    print(f"  Slack distribution:")
    for k in sorted(slack_dist):
        print(f"    k = {k:>2d}:  {slack_dist[k]:>5d} regions")

    print(f"\n  ── Resolution Tower Comparison ──")
    print(f"    Dense-50:   139 regions,  max S = 7")
    print(f"    Dense-100:  717 regions,  max S = 8")
    print(f"    Dense-200:  {len(regions)} regions,  max S = {max_s}")

    print(f"\n  ── Edge Curvature (12 central-cube edges) ──")
    for ec in edge_classes:
        k = ec.kappa_twentieths
        tag = " ← hyperbolic" if k < 0 else (" (flat)" if k == 0 else "")
        print(f"    Valence {ec.valence_in_patch} (×{ec.count}): "
              f"κ₂₀ = {k}{tag}")
    total_k = sum(ec.count * ec.kappa_twentieths for ec in edge_classes)
    print(f"  Total:  Σ κ₂₀ = {total_k}")


def print_monotonicity(regions: list[RegionInfo]) -> None:
    """Analyze and print the monotonicity witness for the tower."""
    max_s = max(r.min_cut for r in regions)
    k = max_s - DENSE100_MAX_MINCUT

    print(f"\n  ════════════════════════════════════════════════════════")
    print(f"  MONOTONICITY WITNESS (Dense-100 → Dense-200)")
    print(f"  ════════════════════════════════════════════════════════")
    print(f"  Dense-100 max min-cut:  {DENSE100_MAX_MINCUT}")
    print(f"  Dense-200 max min-cut:  {max_s}")

    if k > 0:
        print(f"\n  ✓  Spectrum GROWS:  {DENSE100_MAX_MINCUT} < {max_s}")
        print(f"     Agda witness:  spectrum-grows-200 : "
              f"{DENSE100_MAX_MINCUT} ≤ℚ {max_s}")
        print(f"     spectrum-grows-200 = {k} , refl")
        print(f"     (because {k} + {DENSE100_MAX_MINCUT} = {max_s} "
              f"judgmentally)")
    elif k == 0:
        print(f"\n  ≡  Spectrum FLAT:  {DENSE100_MAX_MINCUT} = {max_s}")
        print(f"     Agda witness:  spectrum-grows-200 : "
              f"{DENSE100_MAX_MINCUT} ≤ℚ {max_s}")
        print(f"     spectrum-grows-200 = 0 , refl")
        print(f"     (non-strict monotonicity; max did not increase)")
    else:
        print(f"\n  ✗  Spectrum SHRINKS:  {DENSE100_MAX_MINCUT} > {max_s}")
        print(f"     This is unexpected and may indicate a patch issue.")

    print(f"\n  Resolution tower monotonicity table:")
    print(f"    | Transition             | Max_lo | Max_hi | Witness      |")
    print(f"    |──────────────────────--|────────|────────|──────────────|")
    print(f"    | Dense-50 → Dense-100   |      7 |      8 | (1 , refl)  |")
    if k >= 0:
        print(f"    | Dense-100 → Dense-200  |      8 |"
              f"     {max_s:>2d} | ({k} , refl)  |")
    else:
        print(f"    | Dense-100 → Dense-200  |      8 |"
              f"     {max_s:>2d} | VIOLATION    |")


def print_gate_check(
    regions: list[RegionInfo],
    orbits: list[OrbitRep],
    edge_classes: list[EdgeClassInfo],
    patch: dict,
) -> bool:
    n_bdy = patch["n_boundary_faces"]
    n_regs = len(regions)
    n_orbs = len(orbits)
    n_full = sum(ec.count for ec in edge_classes
                 if ec.valence_in_patch >= 5)
    max_cut = max(r.min_cut for r in regions) if regions else 0
    area_ok = all(r.slack >= 0 for r in regions)

    print(f"\n  ═══════════════════════════════════════════════════════")
    print(f"  GATE CHECK (Dense-200 — Phase G.1)")
    print(f"  ═══════════════════════════════════════════════════════")

    gate_pass = True
    checks = [
        ("Region count (orbit ≤ 200)",
         n_orbs <= 200, f"{n_regs} raw / {n_orbs} orbits"),
        ("≥1 full-valence edge in patch",
         n_full > 0, n_full),
        ("Max min-cut ≥ 8 (at least matches Dense-100)",
         max_cut >= DENSE100_MAX_MINCUT, max_cut),
        ("Area law holds (S ≤ area for all regions)",
         area_ok, f"{'✓' if area_ok else '✗'}"),
        ("Orbit reduction effective (ratio > 5×)",
         n_regs / max(n_orbs, 1) > 5,
         f"{n_regs / max(n_orbs, 1):.0f}×"),
    ]
    for desc, ok, val in checks:
        status = "✓ PASS" if ok else "✗ FAIL"
        if not ok:
            gate_pass = False
        print(f"    {status}  {desc}  (actual: {val})")

    if gate_pass:
        print(f"\n  ▶  ALL GATES PASS — Dense-200 extends the "
              f"convergence certificate!")
    else:
        print(f"\n  ▶  GATE(S) BLOCKED")

    return gate_pass


# ════════════════════════════════════════════════════════════════════
#  9.  Main
# ════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Dense-200 Cubical Agda modules "
                    "with orbit reduction + area law (Phase G.1)")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_SRC_DIR,
                        help="Root source directory "
                             "(default: ../../src relative to script)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Compute and verify without writing files")
    args = parser.parse_args()

    print("╔═══════════════════════════════════════════════════════════╗")
    print("║  Phase G.1: Dense-200 {4,3,5} — Resolution Tower Level 3 ║")
    print("║  Orbit reduction + area law • Convergence certificate     ║")
    print("╚═══════════════════════════════════════════════════════════╝")

    # ── Step 1: Build the Dense-200 patch ───────────────────────────
    print("\n  Building Dense-200 patch via greedy max-connectivity ...")
    data = build_dense200_patch()
    patch = data["patch"]
    print(f"  ✓  {len(patch['cells'])} cells, "
          f"{len(patch['internal_faces'])} internal faces, "
          f"{patch['n_boundary_faces']} boundary faces.")

    # ── Step 2: Compute regions with min-cuts and areas ─────────────
    print(f"\n  Enumerating cell-aligned boundary regions "
          f"(max {MAX_REGION_CELLS} cells) ...")
    print("  Computing min-cut values and boundary surface areas ...")
    regions = compute_regions(patch)
    print(f"  ✓  {len(regions)} regions computed.")

    if not regions:
        print("  ✗  No regions found!")
        return

    min_s = min(r.min_cut for r in regions)
    max_s = max(r.min_cut for r in regions)
    print(f"  Min-cut range: {min_s} – {max_s}")

    # Verify area law
    violations = [r for r in regions if r.slack < 0]
    if violations:
        print(f"  ✗  Area law VIOLATED for {len(violations)} regions!")
        for v in violations[:5]:
            print(f"      {region_agda_name(v)}: S={v.min_cut} > "
                  f"area={v.boundary_area}")
        return
    else:
        print(f"  ✓  Area law verified for all {len(regions)} regions.")

    # ── Step 3: Compute orbit reduction ─────────────────────────────
    print("  Computing orbit reduction by min-cut value ...")
    orbits = compute_orbits(regions)
    print(f"  ✓  {len(orbits)} orbit representatives "
          f"(from {len(regions)} regions, "
          f"{len(regions) / len(orbits):.0f}× reduction)")

    # ── Step 4: Compute edge curvature classes ──────────────────────
    print("  Computing edge curvature classes ...")
    edge_classes = compute_edge_classes(data, patch)
    print(f"  ✓  {len(edge_classes)} edge class(es).")

    # ── Step 5: Summary, monotonicity, and gate check ───────────────
    print_summary(regions, orbits, edge_classes, patch)
    print_monotonicity(regions)
    gate_ok = print_gate_check(regions, orbits, edge_classes, patch)

    if not gate_ok:
        print("\n  WARNING: Gate check failed.")

    # ── Step 6: Generate and write Agda files ───────────────────────
    src_dir = args.output_dir.resolve()
    print(f"\n  Output directory: {src_dir}")
    if args.dry_run:
        print("  [DRY RUN — no files will be written]\n")
    print()

    generators = {
        "spec":  lambda: gen_spec(regions, orbits),
        "cut":   lambda: gen_cut(regions, orbits),
        "chain": lambda: gen_chain(regions, orbits),
        "curv":  lambda: gen_curvature(edge_classes),
        "obs":   lambda: gen_obs(regions, orbits),
        "area":  lambda: gen_area_law(regions),
    }

    total_lines = 0
    for rel_path, gen_key in FILE_MAP:
        content = generators[gen_key]()
        full_path = src_dir / rel_path
        write_file(full_path, content, args.dry_run)
        total_lines += content.count("\n")

    # ── Step 7: Final report ────────────────────────────────────────
    action = "would generate" if args.dry_run else "generated"
    print(f"\n  ── Summary: {action} {len(FILE_MAP)} files, "
          f"~{total_lines} lines total ──")

    print(f"\n  Module contents:")
    print(f"    D200Region constructors:        {len(regions)}")
    print(f"    D200OrbitRep constructors:       {len(orbits)}")
    print(f"    classify200 clauses:             {len(regions)}")
    print(f"    S-cut-rep / L-min-rep clauses:   {len(orbits)} each")
    print(f"    Pointwise-rep refl proofs:       {len(orbits)}")
    print(f"    Pointwise lifting:               1 line")
    print(f"    Edge curvature classes:          {len(edge_classes)}")
    print(f"    regionArea clauses:              {len(regions)}")
    print(f"    area-law abstract proofs:        {len(regions)}")

    total_k = sum(ec.count * ec.kappa_twentieths for ec in edge_classes)
    if total_k >= 0:
        expected_agda = f"pos {total_k}"
    else:
        expected_agda = f"negsuc {-total_k - 1}"
    print(f"    totalD200Curvature-check:        refl  (= {expected_agda})")

    k = max_s - DENSE100_MAX_MINCUT
    print(f"\n  ── KEY RESULT: Monotonicity ──")
    print(f"    Dense-100 max min-cut:  {DENSE100_MAX_MINCUT}")
    print(f"    Dense-200 max min-cut:  {max_s}")
    if k > 0:
        print(f"    ★  Spectrum GROWS!")
        print(f"       Agda: spectrum-grows-200 = {k} , refl")
    elif k == 0:
        print(f"    Spectrum flat (non-strict monotonicity)")
        print(f"       Agda: spectrum-grows-200 = 0 , refl")
    else:
        print(f"    ✗  Unexpected: spectrum decreased")

    print(f"""
  The Dense-200 instance adds a third level to the convergence
  certificate (§10.9 of docs/10-frontier.md):

    Level 1:  Dense-50   (139 regions, max S = 7)
    Level 2:  Dense-100  (717 regions, max S = 8, 8 orbits)
    Level 3:  Dense-200  ({len(regions)} regions, max S = {max_s}, {len(orbits)} orbits)

  To integrate into the resolution tower:
    1. Load all 6 generated files in Agda.
    2. Write  Bridge/Dense200Equiv.agda  (hand-written enriched equiv).
    3. Extend  Bridge/ResolutionTower.agda  to a 2-step tower
       (Phase G.2) with 2 monotonicity witnesses.

  Exit criterion (§10.13.3 — stretch):
    "A Dense-200 instance extends the certificate to 3 levels,
     with the new max min-cut ≥ 8 witnessed by (k , refl)."
""")


if __name__ == "__main__":
    main()