#!/usr/bin/env python3
"""
12b_generate_dense1000.py  —  Dense-1000 Agda Code Generator

Generates 7 Cubical Agda modules for the Dense-1000 patch of the
{4,3,5} hyperbolic honeycomb, using orbit reduction, area-law, and
half-bound emission.

Key difference from Dense-200 (12_generate_dense200.py):
  At max_region_cells=5, deeply-embedded boundary cells from smaller
  patches become interior cells in Dense-1000.  The new boundary is
  further from the dense core, so bounded-size regions achieve LOWER
  min-cuts than Dense-200 (maxS=8 < 9).

  FIX: Use ADAPTIVE max_region_cells, starting at 6.  Larger region
  subsets can probe deeper into the bulk and recover the min-cut
  values needed for tower monotonicity with Dense-200 (maxS=9).

  From 14c_entropic_convergence_sup_half.py data:
    max_rc=5 → maxS≈8 at 1000 cells
    max_rc=6 → maxS≈9 at 1000 cells (restores monotonicity)
    max_rc=7 → maxS≈10 (if needed)

Generated modules:
  src/Common/Dense1000Spec.agda
  src/Boundary/Dense1000Cut.agda
  src/Bulk/Dense1000Chain.agda
  src/Bulk/Dense1000Curvature.agda
  src/Bridge/Dense1000Obs.agda
  src/Boundary/Dense1000AreaLaw.agda
  src/Boundary/Dense1000HalfBound.agda

Usage (from repository root):
  python3 sim/prototyping/12b_generate_dense1000.py
  python3 sim/prototyping/12b_generate_dense1000.py --dry-run
  python3 sim/prototyping/12b_generate_dense1000.py --initial-max-rc 7

Dependencies:  numpy, networkx

Reference:
  docs/formal/11-generic-bridge.md   (SchematicTower)
  docs/formal/12-bekenstein-hawking.md (HalfBound)
  sim/prototyping/12_generate_dense200.py  (Dense-200 pattern)
"""

from __future__ import annotations

import argparse
import importlib
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import NamedTuple

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

try:
    multi = importlib.import_module("07_honeycomb_3d_multiStrategy")
except ModuleNotFoundError:
    sys.exit(
        "ERROR: Could not import 07_honeycomb_3d_multiStrategy.py.\n"
        "       Run this script from the repository root:\n"
        "         python3 sim/prototyping/12b_generate_dense1000.py"
    )

try:
    import numpy as np
    import networkx as nx
except ImportError:
    sys.exit("ERROR: numpy and networkx are required.  "
             "pip install numpy networkx")

DEFAULT_SRC_DIR = SCRIPT_DIR.parent.parent / "src"

GENERATED_BANNER = (
    "--  Generated by sim/prototyping/12b_generate_dense1000.py\n"
    "--  Do not edit by hand.  Regenerate with:\n"
    "--    python3 sim/prototyping/12b_generate_dense1000.py"
)

MAX_CELLS = 1000

# ── Adaptive max_region_cells ───────────────────────────────────────
# At max_rc=5, Dense-1000 only achieves maxS=8 because boundary cells
# are farther from the dense core.  We start at max_rc=6 and increment
# if needed to restore monotonicity with Dense-200 (maxS=9).
INITIAL_MAX_RC = 6
MAX_MAX_RC = 8          # upper safety limit

# Previous tower levels' max min-cuts (for monotonicity checks)
PREVIOUS_LEVELS = {
    "Dense-50":  7,
    "Dense-100": 8,
    "Dense-200": 9,
}
TARGET_MAX_MINCUT = max(PREVIOUS_LEVELS.values())  # 9


# ════════════════════════════════════════════════════════════════════
#  1.  Build the Dense-1000 Patch
# ════════════════════════════════════════════════════════════════════

def build_dense1000_patch() -> dict:
    G = multi.build_gram_matrix()
    refls = multi.build_reflections(G)
    multi.validate_reflections(G, refls)
    cell_center = multi.find_cell_center(G)
    stab = multi.enumerate_group(refls[:3], expected=48)
    face_crossings = multi.find_face_crossings(refls, stab, G)
    adj_pairs, opp_pairs = multi.classify_face_pairs(face_crossings)
    patch = multi.build_patch_dense(
        face_crossings, cell_center, MAX_CELLS,
        name="Dense-1000 ({4,3,5} honeycomb)"
    )
    return {
        "patch": patch,
        "face_crossings": face_crossings,
        "adj_pairs": adj_pairs,
        "opp_pairs": opp_pairs,
        "cell_center": cell_center,
        "gram": G,
    }


# ════════════════════════════════════════════════════════════════════
#  2.  Region Computation (with boundary area)
# ════════════════════════════════════════════════════════════════════

class RegionInfo(NamedTuple):
    idx: int
    cells: frozenset[int]
    n_bdy_faces: int
    min_cut: int
    boundary_area: int
    slack: int               # area - S  (area-law slack)
    half_slack: int          # area - 2*S  (half-bound slack)


def compute_boundary_area(
    cells: frozenset[int],
    internal_faces: list[tuple[int, int]],
) -> int:
    n_cells = len(cells)
    internal_within = sum(
        1 for c1, c2 in internal_faces
        if c1 in cells and c2 in cells
    )
    return 6 * n_cells - 2 * internal_within


def compute_regions(patch: dict, max_rc: int) -> list[RegionInfo]:
    flow_G, bnode_ids, bnode_to_cell = multi.build_flow_graph(patch)
    internal_faces = patch["internal_faces"]

    regions_raw = multi.enumerate_cell_aligned_regions(
        patch, bnode_to_cell, bnode_ids,
        max_region_cells=max_rc,
    )

    regions: list[RegionInfo] = []
    for label, idx_set in regions_raw:
        cells_str = label.strip("{}").split(",")
        cells = frozenset(
            int(s.strip().lstrip("c")) for s in cells_str if s.strip()
        )
        s = multi.compute_min_cut(flow_G, bnode_ids, idx_set)
        area = compute_boundary_area(cells, internal_faces)
        slack = area - s
        half_slack = area - 2 * s
        regions.append(RegionInfo(
            idx=len(regions), cells=cells, n_bdy_faces=len(idx_set),
            min_cut=s, boundary_area=area, slack=slack,
            half_slack=half_slack,
        ))
    return regions


# ════════════════════════════════════════════════════════════════════
#  3.  Orbit Reduction
# ════════════════════════════════════════════════════════════════════

class OrbitRep(NamedTuple):
    name: str
    min_cut: int
    count: int


def compute_orbits(regions: list[RegionInfo]) -> list[OrbitRep]:
    cut_counts = Counter(r.min_cut for r in regions)
    return [OrbitRep(f"mc{v}", v, cut_counts[v])
            for v in sorted(cut_counts)]


def orbit_for_region(r: RegionInfo, orbits: list[OrbitRep]) -> OrbitRep:
    for orb in orbits:
        if orb.min_cut == r.min_cut:
            return orb
    raise ValueError(f"No orbit for min-cut {r.min_cut}")


# ════════════════════════════════════════════════════════════════════
#  4.  Edge Curvature Classes
# ════════════════════════════════════════════════════════════════════

class EdgeClassInfo(NamedTuple):
    name: str
    valence_in_patch: int
    full_valence: int
    count: int
    kappa_twentieths: int


def compute_edge_classes(data: dict, patch: dict) -> list[EdgeClassInfo]:
    face_crossings = data["face_crossings"]
    adj_pairs = data["adj_pairs"]
    cell_center = data["cell_center"]
    p = cell_center
    patch_centers = {multi._vec_key(mat @ p)
                     for mat in patch["cells"].values()}
    valences: list[int] = []
    for fi, fj in adj_pairs:
        F_a, F_b = face_crossings[fi], face_crossings[fj]
        dih_elems = multi.enumerate_group([F_a, F_b])
        orbit_centers = {multi._vec_key(g @ p) for g in dih_elems}
        in_patch = len(orbit_centers & patch_centers)
        valences.append(in_patch)
    val_counts = Counter(valences)
    return [EdgeClassInfo(f"ev{v}", v, 5, val_counts[v], 20 - 5 * v)
            for v in sorted(val_counts)]


# ════════════════════════════════════════════════════════════════════
#  5.  Agda Naming Helpers
# ════════════════════════════════════════════════════════════════════

def region_agda_name(r: RegionInfo) -> str:
    return f"d1000r{r.idx}"


def cells_comment(r: RegionInfo) -> str:
    cs = sorted(r.cells)
    if len(cs) <= 6:
        return "{" + ",".join(f"c{c}" for c in cs) + "}"
    return "{" + ",".join(f"c{c}" for c in cs[:5]) + ",..." + "}"


# ════════════════════════════════════════════════════════════════════
#  6.  Agda Module Generators
# ════════════════════════════════════════════════════════════════════

def gen_spec(regions, orbits):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Common.Dense1000Spec where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars"); a("")
    a(GENERATED_BANNER); a("")
    a("data D1000Region : Type₀ where")
    sizes: dict[int, list] = defaultdict(list)
    for r in regions:
        sizes[len(r.cells)].append(r)
    for size in sorted(sizes):
        rs = sizes[size]
        names = [region_agda_name(r) for r in rs]
        a(f"  -- size {size}  ({len(rs)} regions)")
        for i in range(0, len(names), 10):
            a(f"  {' '.join(names[i:i+10])} : D1000Region")
    a("")
    a("data D1000OrbitRep : Type₀ where")
    a(f"  {' '.join(o.name for o in orbits)} : D1000OrbitRep")
    a("")
    a(GENERATED_BANNER); a("")
    a("classify1000 : D1000Region → D1000OrbitRep")
    for r in regions:
        orb = orbit_for_region(r, orbits)
        a(f"classify1000 {region_agda_name(r)} = {orb.name}")
    a("")
    return "\n".join(L) + "\n"


def gen_cut(orbits):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Boundary.Dense1000Cut where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense1000Spec"); a("")
    a("record D1000BdyView : Type₀ where")
    a("  field"); a("    dummy : ℚ≥0"); a("")
    a(GENERATED_BANNER); a("")
    a("S-cut-rep : D1000OrbitRep → ℚ≥0")
    for orb in orbits:
        a(f"S-cut-rep {orb.name} = {orb.min_cut}")
    a("")
    a("S-cut : D1000BdyView → D1000Region → ℚ≥0")
    a("S-cut _ r = S-cut-rep (classify1000 r)")
    a("")
    return "\n".join(L) + "\n"


def gen_chain(orbits):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Bulk.Dense1000Chain where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense1000Spec"); a("")
    a("record D1000BulkView : Type₀ where")
    a("  field"); a("    dummy : ℚ≥0"); a("")
    a(GENERATED_BANNER); a("")
    a("L-min-rep : D1000OrbitRep → ℚ≥0")
    for orb in orbits:
        a(f"L-min-rep {orb.name} = {orb.min_cut}")
    a("")
    a("L-min : D1000BulkView → D1000Region → ℚ≥0")
    a("L-min _ r = L-min-rep (classify1000 r)")
    a("")
    return "\n".join(L) + "\n"


def gen_curvature(edge_classes):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Bulk.Dense1000Curvature where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Cubical.Data.Nat  using (ℕ ; zero ; suc ; _+_ ; _·_)")
    a("open import Cubical.Data.Int")
    a("  using (ℤ ; pos ; negsuc)")
    a("  renaming (_+_ to _+ℤ_)")
    a(""); a("open import Util.Rationals")
    a(""); a(GENERATED_BANNER); a("")
    a("data D1000EdgeClass : Type₀ where")
    a(f"  {' '.join(ec.name for ec in edge_classes)} : D1000EdgeClass")
    a("")
    a("d1000EdgeCount : D1000EdgeClass → ℕ")
    for ec in edge_classes:
        a(f"d1000EdgeCount {ec.name} = {ec.count}")
    a("")
    a("d1000Kappa : D1000EdgeClass → ℚ₁₀")
    for ec in edge_classes:
        k20 = ec.kappa_twentieths
        if k20 >= 0:
            a(f"d1000Kappa {ec.name} = pos {k20}")
        else:
            a(f"d1000Kappa {ec.name} = negsuc {-k20 - 1}")
    a("")
    a("totalD1000Curvature : ℚ₁₀")
    parts = [f"{ec.count} ·₁₀ d1000Kappa {ec.name}" for ec in edge_classes]
    a(f"totalD1000Curvature = {' +₁₀ '.join(parts)}")
    a("")
    total_val = sum(ec.count * ec.kappa_twentieths for ec in edge_classes)
    exp = f"pos {total_val}" if total_val >= 0 else f"negsuc {-total_val - 1}"
    a(f"totalD1000Curvature-check : totalD1000Curvature ≡ {exp}")
    a("totalD1000Curvature-check = refl")
    a("")
    return "\n".join(L) + "\n"


def gen_obs(regions, orbits):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Bridge.Dense1000Obs where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Util.Scalars")
    a("open import Common.Dense1000Spec")
    a("open import Common.ObsPackage")
    a("open import Boundary.Dense1000Cut")
    a("open import Bulk.Dense1000Chain"); a("")
    a("d1000BdyView : D1000BdyView")
    a("d1000BdyView .D1000BdyView.dummy = 0"); a("")
    a("d1000BulkView : D1000BulkView")
    a("d1000BulkView .D1000BulkView.dummy = 0"); a("")
    a("D1000Obs∂ : ObsPackage D1000Region")
    a("D1000Obs∂ .ObsPackage.obs = S-cut d1000BdyView"); a("")
    a("D1000ObsBulk : ObsPackage D1000Region")
    a("D1000ObsBulk .ObsPackage.obs = L-min d1000BulkView"); a("")
    a(GENERATED_BANNER); a("")
    a("d1000-pointwise-rep :")
    a("  (o : D1000OrbitRep) → S-cut-rep o ≡ L-min-rep o")
    for orb in orbits:
        a(f"d1000-pointwise-rep {orb.name} = refl")
    a("")
    a("d1000-pointwise :")
    a("  (r : D1000Region) →")
    a("  S-cut d1000BdyView r ≡ L-min d1000BulkView r")
    a("d1000-pointwise r = d1000-pointwise-rep (classify1000 r)")
    a("")
    a("S∂D1000 : D1000Region → ℚ≥0")
    a("S∂D1000 = S-cut d1000BdyView"); a("")
    a("LBD1000 : D1000Region → ℚ≥0")
    a("LBD1000 = L-min d1000BulkView"); a("")
    a("d1000-obs-path : S∂D1000 ≡ LBD1000")
    a("d1000-obs-path = funExt d1000-pointwise"); a("")
    a("d1000-package-path : D1000Obs∂ ≡ D1000ObsBulk")
    a("d1000-package-path i .ObsPackage.obs = d1000-obs-path i")
    a("")
    return "\n".join(L) + "\n"


def gen_area_law(regions):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Boundary.Dense1000AreaLaw where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Cubical.Data.Nat using (ℕ ; _+_)")
    a("open import Util.Scalars")
    a("open import Common.Dense1000Spec")
    a("open import Boundary.Dense1000Cut")
    a("open import Bridge.Dense1000Obs using (d1000BdyView)")
    a(""); a(GENERATED_BANNER); a("")
    a("regionArea : D1000Region → ℚ≥0")
    for r in regions:
        a(f"regionArea {region_agda_name(r)} = {r.boundary_area}"
          f"    -- {len(r.cells)} cells")
    a("")
    a("abstract")
    a("  area-law : (r : D1000Region)"
      " → S-cut d1000BdyView r ≤ℚ regionArea r")
    prev_key = (-1, -1)
    for r in regions:
        key = (r.min_cut, r.slack)
        if key != prev_key:
            a(f"  -- S={r.min_cut}, area={r.boundary_area},"
              f" slack={r.slack}")
            prev_key = key
        a(f"  area-law {region_agda_name(r)} = {r.slack} , refl")
    a("")
    return "\n".join(L) + "\n"


def gen_half_bound(regions, achiever):
    L = []
    a = L.append
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a(""); a("module Boundary.Dense1000HalfBound where")
    a(""); a("open import Cubical.Foundations.Prelude")
    a("open import Cubical.Data.Nat using (ℕ ; _+_)")
    a("open import Cubical.Data.Sigma using (Σ-syntax)")
    a(""); a("open import Util.Scalars")
    a("open import Common.Dense1000Spec")
    a("open import Boundary.Dense1000AreaLaw using (regionArea)")
    a("open import Bridge.GenericBridge using (PatchData ; orbit-to-patch)")
    a("open import Bridge.GenericValidation using (d1000OrbitPatch)")
    a("open import Bridge.HalfBound using (HalfBoundWitness)")
    a(""); a(GENERATED_BANNER); a("")
    a("private")
    a("  pd : PatchData")
    a("  pd = orbit-to-patch d1000OrbitPatch")
    a("")
    a("  S∂ : D1000Region → ℚ≥0")
    a("  S∂ = PatchData.S∂ pd")
    a("")
    a("abstract")
    a("  half-bound-proof : (r : D1000Region)"
      " → (S∂ r +ℚ S∂ r) ≤ℚ regionArea r")
    prev_key = (-1, -1)
    for r in regions:
        key = (r.min_cut, r.half_slack)
        if key != prev_key:
            a(f"  -- S={r.min_cut}, area={r.boundary_area},"
              f" 2·S={2*r.min_cut}, slack={r.half_slack}")
            prev_key = key
        a(f"  half-bound-proof {region_agda_name(r)} = {r.half_slack} , refl")
    a("")
    ach_rn = region_agda_name(achiever)
    a(f"tight-witness :"
      f" Σ[ r ∈ D1000Region ] (S∂ r +ℚ S∂ r ≡ regionArea r)")
    a(f"tight-witness = {ach_rn} , refl")
    a("")
    a("dense1000HalfBound : HalfBoundWitness pd")
    a("dense1000HalfBound .HalfBoundWitness.area = regionArea")
    a("dense1000HalfBound .HalfBoundWitness.half-bound = half-bound-proof")
    a("dense1000HalfBound .HalfBoundWitness.tight = tight-witness")
    a("")
    return "\n".join(L) + "\n"


# ════════════════════════════════════════════════════════════════════
#  7.  File Writing
# ════════════════════════════════════════════════════════════════════

FILE_MAP = [
    ("Common/Dense1000Spec.agda",        "spec"),
    ("Boundary/Dense1000Cut.agda",       "cut"),
    ("Bulk/Dense1000Chain.agda",         "chain"),
    ("Bulk/Dense1000Curvature.agda",     "curv"),
    ("Bridge/Dense1000Obs.agda",         "obs"),
    ("Boundary/Dense1000AreaLaw.agda",   "area"),
    ("Boundary/Dense1000HalfBound.agda", "half"),
]


def write_file(path: Path, content: str, dry_run: bool) -> None:
    lines = content.count("\n")
    if dry_run:
        print(f"  [dry-run]  {path}  ({lines} lines)")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  ✓  {path}  ({lines} lines)")


# ════════════════════════════════════════════════════════════════════
#  8.  Main
# ════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Dense-1000 Cubical Agda modules "
                    "with adaptive max_region_cells for tower monotonicity")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_SRC_DIR)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--initial-max-rc", type=int, default=INITIAL_MAX_RC,
                        help=f"Starting max_region_cells (default: {INITIAL_MAX_RC})")
    args = parser.parse_args()

    print("╔════════════════════════════════════════════════════════════╗")
    print("║  Dense-1000 {4,3,5} — Formal Physics Oracle (Dense-1000)   ║")
    print("║  Adaptive max_rc + orbit reduction + area law + half-bound ║")
    print("╚════════════════════════════════════════════════════════════╝")

    # ── Step 1: Build the patch ─────────────────────────────────────
    print(f"\n  Building Dense-{MAX_CELLS} patch ...")
    t0 = time.time()
    data = build_dense1000_patch()
    patch = data["patch"]
    n_cells = len(patch["cells"])
    n_int = len(patch["internal_faces"])
    n_bdy = patch["n_boundary_faces"]
    density = 2 * n_int / max(n_cells, 1)
    print(f"  ✓  {n_cells} cells, {n_int} int.faces, "
          f"{n_bdy} bdy.faces  ({time.time()-t0:.1f}s)")

    # ── Step 2: Adaptive region enumeration ─────────────────────────
    # Try increasing max_rc until maxS >= TARGET_MAX_MINCUT
    max_rc = args.initial_max_rc
    regions = None
    max_s = 0

    while max_rc <= MAX_MAX_RC:
        print(f"\n  Enumerating regions (max_rc={max_rc}) ...")
        t0 = time.time()
        regions = compute_regions(patch, max_rc)
        elapsed = time.time() - t0
        max_s = max(r.min_cut for r in regions) if regions else 0
        print(f"  ✓  {len(regions)} regions, maxS={max_s}  ({elapsed:.1f}s)")

        if max_s >= TARGET_MAX_MINCUT:
            print(f"  ✓  maxS={max_s} ≥ target={TARGET_MAX_MINCUT}"
                  f" — monotonicity with Dense-200 achieved!")
            break
        else:
            print(f"  ✗  maxS={max_s} < target={TARGET_MAX_MINCUT}"
                  f" — increasing max_rc to {max_rc + 1}")
            max_rc += 1

    if max_s < TARGET_MAX_MINCUT:
        print(f"\n  WARNING: Could not achieve maxS ≥ {TARGET_MAX_MINCUT}"
              f" even at max_rc={MAX_MAX_RC}.")
        print(f"  Proceeding with maxS={max_s}."
              f" Tower will extend from Dense-100 (maxS=8), not Dense-200.")

    assert regions is not None

    # ── Step 3: Verify bounds ───────────────────────────────────────
    area_violations = [r for r in regions if r.slack < 0]
    half_violations = [r for r in regions if r.half_slack < 0]
    if area_violations:
        print(f"  ✗  Area law VIOLATED for {len(area_violations)} regions!")
        return
    if half_violations:
        print(f"  ✗  Half-bound VIOLATED for {len(half_violations)} regions!")
        return
    print(f"  ✓  Area law verified.  Half-bound verified.")

    # ── Step 4: Orbit reduction ─────────────────────────────────────
    orbits = compute_orbits(regions)
    reduction = len(regions) // max(len(orbits), 1)
    print(f"  ✓  {len(orbits)} orbits ({len(regions)}→{len(orbits)},"
          f" {reduction}×)")

    # ── Step 5: Edge curvature ──────────────────────────────────────
    edge_classes = compute_edge_classes(data, patch)
    print(f"  ✓  {len(edge_classes)} edge class(es)")

    # ── Step 6: Find achiever ───────────────────────────────────────
    achievers = [r for r in regions if r.half_slack == 0]
    if not achievers:
        print(f"  ✗  No half-bound achiever found (2·S < area for all).")
        return
    achiever = achievers[0]

    # ── Summary ─────────────────────────────────────────────────────
    print(f"\n  ── Patch Topology ──")
    print(f"  Cells:            {n_cells}")
    print(f"  Internal faces:   {n_int}")
    print(f"  Boundary faces:   {n_bdy}")
    print(f"  Density:          {density:.2f}")
    print(f"  max_region_cells: {max_rc}")

    cut_dist = Counter(r.min_cut for r in regions)
    size_dist = Counter(len(r.cells) for r in regions)
    half_slack_dist = Counter(r.half_slack for r in regions)

    print(f"\n  ── Region Statistics ({len(regions)} total) ──")
    print(f"  By size:")
    for sz in sorted(size_dist):
        print(f"    {sz}-cell:     {size_dist[sz]} regions")
    print(f"  By min-cut value:")
    for val in sorted(cut_dist):
        print(f"    S = {val:>2d}:       {cut_dist[val]:>5d} regions")
    print(f"  Min-cut range:  {min(cut_dist)} – {max(cut_dist)}")

    print(f"\n  ── Orbit Reduction ──")
    print(f"  Orbits: {len(orbits)}")
    for orb in orbits:
        print(f"    {orb.name} (S={orb.min_cut}): {orb.count} regions")
    print(f"  Reduction: {len(regions)} → {len(orbits)} ({reduction}×)")

    print(f"\n  ── Half-slack distribution ──")
    for k in sorted(half_slack_dist):
        print(f"    k = {k:>2d}:     {half_slack_dist[k]} regions")

    achiever_sizes = Counter(len(a.cells) for a in achievers)
    print(f"\n  ── Achievers (2·S = area): {len(achievers)} ──")
    for k, cnt in sorted(achiever_sizes.items()):
        ex = next(a for a in achievers if len(a.cells) == k)
        print(f"    k={k}: {cnt} regions (e.g. S={ex.min_cut},"
              f" area={ex.boundary_area})")

    # ── Monotonicity ────────────────────────────────────────────────
    print(f"\n  ── Monotonicity (Dense-1000 vs all previous levels) ──")
    best_pred = None
    best_pred_name = None
    for name, prev_max in sorted(PREVIOUS_LEVELS.items(),
                                  key=lambda x: x[1]):
        k = max_s - prev_max
        if k >= 0:
            print(f"  ✓  {name} (maxS={prev_max}) ≤ Dense-1000"
                  f" (maxS={max_s})   witness: ({k} , refl)")
            if best_pred is None or prev_max > best_pred:
                best_pred = prev_max
                best_pred_name = name
        else:
            print(f"  ✗  {name} (maxS={prev_max}) > Dense-1000"
                  f" (maxS={max_s})   (decrease by {-k})")

    if best_pred is not None:
        witness_k = max_s - best_pred
        print(f"\n  Best predecessor for tower: {best_pred_name}"
              f" (maxS={best_pred})")
        print(f"  Monotonicity witness: ({witness_k} , refl)")
    else:
        print(f"\n  No valid predecessor found!")

    print(f"\n  ── Edge Curvature ──")
    for ec in edge_classes:
        k = ec.kappa_twentieths
        tag = " ← hyperbolic" if k < 0 else ""
        print(f"    v={ec.valence_in_patch} (×{ec.count}): κ₂₀={k}{tag}")

    # ── Step 7: Generate Agda files ─────────────────────────────────
    src_dir = args.output_dir.resolve()
    print(f"\n  Output directory: {src_dir}")
    if args.dry_run:
        print("  [DRY RUN]\n")
    print()

    generators = {
        "spec":  lambda: gen_spec(regions, orbits),
        "cut":   lambda: gen_cut(orbits),
        "chain": lambda: gen_chain(orbits),
        "curv":  lambda: gen_curvature(edge_classes),
        "obs":   lambda: gen_obs(regions, orbits),
        "area":  lambda: gen_area_law(regions),
        "half":  lambda: gen_half_bound(regions, achiever),
    }

    total_lines = 0
    for rel_path, gen_key in FILE_MAP:
        content = generators[gen_key]()
        write_file(src_dir / rel_path, content, args.dry_run)
        total_lines += content.count("\n")

    action = "would generate" if args.dry_run else "generated"
    print(f"\n  ── {action} {len(FILE_MAP)} files,"
          f" ~{total_lines} lines total ──")

    print(f"\n  D1000Region constructors:     {len(regions)}")
    print(f"  D1000OrbitRep constructors:    {len(orbits)}")
    print(f"  classify1000 clauses:          {len(regions)}")
    print(f"  Pointwise-rep refl proofs:     {len(orbits)}")
    print(f"  AreaLaw abstract proofs:       {len(regions)}")
    print(f"  HalfBound abstract proofs:     {len(regions)}")
    print(f"  Achievers (2·S = area):        {len(achievers)}")
    print(f"  Max min-cut:                   {max_s}")
    print(f"  max_region_cells used:         {max_rc}")

    if best_pred_name:
        print(f"\n  ── Tower Registration ──")
        print(f"  Best predecessor: {best_pred_name} (maxS={best_pred})")
        print(f"  Dense-1000 maxS:  {max_s}")
        print(f"  Witness: ({max_s - best_pred} , refl)")
        print(f"""
  To register in Bridge/SchematicTower.agda:

    open import Common.Dense1000Spec
    import Boundary.Dense1000Cut as D1000Cut
    import Bulk.Dense1000Chain   as D1000Chain
    open import Bridge.Dense1000Obs using (d1000-pointwise-rep)

    d1000OrbitPatch : OrbitReducedPatch
    d1000OrbitPatch .OrbitReducedPatch.RegionTy  = D1000Region
    d1000OrbitPatch .OrbitReducedPatch.OrbitTy   = D1000OrbitRep
    d1000OrbitPatch .OrbitReducedPatch.classify  = classify1000
    d1000OrbitPatch .OrbitReducedPatch.S-rep     = D1000Cut.S-cut-rep
    d1000OrbitPatch .OrbitReducedPatch.L-rep     = D1000Chain.L-min-rep
    d1000OrbitPatch .OrbitReducedPatch.rep-agree = d1000-pointwise-rep

    d1000-tower-level : TowerLevel
    d1000-tower-level = mkTowerLevel d1000OrbitPatch {max_s}

    -- Monotonicity: extends from {best_pred_name} (maxS={best_pred})
    -- Witness: ({max_s - best_pred} , refl)
""")


if __name__ == "__main__":
    main()