#!/usr/bin/env python3
"""
17_generate_half_bound.py — §15.11 Phase A: Per-Instance HalfBound Witnesses

Generates Cubical Agda modules instantiating  HalfBoundWitness  (from
src/Bridge/HalfBound.agda) for the Dense-100 and Dense-200 patches of
the {4,3,5} hyperbolic honeycomb.

For each region r:
  half-slack = area(r) - 2 * S(r)    (must be ≥ 0)
  emit:  half-bound-proof r = half-slack , refl

Also identifies a concrete "tight" achiever region where 2·S = area,
needed for the  tight  field of HalfBoundWitness.

Generated modules:
  src/Boundary/Dense100HalfBound.agda   — 717 abstract (k, refl) proofs
  src/Boundary/Dense200HalfBound.agda   — 1246 abstract (k, refl) proofs

Each module instantiates  HalfBoundWitness pd  where  pd  is the
PatchData from  Bridge/GenericValidation.agda , consuming:
  • regionArea from the corresponding AreaLaw module
  • S∂ from the PatchData (= S-cut-rep ∘ classify)

The strengthened bound  2·S ≤ area  replaces the weaker  S ≤ area
from Dense100AreaLaw / Dense200AreaLaw, and eliminates the need for
constructive reals in the entropy-area relationship (see §15.11 of
docs/10-frontier.md).

Usage (from repository root):
  python3 sim/prototyping/17_generate_half_bound.py
  python3 sim/prototyping/17_generate_half_bound.py --dry-run
  python3 sim/prototyping/17_generate_half_bound.py --output-dir /path/to/src

Dependencies:  numpy, networkx

Reference:
  docs/10-frontier.md §15.11  (Phase A: Per-Instance HalfBound Witnesses)
  src/Bridge/HalfBound.agda   (HalfBoundWitness record, from-two-cuts)
  sim/prototyping/11_generate_area_law.py   (area-law pattern)
  sim/prototyping/15_discrete_bekenstein_hawking.py  (proof + verification)
"""

from __future__ import annotations

import argparse
import importlib
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import NamedTuple

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

try:
    multi = importlib.import_module("07_honeycomb_3d_multiStrategy")
except ModuleNotFoundError:
    sys.exit(
        "ERROR: Could not import 07_honeycomb_3d_multiStrategy.py.\n"
        "       Run this script from the repository root:\n"
        "         python3 sim/prototyping/17_generate_half_bound.py"
    )

try:
    import numpy as np
    import networkx as nx
except ImportError:
    sys.exit("ERROR: numpy and networkx are required.  "
             "pip install numpy networkx")

DEFAULT_SRC_DIR = SCRIPT_DIR.parent.parent / "src"

GENERATED_BANNER = (
    "--  Generated by sim/prototyping/17_generate_half_bound.py\n"
    "--  Do not edit by hand.  Regenerate with:\n"
    "--    python3 sim/prototyping/17_generate_half_bound.py"
)


# ════════════════════════════════════════════════════════════════════
#  1.  Data Structures
# ════════════════════════════════════════════════════════════════════

class HalfBoundDatum(NamedTuple):
    """Per-region data for the half-bound witness."""
    idx: int
    cells: frozenset[int]
    min_cut: int         # S(A)
    boundary_area: int   # area(A) = 6k − 2·|internal faces within A|
    half_slack: int      # area(A) − 2·S(A)   (must be ≥ 0)


# ════════════════════════════════════════════════════════════════════
#  2.  Patch Building and Region Computation
# ════════════════════════════════════════════════════════════════════

MAX_REGION_CELLS = 5


def build_dense_patch(max_cells: int) -> dict:
    """Build a Dense-N patch using the {4,3,5} greedy strategy."""
    G = multi.build_gram_matrix()
    refls = multi.build_reflections(G)
    multi.validate_reflections(G, refls)
    cell_center = multi.find_cell_center(G)
    stab = multi.enumerate_group(refls[:3], expected=48)
    face_crossings = multi.find_face_crossings(refls, stab, G)
    patch = multi.build_patch_dense(
        face_crossings, cell_center, max_cells,
        name=f"Dense-{max_cells}")
    return patch


def compute_boundary_area(
    cells: frozenset[int],
    internal_faces: list[tuple[int, int]],
) -> int:
    """area(A) = 6·|A| − 2·|{shared faces between two cells in A}|"""
    internal_within = sum(
        1 for c1, c2 in internal_faces
        if c1 in cells and c2 in cells
    )
    return 6 * len(cells) - 2 * internal_within


def compute_half_bound_data(patch: dict) -> list[HalfBoundDatum]:
    """
    Enumerate all cell-aligned boundary regions, compute min-cuts
    and boundary areas, and derive half-bound slack values.
    """
    flow_G, bnode_ids, bnode_to_cell = multi.build_flow_graph(patch)
    internal_faces = patch["internal_faces"]

    regions_raw = multi.enumerate_cell_aligned_regions(
        patch, bnode_to_cell, bnode_ids,
        max_region_cells=MAX_REGION_CELLS,
    )

    data: list[HalfBoundDatum] = []
    for label, idx_set in regions_raw:
        cells_str = label.strip("{}").split(",")
        cells = frozenset(
            int(s.strip().lstrip("c")) for s in cells_str if s.strip()
        )
        s = multi.compute_min_cut(flow_G, bnode_ids, idx_set)
        area = compute_boundary_area(cells, internal_faces)
        half_slack = area - 2 * s
        data.append(HalfBoundDatum(
            idx=len(data),
            cells=cells,
            min_cut=s,
            boundary_area=area,
            half_slack=half_slack,
        ))

    return data


# ════════════════════════════════════════════════════════════════════
#  3.  Agda Naming Helpers
# ════════════════════════════════════════════════════════════════════

def region_name(prefix: str, d: HalfBoundDatum) -> str:
    """Agda constructor name for a region: d100r0, d200r0, ..."""
    return f"{prefix}r{d.idx}"


# ════════════════════════════════════════════════════════════════════
#  4.  Agda Module Generator
# ════════════════════════════════════════════════════════════════════

def generate_half_bound_module(
    n_cells: int,
    data: list[HalfBoundDatum],
    achiever: HalfBoundDatum,
) -> str:
    """
    Generate a  Boundary/DenseNHalfBound.agda  module.

    The module instantiates  HalfBoundWitness pd  where  pd  is the
    PatchData for the Dense-N patch (from GenericValidation), using
    regionArea from the corresponding AreaLaw module.
    """
    # Determine naming prefixes based on cell count
    N = n_cells
    prefix = f"d{N}"       # d100, d200
    mod_N = str(N)          # "100", "200"

    L: list[str] = []
    a = L.append

    # ── Header ──────────────────────────────────────────────────────
    a("{-# OPTIONS --cubical --safe --guardedness #-}")
    a("")
    a(f"module Boundary.Dense{mod_N}HalfBound where")
    a("")
    a("open import Cubical.Foundations.Prelude")
    a("open import Cubical.Data.Nat using (ℕ ; _+_)")
    a("open import Cubical.Data.Sigma using (Σ-syntax)")
    a("")
    a("open import Util.Scalars")
    a(f"open import Common.Dense{mod_N}Spec")
    a(f"open import Boundary.Dense{mod_N}AreaLaw using (regionArea)")
    a("open import Bridge.GenericBridge using (PatchData ; orbit-to-patch)")
    a(f"open import Bridge.GenericValidation using (d{mod_N}OrbitPatch)")
    a("open import Bridge.HalfBound using (HalfBoundWitness)")
    a("")
    a(GENERATED_BANNER)
    a("")

    # ── PatchData and S∂ shorthand ──────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a(f"--  PatchData for the Dense-{mod_N} patch")
    a("-- ═══════════════════════════════════════════════════════════")
    a("")
    a("private")
    a("  pd : PatchData")
    a(f"  pd = orbit-to-patch d{mod_N}OrbitPatch")
    a("")
    a(f"  S∂ : D{mod_N}Region → ℚ≥0")
    a("  S∂ = PatchData.S∂ pd")
    a("")

    # ── Half-bound proof (abstract) ─────────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a(f"--  half-bound-proof — 2·S(A) ≤ area(A)  ({len(data)} cases)")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  The discrete Bekenstein–Hawking bound:  S(A) ≤ area(A)/2.")
    a("--  Stated as  (S∂ r + S∂ r) ≤ℚ regionArea r  to avoid")
    a("--  division in ℕ.")
    a("--")
    a("--  Each witness  (k , refl)  type-checks because")
    a("--  k + (S∂ r + S∂ r) reduces judgmentally to regionArea r")
    a("--  via ℕ addition on closed numerals.")
    a("--")
    a("--  Wrapped in  abstract  so downstream modules never")
    a("--  re-unfold the proof.  Since  _≤ℚ_  is propositional,")
    a("--  the abstract barrier does not damage the Univalence bridge.")
    a("--")
    a(GENERATED_BANNER)
    a("")
    a("abstract")
    a(f"  half-bound-proof : (r : D{mod_N}Region)"
      f" → (S∂ r +ℚ S∂ r) ≤ℚ regionArea r")

    # Group by (min_cut, half_slack) for readability
    prev_key = (-1, -1)
    for d in data:
        key = (d.min_cut, d.half_slack)
        if key != prev_key:
            a(f"  -- S={d.min_cut}, area={d.boundary_area},"
              f" 2·S={2*d.min_cut}, slack={d.half_slack}")
            prev_key = key
        rn = region_name(prefix, d)
        a(f"  half-bound-proof {rn} = {d.half_slack} , refl")

    a("")

    # ── Tight witness ───────────────────────────────────────────────
    ach_rn = region_name(prefix, achiever)
    a("-- ═══════════════════════════════════════════════════════════")
    a("--  tight-witness — A region achieving 2·S = area")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a(f"--  {ach_rn}: S={achiever.min_cut}, area={achiever.boundary_area},"
      f" 2·{achiever.min_cut}={2*achiever.min_cut}={achiever.boundary_area}")
    a(f"--  This is a {len(achiever.cells)}-cell region with"
      f" n_cross = n_bdy = {achiever.boundary_area // 2}.")
    a("--")
    a("")
    a(f"tight-witness :"
      f" Σ[ r ∈ D{mod_N}Region ] (S∂ r +ℚ S∂ r ≡ regionArea r)")
    a(f"tight-witness = {ach_rn} , refl")
    a("")

    # ── HalfBoundWitness instantiation ──────────────────────────────
    a("-- ═══════════════════════════════════════════════════════════")
    a(f"--  dense{mod_N}HalfBound — The complete HalfBoundWitness")
    a("-- ═══════════════════════════════════════════════════════════")
    a("--")
    a("--  Packages the area function, the abstract half-bound proof,")
    a("--  and the tight achiever witness into a single record.")
    a("--  This is the per-instance deliverable from §15.11 Phase A.")
    a("--")
    a("")
    a(f"dense{mod_N}HalfBound : HalfBoundWitness pd")
    a(f"dense{mod_N}HalfBound .HalfBoundWitness.area = regionArea")
    a(f"dense{mod_N}HalfBound .HalfBoundWitness.half-bound"
      f" = half-bound-proof")
    a(f"dense{mod_N}HalfBound .HalfBoundWitness.tight = tight-witness")
    a("")

    return "\n".join(L) + "\n"


# ════════════════════════════════════════════════════════════════════
#  5.  Verification and Summary
# ════════════════════════════════════════════════════════════════════

def verify_and_summarize(
    n_cells: int,
    data: list[HalfBoundDatum],
) -> tuple[bool, HalfBoundDatum | None]:
    """
    Verify the half-bound holds for all regions and find an achiever.

    Returns (all_ok, achiever_or_None).
    """
    violations = [d for d in data if d.half_slack < 0]
    achievers = [d for d in data if d.half_slack == 0]

    print(f"\n  ── Dense-{n_cells} Half-Bound Statistics"
          f" ({len(data)} regions) ──")

    slack_dist = Counter(d.half_slack for d in data)
    print(f"  Half-slack distribution (area − 2·S):")
    for k in sorted(slack_dist):
        print(f"    k = {k:>2d}:  {slack_dist[k]:>5d} regions")

    min_slack = min(d.half_slack for d in data)
    max_slack = max(d.half_slack for d in data)
    mean_slack = sum(d.half_slack for d in data) / len(data)
    print(f"  Slack range:  {min_slack} – {max_slack}  "
          f"(mean {mean_slack:.1f})")

    if violations:
        print(f"\n  ✗  {len(violations)} VIOLATIONS of 2·S ≤ area!")
        for v in violations[:5]:
            print(f"      idx={v.idx}: S={v.min_cut}, area={v.boundary_area},"
                  f" 2·S={2*v.min_cut}, slack={v.half_slack}")
        return False, None

    print(f"  ✓  Half-bound 2·S ≤ area verified for all"
          f" {len(data)} regions.")

    if achievers:
        ach = achievers[0]
        n_ach = len(achievers)
        size_dist = Counter(len(a.cells) for a in achievers)
        print(f"  Achievers (2·S = area): {n_ach} regions")
        for k, cnt in sorted(size_dist.items()):
            # Find an example at this size
            ex = next(a for a in achievers if len(a.cells) == k)
            print(f"    k={k} cells: {cnt} regions  "
                  f"(e.g. S={ex.min_cut}, area={ex.boundary_area})")
        return True, ach
    else:
        print(f"  ✗  No achiever found (2·S < area for all regions).")
        print(f"     Cannot populate the 'tight' field.")
        return False, None


# ════════════════════════════════════════════════════════════════════
#  6.  File Writing
# ════════════════════════════════════════════════════════════════════

def write_file(path: Path, content: str, dry_run: bool) -> None:
    """Write content to path, creating parent directories as needed."""
    lines = content.count("\n")
    if dry_run:
        print(f"  [dry-run]  {path}  ({lines} lines)")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  ✓  {path}  ({lines} lines)")


# ════════════════════════════════════════════════════════════════════
#  7.  Main
# ════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate HalfBoundWitness Agda modules for "
                    "Dense-100 and Dense-200 patches (§15.11 Phase A)")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_SRC_DIR,
                        help="Root source directory "
                             "(default: ../../src relative to script)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Compute and verify without writing files")
    args = parser.parse_args()

    print("╔═══════════════════════════════════════════════════════════╗")
    print("║  §15.11 Phase A:  Per-Instance HalfBound Witnesses       ║")
    print("║  2·S(A) ≤ area(A)  — Dense-100 and Dense-200 patches    ║")
    print("╚═══════════════════════════════════════════════════════════╝")

    src_dir = args.output_dir.resolve()
    targets = [100, 200]
    all_ok = True

    for n_cells in targets:
        # ── Build patch ─────────────────────────────────────────────
        print(f"\n  Building Dense-{n_cells} patch ...", flush=True)
        t0 = time.time()
        patch = build_dense_patch(n_cells)
        nc = len(patch["cells"])
        nf = len(patch["internal_faces"])
        nb = patch["n_boundary_faces"]
        print(f"  ✓  {nc} cells, {nf} internal faces, {nb} boundary faces."
              f"  ({time.time() - t0:.1f}s)")

        # ── Compute region data ─────────────────────────────────────
        print(f"  Computing half-bound data for all regions "
              f"(max_rc={MAX_REGION_CELLS}) ...", flush=True)
        t0 = time.time()
        data = compute_half_bound_data(patch)
        print(f"  ✓  {len(data)} regions computed.  ({time.time() - t0:.1f}s)")

        if not data:
            print(f"  ✗  No regions found for Dense-{n_cells}!")
            all_ok = False
            continue

        # ── Verify and find achiever ────────────────────────────────
        ok, achiever = verify_and_summarize(n_cells, data)
        if not ok or achiever is None:
            all_ok = False
            print(f"  ✗  Cannot generate module for Dense-{n_cells}.")
            continue

        # ── Generate Agda module ────────────────────────────────────
        content = generate_half_bound_module(n_cells, data, achiever)
        out_path = src_dir / "Boundary" / f"Dense{n_cells}HalfBound.agda"
        print(f"\n  Output: {out_path}")
        write_file(out_path, content, args.dry_run)

    # ── Final report ────────────────────────────────────────────────
    print(f"\n{'═' * 60}")
    if all_ok:
        action = "would generate" if args.dry_run else "generated"
        print(f"  ✓  Successfully {action} {len(targets)} modules.")
    else:
        print(f"  ✗  Some modules could not be generated.")

    print(f"""
  Each generated module provides a  HalfBoundWitness pd  containing:
    • area       :  regionArea  (imported from DenseNAreaLaw)
    • half-bound :  abstract proof,  (k , refl) per region
    • tight      :  concrete achiever where 2·S = area

  The strengthened bound  2·S ≤ area  replaces the weaker  S ≤ area
  from the AreaLaw modules.  Together with the generic  from-two-cuts
  lemma in  Bridge/HalfBound.agda , this establishes:

    1/(4G) = 1/2  in bond-dimension-1 units

  as an exact discrete constant — the discrete Newton's constant.

  This eliminates the constructive-reals wall for the entropy-area
  relationship: no convergence argument needed, just refl on closed
  ℕ terms at every resolution level.

  Next steps:
    1. Load generated modules in Agda to verify they type-check.
    2. Extend  Bridge/SchematicTower.agda  to carry HalfBoundWitness
       at each tower level.
    3. Update  Bridge/Dense100Thermodynamics.agda  to use the
       strengthened bound.
""")


if __name__ == "__main__":
    main()