{-# OPTIONS --cubical --safe --guardedness #-}

module Common.Honeycomb3DSpec where

open import Cubical.Foundations.Prelude
open import Util.Scalars

-- ═══════════════════════════════════════════════════════════
--  H3Region — Cell-aligned boundary regions of the
--  {4,3,5} 3D star patch (connected subsets of bdy cells)
-- ═══════════════════════════════════════════════════════════
--
--  The patch is the BFS neighborhood of a central cube in
--  the {4,3,5} hyperbolic honeycomb (5 cubes per edge).
--  Boundary cells = cells with at least one exposed face.
--  Regions = connected subsets of boundary cells.
--
--  Generated by sim/prototyping/06_generate_honeycomb_3d.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/06_generate_honeycomb_3d.py

data H3Region : Type₀ where
  -- size 1  (26 regions)
  h3r0 h3r1 h3r2 h3r3 h3r4 h3r5 h3r6 h3r7 h3r8 h3r9 : H3Region
  h3r10 h3r11 h3r12 h3r13 h3r14 h3r15 h3r16 h3r17 h3r18 h3r19 : H3Region
  h3r20 h3r21 h3r22 h3r23 h3r24 h3r25 : H3Region

