{-# OPTIONS --cubical --safe --guardedness #-}

module Common.Layer54d4Spec where

open import Cubical.Foundations.Prelude
open import Util.Scalars

-- Layer54d4Region — Cell-aligned boundary regions of the
-- {5,4} tiling patch at BFS depth 4
-- 105 regions, 2 orbit representatives
--  Generated by sim/prototyping/13_generate_layerN.py --depth 4
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 4

data Layer54d4Region : Type₀ where
  -- size 1  (105 regions)
  l4r0 l4r1 l4r2 l4r3 l4r4 l4r5 l4r6 l4r7 l4r8 l4r9 : Layer54d4Region
  l4r10 l4r11 l4r12 l4r13 l4r14 l4r15 l4r16 l4r17 l4r18 l4r19 : Layer54d4Region
  l4r20 l4r21 l4r22 l4r23 l4r24 l4r25 l4r26 l4r27 l4r28 l4r29 : Layer54d4Region
  l4r30 l4r31 l4r32 l4r33 l4r34 l4r35 l4r36 l4r37 l4r38 l4r39 : Layer54d4Region
  l4r40 l4r41 l4r42 l4r43 l4r44 l4r45 l4r46 l4r47 l4r48 l4r49 : Layer54d4Region
  l4r50 l4r51 l4r52 l4r53 l4r54 l4r55 l4r56 l4r57 l4r58 l4r59 : Layer54d4Region
  l4r60 l4r61 l4r62 l4r63 l4r64 l4r65 l4r66 l4r67 l4r68 l4r69 : Layer54d4Region
  l4r70 l4r71 l4r72 l4r73 l4r74 l4r75 l4r76 l4r77 l4r78 l4r79 : Layer54d4Region
  l4r80 l4r81 l4r82 l4r83 l4r84 l4r85 l4r86 l4r87 l4r88 l4r89 : Layer54d4Region
  l4r90 l4r91 l4r92 l4r93 l4r94 l4r95 l4r96 l4r97 l4r98 l4r99 : Layer54d4Region
  l4r100 l4r101 l4r102 l4r103 l4r104 : Layer54d4Region

-- Layer54d4OrbitRep — Orbit representatives by min-cut value
-- Orbit decomposition:
--   mc1  (S = 1):  65 regions
--   mc2  (S = 2):  40 regions
--  Generated by sim/prototyping/13_generate_layerN.py --depth 4
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 4

data Layer54d4OrbitRep : Type₀ where
  mc1 mc2 : Layer54d4OrbitRep

-- classifyLayer54d4 — Map each region to its orbit representative
--  Generated by sim/prototyping/13_generate_layerN.py --depth 4
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 4

classifyLayer54d4 : Layer54d4Region → Layer54d4OrbitRep
classifyLayer54d4 l4r0 = mc2
classifyLayer54d4 l4r1 = mc1
classifyLayer54d4 l4r2 = mc2
classifyLayer54d4 l4r3 = mc2
classifyLayer54d4 l4r4 = mc1
classifyLayer54d4 l4r5 = mc2
classifyLayer54d4 l4r6 = mc1
classifyLayer54d4 l4r7 = mc1
classifyLayer54d4 l4r8 = mc2
classifyLayer54d4 l4r9 = mc2
classifyLayer54d4 l4r10 = mc1
classifyLayer54d4 l4r11 = mc1
classifyLayer54d4 l4r12 = mc1
classifyLayer54d4 l4r13 = mc2
classifyLayer54d4 l4r14 = mc2
classifyLayer54d4 l4r15 = mc1
classifyLayer54d4 l4r16 = mc2
classifyLayer54d4 l4r17 = mc1
classifyLayer54d4 l4r18 = mc1
classifyLayer54d4 l4r19 = mc1
classifyLayer54d4 l4r20 = mc1
classifyLayer54d4 l4r21 = mc2
classifyLayer54d4 l4r22 = mc1
classifyLayer54d4 l4r23 = mc2
classifyLayer54d4 l4r24 = mc2
classifyLayer54d4 l4r25 = mc1
classifyLayer54d4 l4r26 = mc1
classifyLayer54d4 l4r27 = mc1
classifyLayer54d4 l4r28 = mc1
classifyLayer54d4 l4r29 = mc1
classifyLayer54d4 l4r30 = mc2
classifyLayer54d4 l4r31 = mc1
classifyLayer54d4 l4r32 = mc1
classifyLayer54d4 l4r33 = mc1
classifyLayer54d4 l4r34 = mc2
classifyLayer54d4 l4r35 = mc2
classifyLayer54d4 l4r36 = mc1
classifyLayer54d4 l4r37 = mc2
classifyLayer54d4 l4r38 = mc2
classifyLayer54d4 l4r39 = mc1
classifyLayer54d4 l4r40 = mc1
classifyLayer54d4 l4r41 = mc1
classifyLayer54d4 l4r42 = mc2
classifyLayer54d4 l4r43 = mc1
classifyLayer54d4 l4r44 = mc2
classifyLayer54d4 l4r45 = mc2
classifyLayer54d4 l4r46 = mc1
classifyLayer54d4 l4r47 = mc1
classifyLayer54d4 l4r48 = mc1
classifyLayer54d4 l4r49 = mc1
classifyLayer54d4 l4r50 = mc1
classifyLayer54d4 l4r51 = mc1
classifyLayer54d4 l4r52 = mc2
classifyLayer54d4 l4r53 = mc2
classifyLayer54d4 l4r54 = mc1
classifyLayer54d4 l4r55 = mc2
classifyLayer54d4 l4r56 = mc1
classifyLayer54d4 l4r57 = mc1
classifyLayer54d4 l4r58 = mc2
classifyLayer54d4 l4r59 = mc1
classifyLayer54d4 l4r60 = mc1
classifyLayer54d4 l4r61 = mc1
classifyLayer54d4 l4r62 = mc1
classifyLayer54d4 l4r63 = mc2
classifyLayer54d4 l4r64 = mc1
classifyLayer54d4 l4r65 = mc2
classifyLayer54d4 l4r66 = mc2
classifyLayer54d4 l4r67 = mc1
classifyLayer54d4 l4r68 = mc2
classifyLayer54d4 l4r69 = mc1
classifyLayer54d4 l4r70 = mc1
classifyLayer54d4 l4r71 = mc2
classifyLayer54d4 l4r72 = mc1
classifyLayer54d4 l4r73 = mc2
classifyLayer54d4 l4r74 = mc1
classifyLayer54d4 l4r75 = mc1
classifyLayer54d4 l4r76 = mc2
classifyLayer54d4 l4r77 = mc1
classifyLayer54d4 l4r78 = mc1
classifyLayer54d4 l4r79 = mc1
classifyLayer54d4 l4r80 = mc2
classifyLayer54d4 l4r81 = mc1
classifyLayer54d4 l4r82 = mc1
classifyLayer54d4 l4r83 = mc1
classifyLayer54d4 l4r84 = mc2
classifyLayer54d4 l4r85 = mc2
classifyLayer54d4 l4r86 = mc1
classifyLayer54d4 l4r87 = mc2
classifyLayer54d4 l4r88 = mc1
classifyLayer54d4 l4r89 = mc1
classifyLayer54d4 l4r90 = mc1
classifyLayer54d4 l4r91 = mc2
classifyLayer54d4 l4r92 = mc2
classifyLayer54d4 l4r93 = mc2
classifyLayer54d4 l4r94 = mc1
classifyLayer54d4 l4r95 = mc1
classifyLayer54d4 l4r96 = mc1
classifyLayer54d4 l4r97 = mc2
classifyLayer54d4 l4r98 = mc1
classifyLayer54d4 l4r99 = mc1
classifyLayer54d4 l4r100 = mc1
classifyLayer54d4 l4r101 = mc1
classifyLayer54d4 l4r102 = mc2
classifyLayer54d4 l4r103 = mc1
classifyLayer54d4 l4r104 = mc1

