{-# OPTIONS --cubical --safe --guardedness #-}

module Common.Layer54d5Spec where

open import Cubical.Foundations.Prelude
open import Util.Scalars

-- Layer54d5Region — Cell-aligned boundary regions of the
-- {5,4} tiling patch at BFS depth 5
-- 275 regions, 2 orbit representatives
--  Generated by sim/prototyping/13_generate_layerN.py --depth 5
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 5

data Layer54d5Region : Type₀ where
  -- size 1  (275 regions)
  l5r0 l5r1 l5r2 l5r3 l5r4 l5r5 l5r6 l5r7 l5r8 l5r9 : Layer54d5Region
  l5r10 l5r11 l5r12 l5r13 l5r14 l5r15 l5r16 l5r17 l5r18 l5r19 : Layer54d5Region
  l5r20 l5r21 l5r22 l5r23 l5r24 l5r25 l5r26 l5r27 l5r28 l5r29 : Layer54d5Region
  l5r30 l5r31 l5r32 l5r33 l5r34 l5r35 l5r36 l5r37 l5r38 l5r39 : Layer54d5Region
  l5r40 l5r41 l5r42 l5r43 l5r44 l5r45 l5r46 l5r47 l5r48 l5r49 : Layer54d5Region
  l5r50 l5r51 l5r52 l5r53 l5r54 l5r55 l5r56 l5r57 l5r58 l5r59 : Layer54d5Region
  l5r60 l5r61 l5r62 l5r63 l5r64 l5r65 l5r66 l5r67 l5r68 l5r69 : Layer54d5Region
  l5r70 l5r71 l5r72 l5r73 l5r74 l5r75 l5r76 l5r77 l5r78 l5r79 : Layer54d5Region
  l5r80 l5r81 l5r82 l5r83 l5r84 l5r85 l5r86 l5r87 l5r88 l5r89 : Layer54d5Region
  l5r90 l5r91 l5r92 l5r93 l5r94 l5r95 l5r96 l5r97 l5r98 l5r99 : Layer54d5Region
  l5r100 l5r101 l5r102 l5r103 l5r104 l5r105 l5r106 l5r107 l5r108 l5r109 : Layer54d5Region
  l5r110 l5r111 l5r112 l5r113 l5r114 l5r115 l5r116 l5r117 l5r118 l5r119 : Layer54d5Region
  l5r120 l5r121 l5r122 l5r123 l5r124 l5r125 l5r126 l5r127 l5r128 l5r129 : Layer54d5Region
  l5r130 l5r131 l5r132 l5r133 l5r134 l5r135 l5r136 l5r137 l5r138 l5r139 : Layer54d5Region
  l5r140 l5r141 l5r142 l5r143 l5r144 l5r145 l5r146 l5r147 l5r148 l5r149 : Layer54d5Region
  l5r150 l5r151 l5r152 l5r153 l5r154 l5r155 l5r156 l5r157 l5r158 l5r159 : Layer54d5Region
  l5r160 l5r161 l5r162 l5r163 l5r164 l5r165 l5r166 l5r167 l5r168 l5r169 : Layer54d5Region
  l5r170 l5r171 l5r172 l5r173 l5r174 l5r175 l5r176 l5r177 l5r178 l5r179 : Layer54d5Region
  l5r180 l5r181 l5r182 l5r183 l5r184 l5r185 l5r186 l5r187 l5r188 l5r189 : Layer54d5Region
  l5r190 l5r191 l5r192 l5r193 l5r194 l5r195 l5r196 l5r197 l5r198 l5r199 : Layer54d5Region
  l5r200 l5r201 l5r202 l5r203 l5r204 l5r205 l5r206 l5r207 l5r208 l5r209 : Layer54d5Region
  l5r210 l5r211 l5r212 l5r213 l5r214 l5r215 l5r216 l5r217 l5r218 l5r219 : Layer54d5Region
  l5r220 l5r221 l5r222 l5r223 l5r224 l5r225 l5r226 l5r227 l5r228 l5r229 : Layer54d5Region
  l5r230 l5r231 l5r232 l5r233 l5r234 l5r235 l5r236 l5r237 l5r238 l5r239 : Layer54d5Region
  l5r240 l5r241 l5r242 l5r243 l5r244 l5r245 l5r246 l5r247 l5r248 l5r249 : Layer54d5Region
  l5r250 l5r251 l5r252 l5r253 l5r254 l5r255 l5r256 l5r257 l5r258 l5r259 : Layer54d5Region
  l5r260 l5r261 l5r262 l5r263 l5r264 l5r265 l5r266 l5r267 l5r268 l5r269 : Layer54d5Region
  l5r270 l5r271 l5r272 l5r273 l5r274 : Layer54d5Region

-- Layer54d5OrbitRep — Orbit representatives by min-cut value
-- Orbit decomposition:
--   mc1  (S = 1):  170 regions
--   mc2  (S = 2):  105 regions
--  Generated by sim/prototyping/13_generate_layerN.py --depth 5
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 5

data Layer54d5OrbitRep : Type₀ where
  mc1 mc2 : Layer54d5OrbitRep

-- classifyLayer54d5 — Map each region to its orbit representative
--  Generated by sim/prototyping/13_generate_layerN.py --depth 5
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 5

classifyLayer54d5 : Layer54d5Region → Layer54d5OrbitRep
classifyLayer54d5 l5r0 = mc2
classifyLayer54d5 l5r1 = mc2
classifyLayer54d5 l5r2 = mc1
classifyLayer54d5 l5r3 = mc1
classifyLayer54d5 l5r4 = mc1
classifyLayer54d5 l5r5 = mc2
classifyLayer54d5 l5r6 = mc2
classifyLayer54d5 l5r7 = mc1
classifyLayer54d5 l5r8 = mc2
classifyLayer54d5 l5r9 = mc2
classifyLayer54d5 l5r10 = mc1
classifyLayer54d5 l5r11 = mc1
classifyLayer54d5 l5r12 = mc1
classifyLayer54d5 l5r13 = mc2
classifyLayer54d5 l5r14 = mc1
classifyLayer54d5 l5r15 = mc2
classifyLayer54d5 l5r16 = mc2
classifyLayer54d5 l5r17 = mc1
classifyLayer54d5 l5r18 = mc1
classifyLayer54d5 l5r19 = mc1
classifyLayer54d5 l5r20 = mc1
classifyLayer54d5 l5r21 = mc2
classifyLayer54d5 l5r22 = mc1
classifyLayer54d5 l5r23 = mc2
classifyLayer54d5 l5r24 = mc2
classifyLayer54d5 l5r25 = mc1
classifyLayer54d5 l5r26 = mc2
classifyLayer54d5 l5r27 = mc1
classifyLayer54d5 l5r28 = mc1
classifyLayer54d5 l5r29 = mc2
classifyLayer54d5 l5r30 = mc1
classifyLayer54d5 l5r31 = mc1
classifyLayer54d5 l5r32 = mc1
classifyLayer54d5 l5r33 = mc1
classifyLayer54d5 l5r34 = mc2
classifyLayer54d5 l5r35 = mc1
classifyLayer54d5 l5r36 = mc2
classifyLayer54d5 l5r37 = mc2
classifyLayer54d5 l5r38 = mc1
classifyLayer54d5 l5r39 = mc2
classifyLayer54d5 l5r40 = mc1
classifyLayer54d5 l5r41 = mc1
classifyLayer54d5 l5r42 = mc2
classifyLayer54d5 l5r43 = mc1
classifyLayer54d5 l5r44 = mc2
classifyLayer54d5 l5r45 = mc1
classifyLayer54d5 l5r46 = mc1
classifyLayer54d5 l5r47 = mc2
classifyLayer54d5 l5r48 = mc1
classifyLayer54d5 l5r49 = mc1
classifyLayer54d5 l5r50 = mc1
classifyLayer54d5 l5r51 = mc2
classifyLayer54d5 l5r52 = mc1
classifyLayer54d5 l5r53 = mc1
classifyLayer54d5 l5r54 = mc1
classifyLayer54d5 l5r55 = mc2
classifyLayer54d5 l5r56 = mc2
classifyLayer54d5 l5r57 = mc1
classifyLayer54d5 l5r58 = mc2
classifyLayer54d5 l5r59 = mc1
classifyLayer54d5 l5r60 = mc1
classifyLayer54d5 l5r61 = mc1
classifyLayer54d5 l5r62 = mc2
classifyLayer54d5 l5r63 = mc2
classifyLayer54d5 l5r64 = mc2
classifyLayer54d5 l5r65 = mc1
classifyLayer54d5 l5r66 = mc1
classifyLayer54d5 l5r67 = mc1
classifyLayer54d5 l5r68 = mc2
classifyLayer54d5 l5r69 = mc1
classifyLayer54d5 l5r70 = mc1
classifyLayer54d5 l5r71 = mc1
classifyLayer54d5 l5r72 = mc1
classifyLayer54d5 l5r73 = mc2
classifyLayer54d5 l5r74 = mc1
classifyLayer54d5 l5r75 = mc1
classifyLayer54d5 l5r76 = mc1
classifyLayer54d5 l5r77 = mc1
classifyLayer54d5 l5r78 = mc2
classifyLayer54d5 l5r79 = mc2
classifyLayer54d5 l5r80 = mc1
classifyLayer54d5 l5r81 = mc2
classifyLayer54d5 l5r82 = mc1
classifyLayer54d5 l5r83 = mc1
classifyLayer54d5 l5r84 = mc2
classifyLayer54d5 l5r85 = mc1
classifyLayer54d5 l5r86 = mc1
classifyLayer54d5 l5r87 = mc1
classifyLayer54d5 l5r88 = mc1
classifyLayer54d5 l5r89 = mc2
classifyLayer54d5 l5r90 = mc1
classifyLayer54d5 l5r91 = mc2
classifyLayer54d5 l5r92 = mc2
classifyLayer54d5 l5r93 = mc1
classifyLayer54d5 l5r94 = mc2
classifyLayer54d5 l5r95 = mc1
classifyLayer54d5 l5r96 = mc1
classifyLayer54d5 l5r97 = mc2
classifyLayer54d5 l5r98 = mc1
classifyLayer54d5 l5r99 = mc2
classifyLayer54d5 l5r100 = mc2
classifyLayer54d5 l5r101 = mc1
classifyLayer54d5 l5r102 = mc2
classifyLayer54d5 l5r103 = mc1
classifyLayer54d5 l5r104 = mc1
classifyLayer54d5 l5r105 = mc1
classifyLayer54d5 l5r106 = mc2
classifyLayer54d5 l5r107 = mc1
classifyLayer54d5 l5r108 = mc1
classifyLayer54d5 l5r109 = mc1
classifyLayer54d5 l5r110 = mc2
classifyLayer54d5 l5r111 = mc2
classifyLayer54d5 l5r112 = mc1
classifyLayer54d5 l5r113 = mc2
classifyLayer54d5 l5r114 = mc1
classifyLayer54d5 l5r115 = mc1
classifyLayer54d5 l5r116 = mc1
classifyLayer54d5 l5r117 = mc2
classifyLayer54d5 l5r118 = mc2
classifyLayer54d5 l5r119 = mc2
classifyLayer54d5 l5r120 = mc1
classifyLayer54d5 l5r121 = mc1
classifyLayer54d5 l5r122 = mc1
classifyLayer54d5 l5r123 = mc2
classifyLayer54d5 l5r124 = mc1
classifyLayer54d5 l5r125 = mc1
classifyLayer54d5 l5r126 = mc1
classifyLayer54d5 l5r127 = mc1
classifyLayer54d5 l5r128 = mc2
classifyLayer54d5 l5r129 = mc1
classifyLayer54d5 l5r130 = mc1
classifyLayer54d5 l5r131 = mc1
classifyLayer54d5 l5r132 = mc2
classifyLayer54d5 l5r133 = mc1
classifyLayer54d5 l5r134 = mc1
classifyLayer54d5 l5r135 = mc1
classifyLayer54d5 l5r136 = mc2
classifyLayer54d5 l5r137 = mc2
classifyLayer54d5 l5r138 = mc1
classifyLayer54d5 l5r139 = mc2
classifyLayer54d5 l5r140 = mc2
classifyLayer54d5 l5r141 = mc1
classifyLayer54d5 l5r142 = mc1
classifyLayer54d5 l5r143 = mc1
classifyLayer54d5 l5r144 = mc2
classifyLayer54d5 l5r145 = mc1
classifyLayer54d5 l5r146 = mc2
classifyLayer54d5 l5r147 = mc2
classifyLayer54d5 l5r148 = mc1
classifyLayer54d5 l5r149 = mc1
classifyLayer54d5 l5r150 = mc1
classifyLayer54d5 l5r151 = mc1
classifyLayer54d5 l5r152 = mc2
classifyLayer54d5 l5r153 = mc1
classifyLayer54d5 l5r154 = mc2
classifyLayer54d5 l5r155 = mc1
classifyLayer54d5 l5r156 = mc1
classifyLayer54d5 l5r157 = mc2
classifyLayer54d5 l5r158 = mc1
classifyLayer54d5 l5r159 = mc1
classifyLayer54d5 l5r160 = mc1
classifyLayer54d5 l5r161 = mc2
classifyLayer54d5 l5r162 = mc1
classifyLayer54d5 l5r163 = mc1
classifyLayer54d5 l5r164 = mc1
classifyLayer54d5 l5r165 = mc2
classifyLayer54d5 l5r166 = mc2
classifyLayer54d5 l5r167 = mc1
classifyLayer54d5 l5r168 = mc2
classifyLayer54d5 l5r169 = mc1
classifyLayer54d5 l5r170 = mc1
classifyLayer54d5 l5r171 = mc1
classifyLayer54d5 l5r172 = mc2
classifyLayer54d5 l5r173 = mc2
classifyLayer54d5 l5r174 = mc2
classifyLayer54d5 l5r175 = mc1
classifyLayer54d5 l5r176 = mc1
classifyLayer54d5 l5r177 = mc1
classifyLayer54d5 l5r178 = mc2
classifyLayer54d5 l5r179 = mc2
classifyLayer54d5 l5r180 = mc1
classifyLayer54d5 l5r181 = mc1
classifyLayer54d5 l5r182 = mc1
classifyLayer54d5 l5r183 = mc2
classifyLayer54d5 l5r184 = mc1
classifyLayer54d5 l5r185 = mc1
classifyLayer54d5 l5r186 = mc2
classifyLayer54d5 l5r187 = mc2
classifyLayer54d5 l5r188 = mc1
classifyLayer54d5 l5r189 = mc1
classifyLayer54d5 l5r190 = mc1
classifyLayer54d5 l5r191 = mc2
classifyLayer54d5 l5r192 = mc2
classifyLayer54d5 l5r193 = mc1
classifyLayer54d5 l5r194 = mc2
classifyLayer54d5 l5r195 = mc1
classifyLayer54d5 l5r196 = mc1
classifyLayer54d5 l5r197 = mc1
classifyLayer54d5 l5r198 = mc1
classifyLayer54d5 l5r199 = mc2
classifyLayer54d5 l5r200 = mc1
classifyLayer54d5 l5r201 = mc2
classifyLayer54d5 l5r202 = mc2
classifyLayer54d5 l5r203 = mc1
classifyLayer54d5 l5r204 = mc1
classifyLayer54d5 l5r205 = mc1
classifyLayer54d5 l5r206 = mc1
classifyLayer54d5 l5r207 = mc1
classifyLayer54d5 l5r208 = mc1
classifyLayer54d5 l5r209 = mc2
classifyLayer54d5 l5r210 = mc2
classifyLayer54d5 l5r211 = mc1
classifyLayer54d5 l5r212 = mc2
classifyLayer54d5 l5r213 = mc1
classifyLayer54d5 l5r214 = mc1
classifyLayer54d5 l5r215 = mc2
classifyLayer54d5 l5r216 = mc1
classifyLayer54d5 l5r217 = mc1
classifyLayer54d5 l5r218 = mc1
classifyLayer54d5 l5r219 = mc1
classifyLayer54d5 l5r220 = mc2
classifyLayer54d5 l5r221 = mc1
classifyLayer54d5 l5r222 = mc2
classifyLayer54d5 l5r223 = mc2
classifyLayer54d5 l5r224 = mc1
classifyLayer54d5 l5r225 = mc2
classifyLayer54d5 l5r226 = mc1
classifyLayer54d5 l5r227 = mc1
classifyLayer54d5 l5r228 = mc2
classifyLayer54d5 l5r229 = mc2
classifyLayer54d5 l5r230 = mc1
classifyLayer54d5 l5r231 = mc1
classifyLayer54d5 l5r232 = mc1
classifyLayer54d5 l5r233 = mc2
classifyLayer54d5 l5r234 = mc1
classifyLayer54d5 l5r235 = mc1
classifyLayer54d5 l5r236 = mc1
classifyLayer54d5 l5r237 = mc1
classifyLayer54d5 l5r238 = mc2
classifyLayer54d5 l5r239 = mc1
classifyLayer54d5 l5r240 = mc2
classifyLayer54d5 l5r241 = mc2
classifyLayer54d5 l5r242 = mc1
classifyLayer54d5 l5r243 = mc2
classifyLayer54d5 l5r244 = mc2
classifyLayer54d5 l5r245 = mc1
classifyLayer54d5 l5r246 = mc2
classifyLayer54d5 l5r247 = mc1
classifyLayer54d5 l5r248 = mc1
classifyLayer54d5 l5r249 = mc2
classifyLayer54d5 l5r250 = mc1
classifyLayer54d5 l5r251 = mc1
classifyLayer54d5 l5r252 = mc1
classifyLayer54d5 l5r253 = mc1
classifyLayer54d5 l5r254 = mc2
classifyLayer54d5 l5r255 = mc1
classifyLayer54d5 l5r256 = mc2
classifyLayer54d5 l5r257 = mc2
classifyLayer54d5 l5r258 = mc1
classifyLayer54d5 l5r259 = mc1
classifyLayer54d5 l5r260 = mc1
classifyLayer54d5 l5r261 = mc1
classifyLayer54d5 l5r262 = mc1
classifyLayer54d5 l5r263 = mc2
classifyLayer54d5 l5r264 = mc1
classifyLayer54d5 l5r265 = mc1
classifyLayer54d5 l5r266 = mc1
classifyLayer54d5 l5r267 = mc2
classifyLayer54d5 l5r268 = mc2
classifyLayer54d5 l5r269 = mc1
classifyLayer54d5 l5r270 = mc2
classifyLayer54d5 l5r271 = mc1
classifyLayer54d5 l5r272 = mc1
classifyLayer54d5 l5r273 = mc1
classifyLayer54d5 l5r274 = mc1

