{-# OPTIONS --cubical --safe --guardedness #-}

module Common.Layer54d3Spec where

open import Cubical.Foundations.Prelude
open import Util.Scalars

-- Layer54d3Region — Cell-aligned boundary regions of the
-- {5,4} tiling patch at BFS depth 3
-- 40 regions, 2 orbit representatives
--  Generated by sim/prototyping/13_generate_layerN.py --depth 3
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 3

data Layer54d3Region : Type₀ where
  -- size 1  (40 regions)
  l3r0 l3r1 l3r2 l3r3 l3r4 l3r5 l3r6 l3r7 l3r8 l3r9 : Layer54d3Region
  l3r10 l3r11 l3r12 l3r13 l3r14 l3r15 l3r16 l3r17 l3r18 l3r19 : Layer54d3Region
  l3r20 l3r21 l3r22 l3r23 l3r24 l3r25 l3r26 l3r27 l3r28 l3r29 : Layer54d3Region
  l3r30 l3r31 l3r32 l3r33 l3r34 l3r35 l3r36 l3r37 l3r38 l3r39 : Layer54d3Region

-- Layer54d3OrbitRep — Orbit representatives by min-cut value
-- Orbit decomposition:
--   mc1  (S = 1):  25 regions
--   mc2  (S = 2):  15 regions
--  Generated by sim/prototyping/13_generate_layerN.py --depth 3
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 3

data Layer54d3OrbitRep : Type₀ where
  mc1 mc2 : Layer54d3OrbitRep

-- classifyLayer54d3 — Map each region to its orbit representative
--  Generated by sim/prototyping/13_generate_layerN.py --depth 3
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 3

classifyLayer54d3 : Layer54d3Region → Layer54d3OrbitRep
classifyLayer54d3 l3r0 = mc2
classifyLayer54d3 l3r1 = mc2
classifyLayer54d3 l3r2 = mc1
classifyLayer54d3 l3r3 = mc2
classifyLayer54d3 l3r4 = mc1
classifyLayer54d3 l3r5 = mc2
classifyLayer54d3 l3r6 = mc1
classifyLayer54d3 l3r7 = mc1
classifyLayer54d3 l3r8 = mc2
classifyLayer54d3 l3r9 = mc1
classifyLayer54d3 l3r10 = mc1
classifyLayer54d3 l3r11 = mc1
classifyLayer54d3 l3r12 = mc1
classifyLayer54d3 l3r13 = mc2
classifyLayer54d3 l3r14 = mc2
classifyLayer54d3 l3r15 = mc1
classifyLayer54d3 l3r16 = mc2
classifyLayer54d3 l3r17 = mc1
classifyLayer54d3 l3r18 = mc1
classifyLayer54d3 l3r19 = mc1
classifyLayer54d3 l3r20 = mc2
classifyLayer54d3 l3r21 = mc1
classifyLayer54d3 l3r22 = mc1
classifyLayer54d3 l3r23 = mc1
classifyLayer54d3 l3r24 = mc2
classifyLayer54d3 l3r25 = mc2
classifyLayer54d3 l3r26 = mc1
classifyLayer54d3 l3r27 = mc2
classifyLayer54d3 l3r28 = mc1
classifyLayer54d3 l3r29 = mc1
classifyLayer54d3 l3r30 = mc1
classifyLayer54d3 l3r31 = mc1
classifyLayer54d3 l3r32 = mc2
classifyLayer54d3 l3r33 = mc1
classifyLayer54d3 l3r34 = mc2
classifyLayer54d3 l3r35 = mc2
classifyLayer54d3 l3r36 = mc1
classifyLayer54d3 l3r37 = mc1
classifyLayer54d3 l3r38 = mc1
classifyLayer54d3 l3r39 = mc1

