{-# OPTIONS --cubical --safe --guardedness #-}

module Bulk.Dense1000Chain where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Dense1000Spec

record D1000BulkView : Type₀ where
  field
    dummy : ℚ≥0

--  Generated by sim/prototyping/12b_generate_dense1000.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/12b_generate_dense1000.py

L-min-rep : D1000OrbitRep → ℚ≥0
L-min-rep mc1 = 1
L-min-rep mc2 = 2
L-min-rep mc3 = 3
L-min-rep mc4 = 4
L-min-rep mc5 = 5
L-min-rep mc6 = 6
L-min-rep mc7 = 7
L-min-rep mc8 = 8
L-min-rep mc9 = 9

L-min : D1000BulkView → D1000Region → ℚ≥0
L-min _ r = L-min-rep (classify1000 r)

