{-# OPTIONS --cubical --safe --guardedness #-}

module Bulk.Dense200Chain where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Dense200Spec

record D200BulkView : Type₀ where
  field
    dummy : ℚ≥0

-- ═══════════════════════════════════════════════════════════
--  L-min-rep — Bulk minimal surface on orbit representatives
-- ═══════════════════════════════════════════════════════════
--
--  Generated by sim/prototyping/12_generate_dense200.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/12_generate_dense200.py

L-min-rep : D200OrbitRep → ℚ≥0
L-min-rep mc1 = 1
L-min-rep mc2 = 2
L-min-rep mc3 = 3
L-min-rep mc4 = 4
L-min-rep mc5 = 5
L-min-rep mc6 = 6
L-min-rep mc7 = 7
L-min-rep mc8 = 8
L-min-rep mc9 = 9

-- ═══════════════════════════════════════════════════════════
--  L-min — Bulk minimal separating surface for Dense-200
-- ═══════════════════════════════════════════════════════════
--
--  Defined as  L-min-rep ∘ classify200 , mirroring S-cut.
--
--  Generated by sim/prototyping/12_generate_dense200.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/12_generate_dense200.py

L-min : D200BulkView → D200Region → ℚ≥0
L-min _ r = L-min-rep (classify200 r)

