{-# OPTIONS --cubical --safe --guardedness #-}

module Bulk.Dense1000Curvature where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat  using (ℕ ; zero ; suc ; _+_ ; _·_)
open import Cubical.Data.Int
  using (ℤ ; pos ; negsuc)
  renaming (_+_ to _+ℤ_)

open import Util.Rationals

--  Generated by sim/prototyping/12b_generate_dense1000.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/12b_generate_dense1000.py

data D1000EdgeClass : Type₀ where
  ev5 : D1000EdgeClass

d1000EdgeCount : D1000EdgeClass → ℕ
d1000EdgeCount ev5 = 12

d1000Kappa : D1000EdgeClass → ℚ₁₀
d1000Kappa ev5 = negsuc 4

totalD1000Curvature : ℚ₁₀
totalD1000Curvature = 12 ·₁₀ d1000Kappa ev5

totalD1000Curvature-check : totalD1000Curvature ≡ negsuc 59
totalD1000Curvature-check = refl

