{-# OPTIONS --cubical --safe --guardedness #-}

module Bulk.Dense50Curvature where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat  using (ℕ ; zero ; suc ; _+_ ; _·_)
open import Cubical.Data.Int
  using (ℤ ; pos ; negsuc)
  renaming (_+_ to _+ℤ_)

open import Util.Rationals

-- ═══════════════════════════════════════════════════════════
--  3D Edge Curvature for the Dense-50 {4,3,5} Patch
-- ═══════════════════════════════════════════════════════════
--
--  In 3D, curvature lives on EDGES (not vertices).
--  At an interior edge e with valence v (cubes meeting):
--    κ(e) = 2π − v · (π/2)
--
--  For {4,3,5}: full valence = 5, so κ = −π/2 (hyperbolic).
--  In the flat cubic tiling {4,3,4}: valence = 4, κ = 0.
--
--  Combinatorial encoding in twentieths (via ℚ₁₀ = ℤ):
--    κ₂₀(e) = 20 − 5·v
--      v=5 → κ₂₀ = −5   (hyperbolic)
--      v=4 → κ₂₀ =  0   (flat)
--      v=3 → κ₂₀ = +5   (boundary)
--      v=2 → κ₂₀ = +10  (boundary)
--
--  Edge valences are computed with deduplicated dihedral
--  orbit enumeration (07_honeycomb_3d_multiStrategy.py),
--  counting distinct cell centers in the patch.
--
--  Generated by sim/prototyping/08_generate_dense50.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/08_generate_dense50.py

-- ═══════════════════════════════════════════════════════════
--  D50EdgeClass — Edge classes by in-patch valence
-- ═══════════════════════════════════════════════════════════

data D50EdgeClass : Type₀ where
  ev5 : D50EdgeClass

d50EdgeCount : D50EdgeClass → ℕ
d50EdgeCount ev5 = 12

d50Valence : D50EdgeClass → ℕ
d50Valence ev5 = 5

-- Curvature in twentieths:  κ₂₀ = 20 − 5·valence
d50Kappa : D50EdgeClass → ℚ₁₀
d50Kappa ev5 = negsuc 4    -- val=5, κ₂₀=-5

-- ═══════════════════════════════════════════════════════════
--  Total edge curvature (class-weighted sum over 12 edges
--  of the central cube)
-- ═══════════════════════════════════════════════════════════

totalD50Curvature : ℚ₁₀
totalD50Curvature = 12 ·₁₀ d50Kappa ev5

-- Expected value: negsuc 59  (= -60 in twentieths)
-- Interpretation: total edge curvature = -60/20 × 2π
--
-- For the Dense-50 patch, all 12 central-cube edges are
-- fully surrounded by 5 cubes (the {4,3,5} condition),
-- confirming genuine 3D hyperbolic geometry.

totalD50Curvature-check : totalD50Curvature ≡ negsuc 59
totalD50Curvature-check = refl

-- ═══════════════════════════════════════════════════════════
--  Per-class contribution regression tests
-- ═══════════════════════════════════════════════════════════

-- 12 edges × κ₂₀=-5 = -60
contrib-ev5 : 12 ·₁₀ d50Kappa ev5 ≡ negsuc 59
contrib-ev5 = refl

