{-# OPTIONS --cubical --safe --guardedness #-}

module Bulk.FilledChain where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.FilledSpec

-- ════════════════════════════════════════════════════════════
--  FilledBulkView — Bulk-side view (architectural wrapper)
-- ════════════════════════════════════════════════════════════

record FilledBulkView : Type₀ where
  field
    dummy : ℚ≥0

-- ════════════════════════════════════════════════════════════
--  L-min — Bulk minimal separating chain (redefined)
-- ════════════════════════════════════════════════════════════
--
--  Under the N-singleton resolution (§3.2, docs/10-frontier.md),
--  the bulk observable is the true min-cut (allowing boundary
--  bonds to be severed), matching S-cut on all 90 regions.
--
--  Generated by sim/prototyping/03_generate_filled_patch.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/03_generate_filled_patch.py

L-min : FilledBulkView → FilledRegion → ℚ≥0
L-min _ r0x1 = 2    -- {N0}
L-min _ r1x1 = 2    -- {G1}
L-min _ r2x1 = 2    -- {N1}
L-min _ r3x1 = 2    -- {G2}
L-min _ r4x1 = 2    -- {N2}
L-min _ r5x1 = 2    -- {G3}
L-min _ r6x1 = 2    -- {N3}
L-min _ r7x1 = 2    -- {G4}
L-min _ r8x1 = 2    -- {N4}
L-min _ r9x1 = 2    -- {G0}
L-min _ r0x2 = 3    -- {N0, G1}
L-min _ r1x2 = 3    -- {G1, N1}
L-min _ r2x2 = 3    -- {N1, G2}
L-min _ r3x2 = 3    -- {G2, N2}
L-min _ r4x2 = 3    -- {N2, G3}
L-min _ r5x2 = 3    -- {G3, N3}
L-min _ r6x2 = 3    -- {N3, G4}
L-min _ r7x2 = 3    -- {G4, N4}
L-min _ r8x2 = 3    -- {N4, G0}
L-min _ r9x2 = 3    -- {G0, N0}
L-min _ r0x3 = 4    -- {N0, G1, N1}
L-min _ r1x3 = 3    -- {G1, N1, G2}
L-min _ r2x3 = 4    -- {N1, G2, N2}
L-min _ r3x3 = 3    -- {G2, N2, G3}
L-min _ r4x3 = 4    -- {N2, G3, N3}
L-min _ r5x3 = 3    -- {G3, N3, G4}
L-min _ r6x3 = 4    -- {N3, G4, N4}
L-min _ r7x3 = 3    -- {G4, N4, G0}
L-min _ r8x3 = 4    -- {N4, G0, N0}
L-min _ r9x3 = 3    -- {G0, N0, G1}
L-min _ r0x4 = 4    -- {N0, G1, N1, G2}
L-min _ r1x4 = 4    -- {G1, N1, G2, N2}
L-min _ r2x4 = 4    -- {N1, G2, N2, G3}
L-min _ r3x4 = 4    -- {G2, N2, G3, N3}
L-min _ r4x4 = 4    -- {N2, G3, N3, G4}
L-min _ r5x4 = 4    -- {G3, N3, G4, N4}
L-min _ r6x4 = 4    -- {N3, G4, N4, G0}
L-min _ r7x4 = 4    -- {G4, N4, G0, N0}
L-min _ r8x4 = 4    -- {N4, G0, N0, G1}
L-min _ r9x4 = 4    -- {G0, N0, G1, N1}
L-min _ r0x5 = 4    -- {N0, G1, N1, G2, N2}
L-min _ r1x5 = 4    -- {G1, N1, G2, N2, G3}
L-min _ r2x5 = 4    -- {N1, G2, N2, G3, N3}
L-min _ r3x5 = 4    -- {G2, N2, G3, N3, G4}
L-min _ r4x5 = 4    -- {N2, G3, N3, G4, N4}
L-min _ r5x5 = 4    -- {G3, N3, G4, N4, G0}
L-min _ r6x5 = 4    -- {N3, G4, N4, G0, N0}
L-min _ r7x5 = 4    -- {G4, N4, G0, N0, G1}
L-min _ r8x5 = 4    -- {N4, G0, N0, G1, N1}
L-min _ r9x5 = 4    -- {G0, N0, G1, N1, G2}
L-min _ r0x6 = 4    -- {N0, G1, N1, G2, N2, G3}
L-min _ r1x6 = 4    -- {G1, N1, G2, N2, G3, N3}
L-min _ r2x6 = 4    -- {N1, G2, N2, G3, N3, G4}
L-min _ r3x6 = 4    -- {G2, N2, G3, N3, G4, N4}
L-min _ r4x6 = 4    -- {N2, G3, N3, G4, N4, G0}
L-min _ r5x6 = 4    -- {G3, N3, G4, N4, G0, N0}
L-min _ r6x6 = 4    -- {N3, G4, N4, G0, N0, G1}
L-min _ r7x6 = 4    -- {G4, N4, G0, N0, G1, N1}
L-min _ r8x6 = 4    -- {N4, G0, N0, G1, N1, G2}
L-min _ r9x6 = 4    -- {G0, N0, G1, N1, G2, N2}
L-min _ r0x7 = 3    -- {N0, G1, N1, G2, N2, G3, N3}
L-min _ r1x7 = 4    -- {G1, N1, G2, N2, G3, N3, G4}
L-min _ r2x7 = 3    -- {N1, G2, N2, G3, N3, G4, N4}
L-min _ r3x7 = 4    -- {G2, N2, G3, N3, G4, N4, G0}
L-min _ r4x7 = 3    -- {N2, G3, N3, G4, N4, G0, N0}
L-min _ r5x7 = 4    -- {G3, N3, G4, N4, G0, N0, G1}
L-min _ r6x7 = 3    -- {N3, G4, N4, G0, N0, G1, N1}
L-min _ r7x7 = 4    -- {G4, N4, G0, N0, G1, N1, G2}
L-min _ r8x7 = 3    -- {N4, G0, N0, G1, N1, G2, N2}
L-min _ r9x7 = 4    -- {G0, N0, G1, N1, G2, N2, G3}
L-min _ r0x8 = 3    -- {N0, G1, N1, G2, N2, G3, N3, G4}
L-min _ r1x8 = 3    -- {G1, N1, G2, N2, G3, N3, G4, N4}
L-min _ r2x8 = 3    -- {N1, G2, N2, G3, N3, G4, N4, G0}
L-min _ r3x8 = 3    -- {G2, N2, G3, N3, G4, N4, G0, N0}
L-min _ r4x8 = 3    -- {N2, G3, N3, G4, N4, G0, N0, G1}
L-min _ r5x8 = 3    -- {G3, N3, G4, N4, G0, N0, G1, N1}
L-min _ r6x8 = 3    -- {N3, G4, N4, G0, N0, G1, N1, G2}
L-min _ r7x8 = 3    -- {G4, N4, G0, N0, G1, N1, G2, N2}
L-min _ r8x8 = 3    -- {N4, G0, N0, G1, N1, G2, N2, G3}
L-min _ r9x8 = 3    -- {G0, N0, G1, N1, G2, N2, G3, N3}
L-min _ r0x9 = 2    -- {N0, G1, N1, G2, N2, G3, N3, G4, N4}
L-min _ r1x9 = 2    -- {G1, N1, G2, N2, G3, N3, G4, N4, G0}
L-min _ r2x9 = 2    -- {N1, G2, N2, G3, N3, G4, N4, G0, N0}
L-min _ r3x9 = 2    -- {G2, N2, G3, N3, G4, N4, G0, N0, G1}
L-min _ r4x9 = 2    -- {N2, G3, N3, G4, N4, G0, N0, G1, N1}
L-min _ r5x9 = 2    -- {G3, N3, G4, N4, G0, N0, G1, N1, G2}
L-min _ r6x9 = 2    -- {N3, G4, N4, G0, N0, G1, N1, G2, N2}
L-min _ r7x9 = 2    -- {G4, N4, G0, N0, G1, N1, G2, N2, G3}
L-min _ r8x9 = 2    -- {N4, G0, N0, G1, N1, G2, N2, G3, N3}
L-min _ r9x9 = 2    -- {G0, N0, G1, N1, G2, N2, G3, N3, G4}

