{-# OPTIONS --cubical --safe --guardedness #-}

module Bulk.Honeycomb3DChain where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Honeycomb3DSpec

-- ═══════════════════════════════════════════════════════════
--  H3BulkView — Bulk-side architectural wrapper
-- ═══════════════════════════════════════════════════════════

record H3BulkView : Type₀ where
  field
    dummy : ℚ≥0

-- ═══════════════════════════════════════════════════════════
--  L-min — Bulk minimal separating surface for the 3D patch
-- ═══════════════════════════════════════════════════════════
--
--  In 3D the bulk minimal chain is a minimal *surface*: a
--  set of internal faces whose removal disconnects the region
--  from its complement.  The min-cut = min surface area
--  (measured in face-count units) is the 3D discrete RT.
--
--  Generated by sim/prototyping/06_generate_honeycomb_3d.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/06_generate_honeycomb_3d.py

L-min : H3BulkView → H3Region → ℚ≥0
L-min _ h3r0 = 1    -- {c6}
L-min _ h3r1 = 1    -- {c7}
L-min _ h3r2 = 1    -- {c8}
L-min _ h3r3 = 1    -- {c9}
L-min _ h3r4 = 1    -- {c10}
L-min _ h3r5 = 1    -- {c11}
L-min _ h3r6 = 1    -- {c12}
L-min _ h3r7 = 1    -- {c13}
L-min _ h3r8 = 1    -- {c14}
L-min _ h3r9 = 1    -- {c15}
L-min _ h3r10 = 1    -- {c16}
L-min _ h3r11 = 1    -- {c17}
L-min _ h3r12 = 1    -- {c18}
L-min _ h3r13 = 1    -- {c19}
L-min _ h3r14 = 1    -- {c20}
L-min _ h3r15 = 1    -- {c21}
L-min _ h3r16 = 1    -- {c22}
L-min _ h3r17 = 1    -- {c23}
L-min _ h3r18 = 1    -- {c24}
L-min _ h3r19 = 1    -- {c25}
L-min _ h3r20 = 1    -- {c26}
L-min _ h3r21 = 1    -- {c27}
L-min _ h3r22 = 1    -- {c28}
L-min _ h3r23 = 1    -- {c29}
L-min _ h3r24 = 1    -- {c30}
L-min _ h3r25 = 1    -- {c31}

