{-# OPTIONS --cubical --safe --guardedness #-}

module Bulk.Honeycomb3DCurvature where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat  using (ℕ ; zero ; suc ; _+_ ; _·_)
open import Cubical.Data.Int
  using (ℤ ; pos ; negsuc)
  renaming (_+_ to _+ℤ_)

open import Util.Rationals

-- ═══════════════════════════════════════════════════════════
--  3D Edge Curvature for the {4,3,5} Honeycomb Patch
-- ═══════════════════════════════════════════════════════════
--
--  In 3D, curvature lives on EDGES (not vertices).
--  At an interior edge e with valence v (cubes meeting):
--    κ(e) = 2π − v · (π/2)
--
--  For {4,3,5}: full valence = 5, so κ = −π/2 (hyperbolic).
--  In the flat cubic tiling {4,3,4}: valence = 4, κ = 0.
--
--  Combinatorial encoding:  ℚ₁₀ with denominator 20.
--  κ₂₀(e) = 20 · (1 − v/4) = 20 − 5v   (in twentieths)
--    v=5 → κ₂₀ = −5   (hyperbolic)
--    v=4 → κ₂₀ =  0   (flat)
--    v=3 → κ₂₀ = +5   (boundary)
--    v=2 → κ₂₀ = +10  (boundary)
--
--  Generated by sim/prototyping/06_generate_honeycomb_3d.py
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/06_generate_honeycomb_3d.py

-- ═══════════════════════════════════════════════════════════
--  H3EdgeClass — Edge classes by in-patch valence
-- ═══════════════════════════════════════════════════════════

data H3EdgeClass : Type₀ where
  ev8 ev10 : H3EdgeClass

h3EdgeCount : H3EdgeClass → ℕ
h3EdgeCount ev8 = 4
h3EdgeCount ev10 = 8

h3Valence : H3EdgeClass → ℕ
h3Valence ev8 = 8
h3Valence ev10 = 10

-- Curvature in twentieths:  20 − 5·valence
h3Kappa : H3EdgeClass → ℚ₁₀
h3Kappa ev8 = negsuc 19    -- val=8, κ₂₀=-20
h3Kappa ev10 = negsuc 29    -- val=10, κ₂₀=-30

-- ═══════════════════════════════════════════════════════════
--  Total edge curvature (class-weighted sum over 12 edges
--  of the central cube)
-- ═══════════════════════════════════════════════════════════

totalH3Curvature : ℚ₁₀
totalH3Curvature = 4 ·₁₀ h3Kappa ev8 +₁₀ 8 ·₁₀ h3Kappa ev10

-- Expected value: negsuc 319
totalH3Curvature-check : totalH3Curvature ≡ negsuc 319
totalH3Curvature-check = refl

