{-# OPTIONS --cubical --safe --guardedness #-}

module Bulk.Layer54d3Chain where

open import Cubical.Foundations.Prelude
open import Util.Scalars
open import Common.Layer54d3Spec

record Layer54d3BulkView : Type₀ where
  field
    dummy : ℚ≥0

-- L-min-rep — Bulk minimal chain on orbit representatives
--  Generated by sim/prototyping/13_generate_layerN.py --depth 3
--  Do not edit by hand.  Regenerate with:
--    python3 sim/prototyping/13_generate_layerN.py --depth 3

L-min-rep : Layer54d3OrbitRep → ℚ≥0
L-min-rep mc1 = 1
L-min-rep mc2 = 2

-- L-min — Bulk minimal separating chain (via orbit reduction)
L-min : Layer54d3BulkView → Layer54d3Region → ℚ≥0
L-min _ r = L-min-rep (classifyLayer54d3 r)

